import {randomUUID} from 'node:crypto';
import {gzipSync} from 'node:zlib';
import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,mkdirSync,mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import Fastify from 'fastify';
import {Context} from '@deepseek-ai/cordis';
import {ServerFeatureHost,ServerFeatureScope} from '../src/feature-host.js';
import {buildApp} from '../src/app.js';
import {createInsightSnapshot} from '../src/insight-snapshots.js';
import {contextBundle} from '../src/context-bundle.js';
import type {Config} from '../src/config.js';
import {setImmediate as yieldTurn} from 'node:timers/promises';
test('server feature disposal revokes routes without deleting retained data',async t=>{
  const app=Fastify(),root=new Context(),host=new ServerFeatureHost(root,app);let retained=1;
  const fiber=await host.install({id:'fixture.feature',version:'1',components:[]},server=>server.get('/fixture',async()=>({retained})));
  t.after(async()=>{await app.close();await root.fiber.dispose();});
  assert.equal((await app.inject('/fixture')).json().retained,1);
  assert.ok(host.registry.inventory().capabilities.some(c=>c.id==='http:GET:/fixture'));
  await fiber.dispose();assert.equal(host.registry.inventory().capabilities.length,0);
  assert.equal((await app.inject('/fixture')).statusCode,503);assert.equal(retained,1);
});
test('small Coding upload flows through feature routes to pinned owner and real Agent projections',async t=>{
  const directory=mkdtempSync(join(tmpdir(),'mote-feature-fixture-'));
  const config:Config={dataDir:directory,token:'generated-fixture-token',tokenPath:'fixture-only',host:'127.0.0.1',port:0,maxStorageBytes:10_000_000,maxExportBytes:1_000_000,retentionDays:0,insightIntervalHours:0,allowedOrigins:[],model:'',modelBaseUrl:'',apiKey:'',allowUnauthenticatedLocal:false,embeddingModel:'',embeddingBaseUrl:'',embeddingApiKey:'',logLevel:'silent'};
  const node=await buildApp(config);t.after(async()=>{await node.app.close();rmSync(directory,{recursive:true,force:true});});
  const headers={authorization:'Bearer '+config.token,'x-mote-ingress-version':'2'};
  const call=(url:string,method:'GET'|'POST'|'DELETE'='GET',payload?:unknown)=>node.app.inject({url,method,headers,payload});
  for(const url of ['/api/features','/api/coding/uploads','/api/agent-view/catalog','/api/agent-view/events'])assert.equal((await node.app.inject(url)).statusCode,401);
  assert.equal((await call('/api/sources','POST',{id:'fixture-coding',name:'Generated Coding',kind:'coding-agent',deviceId:'fixture-device',platform:'macos'})).statusCode,200);
  const event=(i:number)=>({externalId:'event-'+i,revision:'1',observedAt:`2026-09-24T01:00:0${i}.000Z`,kind:'message',layer:'original',text:`Generated event ${i}: everyday plugin fixture`,document:{contentRole:'transcript',coding:{version:1,provider:'codex',projectKey:'generated-project',sessionId:'generated-session',eventId:'event-'+i,role:'user',part:0,parts:1}}});
  const sent=await call('/api/sources/fixture-coding/items/batch','POST',{items:[event(0),event(1),event(2)]});assert.equal(sent.statusCode,200,sent.body);
  assert.ok(sent.json().receipts.every((r:any)=>r.receipt.state==='received'));
  assert.equal((await call('/api/coding/uploads')).json().items[0].received.events,3);
  assert.equal((await call('/api/sources/fixture-coding/items/batch','POST',{items:[event(0)]})).statusCode,200);
  assert.equal((await call('/api/coding/uploads')).json().items[0].received.events,3,'retry does not duplicate events');
  await node.sourcePipelines.tick();
  const materials=(await call('/api/agent-view/materials')).json();assert.equal(materials.items.length,1);
  const material=materials.items[0];assert.equal(material.kind,'mote.coding-session');
  const scope={after:'2026-09-24T00:00:00.000Z',before:'2026-09-25T00:00:00.000Z'};
  const snapshot=createInsightSnapshot(node.store,'generated-snapshot',scope,node.featureServices.evidenceReader);
  assert.equal(snapshot.coverage.materialRecords,1);assert.equal(snapshot.coverage.measured.observedDurationMs,0);assert.ok(!snapshot.coverage.limitations.includes('no_records_in_scope'));
  const selection=node.featureServices.evidenceReader.memorySelection(scope);
  assert.ok(selection.evidenceIds.length>0);assert.ok(selection.evidenceIds.every(id=>node.materials.isCurrentEvidence(id)));
  const bundle=await contextBundle(node.featureServices.evidenceReader,node.featureServices.archiveReader,{maxCharacters:1000,projectKey:'generated-project'});
  assert.equal(bundle.recentSessions.length,1);assert.ok(JSON.stringify(bundle).length<=1000);
  assert.equal((await contextBundle(node.featureServices.evidenceReader,node.featureServices.archiveReader,{projectKey:'other-project'})).recentSessions.length,0);

  const read=(await call('/api/agent-view/material-read?ref='+encodeURIComponent(material.ref))).json();assert.match(read.text,/Generated event 2/);
  assert.equal((await call('/api/agent-view/materials?deviceId=unrelated')).json().items.length,0);
  assert.equal((await call('/api/agent-view/material-read?ref='+encodeURIComponent(material.ref)+'&deviceId=unrelated')).statusCode,404);
  assert.deepEqual((await call('/api/agent-view/materials')).json(),await node.featureServices.archiveReader.materialCatalog!({limit:12}));
  const inventory=(await call('/api/features')).json();
  for(const surface of ['ingress','upload','data','command','agent'])assert.ok(inventory.capabilities.some((c:any)=>c.surface===surface),surface);
  assert.ok(inventory.capabilities.some((c:any)=>c.featureId==='mote.notes'&&c.id==='http:POST:/api/notes'));
  assert.ok(inventory.capabilities.some((c:any)=>c.featureId==='mote.files'&&c.surface==='upload'));
  assert.doesNotMatch(JSON.stringify(inventory),/generated-fixture-token|fixture-only/);
  assert.equal((await call('/api/agent-view/catalog?path=%2Fetc')).statusCode,400);
  assert.equal((await call('/api/agent-view/material-read?ref='+encodeURIComponent('archive:raw-hidden'))).statusCode,400);
  await call('/api/sources/fixture-coding/items/batch','POST',{items:[event(3)]});await node.sourcePipelines.tick();
  assert.notEqual(createInsightSnapshot(node.store,'next-snapshot',scope,node.featureServices.evidenceReader).scopeFingerprint,snapshot.scopeFingerprint);
  assert.equal((await call('/api/agent-view/material-read?ref='+encodeURIComponent(material.ref))).statusCode,404,'old ref cannot regain Agent access');
  assert.equal((await call('/api/materials/'+material.id+'/read?revision='+material.revision)).statusCode,200,'owner can inspect retained revision');
  const captures=Array.from({length:500},()=>({id:randomUUID(),deviceId:'generated-bundle-device',deviceName:'Generated',platform:'macos',source:'activity',capturedAt:'2026-09-24T00:00:00.000Z',durationMs:0,appId:'fixture',appName:'Generated',privacy:{excluded:false,redacted:false,mode:'none',collection:'activity'}}));
  const bulk=await node.app.inject({url:'/api/captures/bundle',method:'POST',headers:{...headers,'content-type':'application/gzip'},payload:gzipSync(captures.map(record=>JSON.stringify(record)).join('\n'))});
  assert.equal(bulk.statusCode,200,bulk.body);assert.equal(bulk.json().results.length,500);assert.ok(bulk.json().results.every((row:{status:number})=>row.status===201));
  await call('/api/source-pipelines/fixture-coding','DELETE');
  assert.equal((await call('/api/agent-view/materials')).json().items.length,0);
  await node.featureHost.dispose('mote.materials');assert.equal((await call('/api/materials')).statusCode,503);await assert.rejects(async()=>node.featureServices.archiveReader.materialCatalog!({}),{statusCode:503});
});

test('feature scope stops recurring work and releases resources exactly once',async t=>{
 const app=Fastify(),root=new Context(),host=new ServerFeatureHost(root,app);let ticks=0,closes=0;
 await host.install({id:'fixture.lifecycle',version:'1',components:[]},(server,scope)=>{scope.every(5,()=>{ticks++;});scope.defer(()=>{closes++;});server.get('/lifecycle',async()=>({ticks}));});
 await app.ready();t.after(async()=>{await host.close();await app.close();await root.fiber.dispose();});
 await new Promise(resolve=>setTimeout(resolve,25));assert.ok(ticks>0);
 host.stop();const stopped=ticks;await new Promise(resolve=>setTimeout(resolve,25));
 assert.equal(ticks,stopped);assert.equal(closes,0);assert.ok(host.registry.inventory().capabilities.length>0);assert.equal((await app.inject('/lifecycle')).statusCode,503);
 await host.dispose('fixture.lifecycle');assert.equal(closes,1);
});

test('stopping a feature blocks admission but keeps resources until disposal',async()=>{
 const scope=new ServerFeatureScope();let work=0,disposed=0;
 scope.defer(()=>{disposed++;});scope.stop();
 await scope.run(()=>{work++;});assert.equal(work,0);assert.equal(disposed,0);
 await Promise.all([scope.close(),scope.close()]);assert.equal(disposed,1);
});

test('Ask, Insight and Import disposal cancels owned execution and fences uncooperative late results',async t=>{
 const directory=mkdtempSync(join(tmpdir(),'mote-feature-stop-'));
 const config:Config={dataDir:directory,token:'generated-feature-token',tokenPath:'fixture-only',host:'127.0.0.1',port:0,maxStorageBytes:10_000_000,maxExportBytes:1_000_000,retentionDays:0,insightIntervalHours:0,allowedOrigins:[],model:'',modelBaseUrl:'',apiKey:'',allowUnauthenticatedLocal:false,embeddingModel:'',embeddingBaseUrl:'',embeddingApiKey:'',logLevel:'silent'};
 let release!:()=>void,entered!:()=>void,importSignal:AbortSignal|undefined;
 const held=new Promise<void>(resolve=>release=resolve),started=new Promise<void>(resolve=>entered=resolve);
 const node=await buildApp(config,{prepareImport:async input=>{importSignal=input.signal;entered();await held;throw Error('Generated late parser failure');}});
 t.after(async()=>{release();await node.app.close();rmSync(directory,{recursive:true,force:true});});await node.app.ready();
 const queryId=randomUUID(),insightId=randomUUID();let querySignal:AbortSignal|undefined,insightSignal:AbortSignal|undefined;
 node.featureServices.queryRuns.start(queryId,{},async(_observe,signal)=>{querySignal=signal;await held;return {conversationId:randomUUID(),turnId:randomUUID()};});
 node.insightRuns.start(insightId,{},async(_observe,signal)=>{insightSignal=signal;await held;return {runId:randomUUID(),answer:'Generated late report',citations:[],trace:[]};});
 const imported=await node.imports.create({files:[{name:'generated.txt',dataBase64:Buffer.from('Generated input').toString('base64')}],instruction:'Generate a preview',processing:'preview'});
 const preparing=node.imports.prepare(imported.id);await started;await new Promise(resolve=>setImmediate(resolve));
 await Promise.all(['mote.ask','mote.insights','mote.imports'].map(feature=>node.featureHost.dispose(feature)));
 assert.equal(querySignal?.aborted,true);assert.equal(insightSignal?.aborted,true);assert.equal(importSignal?.aborted,true);
 assert.equal(node.featureServices.queryRuns.get(queryId).status,'cancelled');assert.equal(node.insightRuns.get(insightId).status,'cancelled');assert.equal(node.imports.get(imported.id).status,'cancelled');
 assert.throws(()=>node.featureServices.queryRuns.start(randomUUID(),{},async()=>({conversationId:randomUUID(),turnId:randomUUID()})),{statusCode:503});
 await assert.rejects(node.imports.prepare(imported.id),{statusCode:503});
 const headers={authorization:'Bearer '+config.token};
 for(const path of ['/api/query-runs','/api/insight-runs','/api/imports'])assert.equal((await node.app.inject({url:path,headers})).statusCode,503);
 assert.equal((await node.app.inject({url:'/api/devices',headers})).statusCode,200,'unrelated feature remains live');
 release();await preparing;await new Promise(resolve=>setImmediate(resolve));
 assert.equal(node.store.insights().length,0);assert.equal(node.insightRuns.get(insightId).status,'cancelled');assert.equal(node.imports.get(imported.id).status,'cancelled');
});

test('Import scope cancels initial container expansion and removes late temporary output while retaining the original',async t=>{
 const directory=mkdtempSync(join(tmpdir(),'mote-feature-container-stop-'));
 const config:Config={dataDir:directory,token:'generated-feature-token',tokenPath:'fixture-only',host:'127.0.0.1',port:0,maxStorageBytes:10_000_000,maxExportBytes:1_000_000,retentionDays:0,insightIntervalHours:0,allowedOrigins:[],model:'',modelBaseUrl:'',apiKey:'',allowUnauthenticatedLocal:false,embeddingModel:'',embeddingBaseUrl:'',embeddingApiKey:'',logLevel:'silent'};
 const node=await buildApp(config);t.after(async()=>{await node.app.close();rmSync(directory,{recursive:true,force:true});});await node.app.ready();
 let entered!:()=>void,release!:()=>void,settled!:()=>void,signal:AbortSignal|undefined,output='';
 const started=new Promise<void>(resolve=>entered=resolve),held=new Promise<void>(resolve=>release=resolve),finished=new Promise<void>(resolve=>settled=resolve);
 node.imports.intake.registerContainer({id:'fixture.uncooperative-container',version:'1',priority:100,probe:()=>true,
  expand:async input=>{signal=input.signal;output=input.output;entered();await held;mkdirSync(output,{recursive:true});
   const path=join(output,'late.txt');writeFileSync(path,'Generated late expanded content');settled();return {files:[{name:'late.txt',path,bytes:31}]};}});
 const creating=node.imports.create({files:[{name:'generated.container',dataBase64:Buffer.from('Generated original container').toString('base64')}],processing:'preview'});
 const rejected=assert.rejects(creating,{name:'AbortError'});await started;
 await node.featureHost.dispose('mote.imports');await rejected;
 assert.equal(signal?.aborted,true);assert.equal(node.imports.list()[0]?.status,'cancelled');
 assert.equal(node.imports.list()[0]?.archive.files,1,'the explicitly uploaded original stays archived');
 assert.equal(existsSync(output),false);release();await finished;await yieldTurn();
 assert.equal(existsSync(output),false,'temporary output from an ignored cancellation is swept after settlement');
 assert.equal(node.imports.list()[0]?.archive.files,1,'late container results cannot publish new archived files');
});

test('Import scope disposes a running binary-upload worker and retains resumable acknowledged parts',async t=>{
 const directory=mkdtempSync(join(tmpdir(),'mote-feature-upload-stop-'));
 const config:Config={dataDir:directory,token:'generated-feature-token',tokenPath:'fixture-only',host:'127.0.0.1',port:0,maxStorageBytes:50_000_000,maxExportBytes:1_000_000,retentionDays:0,insightIntervalHours:0,allowedOrigins:[],model:'',modelBaseUrl:'',apiKey:'',allowUnauthenticatedLocal:false,embeddingModel:'',embeddingBaseUrl:'',embeddingApiKey:'',logLevel:'silent'};
 const node=await buildApp(config);t.after(async()=>{await node.app.close();rmSync(directory,{recursive:true,force:true});});await node.app.ready();
 const headers={authorization:'Bearer '+config.token},body=Buffer.alloc(8*1024*1024,71);
 const begun=(await node.app.inject({url:'/api/import-uploads',method:'POST',headers,payload:{name:'generated-large.bin',sizeBytes:body.length}})).json();
 for(let part=0;part<2;part++)assert.equal((await node.app.inject({url:`/api/import-uploads/${begun.id}/parts/${part}`,method:'PUT',headers:{...headers,'content-type':'application/octet-stream'},payload:body.subarray(part*begun.partBytes,(part+1)*begun.partBytes)})).statusCode,200);
 let entered!:()=>void,signal:AbortSignal|undefined;const started=new Promise<void>(resolve=>entered=resolve);
 const originals=node.featureServices.archivedFiles,putUpload=originals.putUpload.bind(originals);
 originals.putUpload=async(...args)=>{signal=args[4];entered();return putUpload(...args);};
 const committing=node.app.inject({url:`/api/import-uploads/${begun.id}/commit`,method:'POST',headers});await started;
 await node.featureHost.dispose('mote.imports');const response=await committing;
 assert.equal(signal?.aborted,true);assert.notEqual(response.statusCode,200);
 assert.equal(node.store.db.prepare('SELECT count(*) n FROM archived_files').get()!.n,0);
 assert.equal(node.store.db.prepare('SELECT count(*) n FROM asset_pins').get()!.n,0);
 assert.equal(node.store.db.prepare('SELECT count(*) n FROM import_upload_parts').get()!.n,2);
 assert.equal((await node.app.inject({url:'/api/import-uploads',method:'POST',headers,payload:{name:'new.bin',sizeBytes:0}})).statusCode,503);
});
