import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import Fastify from 'fastify';
import {Context} from '@deepseek-ai/cordis';
import {ServerFeatureHost} from '../src/feature-host.js';
import {buildApp} from '../src/app.js';
import type {Config} from '../src/config.js';
test('server feature disposal revokes routes without deleting retained data',async t=>{
  const app=Fastify(),root=new Context(),host=new ServerFeatureHost(root,app);let retained=1;
  const fiber=await host.install({id:'fixture.feature',version:'1',components:[]},server=>server.get('/fixture',async()=>({retained})));
  t.after(async()=>{await app.close();await root.fiber.dispose();});
  assert.equal((await app.inject('/fixture')).json().retained,1);
  assert.ok(host.registry.inventory().capabilities.some(c=>c.id==='http:GET:/fixture'));
  await fiber.dispose();assert.equal(host.registry.inventory().capabilities.length,0);
  assert.equal((await app.inject('/fixture')).statusCode,503);assert.equal(retained,1);
});
test('small Coding upload flows through feature routes to pinned owner and real Agent projections',async t=>{
  const directory=mkdtempSync(join(tmpdir(),'mote-feature-fixture-'));
  const config:Config={dataDir:directory,token:'generated-fixture-token',tokenPath:'fixture-only',host:'127.0.0.1',port:0,maxStorageBytes:10_000_000,maxExportBytes:1_000_000,retentionDays:0,insightIntervalHours:0,allowedOrigins:[],model:'',modelBaseUrl:'',apiKey:'',allowUnauthenticatedLocal:false,embeddingModel:'',embeddingBaseUrl:'',embeddingApiKey:'',logLevel:'silent'};
  const node=await buildApp(config);t.after(async()=>{await node.app.close();rmSync(directory,{recursive:true,force:true});});
  const headers={authorization:'Bearer '+config.token,'x-mote-ingress-version':'2'};
  const call=(url:string,method:'GET'|'POST'|'DELETE'='GET',payload?:unknown)=>node.app.inject({url,method,headers,payload});
  for(const url of ['/api/features','/api/coding/uploads','/api/agent-view/catalog','/api/agent-view/events'])assert.equal((await node.app.inject(url)).statusCode,401);
  assert.equal((await call('/api/sources','POST',{id:'fixture-coding',name:'Generated Coding',kind:'coding-agent',deviceId:'fixture-device',platform:'macos'})).statusCode,200);
  const event=(i:number)=>({externalId:'event-'+i,revision:'1',observedAt:`2026-09-24T01:00:0${i}.000Z`,kind:'message',layer:'original',text:`Generated event ${i}: everyday plugin fixture`,document:{contentRole:'transcript',coding:{version:1,provider:'codex',projectKey:'generated-project',sessionId:'generated-session',eventId:'event-'+i,role:'user',part:0,parts:1}}});
  const sent=await call('/api/sources/fixture-coding/items/batch','POST',{items:[event(0),event(1),event(2)]});assert.equal(sent.statusCode,200,sent.body);
  assert.ok(sent.json().receipts.every((r:any)=>r.receipt.state==='received'));
  assert.equal((await call('/api/coding/uploads')).json().items[0].received.events,3);
  assert.equal((await call('/api/sources/fixture-coding/items/batch','POST',{items:[event(0)]})).statusCode,200);
  assert.equal((await call('/api/coding/uploads')).json().items[0].received.events,3,'retry does not duplicate events');
  await node.sourcePipelines.tick();
  const materials=(await call('/api/agent-view/materials')).json();assert.equal(materials.items.length,1);
  const material=materials.items[0];assert.equal(material.kind,'mote.coding-session');
  const read=(await call('/api/agent-view/material-read?ref='+encodeURIComponent(material.ref))).json();assert.match(read.text,/Generated event 2/);
  assert.equal((await call('/api/agent-view/materials?deviceId=unrelated')).json().items.length,0);
  assert.equal((await call('/api/agent-view/material-read?ref='+encodeURIComponent(material.ref)+'&deviceId=unrelated')).statusCode,404);
  assert.deepEqual((await call('/api/agent-view/materials')).json(),await node.featureServices.archiveReader.materialCatalog!({limit:12}));
  const inventory=(await call('/api/features')).json();
  for(const surface of ['ingress','upload','data','command','agent'])assert.ok(inventory.capabilities.some((c:any)=>c.surface===surface),surface);
  assert.ok(inventory.capabilities.some((c:any)=>c.featureId==='mote.notes'&&c.id==='http:POST:/api/notes'));
  assert.ok(inventory.capabilities.some((c:any)=>c.featureId==='mote.files'&&c.surface==='upload'));
  assert.doesNotMatch(JSON.stringify(inventory),/generated-fixture-token|fixture-only/);
  assert.equal((await call('/api/agent-view/catalog?path=%2Fetc')).statusCode,400);
  assert.equal((await call('/api/agent-view/material-read?ref='+encodeURIComponent('archive:raw-hidden'))).statusCode,400);
  await call('/api/sources/fixture-coding/items/batch','POST',{items:[event(3)]});await node.sourcePipelines.tick();
  assert.equal((await call('/api/agent-view/material-read?ref='+encodeURIComponent(material.ref))).statusCode,404,'old ref cannot regain Agent access');
  assert.equal((await call('/api/materials/'+material.id+'/read?revision='+material.revision)).statusCode,200,'owner can inspect retained revision');
  await call('/api/source-pipelines/fixture-coding','DELETE');
  assert.equal((await call('/api/agent-view/materials')).json().items.length,0);
});
