import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {FILE_PART_BYTES} from '@mote/shared';
import {Store,sha256} from '../src/store.js';
import {SourceStore} from '../src/sources.js';
import {FileStore} from '../src/files.js';
import {ArchivedFileStore} from '../src/archived-files.js';
import {FileRawReader,archivedFileCollectionRef,archivedOriginalRawRef,fileOriginalRawRef,sourceFileCollectionRef} from '../src/file-raw-reader.js';
import {MAX_RAW_PAGE_ITEMS,MAX_RAW_READ_BYTES} from '../src/raw-reader.js';

function fixture(t:import('node:test').TestContext){
  const directory=mkdtempSync(join(tmpdir(),'mote-file-raw-reader-')),store=new Store(directory,{dataKey:'ba'.repeat(32),contentEncryptionEnabled:true});
  const sources=new SourceStore(store),files=new FileStore(store,sources),archived=new ArchivedFileStore(store);
  sources.register({id:'generated-files',name:'Generated file source',kind:'local-files',deviceId:'generated-device',platform:'macos',retention:'archive'});
  let sourceAllowed=true,archiveAllowed=true;
  const reader=new FileRawReader(store,files,archived,{
    mayReadFileVersion:(sourceId)=>sourceAllowed&&sourceId==='generated-files',
    mayReadArchivedFile:()=>archiveAllowed,
    mayListSourceFiles:(sourceId)=>sourceAllowed&&sourceId==='generated-files',
    mayListArchivedFiles:()=>archiveAllowed,
  });
  t.after(()=>{store.close();rmSync(directory,{recursive:true,force:true});});
  return {directory,store,files,archived,reader,allowSource:(value:boolean)=>{sourceAllowed=value;},allowArchive:(value:boolean)=>{archiveAllowed=value;}};
}
async function upload(files:FileStore,externalId:string,bytes:Buffer){
  const input={sourceId:'generated-files',previousRevision:null,item:{externalId,revision:'1',observedAt:'2026-09-24T01:00:00.000Z',kind:'file',layer:'original',mimeType:'application/x-generated'},relativePath:externalId,sizeBytes:bytes.length,sha256:sha256(bytes)};
  const started=files.begin(input,()=>{});
  for(let offset=0;offset<bytes.length;offset+=FILE_PART_BYTES)files.part(started.uploadId,Math.floor(offset/FILE_PART_BYTES),bytes.subarray(offset,offset+FILE_PART_BYTES),()=>{});
  return files.commit(started.uploadId,()=>{});
}

test('file and import refs read bounded ranges from the same content-addressed original',async t=>{
  const {directory,store,files,archived,reader}=fixture(t);
  const bytes=Buffer.alloc(FILE_PART_BYTES+150);for(let i=0;i<bytes.length;i++)bytes[i]=i%251;
  const imported=archived.put({name:'generated.bin',bytes,mimeType:'application/x-generated'});
  const committed=await upload(files,'generated.bin',bytes);
  assert.equal(store.db.prepare('SELECT count(*) n FROM assets').get()!.n,1);
  const fileRef=fileOriginalRawRef(committed.id,sha256(bytes)),archiveRef=archivedOriginalRawRef(imported.id,imported.hash);
  assert.ok(!fileRef.includes(directory));assert.ok(!archiveRef.includes(directory));
  for(const ref of [fileRef,archiveRef]){
    const result=await reader.read(ref,{offset:FILE_PART_BYTES-25,length:100});
    assert.equal(result.status,'available');if(result.status!=='available')continue;
    assert.equal(result.totalBytes,bytes.length);assert.equal(result.mediaType,'application/x-generated');
    assert.deepEqual(Buffer.from(result.bytes),bytes.subarray(FILE_PART_BYTES-25,FILE_PART_BYTES+75));
    assert.equal(result.bytes.buffer.byteLength,result.bytes.length);
    assert.equal(result.nextOffset,FILE_PART_BYTES+75);
    const end=await reader.read(ref,{offset:bytes.length,length:1});assert.equal(end.status,'available');
    if(end.status==='available'){assert.equal(end.bytes.length,0);assert.equal(end.nextOffset,null);}
  }
  const sourcePage=await reader.page({collectionRef:sourceFileCollectionRef('generated-files')});
  assert.equal(sourcePage.status,'available');if(sourcePage.status==='available')assert.deepEqual(sourcePage.items.map(i=>i.ref),[fileRef]);
  const importedPage=await reader.page({collectionRef:archivedFileCollectionRef()});
  assert.equal(importedPage.status,'available');if(importedPage.status==='available')assert.deepEqual(importedPage.items.map(i=>i.ref),[archiveRef]);
});

test('file reader gates each original and reports missing, unavailable and range limits',async t=>{
  const {files,archived,reader,allowSource,allowArchive}=fixture(t);
  const bytes=Buffer.from('Generated bytes only.');
  const committed=await upload(files,'one.bin',bytes),fileRef=fileOriginalRawRef(committed.id,sha256(bytes));
  const imported=archived.put({name:'imported.bin',bytes}),archiveRef=archivedOriginalRawRef(imported.id,imported.hash);
  const reference=await files.revision({sourceId:'generated-files',previousRevision:null,item:{externalId:'reference.bin',revision:'1',observedAt:'2026-09-24T01:00:00.000Z',kind:'file',layer:'reference'},sizeBytes:0,relativePath:'reference.bin'},()=>{});
  assert.equal((await reader.read(fileOriginalRawRef(reference.id,null),{offset:0,length:1})).status,'unavailable');
  assert.equal((await reader.read(fileRef,{offset:0,length:MAX_RAW_READ_BYTES+1})).status,'limit_exceeded');
  assert.equal((await reader.read(fileRef,{offset:-1,length:1})).status,'invalid_range');
  assert.equal((await reader.read(fileRef,{offset:bytes.length+1,length:1})).status,'invalid_range');
  assert.equal((await reader.page({collectionRef:archivedFileCollectionRef(),limit:MAX_RAW_PAGE_ITEMS+1})).status,'limit_exceeded');
  assert.equal((await reader.read(fileOriginalRawRef(committed.id,'0'.repeat(64)),{offset:0,length:1})).status,'missing');
  assert.equal((await reader.read('raw-file:v1:bad',{offset:0,length:1})).status,'missing');
  allowSource(false);allowArchive(false);
  assert.equal((await reader.read(fileRef,{offset:0,length:1})).status,'unavailable');
  assert.equal((await reader.read(archiveRef,{offset:0,length:1})).status,'unavailable');
  assert.equal((await reader.page({collectionRef:sourceFileCollectionRef('generated-files')})).status,'unavailable');
  assert.equal((await reader.page({collectionRef:archivedFileCollectionRef()})).status,'unavailable');
  allowSource(true);allowArchive(true);
  files.forget(committed.id);archived.removeUnreferenced([imported.id],new Set());
  assert.equal((await reader.read(fileRef,{offset:0,length:1})).status,'missing');
  assert.equal((await reader.read(archiveRef,{offset:0,length:1})).status,'missing');
});

test('file collection cursor is invalidated by new originals and preserves access filters',async t=>{
  const {store,files,archived}=fixture(t);
  let allowedId:string|undefined;
  const reader=new FileRawReader(store,files,archived,{
    mayReadFileVersion:(_sourceId,id)=>id!==allowedId,mayReadArchivedFile:()=>true,
    mayListSourceFiles:()=>true,mayListArchivedFiles:()=>true,
  });
  const first=await upload(files,'first.bin',Buffer.from('Generated first'));
  const second=await upload(files,'second.bin',Buffer.from('Generated second'));
  const collectionRef=sourceFileCollectionRef('generated-files');
  const page=await reader.page({collectionRef,limit:1});assert.equal(page.status,'available');if(page.status!=='available')return;
  assert.equal(page.total,2);assert.ok(page.nextCursor);
  allowedId=second.id;
  assert.equal((await reader.page({collectionRef,limit:1,cursor:page.nextCursor!})).status,'stale_cursor');
  const filtered=await reader.page({collectionRef});assert.equal(filtered.status,'available');
  if(filtered.status==='available')assert.deepEqual(filtered.items.map(item=>item.ref),[fileOriginalRawRef(first.id,sha256(Buffer.from('Generated first')))]);
});
