import test,{type TestContext} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {FILE_PART_BYTES,type FileRevision} from '@mote/shared';
import {buildApp} from '../src/app.js';
import type {Config} from '../src/config.js';
import {sha256} from '../src/store.js';
import {readAgentCredential} from './login-fixture.js';
import {fixtureFilePolicy} from './fixtures/file-policy.js';
import {FileEvidenceRequests} from '../src/file-evidence.js';

/** Disposable generated bytes only; no host configuration, real files or models. */
async function fixture(t:TestContext){
 const directory=mkdtempSync(join(tmpdir(),'mote-snapshot-recovery-'));
 const token='generated-snapshot-recovery-owner';
 const config:Config={dataDir:directory,token,tokenPath:'fixture',host:'127.0.0.1',port:0,maxStorageBytes:100_000_000,maxExportBytes:1_000_000,retentionDays:0,insightIntervalHours:0,allowedOrigins:[],model:'',modelProvider:'custom',modelProtocol:'openai-completions',modelBaseUrl:'http://127.0.0.1:1/v1',apiKey:'',allowUnauthenticatedLocal:true,embeddingModel:'',embeddingBaseUrl:'',embeddingApiKey:'',diagnosticsEnabled:false,contentEncryptionEnabled:true,dataKey:'75'.repeat(32)};
 const node=await buildApp(config,{backgroundWorker:false,agent:{configured:false,query:async()=>{throw Error('No model expected in transport fixture');},close:async()=>{}}});
 await node.app.ready();
 node.sources.register({id:'generated-source',name:'Generated snapshot source',kind:'local-files',deviceId:'generated-device',platform:'macos',retention:'snapshot'});
 const headers={authorization:'Bearer '+token};
 const request=(method:'GET'|'POST'|'PUT',url:string,payload?:any,selectedHeaders=headers)=>node.app.inject({method,url,headers:selectedHeaders,...(payload===undefined?{}:{payload})});
 const recovery=()=>request('GET','/api/file-sync/v1/recovery?sourceId=generated-source');
 const begin=(manifest:FileRevision)=>request('POST','/api/file-sync/v1/uploads',manifest);
 const commit=(uploadId:string)=>request('POST',`/api/file-sync/v1/uploads/${uploadId}/commit`,{});
 const sendParts=async(uploadId:string,bytes:Buffer)=>{for(let n=0;n<Math.ceil(bytes.length/FILE_PART_BYTES);n++){const response=await request('PUT',`/api/file-sync/v1/uploads/${uploadId}/parts/${n}`,bytes.subarray(n*FILE_PART_BYTES,(n+1)*FILE_PART_BYTES),{...headers,'content-type':'application/octet-stream'});assert.equal(response.statusCode,200,response.body);}};
 const upload=async(manifest:FileRevision,bytes:Buffer)=>{const response=await begin(manifest);assert.equal(response.statusCode,200,response.body);const session=response.json();assert.equal(session.ack,null);await sendParts(session.uploadId,bytes);const committed=await commit(session.uploadId);assert.equal(committed.statusCode,200,committed.body);return {session,ack:committed.json()};};
 const expire=(captureId:string)=>{node.store.db.prepare('UPDATE file_snapshot_inputs SET expires=0 WHERE capture_id=?').run(captureId);node.files.sweepSnapshotInputs();};
 t.after(async()=>{await node.app.close();rmSync(directory,{recursive:true,force:true});});
 return {node,headers,request,recovery,begin,commit,sendParts,upload,expire};
}

function manifest(bytes:Buffer,key='generated-file',revision=sha256(bytes),previousRevision:string|null=null):FileRevision{
 const hash=sha256(bytes);
 return {sourceId:'generated-source',previousRevision,relativePath:key+'.txt',sizeBytes:bytes.length,sha256:hash,item:{externalId:key,revision,observedAt:'2026-10-01T00:00:00Z',title:key,kind:'file',layer:'snapshot',text:'',mimeType:'text/plain',deleted:false,document:{fileIndex:{version:1,fileId:key,contentVersion:hash,mode:'index',coverage:'none',parser:'central-pending',status:'pending',totalCharacters:0,offset:0,length:0,maxIndexCharacters:8000,allowRead:false}}}};
}

function requestIdentity(captureId:string,input:FileRevision){return {captureId,externalId:input.item.externalId,revision:input.item.revision,sha256:input.sha256,sizeBytes:input.sizeBytes,observedAt:input.item.observedAt};}

test('HTTP recovery resupplies an expired snapshot under its immutable version and lost ACK remains idempotent',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated immutable recovery text'),input=manifest(bytes),initial=await f.upload(input,bytes);
 f.expire(initial.ack.id);await f.node.processing.tick();assert.equal(f.node.files.detail(initial.ack.id).job?.error,'snapshot_input_expired');
 assert.deepEqual((await f.recovery()).json(),{items:[requestIdentity(initial.ack.id,input)]});
 const metadata=await f.request('PUT','/api/file-sync/v1/revisions',input);assert.equal(metadata.statusCode,200,metadata.body);assert.equal(metadata.json().duplicate,true);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_inputs').get()!.n,0,'metadata ACK alone cannot restore missing bytes');
 const response=await f.begin(input);assert.equal(response.statusCode,200,response.body);const session=response.json();assert.equal(session.ack,null);assert.deepEqual(session.parts,[]);assert.equal(session.uploadId,initial.session.uploadId,'an acknowledged session is reset for bounded resupply');
 const restarted=f.node.files.upload(session.uploadId,()=>{});assert.equal(restarted.ack,null);await f.sendParts(session.uploadId,bytes);
 const committed=await f.commit(session.uploadId);assert.equal(committed.statusCode,200,committed.body);const ack=committed.json();assert.equal(ack.id,initial.ack.id);assert.equal(ack.receipt.version,2);assert.equal(ack.receipt.state,'received');
 assert.deepEqual((await f.commit(session.uploadId)).json(),ack,'a lost commit ACK does not publish a second revision');
 assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_versions').get()!.n,1);assert.equal(f.node.sources.history(input.sourceId,input.item.externalId).length,1);
 assert.deepEqual(Buffer.concat([...f.node.files.processingBytes(ack.id)]),bytes);assert.equal(f.node.files.detail(ack.id).job?.state,'waiting');assert.deepEqual((await f.recovery()).json(),{items:[]});
 await f.node.processing.tick();assert.equal(f.node.files.detail(ack.id).job?.state,'succeeded');assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_inputs').get()!.n,0);assert.throws(()=>[...f.node.files.bytes(ack.id)],{statusCode:404});
});

test('completed snapshots return duplicate ACK and cannot restart their successful extraction',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated completed recovery fixture'),input=manifest(bytes);let calls=0;
 const processor=f.node.processing.runtime.registry.get('text.utf8'),execute=processor.process;processor.process=async args=>{calls++;return execute(args);};
 const {ack}=await f.upload(input,bytes);await f.node.processing.tick();assert.equal(calls,1);const steps=f.node.store.db.prepare('SELECT artifact_id,attempts FROM file_steps WHERE capture_id=?').all(ack.id);
 assert.deepEqual((await f.recovery()).json(),{items:[]});const response=await f.begin(input);assert.equal(response.statusCode,200,response.body);assert.equal(response.json().ack.duplicate,true);assert.equal(response.json().ack.id,ack.id);
 await f.node.processing.tick();assert.equal(calls,1);assert.deepEqual(f.node.store.db.prepare('SELECT artifact_id,attempts FROM file_steps WHERE capture_id=?').all(ack.id),steps);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_inputs').get()!.n,0);
});

test('cancelled snapshots require owner retry before recovery can restore temporary bytes',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated explicit retry fixture'),input=manifest(bytes),{ack}=await f.upload(input,bytes);
 const cancelled=await f.request('POST',`/api/files/${ack.id}/cancel`,{});assert.equal(cancelled.statusCode,200,cancelled.body);assert.equal(f.node.files.detail(ack.id).job?.state,'cancelled');assert.deepEqual((await f.recovery()).json(),{items:[]});
 const duplicate=await f.begin(input);assert.equal(duplicate.statusCode,200,duplicate.body);assert.equal(duplicate.json().ack.duplicate,true);await f.node.processing.tick();assert.equal(f.node.files.detail(ack.id).job?.state,'cancelled');assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_inputs').get()!.n,0);
 const retried=await f.request('POST',`/api/files/${ack.id}/retry`,{});assert.equal(retried.statusCode,200,retried.body);assert.deepEqual((await f.recovery()).json(),{items:[requestIdentity(ack.id,input)]});
 const session=(await f.begin(input)).json();assert.equal(session.ack,null);await f.sendParts(session.uploadId,bytes);const restored=await f.commit(session.uploadId);assert.equal(restored.statusCode,200,restored.body);assert.equal(restored.json().id,ack.id);await f.node.processing.tick();assert.equal(f.node.files.detail(ack.id).job?.state,'succeeded');
});

test('recovery authorization and strict schema exclude agents, revoked sessions and unrelated request fields',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated private transport fixture'),{ack}=await f.upload(manifest(bytes),bytes);f.expire(ack.id);
 assert.equal((await f.node.app.inject('/api/file-sync/v1/recovery?sourceId=generated-source')).statusCode,401);
 const agent=await readAgentCredential(f.node.connections);assert.equal((await f.request('GET','/api/file-sync/v1/recovery?sourceId=generated-source',undefined,{authorization:'Bearer '+agent.token})).statusCode,403);
 const owner=await f.node.connections.session('http://127.0.0.1:57569','Generated recovery owner');const ownerHeaders={authorization:'Bearer '+owner.token};assert.equal((await f.request('GET','/api/file-sync/v1/recovery?sourceId=generated-source',undefined,ownerHeaders)).statusCode,200);await f.node.connections.revoke(owner.credentialId);assert.equal((await f.request('GET','/api/file-sync/v1/recovery?sourceId=generated-source',undefined,ownerHeaders)).statusCode,401);
 for(const url of ['/api/file-sync/v1/recovery','/api/file-sync/v1/recovery?sourceId=','/api/file-sync/v1/recovery?sourceId=generated-source&deviceId=other','/api/file-sync/v1/recovery?sourceId=generated-source&cursor=1'])assert.equal((await f.request('GET',url)).statusCode,400,url);
 assert.equal((await f.request('GET','/api/file-sync/v1/recovery?sourceId=missing')).statusCode,404);
});

test('source revocation, reference retention, head replacement and forgotten files cannot regain snapshot input',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated source grant fixture'),input=manifest(bytes),{ack}=await f.upload(input,bytes);f.expire(ack.id);
 f.node.sources.update(input.sourceId,{enabled:false});assert.deepEqual((await f.recovery()).json(),{items:[]});assert.equal((await f.begin(input)).statusCode,409);
 f.node.sources.update(input.sourceId,{enabled:true,retention:'reference'});assert.deepEqual((await f.recovery()).json(),{items:[]});assert.equal((await f.begin(input)).statusCode,409);
 f.node.sources.update(input.sourceId,{retention:'snapshot'});const recovery=(await f.begin(input)).json();assert.equal(recovery.ack,null);await f.sendParts(recovery.uploadId,bytes);
 const successorBytes=Buffer.from('Generated successor fixture'),successor=manifest(successorBytes,input.item.externalId,'next',input.item.revision);await f.upload(successor,successorBytes);const stale=await f.commit(recovery.uploadId);assert.equal(stale.statusCode,200,stale.body);assert.equal(stale.json().duplicate,true);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_inputs WHERE capture_id=?').get(ack.id)!.n,0,'stale recovery cannot create an input grant');
 f.node.files.forget(ack.id);assert.deepEqual((await f.recovery()).json(),{items:[]});assert.equal((await f.begin(input)).statusCode,410);
});

test('snapshot restoration verifies exact manifest, bounded bytes and content hash before granting input',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated digest validation'),input=manifest(bytes),{ack}=await f.upload(input,bytes);f.expire(ack.id);
 assert.equal((await f.begin({...input,sizeBytes:input.sizeBytes+1})).statusCode,409);assert.equal((await f.begin({...input,item:{...input.item,title:'Changed metadata'}})).statusCode,409);
 assert.equal((await f.begin({...input,sizeBytes:16*1024*1024+1})).statusCode,400);assert.equal((await f.begin({...input,sha256:'invalid'})).statusCode,400);
 const wrongHash='a'.repeat(64);assert.equal((await f.begin({...input,sha256:wrongHash,item:{...input.item,document:{...input.item.document,fileIndex:{...input.item.document!.fileIndex!,contentVersion:wrongHash}}}})).statusCode,409);
 const session=(await f.begin(input)).json();const undersized=await f.request('PUT',`/api/file-sync/v1/uploads/${session.uploadId}/parts/0`,bytes.subarray(1),{...f.headers,'content-type':'application/octet-stream'});assert.equal(undersized.statusCode,400);
 const wrong=Buffer.alloc(bytes.length,7);await f.sendParts(session.uploadId,wrong);const rejected=await f.commit(session.uploadId);assert.equal(rejected.statusCode,409,rejected.body);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_inputs').get()!.n,0);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_versions').get()!.n,1);
});

test('resupplying an acknowledged snapshot remains subject to the unfinished upload session bound',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated upload bound fixture'),input=manifest(bytes),{ack}=await f.upload(input,bytes);f.expire(ack.id);
 for(let n=0;n<64;n++)assert.equal(f.node.files.begin(manifest(bytes,'pending-'+n),()=>{}).ack,null);
 const rejected=await f.begin(input);assert.equal(rejected.statusCode,429,rejected.body);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_uploads WHERE ack IS NULL').get()!.n,64);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_inputs').get()!.n,0);
});

test('valid pending inputs do not hide later missing snapshot inputs behind the recovery bound',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated bounded recovery fixture');
 let expected:ReturnType<typeof requestIdentity>|undefined;
 for(let n=0;n<201;n++){
  const input=manifest(bytes,'ordered-'+n),ack=await f.node.files.revision(input,()=>{},id=>({id}));
  if(n===200){f.node.files.releaseSnapshotInput(ack.id);expected=requestIdentity(ack.id,input);}
 }
 assert.deepEqual((await f.recovery()).json(),{items:[expected]});
});

test('an obsolete extraction artifact after a crash cannot suppress recovery for the current processor version',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated crash and processor replacement'),input=manifest(bytes),{ack}=await f.upload(input,bytes);
 await f.node.processing.tick();assert.equal(f.node.files.detail(ack.id).job?.state,'succeeded');
 // Reproduce the durable crash boundary: extraction exists, raw input was swept,
 // and the parent pipeline has not durably projected its success yet.
 f.node.store.db.prepare("UPDATE file_jobs SET state='waiting',error=NULL WHERE capture_id=?").run(ack.id);
 const processor=f.node.processing.runtime.registry.get('text.utf8');processor.version+='-generated-upgrade';
 await f.node.processing.tick();assert.equal(f.node.files.detail(ack.id).job?.state,'blocked');assert.equal(f.node.files.detail(ack.id).job?.error,'snapshot_input_expired');
 assert.deepEqual((await f.recovery()).json(),{items:[requestIdentity(ack.id,input)]});
 const response=await f.request('POST',`/api/file-sync/v1/recovery/${ack.id}/uploads`,{});assert.equal(response.statusCode,200,response.body);const session=response.json();await f.sendParts(session.uploadId,bytes);assert.equal((await f.commit(session.uploadId)).statusCode,200);
 await f.node.processing.tick();assert.equal(f.node.files.detail(ack.id).job?.state,'succeeded');assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_inputs').get()!.n,0);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_versions').get()!.n,1);
});

test('opaque recovery sessions use the stored manifest and completed races return a valid existing receipt',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated opaque transport fixture'),input=manifest(bytes),{ack}=await f.upload(input,bytes);
 f.expire(ack.id);const original=f.node.files.version(ack.id).manifest;
 const url=`/api/file-sync/v1/recovery/${ack.id}/uploads`,response=await f.request('POST',url,{});assert.equal(response.statusCode,200,response.body);const session=response.json();assert.equal(session.ack,null);
 assert.equal(f.node.store.db.prepare('SELECT manifest FROM file_uploads WHERE id=?').get(session.uploadId)!.manifest,original,'server owns the immutable manifest; client only sends bytes');
 await f.sendParts(session.uploadId,bytes);const committed=await f.commit(session.uploadId);assert.equal(committed.statusCode,200,committed.body);assert.equal(committed.json().id,ack.id);
 let calls=0;const processor=f.node.processing.runtime.registry.get('text.utf8'),execute=processor.process;processor.process=async args=>{calls++;return execute(args);};await f.node.processing.tick();assert.equal(calls,1);
 assert.equal(f.node.files.version(ack.id).manifest,original);assert.equal(f.node.files.detail(ack.id).item.document?.fileIndex?.status,'ready','public index metadata can change without changing the ingress manifest');
 const duplicate=await f.request('POST',url,{});assert.equal(duplicate.statusCode,200,duplicate.body);assert.equal(duplicate.json().ack.duplicate,true);assert.deepEqual(duplicate.json().ack.receipt,{version:2,id:ack.id,kind:'file-revision',state:'received',duplicate:true,sourceId:input.sourceId,externalId:input.item.externalId,revision:input.item.revision});
 await f.node.processing.tick();assert.equal(calls,1);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_inputs').get()!.n,0);assert.equal(f.node.sources.history(input.sourceId,input.item.externalId).length,1);
});

test('opaque recovery rejects remote paths, resource identity overrides and grants outside the current snapshot',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated opaque authorization fixture'),input=manifest(bytes),{ack}=await f.upload(input,bytes);f.expire(ack.id);
 const url=`/api/file-sync/v1/recovery/${ack.id}/uploads`;
 for(const payload of [{sourceId:'other'},{relativePath:'/private/generated-forbidden.txt'},{sha256:input.sha256},{revision:'other'},{manifest:input}])assert.equal((await f.request('POST',url,payload)).statusCode,400);
 assert.equal((await f.request('POST','/api/file-sync/v1/recovery/not-a-uuid/uploads',{})).statusCode,400);assert.equal((await f.request('POST',`/api/file-sync/v1/recovery/${randomUUID()}/uploads`,{})).statusCode,404);
 assert.equal((await f.node.app.inject({method:'POST',url,payload:{}})).statusCode,401);const agent=await readAgentCredential(f.node.connections);assert.equal((await f.request('POST',url,{}, {authorization:'Bearer '+agent.token})).statusCode,403);
 f.node.sources.update(input.sourceId,{enabled:false});assert.equal((await f.request('POST',url,{})).statusCode,409);f.node.sources.update(input.sourceId,{enabled:true,retention:'reference'});assert.equal((await f.request('POST',url,{})).statusCode,409);
 f.node.sources.update(input.sourceId,{retention:'snapshot'});f.node.processing.cancel(ack.id);const cancelled=await f.request('POST',url,{});assert.equal(cancelled.statusCode,200,cancelled.body);assert.equal(cancelled.json().ack.duplicate,true);assert.equal(f.node.files.detail(ack.id).job?.state,'cancelled');assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_inputs').get()!.n,0);
 const successorBytes=Buffer.from('Generated opaque next version');await f.upload(manifest(successorBytes,input.item.externalId,'next',input.item.revision),successorBytes);assert.equal((await f.request('POST',url,{})).statusCode,409);
 assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_inputs WHERE capture_id=?').get(ack.id)!.n,0);f.node.files.forget(ack.id);assert.equal((await f.request('POST',url,{})).statusCode,404);
});

test('revoking an owner during recovery assembly prevents commit and releases its temporary asset',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated revocation during assembly'),input=manifest(bytes),{ack}=await f.upload(input,bytes);f.expire(ack.id);
 const owner=await f.node.connections.session('http://127.0.0.1:57569','Generated recovery assembly owner'),headers={authorization:'Bearer '+owner.token};
 const response=await f.request('POST',`/api/file-sync/v1/recovery/${ack.id}/uploads`,{},headers);assert.equal(response.statusCode,200,response.body);const session=response.json();await f.sendParts(session.uploadId,bytes);
 const put=f.node.store.assets.putUpload.bind(f.node.store.assets);let release!:()=>void,started!:()=>void;const begun=new Promise<void>(resolve=>started=resolve),gate=new Promise<void>(resolve=>release=resolve);
 f.node.store.assets.putUpload=async(...args)=>{const asset=await put(...args);started();await gate;return asset;};
 const pending=f.request('POST',`/api/file-sync/v1/uploads/${session.uploadId}/commit`,{},headers);await begun;await f.node.connections.revoke(owner.credentialId);release();const rejected=await pending;assert.equal(rejected.statusCode,401,rejected.body);
 assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_inputs').get()!.n,0);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM asset_pins').get()!.n,0);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_versions').get()!.n,1);
 f.node.store.assets.putUpload=put;const committed=await f.commit(session.uploadId);assert.equal(committed.statusCode,200,committed.body);assert.equal(committed.json().id,ack.id,'another current owner can finish the same immutable version');
});

test('reference retention revokes an in-flight snapshot and cannot publish or retain temporary content',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated reference-revoked audio'),input=manifest(bytes);input.item.mimeType='audio/wav';input.item.document!.fileIndex!.allowRead=true;
 const {ack}=await f.upload(input,bytes);await f.node.processing.runtime.ready;
 const settings={...f.node.processing.view().settings,audioProcessor:'audio.http'};f.node.processing.update({revision:f.node.processing.view().revision,settings,policy:fixtureFilePolicy(settings,f.node.processing.runtime.registry)});
 let started!:()=>void,release!:(value:any)=>void;const begun=new Promise<void>(resolve=>started=resolve);
 f.node.processing.runtime.registry.get('audio.http').process=async()=>{started();return new Promise(resolve=>release=resolve);};
 const pending=f.node.processing.tick();await begun;f.node.sources.update(input.sourceId,{retention:'reference'});f.node.files.sweep();
 try{assert.throws(()=>[...f.node.files.processingBytes(ack.id)]);}finally{release({durationMs:1000,segments:[{startMs:0,endMs:1000,text:'Revoked generated transcript must never publish'}]});}await pending;f.node.files.sweep();
 assert.equal(f.node.files.chunks(ack.id).length,0);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_inputs').get()!.n,0);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_text').get()!.n,0);assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_artifacts').get()!.n,0);assert.deepEqual((await f.recovery()).json(),{items:[]});
 assert.throws(()=>f.node.store.assets.get(sha256(bytes)),{statusCode:404});
});

test('reference retention revokes previously granted snapshot text ranges and sweeps their retained text asset',async t=>{
 const f=await fixture(t),bytes=Buffer.from('Generated snapshot full-text grant'),input=manifest(bytes);input.item.document!.fileIndex!.allowRead=true;
 const {ack}=await f.upload(input,bytes);await f.node.processing.tick();const requests=new FileEvidenceRequests(f.node.sources);assert.equal((await requests.read(ack.id,0,9)).status,'ready');
 const textHash=String(f.node.store.db.prepare('SELECT object_hash FROM file_snapshot_text WHERE capture_id=?').get(ack.id)!.object_hash);f.node.sources.update(input.sourceId,{retention:'reference'});
 await assert.rejects(requests.read(ack.id,0,9),{statusCode:409});f.node.files.sweep();assert.equal(f.node.store.db.prepare('SELECT COUNT(*) n FROM file_snapshot_text').get()!.n,0);assert.throws(()=>f.node.store.assets.get(textHash),{statusCode:404});
});
