import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {FILE_PART_BYTES,type FileRevision} from '@mote/shared';
import {Store,sha256} from '../src/store.js';
import {SourceStore} from '../src/sources.js';
import {FileStore} from '../src/files.js';
import {FileProcessing,type TranscriptionProvider} from '../src/file-processing.js';
import {buildApp} from '../src/app.js';
import {configFromEnv} from '../src/config.js';

function fixture(t:any,key?:string){const dir=mkdtempSync(join(tmpdir(),'mote-files-'));const options={dataKey:key,contentEncryptionEnabled:Boolean(key),maxStorageBytes:100*1024*1024};const store=new Store(dir,options);const sources=new SourceStore(store),files=new FileStore(store,sources);sources.register({id:'phone',name:'Synthetic phone',kind:'local-files',deviceId:'phone',platform:'android',retention:'archive'});t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});return {dir,store,sources,files,options};}
const owner=()=>{};
function manifest(bytes:Buffer,revision='v1',previousRevision:string|null=null):FileRevision{return {sourceId:'phone',previousRevision,item:{externalId:'content://generated/recording',revision,observedAt:new Date().toISOString(),title:'合成录音.wav',kind:'file',layer:'original',text:'',mimeType:'audio/wav',deleted:false},relativePath:'calls/合成录音.wav',sizeBytes:bytes.length,sha256:sha256(bytes)};}
async function upload(files:FileStore,input:FileRevision,bytes:Buffer){const session=files.begin(input,owner);for(let n=0;n<Math.ceil(bytes.length/FILE_PART_BYTES);n++)files.part(session.uploadId,n,bytes.subarray(n*FILE_PART_BYTES,(n+1)*FILE_PART_BYTES),owner);return files.commit(session.uploadId,owner);}

test('original bytes resume after reconstruction, ACK loss, encryption and ranged reads',async t=>{
 const {store,sources,files}=fixture(t,'41'.repeat(32)),bytes=Buffer.alloc(FILE_PART_BYTES+100123,7),m=manifest(bytes);
 const begun=files.begin(m,owner);files.part(begun.uploadId,0,bytes.subarray(0,FILE_PART_BYTES),owner);
 await assert.rejects(files.commit(begun.uploadId,owner),{statusCode:409});
 const resumed=new FileStore(store,sources);assert.equal(resumed.begin(m,owner).uploadId,begun.uploadId);assert.equal(resumed.upload(begun.uploadId,owner).parts.length,1);
 assert.throws(()=>resumed.part(begun.uploadId,0,Buffer.alloc(FILE_PART_BYTES,8),owner),{statusCode:409});
 resumed.part(begun.uploadId,1,bytes.subarray(FILE_PART_BYTES),owner);const ack=await resumed.commit(begun.uploadId,owner);
 assert.equal(ack.sha256,sha256(bytes));assert.deepEqual(await resumed.commit(begun.uploadId,owner),ack);
 assert.deepEqual(Buffer.concat([...resumed.bytes(ack.id)]),bytes);assert.deepEqual(Buffer.concat([...resumed.bytes(ack.id,FILE_PART_BYTES-20,FILE_PART_BYTES+20)]),bytes.subarray(FILE_PART_BYTES-20,FILE_PART_BYTES+21));
 assert.notDeepEqual(readFileSync(join(resumed.objects,ack.sha256,'0.aes')),bytes.subarray(0,FILE_PART_BYTES));
 assert.equal(store.list().items.length,1);assert.equal(resumed.list().items.length,1);assert.equal(store.prune('2099-01-01T00:00:00Z'),0);
 assert.throws(()=>store.exportArchive(10000000),{statusCode:409});
 resumed.sweep();assert.throws(()=>resumed.upload(begun.uploadId,owner),{statusCode:404});
 const receipt=resumed.begin(m,owner);assert.equal(receipt.ack?.id,ack.id);assert.equal(receipt.ack?.duplicate,true);
 assert.equal(store.db.prepare('SELECT COUNT(*) n FROM file_uploads').get()!.n,0);
});

test('two source locations share bytes, source deletion retains archive and restoring content gets a new revision',async t=>{
 const {store,sources,files}=fixture(t),bytes=Buffer.from('generated bytes');const first=await upload(files,manifest(bytes),bytes);
 sources.register({id:'nas',name:'Synthetic NAS',kind:'local-files',deviceId:'nas',platform:'linux',retention:'archive'});
 await upload(files,{...manifest(bytes),sourceId:'nas'},bytes);assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM file_objects').get()!.n,1);
 const deleted=manifest(bytes,'removed','v1');delete deleted.sha256;deleted.item.deleted=true;
 await files.revision(deleted,owner);assert.equal(files.detail(first.id).originMissing,true);assert.equal(files.list().items.length,2);assert.ok(store.search({query:'合成录音'}).some(r=>r.id===first.id));
 const restored=await upload(files,manifest(bytes,'restored','removed'),bytes);assert.notEqual(restored.id,first.id);assert.equal(files.detail(restored.id).originMissing,false);
 assert.equal(files.list().items.length,2);assert.equal(sources.history('phone',deleted.item.externalId).length,3);
});

test('reference handles a huge external file without bytes or processing; version conflicts are rejected',async t=>{
 const {store,files}=fixture(t);const m=manifest(Buffer.alloc(0));m.item.layer='reference';m.sizeBytes=10**12;delete m.sha256;
 const ack=await files.revision(m,owner);assert.equal(files.detail(ack.id).hasOriginal,false);assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM file_jobs').get()!.n,0);
 assert.equal(readdirSync(files.objects).length,0);assert.throws(()=>files.begin(m,owner));
 await assert.rejects(files.revision({...m,item:{...m.item,title:'conflict'}},owner),{statusCode:409});
 await assert.rejects(files.revision({...m,item:{...m.item,revision:'out-of-order'},previousRevision:'missing'},owner),{statusCode:409});
 await assert.rejects(files.revision({...m,item:{...m.item,text:'hidden body'}},owner));
});

test('processor builds timestamped layers and tail search, source removal retains them, forget blocks resurrection',async t=>{
 const {files,store}=fixture(t),bytes=Buffer.from('synthetic audio placeholder'),ack=await upload(files,manifest(bytes),bytes);let calls=0;
 const provider:TranscriptionProvider={transcribe:async()=>{calls++;return {durationMs:90000,segments:[{startMs:0,endMs:1000,text:'计划下周联系对方，并未完成。'},{startMs:89000,endMs:90000,text:'尾部校验：项目代号青杉，金额三百元。'}]};}};
 const processing=new FileProcessing(files,provider,async records=>({answer:`合成摘要 [${records[0].id}]`,citations:[{id:records[0].id}]}));t.after(()=>processing.close());
 await processing.tick();assert.equal(files.detail(ack.id).job.state,'blocked');
 processing.update({revision:processing.view().revision,settings:{...processing.view().settings,enabled:true,summarize:true}});await processing.tick();
 assert.equal(calls,1);assert.equal(files.detail(ack.id).job.state,'succeeded');assert.equal(files.detail(ack.id).job.summary_state,'succeeded');
 const tail=files.search({query:'青杉'});assert.equal(tail.length,1);assert.deepEqual(files.search({query:'青杉 金额'}).map(r=>r.id),tail.map(r=>r.id));assert.deepEqual(files.search({query:'青杉 三百元'}).map(r=>r.id),tail.map(r=>r.id));assert.equal((tail[0].fileEvidence as any).startMs,89000);assert.equal(files.search({query:'青杉',deviceId:'other'}).length,0);
 const deletion=manifest(bytes,'removed','v1');delete deletion.sha256;deletion.item.deleted=true;await files.revision(deletion,owner);assert.equal(files.search({query:'青杉'}).length,1);
 files.forget(ack.id);assert.equal(files.evidence(tail.map(r=>r.id)).length,0);assert.equal(files.search({query:'青杉'}).length,0);assert.equal(store.db.prepare('SELECT count(*) AS n FROM file_chunks_trigram WHERE id=?').get(tail[0].id)!.n,0);
 await assert.rejects(upload(files,manifest(bytes,'v3','removed'),bytes),{statusCode:410});
 assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM file_artifacts').get()!.n,0);
});

test('deleting a file while ASR is in flight cannot recreate derived content',async t=>{
 const {files,store}=fixture(t),bytes=Buffer.from('race fixture'),ack=await upload(files,manifest(bytes),bytes);
 let release!:(v:any)=>void,started!:()=>void;const begun=new Promise<void>(r=>{started=r;});
 const processing=new FileProcessing(files,{transcribe:async()=>{started();return new Promise(r=>{release=r;});}});t.after(()=>processing.close());
 processing.update({revision:processing.view().revision,settings:{...processing.view().settings,enabled:true}});
 const running=processing.tick();await begun;files.forget(ack.id);release({durationMs:1000,segments:[{startMs:0,endMs:1000,text:'must disappear'}]});await running;
 assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM file_chunks').get()!.n,0);
});

test('processing settings never expose credentials or silently reuse them at another endpoint',t=>{
 const {files}=fixture(t),processing=new FileProcessing(files);t.after(()=>processing.close());
 const initial=processing.view();processing.update({revision:initial.revision,settings:{...initial.settings,apiKey:'synthetic-secret'}});
 assert.ok(!JSON.stringify(processing.view()).includes('synthetic-secret'));
 assert.throws(()=>processing.update({revision:processing.view().revision,settings:{...processing.view().settings,endpoint:'https://example.test/transcribe',allowRemote:true}}),{statusCode:409});
 assert.throws(()=>processing.update({revision:processing.view().revision,settings:{...processing.view().settings,endpoint:'http://example.test/transcribe',apiKey:null}}));
});

test('HTTP binary ingest, authenticated playback cookie, range, unauthenticated denial and source scoping',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'mote-file-http-'));const priorEnv=process.env.MOTE_ENV_FILE;const env=join(dir,'test.env');writeFileSync(env,`MOTE_DATA_DIR=${dir}
MOTE_TOKEN=generated-files-owner-token-1234567890
MOTE_MODEL=
MOTE_LOG_LEVEL=silent
`);process.env.MOTE_ENV_FILE=env;let config;try{config=configFromEnv();}finally{if(priorEnv===undefined)delete process.env.MOTE_ENV_FILE;else process.env.MOTE_ENV_FILE=priorEnv;}
 const {app,connections}=await buildApp(config,{agent:{configured:false,query:async()=>{throw Error();},close:async()=>{}}});t.after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});
 const headers={authorization:`Bearer ${config.token}`};
 await app.inject({method:'POST',url:'/api/sources',headers,payload:{id:'phone',name:'Generated',kind:'local-files',deviceId:'phone',platform:'android',retention:'archive'}});
 const bytes=Buffer.from('0123456789'),m=manifest(bytes);
 const started=await app.inject({method:'POST',url:'/api/file-sync/v1/uploads',headers,payload:m});assert.equal(started.statusCode,200,started.body);const session=started.json();
 assert.equal((await app.inject({method:'PUT',url:`/api/file-sync/v1/uploads/${session.uploadId}/parts/0`,headers:{...headers,'content-type':'application/octet-stream'},payload:bytes})).statusCode,200);
 const committed=await app.inject({method:'POST',url:`/api/file-sync/v1/uploads/${session.uploadId}/commit`,headers,payload:{}});assert.equal(committed.statusCode,200,committed.body);const ack=committed.json();
 assert.equal((await app.inject(`/api/files/${ack.id}/content`)).statusCode,401);
 const playback=await app.inject({method:'POST',url:`/api/files/${ack.id}/playback`,headers,payload:{}});assert.equal(playback.statusCode,200);const cookie=String(playback.headers['set-cookie']).split(';')[0];
 const content=await app.inject({url:`/api/files/${ack.id}/content`,headers:{cookie,range:'bytes=2-5'}});assert.equal(content.statusCode,206);assert.equal(content.body,'2345');
 assert.equal((await app.inject({url:'/api/files',headers:{cookie}})).statusCode,401);
 const issue=async(deviceId:string)=>{const {invitation}=connections.invite({label:'Generated file scope',serverUrl:'http://127.0.0.1:57569',deviceId});return connections.redeem({code:invitation.code,deviceId,deviceName:'Generated',platform:'android'});};
 const phone=await issue('phone'),other=await issue('other');const phoneHeaders={authorization:`Bearer ${phone.token}`},otherHeaders={authorization:`Bearer ${other.token}`};
 const headUrl='/api/file-sync/v1/head?'+new URLSearchParams({sourceId:'phone',externalId:m.item.externalId});
 assert.deepEqual((await app.inject({url:headUrl,headers:phoneHeaders})).json(),{revision:'v1',forgotten:false});
 assert.equal((await app.inject({url:headUrl,headers:otherHeaders})).statusCode,403);
 assert.equal((await app.inject({url:`/api/files/${ack.id}`,headers:otherHeaders})).statusCode,403);
 assert.equal((await app.inject({url:`/api/file-sync/v1/uploads/${session.uploadId}`,headers:otherHeaders})).statusCode,403);
 assert.deepEqual((await app.inject({url:'/api/files',headers:otherHeaders})).json().items,[]);
 assert.equal((await app.inject({method:'DELETE',url:`/api/files/${ack.id}`,headers:phoneHeaders})).statusCode,403);
 assert.equal((await app.inject({method:'PUT',url:'/api/file-processing',headers:phoneHeaders,payload:{}})).statusCode,403);
 const grant=await app.inject({method:'POST',url:`/api/files/${ack.id}/playback`,headers:phoneHeaders,payload:{}});assert.equal(grant.statusCode,200);
 await connections.revoke(phone.credentialId);
 assert.equal((await app.inject({url:`/api/files/${ack.id}/content`,headers:{cookie:String(grant.headers['set-cookie']).split(';')[0]}})).statusCode,401);
 await app.inject({method:'DELETE',url:`/api/files/${ack.id}`,headers});assert.equal((await app.inject({url:`/api/files/${ack.id}/content`,headers:{cookie}})).statusCode,404);
 assert.equal((await app.inject({url:headUrl,headers})).json().forgotten,true);
});

test('reference manifests count towards the vault limit and quota failures do not publish a revision',async t=>{
 const {store,files,options}=fixture(t);const m=manifest(Buffer.alloc(0));m.item.layer='reference';delete m.sha256;
 const ack=await files.revision(m,owner),before=store.logicalBytes();
 options.maxStorageBytes=before+16;
 await assert.rejects(files.revision({...m,previousRevision:'v1',item:{...m.item,revision:'v2'}},owner),{statusCode:507});
 assert.equal(files.list().items[0].captureId,ack.id);assert.equal(store.logicalBytes(),before);
 assert.ok(Number(store.db.prepare('SELECT length(manifest) n FROM file_versions').get()!.n)>0);
});

test('changing a processing provider during a job requeues it and rejects the old derived output; silence is valid',async t=>{
 const {files,store}=fixture(t),bytes=Buffer.from('provider change'),ack=await upload(files,manifest(bytes),bytes);
 let release!:(v:any)=>void,started!:()=>void;const begun=new Promise<void>(r=>{started=r;});let first=true;
 const processing=new FileProcessing(files,{transcribe:async()=>{if(first){first=false;started();return new Promise(r=>{release=r;});}return {durationMs:1000,segments:[]};}});t.after(()=>processing.close());
 const update=()=>processing.update({revision:processing.view().revision,settings:{...processing.view().settings,enabled:true}});update();
 const running=processing.tick();await begun;update();release({durationMs:1000,segments:[{startMs:0,endMs:1000,text:'superseded output'}]});await running;
 assert.equal(files.detail(ack.id).job.state,'waiting');assert.equal(files.chunks(ack.id).length,0);await processing.tick();
 assert.equal(files.detail(ack.id).job.state,'succeeded');assert.equal(store.db.prepare('SELECT audio_ms FROM file_usage').get()!.audio_ms,1000);assert.equal(files.chunks(ack.id).length,0);
});

test('file digest mismatch never creates an archive or ACK',async t=>{
 const {files}=fixture(t),bytes=Buffer.from('expected bytes'),input=manifest(bytes),session=files.begin(input,owner);
 files.part(session.uploadId,0,Buffer.alloc(bytes.length,42),owner);
 await assert.rejects(files.commit(session.uploadId,owner),{statusCode:409});assert.equal(files.upload(session.uploadId,owner).ack,null);assert.equal(files.list().items.length,0);
});

test('derived semantic index respects device/app bounds and disappears with its file',async t=>{
 const {files}=fixture(t),bytes=Buffer.from('generated vector input'),ack=await upload(files,manifest(bytes),bytes);
 const processing=new FileProcessing(files,{transcribe:async()=>({durationMs:1000,segments:[{startMs:0,endMs:1000,text:'A planned visit; attendance unknown.'}]})});t.after(()=>processing.close());
 processing.update({revision:processing.view().revision,settings:{...processing.view().settings,enabled:true}});await processing.tick();const chunk=files.chunks(ack.id)[0];
 assert.equal(files.pendingIndex('fixture-vector').length,1);files.indexed(chunk.id,[1,0,0],'fixture-vector');assert.equal(files.pendingIndex('fixture-vector').length,0);
 assert.equal(files.vectorSearch([1,0,0],'fixture-vector',{deviceId:'phone'})[0].id,chunk.id);assert.equal(files.vectorSearch([1,0,0],'fixture-vector',{deviceId:'other'}).length,0);
 assert.equal(files.vectorSearch([1,0,0],'fixture-vector',{appId:'other'}).length,0);assert.equal(files.search({query:'planned',appId:'other'}).length,0);
 files.forget(ack.id);assert.equal(files.vectorSearch([1,0,0],'fixture-vector',{}).length,0);
});
