import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {buildApp} from '../src/app.js';
import type {Config} from '../src/config.js';

test('receipts promise recoverable input before Coding publication and remain idempotent',async t=>{
  const dataDir=mkdtempSync(join(tmpdir(),'mote-ingress-receipts-'));
  const token='generated-ingress-owner-token';
  const config:Config={dataDir,token,tokenPath:'fixture-only',host:'127.0.0.1',port:0,maxStorageBytes:10_000_000,maxExportBytes:1_000_000,retentionDays:0,insightIntervalHours:0,allowedOrigins:[],model:'',modelBaseUrl:'',apiKey:'',allowUnauthenticatedLocal:false,embeddingModel:'',embeddingBaseUrl:'',embeddingApiKey:''};
  const node=await buildApp(config,{backgroundWorker:false,agent:{configured:false,query:async()=>{throw Error('No live model');},close:async()=>{}}});
  t.after(async()=>{await node.app.close();rmSync(dataDir,{recursive:true,force:true});});
  const headers={authorization:`Bearer ${token}`};
  const source={id:'generated-coding',name:'Generated Coding',kind:'coding-agent',deviceId:'fixture-device',platform:'macos'};
  assert.equal((await node.app.inject({method:'POST',url:'/api/sources',headers,payload:source})).statusCode,200);
  const invitation=await node.app.inject({method:'POST',url:'/api/connections/invitations',headers,payload:{serverUrl:'https://fixture.invalid',label:'Generated collector',deviceId:'fixture-device'}});
  const redeem=await node.app.inject({method:'POST',url:'/api/connections/redeem',payload:{code:invitation.json().invitation.code,deviceId:'fixture-device',deviceName:'Generated',platform:'macos'}});
  assert.equal(redeem.statusCode,200,redeem.body);
  const collectorHeaders={authorization:`Bearer ${redeem.json().token}`};
  const item={externalId:'event-1',revision:'1',observedAt:'2026-09-24T01:00:00Z',kind:'message',layer:'snapshot',text:'Generated decision',document:{contentRole:'transcript',coding:{version:1,provider:'codex',sessionId:'generated-session',projectKey:'generated-project',eventId:'000001',role:'user',part:0,parts:1}}};
  const send=()=>node.app.inject({method:'PUT',url:'/api/sources/generated-coding/items',headers,payload:item});
  const first=await send();assert.equal(first.statusCode,200,first.body);
  assert.deepEqual(first.json().receipt,{version:2,id:first.json().id,kind:'source-item',state:'received',duplicate:false,sourceId:source.id,externalId:item.externalId,revision:item.revision});
  assert.equal(node.materials.list().items.length,0);
  const retry=await send();assert.equal(retry.statusCode,200,retry.body);
  assert.deepEqual(retry.json().receipt,{...first.json().receipt,duplicate:true});
  const second={...item,externalId:'event-2'};
  const oldClient=await node.app.inject({method:'PUT',url:'/api/sources/generated-coding/items',headers:collectorHeaders,payload:second});
  assert.equal(oldClient.statusCode,426,oldClient.body);
  assert.equal(oldClient.json().error,'ingress_protocol_upgrade_required');
  const upgraded=await node.app.inject({method:'PUT',url:'/api/sources/generated-coding/items',headers:{...collectorHeaders,'x-mote-ingress-version':'2'},payload:second});
  assert.equal(upgraded.statusCode,200,upgraded.body);
  assert.equal(upgraded.json().receipt.state,'received');
  const capture={id:randomUUID(),deviceId:'fixture-device',deviceName:'Generated',platform:'import',source:'note',capturedAt:'2026-09-24T01:00:00Z',durationMs:0,ocrText:'Generated note'};
  const note=await node.app.inject({method:'POST',url:'/api/captures',headers,payload:capture});
  assert.equal(note.statusCode,201,note.body);
  assert.deepEqual(note.json().receipt,{version:2,id:capture.id,kind:'capture',state:'received',duplicate:false});
});
