import {test,type TestContext} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../src/store.js';
import {SourceStore} from '../src/sources.js';
import {FileStore} from '../src/files.js';
import {MemoryStore} from '../src/memory.js';
import {MemoryPipeline} from '../src/memory-pipeline.js';
import {Actions} from '../src/actions.js';
import {UsageLedger} from '../src/usage.js';
import {parseSemanticProducts,semanticProcessor} from '../src/semantic-extraction.js';
import type {QueryInput} from '@mote/agent';
import type {QueryResult} from '@mote/shared';
const text='Generated fixture: I will attend Project A review on 2099-02-01 from 09:00 to 10:00 UTC. In Project A I explicitly prefer written decisions. Unselected original detail remains searchable.';
const event={title:'Project A review',start:'2099-02-01T09:00:00Z',end:'2099-02-01T10:00:00Z',timeZone:'UTC',allDay:false,location:'',description:'Generated fixture'};
function output(id:string,memory=true,action=true){const evidence=[{id,quote:text}];return {summary:'Generated fixture with explicit scoped decision and appointment',evidence,events:[{statement:'A future appointment is planned; attendance unknown',uncertainty:'future plan',evidence}],memoryCandidates:memory?[{title:'Written decisions in Project A',statement:`The author prefers written decisions in Project A [${id}]`,uncertainty:'Project A only',admission:{layer:'memory',reason:'Explicit decision preference for later Project A work',scope:'Project A only',attribution:'user'},evidenceIds:[id],evidence}]:[],actionCues:action?[{kind:'calendar.create',event,uncertainty:'Future plan only',evidence}]:[]};}
async function fixture(t:TestContext){const dir=mkdtempSync(join(tmpdir(),'mote-semantic-products-')),store=new Store(dir),sources=new SourceStore(store),files=new FileStore(store,sources),memories=new MemoryStore(store);t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});sources.register({id:'fixture',kind:'custom',name:'Generated only',deviceId:'fixture',platform:'import'});const {id}=await sources.upsert('fixture',{externalId:'1',revision:'1',observedAt:'2026-01-01T00:00:00Z',kind:'message',layer:'original',text});store.archive.aggregate();const segment=store.archive.page({kind:'segment'}).items[0];return {store,sources,files,memories,id,segment:store.archive.get(segment.id)!};}
function result(id:string,body:unknown):QueryResult{return {answer:JSON.stringify(body),citations:[{id,capturedAt:'2026-01-01T00:00:00Z',appName:'Fixture',excerpt:text}],trace:[],runId:'generated-semantic'};}
const config={owner:'models' as const,fingerprint:'a'.repeat(64),revision:1,profileId:'generated',provider:'openai',model:'fixture',configured:true};
async function produce(f:Awaited<ReturnType<typeof fixture>>,body=output(f.id),query?:(input:QueryInput)=>Promise<QueryResult>){const processor=semanticProcessor({store:f.store,memories:f.memories,records:ids=>f.store.evidence(ids),query:query??(async()=>result(f.id,body)),selection:()=>config,usage:new UsageLedger(f.store)});const products=await processor.process({observations:[],artifacts:[{id:f.segment.id,outputs:[f.segment]}],config:{artifactId:f.segment.id,modelFingerprint:config.fingerprint},signal:new AbortController().signal});const id='f'.repeat(64);f.store.archive.save(id,id,id,products[0],[],'mote.segment-understanding','3',config.fingerprint,[],[{id:f.segment.id,revision:f.segment.revision}]);return id;}
test('one unified extraction supplies independent reviewed memory and action consumers before any memory is published',async t=>{
 const f=await fixture(t);let semanticCalls=0,reviewCalls=0,relationCalls=0;const artifact=await produce(f,output(f.id),async input=>{semanticCalls++;assert.equal(input.modelOverride,'fixture');assert.equal(input.evidenceRanges?.length,1);return result(f.id,output(f.id));});
 const pipeline=new MemoryPipeline({...f,model:()=> 'fixture',configured:()=>true,requireAdmission:true,query:async()=>{throw Error('Must reuse unified candidates');},review:async(_input,draft)=>{reviewCalls++;return draft;}});
 const job=pipeline.createFromArtifacts([artifact],'generated-unified')!;const done=await pipeline.run(job.id);assert.equal(done.status,'completed');assert.equal(done.memoryIds.length,1);assert.equal(f.memories.get(done.memoryIds[0]).status,'proposed');
 const actions=new Actions(f.store,f.files,async input=>{relationCalls++;assert.ok(input.question.includes('sharedActionCues'));return result(f.id,{actions:[{...output(f.id).actionCues[0],sameAs:null}]});},()=>true,{semanticArtifacts:async()=>[artifact]});actions.configure({enabled:true,timeZone:'UTC',reviewDeviceIds:[]});await actions.tick();assert.equal(actions.list().length,1);assert.equal(actions.list()[0].status,'proposed');assert.equal(semanticCalls,1);assert.equal(reviewCalls,1);assert.equal(relationCalls,1);
 assert.ok(f.store.search({query:'Unselected original'}).some(r=>r.id===f.id));await actions.tick();assert.equal(relationCalls,1);await actions.close();await pipeline.close();
});
test('zero memories does not suppress an action cue; zero actions skips relationship model work',async t=>{
 const f=await fixture(t),artifact=await produce(f,output(f.id,false,true));let calls=0;const actions=new Actions(f.store,f.files,async()=>{calls++;return result(f.id,{actions:[{...output(f.id,false,true).actionCues[0],sameAs:null}]});},()=>true,{semanticArtifacts:async()=>[artifact]});actions.configure({enabled:true,timeZone:'UTC',reviewDeviceIds:[]});await actions.tick();assert.equal(actions.list().length,1);assert.equal(f.memories.list().length,0);assert.equal(calls,1);await actions.close();
 const other=await f.sources.upsert('fixture',{externalId:'2',revision:'1',observedAt:'2026-01-02T00:00:00Z',kind:'message',layer:'original',text});f.store.archive.aggregate();const segment=f.store.archive.page({kind:'segment'}).items.find(s=>s.id!==f.segment.id)!;f.segment=f.store.archive.get(segment.id)!;f.id=other.id;const none=await produce(f,output(other.id,false,false));const skip=new Actions(f.store,f.files,async()=>{throw Error('No action cue needs no relation query');},()=>true,{semanticArtifacts:async()=>[none]});await skip.tick();assert.equal(skip.progress().error,null);assert.equal(skip.progress().jobs.find((j:any)=>j.status==='completed')?.count,2);await skip.close();
});
test('shared products reject fabricated, ambiguous, uncited, and oversized evidence without saving any memory',async t=>{
 const f=await fixture(t);const value=output(f.id);value.actionCues[0].evidence[0].quote='Invented original';assert.throws(()=>parseSemanticProducts(JSON.stringify(value),f.store.evidence([f.id])));assert.throws(()=>parseSemanticProducts(JSON.stringify(output(f.id)),f.store.evidence([f.id]),[]));assert.throws(()=>parseSemanticProducts(' '.repeat(64001),f.store.evidence([f.id])));await assert.rejects(produce(f,value));assert.equal(f.memories.list().length,0);
});
test('relevant model settings changing during shared extraction reject the commit',async t=>{
 const f=await fixture(t);let selected={...config};const processor=semanticProcessor({store:f.store,memories:f.memories,records:ids=>f.store.evidence(ids),query:async()=>{selected={...selected,fingerprint:'b'.repeat(64)};return result(f.id,output(f.id));},selection:()=>selected,usage:new UsageLedger(f.store)});await assert.rejects(processor.process({observations:[],artifacts:[{id:f.segment.id,outputs:[f.segment]}],config:{artifactId:f.segment.id,modelFingerprint:config.fingerprint},signal:new AbortController().signal}),{statusCode:409});assert.equal(f.memories.list().length,0);
});

test('large shared products stay expandable under the ordinary detail response budget',async t=>{
 const f=await fixture(t),id='e'.repeat(64);f.store.archive.save(id,id,id,{kind:'semantic',text:'Generated event summary',metadata:{productsVersion:1,events:Array.from({length:12},()=>({statement:'x'.repeat(1200)})),memoryCandidates:Array.from({length:8},()=>({statement:'m'.repeat(3000)})),actionCues:Array.from({length:8},()=>({event:{description:'a'.repeat(2000)}})),evidenceRanges:[{id:f.id,offset:0,length:text.length}],citations:[f.id],complete:true}},[],'fixture','1','fixture',[],[{id:f.segment.id,revision:f.segment.revision}]);const page=f.store.archive.page({id});assert.equal(page.items.length,1);assert.equal(page.items[0].metadata.productBodiesOmitted,true);assert.deepEqual(page.items[0].metadata.productCounts,{events:12,memoryCandidates:8,actionCues:8,evidenceRanges:1});assert.ok(page.characters<24000);assert.equal((f.store.archive.get(id)!.metadata.actionCues as unknown[]).length,8);
});
test('one shared action cue consumes all its original supports exactly once across observation jobs',async t=>{
 const f=await fixture(t),other=await f.sources.upsert('fixture',{externalId:'second',revision:'1',observedAt:'2026-01-02T00:00:00Z',kind:'message',layer:'original',text:'Generated participant confirms the same Project A review.'});const id='d'.repeat(64),proof=[{id:f.id,quote:text},{id:other.id,quote:f.store.evidence([other.id])[0].ocrText}];f.store.archive.save(id,id,id,{kind:'semantic',text:'Generated cross-observation cue',metadata:{productsVersion:1,events:[],memoryCandidates:[],actionCues:[{kind:'calendar.create',event,uncertainty:'Generated only',evidence:proof}],evidenceRanges:proof.map(p=>({id:p.id,offset:0,length:p.quote.length})),complete:true}},proof.map(p=>({id:p.id,fingerprint:f.store.archive.fingerprint(p.id)!})),'fixture','1','fixture');let calls=0;const actions=new Actions(f.store,f.files,async input=>{calls++;assert.deepEqual([...input.evidenceIds!].sort(),[f.id,other.id].sort());return {...result(f.id,{actions:[{kind:'calendar.create',event,uncertainty:'Generated',sameAs:null,evidence:proof}]}),citations:proof.map(p=>({id:p.id,capturedAt:'2026-01-01T00:00:00Z',appName:'Fixture',excerpt:p.quote}))};},()=>true,{semanticArtifacts:async()=>[id]});actions.configure({enabled:true,timeZone:'UTC',reviewDeviceIds:[]});await actions.tick();await actions.tick();assert.equal(calls,1);assert.equal(actions.list()[0].evidence.length,2);assert.equal(actions.progress().jobs.find((j:any)=>j.status==='completed')?.count,2);await actions.close();
});

test('semantic model trace and usage reference the executing workflow operation',async t=>{
 const {ProcessingRuntime}=await import('../src/processing-runtime.js');const f=await fixture(t),runtime=new ProcessingRuntime(f.store),usage=new UsageLedger(f.store);let seen:QueryInput['traceContext'];
 runtime.registry.register(semanticProcessor({store:f.store,memories:f.memories,records:ids=>f.store.evidence(ids),usage,selection:()=>config,query:async input=>{seen=input.traceContext;const current=f.store.db.prepare("SELECT operation_id FROM execution_steps WHERE id=? AND state='running'").get(seen!.jobId!);assert.equal(seen!.operationId,current?.operation_id);return result(f.id,output(f.id));}}));
 const ids=runtime.enqueue([{name:'semantics',processor:'mote.segment-understanding',artifactInputs:[{id:f.segment.id,revision:f.segment.revision}],config:{artifactId:f.segment.id,modelFingerprint:config.fingerprint}}]);await runtime.tick();assert.equal(runtime.engine.get(ids.semantics)?.state,'succeeded');assert.equal(seen?.jobId,ids.semantics);const receipt=JSON.parse(String(f.store.db.prepare('SELECT json FROM model_usage').get()!.json));assert.equal(receipt.attribution.operationId,seen!.operationId);assert.equal(receipt.attribution.jobId,ids.semantics);await runtime.close();
});
