import test,{type TestContext} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {setImmediate as yieldTurn} from 'node:timers/promises';
import type {Transcript} from '@mote/shared';
import {buildApp} from '../src/app.js';
import type {Config} from '../src/config.js';
import {Store,sha256} from '../src/store.js';
import {fixtureFilePolicy} from './fixtures/file-policy.js';

const transcript:Transcript={durationMs:1000,segments:[{startMs:0,endMs:1000,text:'Generated shutdown fixture'}]};
function deferred<T=void>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(done=>resolve=done);return {promise,resolve};}
async function fixture(t:TestContext){
 const directory=mkdtempSync(join(tmpdir(),'mote-shutdown-')),store=new Store(directory);
 const config:Config={dataDir:directory,token:'generated-shutdown-token',tokenPath:'fixture-only',host:'127.0.0.1',port:0,maxStorageBytes:100_000_000,maxExportBytes:1_000_000,retentionDays:0,insightIntervalHours:0,allowedOrigins:[],model:'',modelBaseUrl:'',apiKey:'',allowUnauthenticatedLocal:false,embeddingModel:'',embeddingBaseUrl:'',embeddingApiKey:'',logLevel:'silent'};
 const nodes:Awaited<ReturnType<typeof buildApp>>[]=[];
 const start=async(agent?:import('../src/app.js').QueryAgent)=>{const node=await buildApp(config,{store,agent});nodes.push(node);await node.app.ready();return node;};
 t.after(async()=>{for(const node of nodes)await node.app.close();store.close();rmSync(directory,{recursive:true,force:true});});
 return {store,start};
}
type Node=Awaited<ReturnType<typeof buildApp>>;
function configure(node:Node,settings:Record<string,unknown>={}){
 const saved={...node.processing.currentSettings(),enabled:true,summarize:false,...settings};
 node.processing.update({revision:node.processing.view().revision,settings:saved,policy:fixtureFilePolicy(saved,node.processing.runtime.registry)});
}
async function upload(node:Node,name:string,mimeType='audio/wav'){
 if(!node.sources.listSources().some(source=>source.id==='fixture'))node.sources.register({id:'fixture',name:'Generated shutdown files',kind:'local-files',deviceId:'fixture',platform:'macos',retention:'archive'});
 const bytes=Buffer.from('Generated bytes '+name),pending=node.files.begin({sourceId:'fixture',item:{externalId:name,revision:'1',observedAt:new Date().toISOString(),title:name,kind:'file',layer:'original',text:'',mimeType,deleted:false},sizeBytes:bytes.length,sha256:sha256(bytes)},()=>{});
 node.files.part(pending.uploadId,0,bytes,()=>{});return (await node.files.commit(pending.uploadId,()=>{})).id;
}
function fileStep(node:Node,id:string){return node.executor.list({operationId:'file:'+id,kind:'files.pipeline',limit:100}).items[0]!;}

test('app.close preserves 180 model waits, queues, retry deadlines and explicit cancellation; restart resumes eligible files',async t=>{
 const f=await fixture(t);let ready=false,calls=0;
 const start=async()=>{const node=await f.start();node.featureServices.mediaAssets.ready=()=>ready;
  node.processing.runtime.registry.register({id:'fixture.audio',name:'Generated model wait',version:'1',stage:'extract',serviceKind:'asr',localOnly:true,managedModel:'dialogue',mediaTypes:['audio/'],async process(){calls++;return transcript;}});
  return node;
 };
 const node=await start();node.featureHost.stop();configure(node,{audioProcessor:'fixture.audio'});const missing:string[]=[];
 for(let i=0;i<180;i++)missing.push(await upload(node,`missing-${i}.wav`));
 while(node.processing.prepare().length)await node.executor.tick();
 assert.equal(calls,0);for(const id of missing){assert.equal(fileStep(node,id).state,'blocked');assert.equal(fileStep(node,id).error,'model_missing');assert.equal(fileStep(node,id).attempts,0);}
 const queued=await upload(node,'queued.txt','text/plain'),backoff=await upload(node,'backoff.wav'),failed=await upload(node,'failed.wav'),cancelled=await upload(node,'cancelled.wav');node.processing.prepare();
 const retry=fileStep(node,backoff),deadline=Date.now()+3600000;
 f.store.db.prepare("UPDATE execution_steps SET error='provider_unavailable',attempts=2,available_at=?,recovery_deadline=? WHERE id=?").run(deadline,deadline+3600000,retry.id);node.executor.project(retry.id);
 node.executor.fail(fileStep(node,failed).id,'generated_failure');node.processing.cancel(cancelled);
 const before=f.store.db.prepare("SELECT * FROM execution_steps WHERE kind IN ('files.pipeline','files.summary') ORDER BY id").all(),jobs=f.store.db.prepare('SELECT * FROM file_jobs ORDER BY capture_id').all();
 await node.app.close();
 assert.deepEqual(f.store.db.prepare("SELECT * FROM execution_steps WHERE kind IN ('files.pipeline','files.summary') ORDER BY id").all(),before);
 assert.deepEqual(f.store.db.prepare('SELECT * FROM file_jobs ORDER BY capture_id').all(),jobs);
 assert.throws(()=>node.executor.enqueue('late','files.pipeline',{}),{statusCode:503});assert.deepEqual(node.processing.prepare(),[]);
 ready=true;const next=await start();next.featureHost.stop();
 // tick() admits new work without waiting for older work. Include the separate
 // text task, which can already own the file pool before model waits resume.
 await next.executor.drain([...next.processing.prepare(),fileStep(next,queued).id]);await next.processing.tick();await next.processing.tick();
 assert.equal(calls,180);for(const id of [...missing,queued])assert.equal(next.files.detail(id).job.state,'succeeded');
 assert.equal(fileStep(next,backoff).attempts,2);assert.equal(fileStep(next,backoff).availableAt,deadline);
 assert.equal(fileStep(next,failed).state,'failed');assert.equal(fileStep(next,cancelled).state,'cancelled');
});

test('app.close interrupts a child, keeps completed extraction and unknown requests, and fences late results across restart',async t=>{
 const f=await fixture(t),entered=deferred(),response=deferred<unknown>();let asrCalls=0,diarizeCalls=0,signal!:AbortSignal;
 const start=async()=>{const node=await f.start();node.featureServices.mediaAssets.ready=()=>true;
  node.processing.runtime.registry.register({id:'fixture.dialogue',name:'Generated dialogue',version:'1',stage:'extract',serviceKind:'asr',localOnly:true,dialogue:true,mediaTypes:['audio/'],async process(){asrCalls++;return transcript;}});
  node.processing.runtime.registry.register({id:'fixture.diarize',name:'Generated diarization',version:'1',stage:'diarize',localOnly:true,mediaTypes:['audio/'],async process(input){signal=input.signal;if(++diarizeCalls===1){entered.resolve();return response.promise;}return {durationMs:1000,engine:'fixture',expectedSpeakers:null,observedSpeakers:1,overlapDetection:'unknown',segments:[{startMs:0,endMs:1000,speaker:'SPEAKER_0'}],samples:[],warnings:[]};}});
  return node;
 };
 const node=await start();configure(node,{audioProcessor:'fixture.dialogue',diarizationProcessor:'fixture.diarize'});const id=await upload(node,'checkpoint.wav'),run=node.processing.tick();await entered.promise;
 const extraction=node.files.detail(id).artifacts.find((artifact:any)=>artifact.kind==='transcript')!;
 await node.app.close();await run;
 assert.equal(signal.aborted,true);assert.equal(fileStep(node,id).state,'waiting');assert.equal(fileStep(node,id).error,'interrupted');assert.equal(node.files.detail(id).job.state,'waiting');
 const steps=node.executor.list({operationId:'file:'+id,limit:100}).items;
 assert.equal(steps.find(step=>step.input.name==='extract')!.state,'succeeded');assert.equal(steps.find(step=>step.input.name==='diarize')!.state,'waiting');
 assert.equal(f.store.db.prepare('SELECT state FROM file_processor_waits WHERE capture_id=?').get(id)!.state,'unknown');
 const next=await start();await next.processing.tick();assert.equal(diarizeCalls,1);assert.equal(next.processing.cancellation(id).wait,'unknown');assert.throws(()=>next.processing.retry(id,'diarize'),{statusCode:409});
 response.resolve({...transcript,segments:[{startMs:0,endMs:1000,text:'Late generated result must not publish'}]});await yieldTurn();
 assert.equal(next.processing.cancellation(id).wait,'unknown','a disposed runtime must not clear a durable unknown request');
 next.processing.retry(id,'diarize',false,true);await next.processing.tick();assert.equal(next.files.detail(id).job.state,'succeeded');
 assert.equal(asrCalls,1);assert.equal(diarizeCalls,2);assert.ok(next.files.detail(id).artifacts.some((artifact:any)=>artifact.id===extraction.id));assert.doesNotMatch(JSON.stringify(next.files.chunks(id)),/Late generated/);
});

test('app.close preserves durable query work while keeping user cancellation terminal',async t=>{
 const f=await fixture(t),held=deferred(),entered=deferred(),ids=Array.from({length:6},()=>randomUUID());
 const node=await f.start({configured:true,close:async()=>{},query:async input=>{entered.resolve();await Promise.race([held.promise,new Promise(resolve=>input.signal!.addEventListener('abort',resolve,{once:true}))]);return {answer:'Generated answer',citations:[],trace:[],runId:randomUUID()};}});
 for(const id of ids)node.featureServices.queryRuns.start(id,{question:'Generated durable shutdown query'});
 await entered.promise;
 node.featureServices.queryRuns.cancel(ids[5]);await yieldTurn();assert.equal(node.featureServices.queryRuns.get(ids[4]).status,'running');
 await node.app.close();held.resolve();await yieldTurn();
 for(const id of ids.slice(0,5))assert.equal(node.featureServices.queryRuns.get(id).status,'running');
 assert.equal(node.featureServices.queryRuns.get(ids[5]).status,'cancelled');
});

test('app.close retains import admission blocks instead of cancelling inactive imports',async t=>{
 const f=await fixture(t),node=await f.start();
 const imported=await node.imports.create({files:[{name:'generated.txt',dataBase64:Buffer.from('Generated shutdown import').toString('base64')}],instruction:'Generate a preview',processing:'preview'});
 const phases=node.executor.list({operationId:'import:'+imported.id,limit:100}).items;
 assert.ok(phases.length>0);assert.ok(phases.every(step=>step.state==='blocked'));
 await node.app.close();assert.deepEqual(node.executor.list({operationId:'import:'+imported.id,limit:100}).items,phases);assert.equal(node.imports.get(imported.id).status,'queued');
});
