require('../../../scripts/fixture-language.cjs');
const { app, shell } = require('electron');
const { mkdtempSync } = require('node:fs');
const { rm } = require('node:fs/promises');
const { join } = require('node:path');
const { tmpdir } = require('node:os');
const { createServer } = require('node:http');
const assert = require('node:assert/strict');
const { openCentralWindow } = require('../dist/central-window');
const { defaultConfig } = require('../dist/config');
app.on('window-all-closed', () => {});
const profile = mkdtempSync(join(tmpdir(), 'mote-central-fixture-')); app.setPath('userData', profile);
let server, other, window;
const externalUrls = [];
shell.openExternal = async url => { externalUrls.push(url); };
const listen = s => new Promise(resolve => s.listen(0, '127.0.0.1', resolve));
app.whenReady().then(async () => {
  const token = 'synthetic-central-app-token-only'; let observed;
  server = createServer((req, res) => { if (req.url === '/api/probe') { observed = req.headers.authorization; res.setHeader('content-type', 'application/json'); res.end(JSON.stringify({ ok: observed === 'Bearer ' + token })); } else { res.setHeader('content-type', 'text/html'); res.end('<!doctype html><title>Generated central app fixture</title><main>Generated central app fixture</main>'); } });
  other = createServer((_req, res) => res.end('<!doctype html><title>Other node fixture</title>'));
  await listen(server); await listen(other);
  const origin = `http://127.0.0.1:${server.address().port}`, cfg = { ...defaultConfig(), serverUrl: origin, token };
  window = await openCentralWindow(cfg);
  assert.equal((await window.webContents.executeJavaScript('JSON.parse(sessionStorage.getItem("mote.connection")).token')), '__MOTE_NATIVE_AUTH__');
  assert.deepEqual(await window.webContents.executeJavaScript('fetch("/api/probe").then(r => r.json())'), { ok: true });
  assert.equal(observed, 'Bearer ' + token);
  await window.webContents.executeJavaScript(`window.open('https://example.com/private?body=synthetic-secret')`);
  assert.equal(externalUrls.length, 0, 'Unrelated external links remain blocked');
  await window.webContents.executeJavaScript(`window.open('https://github.com/utopiafar/mote/issues/new?template=bug_report.yml&version=synthetic-private-version&body=synthetic-secret')`);
  assert.equal(externalUrls.length, 1);
  const feedback = new URL(externalUrls[0]);
  assert.equal(feedback.origin, 'https://github.com');
  assert.equal(feedback.searchParams.get('template'), 'bug_report.yml');
  assert(feedback.searchParams.get('version').includes(app.getVersion()));
  assert.equal(feedback.searchParams.has('body'), false);
  assert.equal(externalUrls[0].includes('synthetic'), false, 'Renderer query data is never forwarded');
  assert.equal(externalUrls[0].includes(encodeURIComponent(origin)), false);
  await window.webContents.executeJavaScript('localStorage.setItem("generated-note-outbox", JSON.stringify({text:"synthetic offline note",mood:"calm"})); localStorage.setItem("generated-note-draft", "synthetic unsaved draft");');
  const isolated = window.webContents.session;
  await new Promise(resolve => { window.once('closed', resolve); window.close(); });
  assert.equal(isolated.listenerCount('will-download'), 0);
  await assert.rejects(isolated.fetch(origin + '/api/probe'));
  window = await openCentralWindow(cfg);
  assert.equal(await window.webContents.executeJavaScript('JSON.parse(localStorage.getItem("generated-note-outbox")).text'), 'synthetic offline note');
  assert.equal(await window.webContents.executeJavaScript('localStorage.getItem("generated-note-draft")'), 'synthetic unsaved draft');
  assert.equal(await window.webContents.executeJavaScript('typeof require'), 'undefined');
  const next = `http://127.0.0.1:${other.address().port}`;
  await assert.rejects(window.webContents.executeJavaScript(`fetch(${JSON.stringify(next)}).then(r => r.text())`));
  window.close(); window = await openCentralWindow({ ...cfg, serverUrl: next });
  assert.equal(await window.webContents.executeJavaScript('localStorage.getItem("generated-note-outbox")'), null);
  process.stdout.write(JSON.stringify({ ok:true, fixtureOnly:true, tokenOnlyInMain:true, sameOriginApiAuth:true, externalRequestsBlocked:true, safeFeedbackLink:true, persistentDraftAndOutbox:true, nodeStorageIsolated:true, rendererNodeDisabled:true, closedSessionNetworkDenied:true, downloadListenerRemoved:true }) + '\n');
  window.close(); await new Promise(resolve => server.close(resolve)); await new Promise(resolve => other.close(resolve));
  app.quit();
}).catch(error => { process.stderr.write('Central app smoke failed: ' + error.message + '\n'); app.exit(1); });
app.on('quit', () => { void rm(profile, {recursive:true,force:true}); });
