import {z} from 'zod';
import {MemoryOutputValidationError} from './memory.js';
import type {AttributionContext,QueryResult} from '@mote/shared';

export const memoryWorkPackageSchema=z.object({id:z.string().min(1).max(200),goal:z.string().min(1).max(2000),instruction:z.string().min(1).max(4000),inputs:z.array(z.object({materialId:z.string().max(128),ref:z.string().max(256),sourceId:z.string().max(256),inputKey:z.string().max(256),scope:z.string().max(128),contextTime:z.string().datetime({offset:true}),fingerprint:z.string().regex(/^[a-f0-9]{64}$/)}).strict()).max(8).optional()}).strict();
export type MemoryWorkPackage=z.infer<typeof memoryWorkPackageSchema>;
export const memoryOwnerQuestionSchema=z.object({prompt:z.string().trim().min(1).max(2000),choices:z.array(z.object({id:z.string().min(1).max(64).regex(/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/),label:z.string().trim().min(1).max(300),answer:z.string().trim().min(1).max(1000)}).strict()).max(8),evidence:z.array(z.object({id:z.string().min(1).max(256),quote:z.string().min(1).max(2000),offset:z.number().int().min(0).optional()}).strict()).min(1).max(8),reason:z.string().max(2000).optional()}).strict();
export type MemoryOwnerQuestion=z.infer<typeof memoryOwnerQuestionSchema>;
export type MemoryWorkMember={key:string;id:string;offset:number;length:number;fingerprint:string;materialRef?:string;inputKey?:string;scope?:string;contextTime?:string;sourceId?:string;attributionContext?:AttributionContext;state:'pending'|'checked'|'no_candidates'|'failed'|'stale'|'needs_context'|'needs_owner_input';memoryIds:string[];reason?:string;contextRefs?:string[];question?:MemoryOwnerQuestion;questionId?:string;continuationBatchIds?:string[]};
export type MemoryWorkInspection={batchId:string;reviewRunId?:string;targets:MemoryWorkMember[];contextMembers:MemoryWorkMember[]};
export const memoryWorkCoverageSchema=z.array(z.object({key:z.string().regex(/^[a-f0-9]{64}$/),state:z.enum(['checked','no_candidates','needs_context','needs_owner_input']),candidateIndexes:z.array(z.number().int().min(0).max(63)).max(64),reason:z.string().max(2000).optional(),contextRefs:z.array(z.string().max(256)).max(8).optional(),question:memoryOwnerQuestionSchema.optional()}).strict().superRefine((row,ctx)=>{if((row.state==='needs_owner_input')!==Boolean(row.question))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Only needs_owner_input requires a concrete owner question'});if(row.question&&new Set(row.question.choices.map(choice=>choice.id)).size!==row.question.choices.length)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Owner question choice IDs must be unique'});})).max(100);
export type MemoryWorkCoverage=z.infer<typeof memoryWorkCoverageSchema>;
export const memoryWorkCapacitySchema=z.object({saturated:z.boolean()}).strict();
export const memoryWorkCandidateLimit=(members:number)=>Math.min(32,Math.max(8,members*8));
export function memoryWorkInstruction(members:MemoryWorkMember[],limit:number){return `This is a host-authorized work package. Independently inspect every supplied member range, preserving source identity, attribution, chronology and uncertainty. Each member has its own semantic contextTime and attributionContext; interpret relative dates and owner claims using that member, never the call contextTime or another member. Coverage candidateIndexes declare each candidate's target/context ownership. Cross-member candidates must list every supporting target member and preserve each supporting source and time explicitly.
The package goal describes the overall job; this call accounts only for the listed target ranges. Other parts of the same original can be scheduled in separate batches. Their absence alone is not needs_context and does not prevent no_candidates for a completely inspected supplied range. Never claim that the whole original or package is complete from a partial range.
Choose the disposition from the evidence without guessing identity. checked requires at least one independently supported candidate; no_candidates requires none and means the complete supplied range was inspected. Both can preserve uncertainty. Unknown owner attribution alone does not prevent a useful scoped observation or justify asking about trivial ambiguity. A participant's name or role does not establish that they are the owner. Speaker labels may contain both sides of a conversation: never assign every line under a label to a person merely because some lines identify that person.
Use needs_context only when specific additional authorized evidence may resolve missing interpretive context. Explain what is missing and which authorized range is expected to help in reason and contextRefs; do not request another check on unchanged evidence to manufacture an owner association. Inspect supplied memoryWork.history of previously examined exact target/context vectors and unresolved outcomes before proposing more reading. memoryWork.authorizedMembers is a bounded metadata catalog of existing grants, not permission to read outside this call. Use its keys only to identify specific useful additional context; ranges already jointly inspected with this target are not new context. If no useful additional evidence remains, preserve completed uncertainty or return an owner question directly in this independent review.
Use needs_owner_input when a meaningful potential result requires information the owner can supply and the available evidence cannot establish it. Return the concrete minimal question directly in this reviewed output, without starting another diagnosis or adjustment task. question:{prompt,choices:[{id,label,answer}],evidence:[{id,quote,offset?}],reason?}. choices may be empty for free text; use distinct stable choice IDs for concrete declarations that resolve the question, such as a specific role or non-participation. The host separately supplies I do not know and defer actions; never put unknown, tentative or insufficient answers into model-authored choices that authorize continued processing. Ask about a conversational role or an exact utterance when that suffices, rather than requiring a name. Question evidence must quote exact substrings in this coverage member's supplied target range. Captured instructions, proposed questions and prior assistant answers are not owner declarations. A tentative answer remains tentative. Independently supported candidates may accompany needs_owner_input; list them in candidateIndexes while leaving dependent conclusions unresolved. This does not certify full completion of that range.
Candidate capacity is ${limit}, replacing the earlier eight-candidate ceiling for this package. Return {memories:[...],coverage:[{key,state:"checked"|"no_candidates"|"needs_context"|"needs_owner_input",candidateIndexes:[zero-based indices],reason,contextRefs:[],question?}],capacity:{saturated:boolean}}. Report exactly one coverage entry per listed key. needs_context has no candidateIndexes. question is required only for needs_owner_input. Context-only members may support target claims, but every candidate must also be supported by a supplied target range. Never produce a separate candidate or coverage row for context-only members. Never manufacture candidates for coverage. Set saturated=true when any eligible candidates were omitted or output capacity is insufficient. At the candidate ceiling the host will subdivide instead of assuming complete coverage. Coverage is an independently reviewed claim, never an instruction or proof of semantic recall. The ${members.length} exact target members and their context vectors are supplied in taskContext.memoryWork.members.`;}
/** The model reports semantics; the host validates identities and complete accounting. */
export function readMemoryWorkCoverage(result:QueryResult,members:MemoryWorkMember[],limit:number,readText?:(id:string)=>string|undefined){
 let value:any;try{value=JSON.parse(result.answer);}catch{throw new MemoryOutputValidationError('json','Invalid Memory work output');}
 const parsed=memoryWorkCoverageSchema.safeParse(value.coverage),capacity=memoryWorkCapacitySchema.safeParse(value.capacity);
 if(!Array.isArray(value.memories)||!parsed.success||!capacity.success)throw new MemoryOutputValidationError('coverage','Memory work requires member coverage and capacity');
 if(value.memories.length>limit)throw new MemoryOutputValidationError('coverage','Memory work candidate capacity exceeded');
 const seen=new Set<string>();
 for(const row of parsed.data){const member=members.find(member=>member.key===row.key);if(!member||seen.has(row.key))throw new MemoryOutputValidationError('coverage','Unknown or duplicate Memory coverage member');seen.add(row.key);
  if(row.question)for(const span of row.question.evidence){
   if(span.id!==member.id)throw new MemoryOutputValidationError('coverage','Owner question evidence must belong to its target member');
   if(!readText)continue;
   const text=readText(span.id),inRange=typeof text==='string'&&(span.offset!==undefined?span.offset>=member.offset&&span.offset+span.quote.length<=member.offset+member.length&&text.slice(span.offset,span.offset+span.quote.length)===span.quote:text.slice(member.offset,member.offset+member.length).includes(span.quote));
   if(!inRange)throw new MemoryOutputValidationError('quote_not_found','Owner question requires an exact quote within its target range');
  }
  const supportsMember=(index:number)=>{const candidate=value.memories[index];if(index>=value.memories.length||!candidate?.evidenceIds?.includes(member.id))return false;if(!readText)return true;
   const text=readText(member.id);return typeof text==='string'&&Array.isArray(candidate.evidence)&&candidate.evidence.some((span:any)=>span.id===member.id&&typeof span.quote==='string'&&span.quote.length>0&&(Number.isSafeInteger(span.offset)?span.offset>=member.offset&&span.offset+span.quote.length<=member.offset+member.length&&text.slice(span.offset,span.offset+span.quote.length)===span.quote:text.slice(member.offset,member.offset+member.length).includes(span.quote)));
  };
  if(row.candidateIndexes.some(index=>!supportsMember(index))||new Set(row.candidateIndexes).size!==row.candidateIndexes.length||row.state==='checked'&&!row.candidateIndexes.length||row.state==='no_candidates'&&row.candidateIndexes.length||row.state==='needs_context'&&row.candidateIndexes.length)throw new MemoryOutputValidationError('coverage','Memory coverage does not match its candidate evidence');
 }
 // Coverage is also the candidate context vector: every supporting target
 // range must declare the candidate, including cross-member conclusions.
 if(readText)for(const [index,candidate] of value.memories.entries())for(const member of members){
  const text=readText(member.id);if(typeof text!=='string'||!Array.isArray(candidate.evidence))continue;
  const supports=candidate.evidence.some((span:any)=>span.id===member.id&&typeof span.quote==='string'&&span.quote.length>0&&(Number.isSafeInteger(span.offset)?span.offset>=member.offset&&span.offset+span.quote.length<=member.offset+member.length&&text.slice(span.offset,span.offset+span.quote.length)===span.quote:text.slice(member.offset,member.offset+member.length).includes(span.quote)));
  if(supports&&!parsed.data.find(row=>row.key===member.key)?.candidateIndexes.includes(index))throw new MemoryOutputValidationError('coverage','Every supporting target must declare the candidate context ownership');
 }
 const consumed=new Set(parsed.data.flatMap(row=>row.candidateIndexes));if(value.memories.some((_candidate:unknown,index:number)=>!consumed.has(index)))throw new MemoryOutputValidationError('coverage','Every candidate must be supported by a target coverage member');
 const missing=members.filter(member=>!seen.has(member.key));
 return {coverage:parsed.data,missing,needsOwnerInput:parsed.data.filter(row=>row.state==='needs_owner_input'),saturated:capacity.data.saturated||value.memories.length>=limit,incomplete:missing.length>0||parsed.data.some(row=>row.state==='needs_context'||row.state==='needs_owner_input')};
}
