import {useEffect,useMemo,useState,useSyncExternalStore} from 'react';
import {Activity as ActivityIcon,ArrowLeft,ArrowRight,GitBranch,FileCheck2,Eye} from 'lucide-react';
import {moteText} from '@mote/shared/i18n';
import {formatEvidenceRef,parseEvidenceId,type WorkActivity,type WorkActivityPage} from '@mote/shared';
import {type Api,errorMessage} from './api';
import {useResource} from './useResource';
import {operationFeed} from './operation-feed';
import {ListPagination,useCursorPages} from './ListPagination';
import {WorkProgress,WorkStateBadge} from './WorkProgress';
import type {Page} from './navigation';
const tabs=[['overview','概览'],['work','工作分支'],['results','成果'],['evidence','证据'],['technical','技术详情']] as const;
function WorkDetail({api,id,onBack,onNavigate,onOpen}:{api:Api;id:string;onBack:()=>void;onNavigate:(page:Page)=>void;onOpen:(ref:string)=>void}){
 const [tab,setTab]=useState<string>('overview'),paging=useCursorPages();
 const {data:work,error,loading,refresh}=useResource<WorkActivity>(api,'/api/work-activity/'+encodeURIComponent(id)+'?'+new URLSearchParams({limit:'20',...paging.cursor?{cursor:String(paging.cursor)}:{}}),3000);
 useEffect(()=>{document.querySelector<HTMLHeadingElement>('.activity-detail h1')?.focus();},[id,Boolean(work)]);
 const inspector=()=>{const runId=work?.evidence.runId??work?.technical.runId;onNavigate('agentView');if(runId)window.location.hash='#/agent?runId='+encodeURIComponent(runId);};
 return <div className="activity-detail"><button className="back-link" onClick={onBack}><ArrowLeft size={16}/>{moteText('返回活动')}</button>
  {error!==undefined&&<p role="alert">{errorMessage(error)} <button className="text-button" onClick={refresh}>{moteText('重试')}</button></p>}{loading&&!work&&<p role="status">{moteText('正在读取…')}</p>}
  {work&&<><div className="page-heading"><div className="eyebrow">MOTE / <ActivityIcon size={14}/></div><h1 tabIndex={-1}>{work.goal}</h1><WorkStateBadge state={work.state}/><WorkProgress progress={work.progress}/></div>
   <nav className="section-tabs" aria-label={moteText('工作详情')}>{tabs.map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>setTab(key)}>{moteText(label)}</button>)}</nav>
   {tab==='overview'&&<section className="panel panel-pad work-overview"><div className="work-overview-grid"><button className="work-overview-link" onClick={()=>setTab('work')}><GitBranch size={22}/><span><strong>{moteText('工作分支')}</strong><small>{moteText('{0} 个分支正在进行',work.branchCounts?.running??0)}</small></span><ArrowRight size={17}/></button><button className="work-overview-link" onClick={()=>setTab('results')}><FileCheck2 size={22}/><span><strong>{moteText('成果')}</strong><small>{moteText('{0} 项已保存成果',work.artifacts.length)}</small></span><ArrowRight size={17}/></button><button className="work-overview-link" onClick={()=>setTab('evidence')}><Eye size={22}/><span><strong>{moteText('证据')}</strong><small>{moteText('{0} 条来源资料',work.evidence.count)}</small></span><ArrowRight size={17}/></button></div>
    {work.events.length>0&&<><h2>{moteText('最近进展')}</h2><ol className="work-events">{work.events.map(event=><li key={event.id}><time dateTime={event.at}>{new Date(event.at).toLocaleTimeString()}</time><span>{event.summary??moteText({'work.started':'工作已开始','plan.updated':'工作计划已更新','branch.started':'工作分支已开始','branch.completed':'工作分支已完成','branch.replanned':'已调整工作分支','artifact.created':'已保存工作成果','work.needs_input':'工作需要补充','work.completed':'工作已完成','work.failed':'工作未能完成','work.cancelled':'工作已停止'}[event.type])}</span></li>)}</ol></>}
    <button className="button subtle" onClick={()=>onNavigate(work.destination)}>{moteText('打开相关资料与操作')}<ArrowRight size={16}/></button>
   </section>}
   {tab==='work'&&<section className="panel panel-pad"><h2>{moteText('工作分支')}</h2><p>{moteText('每个分支按自己的输入范围推进；完成状态由实际执行记录确认。')}</p><div className="work-branches">{work.branches.map(branch=><article className="work-branch" key={branch.id}><header><h3>{branch.title}</h3><WorkStateBadge state={branch.state}/></header>{branch.progress&&<WorkProgress progress={branch.progress}/>} {branch.artifactIds.length>0&&<p className="fine-print">{moteText('{0} 项已保存成果',branch.artifactIds.length)}</p>}</article>)}</div>{!work.branchCounts?.total&&<p className="empty">{moteText('这项工作直接推进，目前没有独立分支。')}</p>} {!!work.branchCounts?.total&&<ListPagination label={moteText('工作分支分页')} paging={paging} nextCursor={work.branchesNextCursor} count={work.branches.length} loading={loading}/>}</section>}
   {tab==='results'&&<section className="panel panel-pad"><h2>{moteText('成果')}</h2>{work.artifacts.map(artifact=><article className="work-artifact" key={artifact.id}><FileCheck2 size={20}/><div><h3>{artifact.title}</h3>{artifact.summary&&<p>{artifact.summary}</p>}{artifact.href?<a className="text-button" href={artifact.href}>{moteText('查看成果')}<ArrowRight size={15}/></a>:<button className="text-button" onClick={()=>onNavigate(work.destination)}>{moteText('查看成果')}<ArrowRight size={15}/></button>}</div></article>)}{!work.artifacts.length&&<p className="empty">{moteText('成果确认保存后会出现在这里。')}</p>}</section>}
   {tab==='evidence'&&<section className="panel panel-pad"><h2>{moteText('证据')}</h2><p>{moteText('共 {0} 条来源资料。展开原文或查看 Agent 实际读取的内容。',work.evidence.count)}</p><button className="button subtle" onClick={inspector}><Eye size={16}/>{moteText(work.evidence.runId??work.technical.runId?'查看 Agent 实际输入':'查看 Agent 可访问范围')}</button><div className="work-evidence">{work.evidence.refs.map((ref,index)=><button className="text-button" key={ref} onClick={()=>onOpen(parseEvidenceId(ref)?formatEvidenceRef('capture',ref):ref)}>{moteText('来源资料 {0}',index+1)}<ArrowRight size={15}/></button>)}</div>{work.evidence.count>work.evidence.refs.length&&<p className="fine-print">{moteText('这里只列出前 {0} 条资料；完整范围可在相关资料中查看。',work.evidence.refs.length)}</p>}</section>}
   {tab==='technical'&&<section className="panel panel-pad"><h2>{moteText('技术详情')}</h2><p className="fine-print">{moteText('技术执行记录、尝试次数与依赖用于排查问题。')}</p><div className="processing-actions"><button className="button" onClick={()=>onNavigate('processing')}>{moteText('技术执行记录')}</button><button className="button subtle" onClick={inspector}>{moteText('Agent 读取轨迹')}</button></div><details><summary>{moteText('原始 Operation')}</summary>{work.technical.operationIds.map(operationId=><p className="operation-id" key={operationId}><code>{operationId}</code></p>)}</details></section>}
  </>}
 </div>;
}
export function Activity({api,onNavigate,onOpen}:{api:Api;onNavigate:(page:Page)=>void;onOpen:(ref:string)=>void}){
 const [state,setState]=useState<'active'|'attention'|'completed'>('active'),[selected,setSelected]=useState(()=>new URLSearchParams(window.location.hash.split('?')[1]).get('work')??''),[advanced,setAdvanced]=useState(false),paging=useCursorPages();
 const feed=useMemo(()=>operationFeed(api),[api]),feedError=useSyncExternalStore(feed.subscribe,feed.getSnapshot,feed.getSnapshot);
 const query=new URLSearchParams({state,limit:'10',...paging.cursor?{cursor:String(paging.cursor)}:{}}),{data,error,loading,refresh}=useResource<WorkActivityPage>(api,selected?null:'/api/work-activity?'+query,3000);
 useEffect(()=>{const changed=()=>setSelected(new URLSearchParams(window.location.hash.split('?')[1]).get('work')??'');window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed);},[]);
 if(selected)return <WorkDetail key={selected} api={api} id={selected} onBack={()=>{setSelected('');window.location.hash='#/activity';}} onNavigate={onNavigate} onOpen={onOpen}/>;
 return <div className="activity-centre"><div className="page-heading settings-heading"><div><div className="eyebrow">MOTE / <ActivityIcon size={15}/></div><h1>{moteText('活动')}</h1><p>{moteText('看看 Mote 正在做什么、如何分工，以及已经得到的成果。')}</p></div><button className="button subtle" disabled={loading} onClick={refresh}>{moteText('刷新')}</button></div>
  <nav className="section-tabs" aria-label={moteText('活动状态')}>{([['active','进行中'],['attention','需要处理'],['completed','最近完成']] as const).map(([key,label])=><button key={key} aria-current={state===key?'page':undefined} onClick={()=>{setState(key);paging.reset();}}>{moteText(label)}</button>)}</nav>
  {feedError!==undefined&&<p role="status">{moteText('进度连接暂时中断，正在自动重连。')}</p>}{error!==undefined&&<p className="notice error" role="alert">{errorMessage(error)} <button className="text-button" onClick={refresh}>{moteText('重试')}</button></p>}{loading&&!data&&<p role="status">{moteText('正在读取…')}</p>}
  <section className="activity-list" aria-label={moteText('工作列表')} aria-busy={loading}>{data?.items.map(work=><button className="panel activity-card" key={work.id} onClick={()=>{setSelected(work.id);window.location.hash='#/activity?work='+encodeURIComponent(work.id);}}><span className="activity-card-content"><span className="activity-card-heading"><strong>{work.goal}</strong><WorkStateBadge state={work.state}/></span><WorkProgress progress={work.progress} compact/>{(work.branchCounts?.running??0)>0&&<small>{moteText('{0} 个工作分支正在进行',work.branchCounts!.running)}</small>}{work.artifacts.length>0&&<small>{work.artifacts.map(artifact=>artifact.title).join(' · ')}</small>}<time dateTime={work.updatedAt}>{new Date(work.updatedAt).toLocaleString()}</time></span><ArrowRight size={19}/></button>)}</section>
  {data&&!data.items.length&&<section className="panel empty"><h2>{moteText(state==='active'?'目前没有正在进行的工作':state==='attention'?'目前没有需要处理的工作':'这里会显示已完成的工作')}</h2></section>}
  <ListPagination label={moteText('活动分页')} paging={paging} nextCursor={data?.nextCursor} count={data?.items.length??0} loading={loading}/>
  <details className="panel activity-advanced" onToggle={event=>setAdvanced(event.currentTarget.open)}><summary>{moteText('高级')}</summary>{advanced&&<><p>{moteText('查看底层执行记录，排查依赖与失败原因。')}</p><button className="button subtle" onClick={()=>onNavigate('processing')}>{moteText('技术执行记录')}</button></>}</details>
 </div>;
}
