import { moteText } from '@mote/shared/i18n';
import React,{useEffect,useState} from 'react';
import type {ActionProposal,ActionSettings,ActionTarget,CalendarDraft} from '@mote/shared';
import {calendarEventSchema,calendarWallTime,calendarInstant} from '@mote/shared';
import {createApi} from './api';

declare global {interface Window {moteCalendar?:{connect:()=>Promise<{deviceId:string}>;execute:(id:string)=>Promise<void>}}}
type State={nextCursor:number|null;total:number;items:ActionProposal[];settings:ActionSettings;targets:ActionTarget[];progress:{configured:boolean;running:boolean;jobs:{status:string;count:number}[];error:string|null}};
const labels:Record<string,string>={proposed:moteText("待确认"),dismissed:moteText("已忽略"),approved:moteText("等待客户端写入"),executing:moteText("正在写入 / 等待回执"),succeeded:moteText("已添加"),uncertain:moteText("保存结果待核实"),stale:moteText("原文已更新或删除")};
export function Actions({api,onOpen}:{api:ReturnType<typeof createApi>;onOpen:(id:string)=>void}){
 const [data,setData]=useState<State>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string>(),[draft,setDraft]=useState<CalendarDraft>(),[target,setTarget]=useState(''),[devices,setDevices]=useState<{deviceId:string;deviceName:string}[]>([]),[localId,setLocalId]=useState<string>(),[tab,setTab]=useState('proposed'),[cursor,setCursor]=useState(0);
 const refresh=async()=>{const d=await api.request<State>(`/api/actions?cursor=${cursor}`);setData(d);};
 useEffect(()=>{let alive=true;const load=()=>api.request<State>(`/api/actions?cursor=${cursor}`).then(d=>{if(alive)setData(d);}).catch(e=>{if(alive)setError(e.message);});void load();void api.request<{items:typeof devices}>('/api/devices').then(d=>{if(alive)setDevices(d.items);}).catch(()=>{});const timer=setInterval(()=>void load(),15000);return()=>{alive=false;clearInterval(timer);};},[api,cursor]);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError(e instanceof Error?e.message:moteText("操作未完成，请重试"));}finally{setBusy(false);}};
 const post=(path:string,body:unknown)=>api.request(path,{method:'POST',body:JSON.stringify(body)});
 const settings=async(next:ActionSettings)=>{await api.request('/api/actions/settings',{method:'PUT',body:JSON.stringify(next)});};
 const item=data?.items.find(a=>a.id===selected);
 const choices=data?.targets.flatMap(t=>t.calendars.map(c=>({value:JSON.stringify({deviceId:t.deviceId,calendarId:c.id}),label:`${t.deviceName} · ${c.title}`})))??[];
 const edit=(a:ActionProposal)=>{setSelected(a.id);setDraft({...a.event,start:a.event.start&&!a.event.allDay?calendarWallTime(a.event.start,a.event.timeZone??'UTC').slice(0,16):a.event.start,end:a.event.end&&!a.event.allDay?calendarWallTime(a.event.end,a.event.timeZone??'UTC').slice(0,16):a.event.end});};
 return <section><div className="page-heading"><div className="eyebrow">{moteText("把安排留在你的日历里")}</div><h1>{moteText("行动 · 日程建议")}</h1><p>{moteText("从上传资料和持续采集中发现安排。每条由你核对，写入已有日历并带上 #Mote 来源标记。")}</p></div>
 {error&&<div className="error-banner" role="alert">{error}</div>}
 {data&&<details className="panel action-settings"><summary>{moteText("发现设置与设备授权")}</summary><label><input type="checkbox" checked={data.settings.enabled} disabled={busy} onChange={e=>void run(()=>settings({...data.settings,enabled:e.target.checked}))}/> {' '}{moteText("分析已归档及后续新增的上传资料和持续采集内容")}</label><p className="muted">{moteText("使用当前配置的模型；原文可能发送给该模型服务。本地限定文件不会发送。日程写入始终需要逐条确认。")}</p><label>{moteText("解释时间使用的时区")}<input aria-label={moteText("默认时区")} defaultValue={data.settings.timeZone} onBlur={e=>{if(e.target.value!==data.settings.timeZone)void run(()=>settings({...data.settings,timeZone:e.target.value}));}}/></label><p>{moteText("允许以下设备查看跨来源日程建议、相关原文片段并逐条确认：")}</p>{devices.map(d=><label key={d.deviceId}><input type="checkbox" checked={data.settings.reviewDeviceIds.includes(d.deviceId)} disabled={busy} onChange={e=>void run(()=>settings({...data.settings,reviewDeviceIds:e.target.checked?[...data.settings.reviewDeviceIds,d.deviceId]:data.settings.reviewDeviceIds.filter(id=>id!==d.deviceId)}))}/>{d.deviceName}</label>)}</details>}
 <div className="action-toolbar"><button className="button" disabled={busy} onClick={()=>void run(refresh)}>{moteText("刷新")}</button>{window.moteCalendar&&<button className="button" disabled={busy} onClick={()=>void run(async()=>{const r=await window.moteCalendar!.connect();setLocalId(r.deviceId);})}>{moteText("连接这台 Mac 的日历")}</button>}<button className="button subtle" disabled={busy} onClick={()=>void run(()=>post('/api/actions/retry',{}))}>{moteText("重试分析失败的批次")}</button></div>
 <p className="muted">{moteText("在 Android 的「日程建议」中连接本机日历。网页可确认并交给指定设备，客户端联网后会同步已确认日程；打开日程页面可立即同步。")}</p>
 {data&&!data.progress.configured&&<p role="status">{moteText("尚未配置模型；资料继续归档，配置后再开始分析。")}</p>}{data?.progress.error&&<p role="alert">{data.progress.error}</p>}
 {data&&<p className="muted">{data.settings.enabled?moteText("自动发现已开启"):moteText("自动发现未开启")} · {data.progress.running?moteText("正在分析 · "):''}{data.progress.jobs.map(j=>moteText("{0} {1} 批", ({pending:moteText("待分析"),running:moteText("分析中"),completed:moteText("已分析"),failed:moteText("分析失败"),stale:moteText("来源已变更")} as Record<string,string>)[j.status]??j.status, j.count)).join(' · ')}</p>}
 <nav className="segmented-nav" aria-label={moteText("日程建议筛选")}>{[['proposed',moteText("待确认")],['active',moteText("待写入")],['all',moteText("全部")]].map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 <div className="action-toolbar"><span>{moteText("共")}{' '}{data?.total??0}{' '}{moteText("条建议 · 当前页")}</span><button className="button" disabled={cursor===0} onClick={()=>setCursor(0)}>{moteText("最新建议")}</button><button className="button" disabled={!data?.nextCursor} onClick={()=>setCursor(data!.nextCursor!)}>{moteText("更早建议")}</button></div>
 <div className="action-grid">{data?.items.filter(a=>tab==='all'||(tab==='active'?['approved','executing','uncertain'].includes(a.status):a.status==='proposed')).map(a=><article className="panel action-card" key={a.id}><span className="status-label">{labels[a.status]}</span><h2>{a.event.title}</h2><p>{a.event.start??moteText("开始时间待补充")} → {a.event.end??moteText("结束时间待补充")}{a.event.allDay?moteText(" · 全天"):''}</p><p>{a.event.timeZone??moteText("时区待确认")}{a.event.location?` · ${a.event.location}`:''}</p>{a.uncertainty&&<p className="review-notes">{a.uncertainty}</p>}<details><summary>{moteText("查看原文依据（")}{a.evidence.length}）</summary>{a.evidence.map((e,i)=><blockquote key={i}><p>{e.quote}</p><button className="button subtle" onClick={()=>onOpen(e.id)}>{e.source}{' '}{moteText("· 查看原文")}</button></blockquote>)}</details>
 {a.status==='proposed'&&<div className="action-toolbar"><button className="button primary" onClick={()=>edit(a)} disabled={busy}>{moteText("核对并添加")}</button><button className="button subtle" disabled={busy} onClick={()=>void run(()=>post(`/api/actions/${a.id}/dismiss`,{version:a.version}))}>{moteText("忽略")}</button></div>}
 {['approved','executing','uncertain'].includes(a.status)&&<p>{moteText("请在目标设备打开日程建议并同步。结果不明时只核实已有事件，避免重复创建。")}</p>}
 {window.moteCalendar&&a.target?.deviceId===localId&&['approved','executing','uncertain'].includes(a.status)&&<button className="button primary" disabled={busy} onClick={()=>void run(()=>window.moteCalendar!.execute(a.id))}>{moteText("在这台 Mac 写入 / 核实")}</button>}
 {a.status==='succeeded'&&<p>{moteText("已写入已有日历 · #Mote")}</p>}
 </article>)}</div>{data&&!data.items.length&&<div className="panel"><h2>{moteText("发现的日程会出现在这里")}</h2><p>{moteText("开启发现后，上传一份包含明确日期和参与关系的资料，或继续使用已开启的采集来源。")}</p></div>}
 {item&&draft&&<div className="action-dialog-backdrop"><form className="panel action-dialog" role="dialog" aria-modal="true" aria-label={moteText("确认日程")} onSubmit={e=>{e.preventDefault();void run(async()=>{const reviewed={...draft,start:draft.start&&!draft.allDay?calendarInstant(draft.start,draft.timeZone??'UTC'):draft.start,end:draft.end&&!draft.allDay?calendarInstant(draft.end,draft.timeZone??'UTC'):draft.end};const validation=calendarEventSchema.safeParse(reviewed);if(!validation.success)throw Error(validation.error.issues.map(i=>i.message).join('；'));if(!target)throw Error(moteText("请选择目标日历"));const chosen=JSON.parse(target);await post(`/api/actions/${item.id}/confirm`,{version:item.version,event:reviewed,target:chosen});setSelected(undefined);if(window.moteCalendar&&chosen.deviceId===localId)await window.moteCalendar.execute(item.id);});}}><h2>{moteText("确认日程")}</h2><label>{moteText("标题")}<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label><input type="checkbox" checked={draft.allDay} onChange={e=>setDraft({...draft,allDay:e.target.checked,start:null,end:null})}/> {' '}{moteText("全天")}</label><p className="muted">{draft.allDay?moteText("全天日程的结束日期不包含当天。"):moteText("日期和时间按下方所选时区解释。")}</p>{(['start','end','timeZone','location','description'] as const).map(key=><label key={key}>{({start:moteText("开始"),end:moteText("结束"),timeZone:moteText("时区"),location:moteText("地点"),description:moteText("备注")})[key]}<input type={key==='start'||key==='end'?(draft.allDay?'date':'datetime-local'):'text'} required={['start','end','timeZone'].includes(key)} value={draft[key]??''} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label>{moteText("已有日历")}<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">{moteText("选择设备和日历")}</option>{choices.map(c=><option value={c.value} key={c.value}>{c.label}</option>)}</select></label><p>{moteText("保存后会交给该设备写入，备注中附加 #Mote 标记。不会邀请参与人，也不会修改或取消已有日程。")}</p><div className="action-toolbar"><button type="submit" className="button primary" disabled={busy||item.status!=='proposed'}>{moteText("确认添加到此日历")}</button><button type="button" className="button" disabled={busy} onClick={()=>setSelected(undefined)}>{moteText("返回")}</button></div></form></div>}
 </section>;
}
