import {useState} from 'react';
import {moteText} from '@mote/shared/i18n';
import {type Api,errorMessage} from './api';
import {useResource} from './useResource';
import {Materials} from './Materials';
type Entry={path?:string;ref?:string;id?:string;title?:string;preview?:string;description?:string;expand?:string;layer?:string};
function RecordedInput({api}:{api:Api}){
  const [afterSeq,setAfterSeq]=useState(0),[runId,setRunId]=useState('');
  const page=useResource<{items:{seq:number;at:string;trace?:{type:string;runId?:string;payload?:unknown;truncated?:boolean}}[];nextSeq:number;recording:{enabled:boolean}}>(api,`/api/agent-view/events?afterSeq=${afterSeq}&runId=${encodeURIComponent(runId)}`);
  return <section className="panel panel-pad"><p>{moteText('这里只展示已记录的输入和工具事件；未开启追踪或已过保留期的输入无法还原。')}</p><label>{moteText('运行编号')}<input value={runId} onChange={e=>{setRunId(e.target.value);setAfterSeq(0);}}/></label>{page.data&&<p>{page.data.recording.enabled?moteText('输入追踪已开启'):moteText('输入追踪未开启')}</p>}{page.error!==undefined&&<p role="alert">{errorMessage(page.error)}</p>}{page.data?.items.map(item=><details key={item.seq}><summary>{item.at} · {item.trace?.type} · {item.trace?.runId}</summary>{item.trace?.truncated&&<p>{moteText('记录已截断，不能还原完整输入。')}</p>}<pre className="feature-json">{JSON.stringify(item.trace?.payload,null,2)}</pre></details>)}{page.data&&!page.data.items.length&&<p>{moteText('此页没有已保留的模型输入或工具事件。')}</p>}<div className="processing-actions"><button className="button" onClick={page.refresh}>{moteText('刷新')}</button>{afterSeq>0&&<button className="button" onClick={()=>setAfterSeq(0)}>{moteText('返回第一页')}</button>}{page.data&&page.data.nextSeq>afterSeq&&<button className="button" onClick={()=>setAfterSeq(page.data!.nextSeq)}>{moteText('下一页')}</button>}</div></section>;
}
export function AgentInspector({api,onOpen}:{api:Api;onOpen:(ref:string)=>void}){
  const [tab,setTab]=useState('catalog'),[path,setPath]=useState('/context'),[deviceId,setDeviceId]=useState(''),[selected,setSelected]=useState<Entry>();
  const suffix=deviceId?'&deviceId='+encodeURIComponent(deviceId):'';
  const catalog=useResource<{entries:Entry[]}>(api,tab==='catalog'?'/api/agent-view/catalog?path='+encodeURIComponent(path)+suffix:null);
  const detailPath=selected?.expand==='memories'?'/api/agent-view/memories?id='+encodeURIComponent(selected.id??''):selected?.expand==='source_items'?'/api/agent-view/source-items?sourceId='+encodeURIComponent(selected.id??''):selected?.expand==='segments'?'/api/agent-view/segments?id='+encodeURIComponent(selected.ref??''):null;
  const detail=useResource<{items:{id?:string;title?:string;statement?:string;ocrText?:string;text?:string;status?:string}[];nextCursor?:string|null}>(api,tab==='catalog'&&detailPath?detailPath+suffix:null);
  return <div className="agent-inspector"><div className="page-heading"><h1>{moteText('模型可见目录')}</h1><p>{moteText('问一问当前可访问的虚拟目录，来自实际只读权限；这不代表某次回答已经读取这些内容。')}</p></div><nav className="section-tabs">{[['catalog',moteText('可访问范围')],['materials',moteText('正式资料')],['input',moteText('实际输入与读取轨迹')]].map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {tab==='catalog'&&<><label>{moteText('设备范围')}<input value={deviceId} placeholder={moteText('全部设备')} onChange={e=>{setDeviceId(e.target.value);setSelected(undefined);}}/></label><p><button className="text-button" onClick={()=>{setPath('/context');setSelected(undefined);}}>/context</button> / {path.slice('/context'.length)}</p>{catalog.error!==undefined&&<p role="alert">{errorMessage(catalog.error)}</p>}<div className="feature-cards">{catalog.data?.entries.map((entry,i)=><button className="panel source-item" key={entry.path??entry.ref??entry.id??i} onClick={()=>{if(entry.path){setPath(entry.path);setSelected(undefined);}else setSelected(entry);}}><strong>{entry.title??entry.path??entry.layer}</strong><p>{entry.preview??entry.description}</p></button>)}</div>{detail.error!==undefined&&<p role="alert">{errorMessage(detail.error)}</p>}{detail.data?.items.map((item,i)=><article className="panel panel-pad" key={item.id??i}><h2>{item.title}</h2><p>{item.status}</p><pre className="feature-json">{item.statement??item.ocrText??item.text}</pre></article>)}<p className="fine-print">{moteText('目录按页限量展示；没有列出不代表不存在。原始 Coding 事件包和磁盘路径不会作为模型目录公开。')}</p></>}
  {tab==='materials'&&<Materials api={api} agent onOpen={onOpen}/>}{tab==='input'&&<RecordedInput api={api}/>}</div>;
}
