import { moteText } from '@mote/shared/i18n';
import {useMemo, useState} from 'react';
import {Check, Download, FileCheck2, RotateCcw, SlidersHorizontal} from 'lucide-react';
import type {ServerConfiguration, SourceConnection} from '@mote/shared';
import {effectiveValues, environmentFragment, type DraftValues} from './configuration-draft';
export type ConfigCategory = 'model'|'storage'|'embedding'|'connectors'|'diagnostics';
const names: Record<ConfigCategory,string> = {model:moteText("自动回顾计划"),storage:moteText("保留与容量"),embedding:moteText("检索索引"),connectors:moteText("来源与外部应用"),diagnostics:moteText("诊断偏好")};
export function ConfigurationBuilder({config,category,sources=[],sourcesError=''}:{config:ServerConfiguration;category:ConfigCategory;sources?:SourceConnection[];sourcesError?:string}) {
  const current = useMemo(()=>effectiveValues(config),[config]);
  const [changes,setChanges] = useState<DraftValues>({});
  const [review,setReview] = useState(false),[error,setError] = useState('');
  const value=(key:string)=>changes[key]??current[key]??'';
  const set=(key:string,v:string)=>{setChanges(previous=>{const next={...previous};if(v===(current[key]??''))delete next[key];else next[key]=v;return next;});setReview(false);setError('');};
  const count=Object.keys(changes).length;
  const writeSourceIds=value('MOTE_MCP_WRITE_SOURCE_IDS').split(',').map(id=>id.trim()).filter(Boolean);
  const text=(key:string,label:string,extra:{type?:string;placeholder?:string;hint?:string;min?:number;max?:number}={})=><label className="preference-field">{label}<input aria-label={label} value={value(key)} type={extra.type??'text'} placeholder={extra.placeholder} min={extra.min} max={extra.max} autoComplete="off" onChange={e=>{set(key,e.target.value);}}/>{extra.hint&&<small>{extra.hint}</small>}</label>;
  const choice=(key:string,label:string,options:[string,string][])=>{const selected=value(key);return <label className="preference-field">{label}<select aria-label={label} value={selected} onChange={e=>set(key,e.target.value)}>{!options.some(([v])=>v===selected)&&<option value={selected}>{moteText("当前自定义值 ·")}{' '}{selected||moteText("未设置")}</option>}{options.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>;};
  const toggle=(key:string,label:string,hint:string)=><label className="preference-toggle"><span><strong>{label}</strong><small>{hint}</small></span><input type="checkbox" role="switch" checked={value(key)==='1'} onChange={e=>set(key,e.target.checked?'1':'0')}/></label>;
  function validate() {
    const limits:Record<string,[number,number]>={MOTE_RETENTION_DAYS:[0,36500],MOTE_MAX_STORAGE_MB:[1,1000000],MOTE_MODEL_TIMEOUT_MS:[5000,600000],MOTE_MODEL_MAX_TOKENS:[1,128000],MOTE_INSIGHT_INTERVAL_HOURS:[0,168],MOTE_CONNECTOR_SYNC_INTERVAL_SECONDS:[60,86400]};
    for(const [key,v] of Object.entries(changes)) {if(limits[key]){const n=Number(v),[min,max]=limits[key];if(!v||!Number.isInteger(n)||n<min||n>max)throw Error(moteText("{0} 需要 {1}–{2} 之间的整数。", key, min, max));}if(/BASE_URL$/.test(key)&&v){const u=new URL(v);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.search||u.hash)throw Error(moteText("模型地址须为不含凭据或参数的 HTTP(S) 地址。"));}}
    return environmentFragment(changes);
  }
  function download(){try{const blob=new Blob([validate()],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mote-config-changes.env';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}}
  return <section className="panel config-builder" aria-label={moteText("配置草稿")}>
    <div className="section-heading"><div><h2><SlidersHorizontal size={18}/>{moteText("调整")}{names[category]}</h2><p>{moteText("先准备修改，应用到部署配置并重启后生效。")}</p></div><span className="badge amber">{moteText("配置草稿")}</span></div>
    <form onSubmit={e=>{e.preventDefault();try{validate();setReview(true);setError('');}catch(err){setError((err as Error).message);}}}>
      {category==='model'&&<>{choice('MOTE_INSIGHT_INTERVAL_HOURS',moteText("自动生成回顾"),[['0',moteText("仅手动生成")],['6',moteText("每 6 小时")],['12',moteText("每 12 小时")],['24',moteText("每天")]])}<p className="fine-print">{moteText("自动回顾的时间安排属于部署配置，合并草稿并重启中央节点后生效。上方模型服务可以直接保存并应用。")}</p></>}
      {category==='storage'&&<><div className="preference-grid">{choice('MOTE_RETENTION_DAYS',moteText("历史记录保留"),[['0',moteText("持续保留")],['30',moteText("30 天")],['90',moteText("90 天")],['180',moteText("180 天")],['365',moteText("1 年")]])}{choice('MOTE_MAX_STORAGE_MB',moteText("资料容量上限"),[['1024','1 GiB'],['5120','5 GiB'],['10240','10 GiB'],['51200','50 GiB'],['102400','100 GiB']])}</div><div className="preference-note">{moteText("正数保留周期会按采集时间自动清理旧记录。下载草稿不会删除资料；合并配置并重启前，请确认所选周期。")}</div><details className="preference-advanced"><summary>{moteText("自定义保留与容量")}</summary><div className="preference-grid">{text('MOTE_RETENTION_DAYS',moteText("自定义保留天数"),{type:'number',min:0,max:36500})}{text('MOTE_MAX_STORAGE_MB',moteText("自定义容量（MiB）"),{type:'number',min:1,max:1000000})}</div></details></>}
      {category==='embedding'&&<><div className="preference-note">{moteText("文本检索始终可用。配置向量索引后，文本会提交给你选择的 Embedding 服务。")}</div><div className="preference-grid">{text('MOTE_EMBEDDING_MODEL',moteText("Embedding 模型名称"),{hint:moteText("留空使用文本检索；更换模型可能需要重建已有向量。")})}{text('MOTE_EMBEDDING_BASE_URL',moteText("Embedding 服务地址"),{type:'url'})}</div><p className="fine-print">{moteText("如服务需要认证，在部署机器设置 MOTE_EMBEDDING_API_KEY。")}</p></>}
      {category==='connectors'&&<>{choice('MOTE_CONNECTOR_SYNC_INTERVAL_SECONDS',moteText("检查来源的间隔"),[['300',moteText("5 分钟")],['900',moteText("15 分钟")],['1800',moteText("30 分钟")],['3600',moteText("1 小时")]])}{toggle('MOTE_MCP_ENABLED',moteText("允许外部应用检索"),moteText("需在部署机器设置独立的 MCP 读令牌。"))}{toggle('MOTE_MCP_WRITE_ENABLED',moteText("允许指定来源写回"),moteText("写入还需要独立令牌与明确允许的来源。"))}<fieldset className="source-permissions"><legend>{moteText("允许外部应用写入的来源")}</legend><p className="fine-print">{moteText("只授权你勾选的来源。此选择随部署配置重启后生效。")}</p>{sources.map(source=><label className="source-permission" key={source.id}><input type="checkbox" checked={writeSourceIds.includes(source.id)} onChange={e=>set('MOTE_MCP_WRITE_SOURCE_IDS',(e.target.checked?[...new Set([...writeSourceIds,source.id])]:writeSourceIds.filter(id=>id!==source.id)).join(','))}/><span><strong>{source.name}</strong><small>{source.enabled?moteText("已启用"):moteText("已暂停")}</small></span></label>)}{!sources.length&&<p className="fine-print">{sourcesError||moteText("暂无已注册来源。先在“来源”页面添加内容。")}</p>}{writeSourceIds.filter(id=>!sources.some(s=>s.id===id)).length>0&&<p className="fine-print">{moteText("保留了当前配置中未列出的来源 ID；可在高级选项检查。")}</p>}</fieldset><details className="preference-advanced"><summary>{moteText("高级来源 ID 与授权回调")}</summary>{text('MOTE_MCP_WRITE_SOURCE_IDS',moteText("可写来源 ID"),{hint:moteText("保留自定义值；多个已注册来源 ID 以英文逗号分隔。")})}{text('MOTE_GOOGLE_REDIRECT_URI',moteText("Google 授权回调地址"),{type:'url',hint:moteText("须与 Google Cloud 配置完全一致。OAuth 凭据在部署机器设置。")})}</details></>}
      {category==='diagnostics'&&<>{toggle('MOTE_DIAGNOSTICS_ENABLED',moteText("记录运行诊断"),moteText("仅记录固定事件、状态和数值，不包含个人正文。"))}{choice('MOTE_LOG_LEVEL',moteText("日志详细程度"),[['silent',moteText("关闭")],['error',moteText("仅错误")],['warn',moteText("警告与错误")],['info',moteText("标准")],['debug',moteText("调试")]])}{toggle('MOTE_DEBUG',moteText("启用调试模式"),moteText("会增加诊断事件；不会开放任意正文日志。"))}</>}
      {error&&<p className="notice error" role="alert">{error}</p>}
      <div className="config-draft-footer"><span>{count?moteText("{0} 项修改待应用", count):moteText("当前没有修改")}</span><div><button className="button subtle" type="button" disabled={!count} onClick={()=>{setChanges({});setReview(false);}}><RotateCcw size={15}/>{moteText("还原草稿")}</button><button className="button primary" disabled={!count}><FileCheck2 size={16}/>{moteText("检查配置草稿")}</button></div></div>
    </form>
    {review&&<div className="config-review" role="status"><h3><Check size={17}/>{moteText("草稿已准备好，当前节点尚未改变")}</h3><ol><li>{moteText("下载本次修改，将这些变量合并到")}{' '}<code>{config.envFile||moteText("此节点的部署环境配置")}</code>。</li><li>{moteText("保留原配置中的令牌、密钥与目录设置，再重启此环境。")}</li><li>{moteText("刷新“当前生效值”，确认新的配置已加载。")}</li></ol><button className="button primary" onClick={download}><Download size={16}/>{moteText("下载配置变更")}</button><details><summary>{moteText("预览环境变量")}</summary><pre>{environmentFragment(changes)}</pre></details></div>}
  </section>;
}
