import {useMemo, useState} from 'react';
import {Check, Download, FileCheck2, RotateCcw, SlidersHorizontal} from 'lucide-react';
import type {ServerConfiguration, SourceConnection} from '@mote/shared';
import {effectiveValues, environmentFragment, matchingProvider, providerPresets, type DraftValues} from './configuration-draft';
export type ConfigCategory = 'model'|'storage'|'embedding'|'connectors'|'diagnostics';
const names: Record<ConfigCategory,string> = {model:'问答与回顾',storage:'保留与容量',embedding:'检索索引',connectors:'来源与外部应用',diagnostics:'诊断偏好'};
export function ConfigurationBuilder({config,category,sources=[],sourcesError=''}:{config:ServerConfiguration;category:ConfigCategory;sources?:SourceConnection[];sourcesError?:string}) {
  const current = useMemo(()=>effectiveValues(config),[config]);
  const [changes,setChanges] = useState<DraftValues>({});
  const [providerChoice,setProviderChoice] = useState<string>();
  const [review,setReview] = useState(false),[error,setError] = useState('');
  const value=(key:string)=>changes[key]??current[key]??'';
  const set=(key:string,v:string)=>{setChanges(previous=>{const next={...previous};if(v===(current[key]??''))delete next[key];else next[key]=v;return next;});setReview(false);setError('');};
  const count=Object.keys(changes).length;
  const writeSourceIds=value('MOTE_MCP_WRITE_SOURCE_IDS').split(',').map(id=>id.trim()).filter(Boolean);
  const text=(key:string,label:string,extra:{type?:string;placeholder?:string;hint?:string;min?:number;max?:number}={})=><label className="preference-field">{label}<input aria-label={label} value={value(key)} type={extra.type??'text'} placeholder={extra.placeholder} min={extra.min} max={extra.max} autoComplete="off" onChange={e=>{set(key,e.target.value);if(key==='MOTE_MODEL_BASE_URL')setProviderChoice(undefined);}}/>{extra.hint&&<small>{extra.hint}</small>}</label>;
  const choice=(key:string,label:string,options:[string,string][])=>{const selected=value(key);return <label className="preference-field">{label}<select aria-label={label} value={selected} onChange={e=>set(key,e.target.value)}>{!options.some(([v])=>v===selected)&&<option value={selected}>当前自定义值 · {selected||'未设置'}</option>}{options.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>;};
  const toggle=(key:string,label:string,hint:string)=><label className="preference-toggle"><span><strong>{label}</strong><small>{hint}</small></span><input type="checkbox" role="switch" checked={value(key)==='1'} onChange={e=>set(key,e.target.checked?'1':'0')}/></label>;
  function validate() {
    const limits:Record<string,[number,number]>={MOTE_RETENTION_DAYS:[0,36500],MOTE_MAX_STORAGE_MB:[1,1000000],MOTE_MODEL_TIMEOUT_MS:[5000,600000],MOTE_MODEL_MAX_TOKENS:[256,32768],MOTE_INSIGHT_INTERVAL_HOURS:[0,168],MOTE_CONNECTOR_SYNC_INTERVAL_SECONDS:[60,86400]};
    for(const [key,v] of Object.entries(changes)) {if(limits[key]){const n=Number(v),[min,max]=limits[key];if(!v||!Number.isInteger(n)||n<min||n>max)throw Error(`${key} 需要 ${min}–${max} 之间的整数。`);}if(/BASE_URL$/.test(key)&&v){const u=new URL(v);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.search||u.hash)throw Error('模型地址须为不含凭据或参数的 HTTP(S) 地址。');}}
    return environmentFragment(changes);
  }
  function download(){try{const blob=new Blob([validate()],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mote-config-changes.env';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}}
  return <section className="panel config-builder" aria-label="配置草稿">
    <div className="section-heading"><div><h2><SlidersHorizontal size={18}/>调整{names[category]}</h2><p>先准备修改，应用到部署配置并重启后生效。</p></div><span className="badge amber">配置草稿</span></div>
    <form onSubmit={e=>{e.preventDefault();try{validate();setReview(true);setError('');}catch(err){setError((err as Error).message);}}}>
      {category==='model'&&<><div className="preference-grid"><label className="preference-field">服务预设<select aria-label="服务预设" value={providerChoice??matchingProvider(value('MOTE_MODEL_BASE_URL'))} onChange={e=>{setProviderChoice(e.target.value);const p=providerPresets.find(p=>p.id===e.target.value);if(p?.url){set('MOTE_MODEL_BASE_URL',p.url);set('MOTE_MODEL_ALLOW_UNAUTHENTICATED_LOCAL',p.id==='local'?'1':'0');}}}>{providerPresets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><small>预设只填写地址；选择与你部署或购买的模型服务一致的选项。</small></label>{text('MOTE_MODEL','模型名称',{placeholder:'填写服务提供的模型标识',hint:'保留自定义名称。留空将关闭问答与回顾。'})}{text('MOTE_MODEL_BASE_URL','模型服务地址',{type:'url'})}{choice('MOTE_MODEL_REASONING_EFFORT','推理强度',[['off','关闭'],['low','轻量'],['high','深入'],['max','最高']])}{choice('MOTE_INSIGHT_INTERVAL_HOURS','自动生成回顾',[['0','仅手动生成'],['6','每 6 小时'],['12','每 12 小时'],['24','每天']])}{choice('MOTE_MODEL_TIMEOUT_MS','最长等待时间',[['60000','1 分钟'],['120000','2 分钟'],['300000','5 分钟'],['600000','10 分钟']])}</div>{toggle('MOTE_MODEL_ALLOW_UNAUTHENTICATED_LOCAL','允许本机模型免密访问','仅适用于回环地址。容器中的“本机”指容器本身。')}<details className="preference-advanced"><summary>模型输出与认证</summary>{text('MOTE_MODEL_MAX_TOKENS','输出 token 上限',{type:'number',min:256,max:32768})}<p>API 密钥：{config.groups.flatMap(g=>g.fields).find(f=>f.key==='modelApiKeyConfigured')?.value?'当前已配置':'当前未配置'}。请在部署机器设置 MOTE_MODEL_API_KEY；此处不会读取或复制已有密钥。</p></details><p className="fine-print">地址预设依据 <a href="https://api-docs.deepseek.com/" target="_blank" rel="noreferrer">DeepSeek</a> 与 <a href="https://docs.ollama.com/api/openai-compatibility" target="_blank" rel="noreferrer">Ollama 官方文档</a>。本页不会探测模型或发送资料。</p></>}
      {category==='storage'&&<><div className="preference-grid">{choice('MOTE_RETENTION_DAYS','历史记录保留',[['0','持续保留'],['30','30 天'],['90','90 天'],['180','180 天'],['365','1 年']])}{choice('MOTE_MAX_STORAGE_MB','资料容量上限',[['1024','1 GiB'],['5120','5 GiB'],['10240','10 GiB'],['51200','50 GiB'],['102400','100 GiB']])}</div><div className="preference-note">正数保留周期会按采集时间自动清理旧记录。下载草稿不会删除资料；合并配置并重启前，请确认所选周期。</div><details className="preference-advanced"><summary>自定义保留与容量</summary><div className="preference-grid">{text('MOTE_RETENTION_DAYS','自定义保留天数',{type:'number',min:0,max:36500})}{text('MOTE_MAX_STORAGE_MB','自定义容量（MiB）',{type:'number',min:1,max:1000000})}</div></details></>}
      {category==='embedding'&&<><div className="preference-note">文本检索始终可用。配置向量索引后，文本会提交给你选择的 Embedding 服务。</div><div className="preference-grid">{text('MOTE_EMBEDDING_MODEL','Embedding 模型名称',{hint:'留空使用文本检索；更换模型可能需要重建已有向量。'})}{text('MOTE_EMBEDDING_BASE_URL','Embedding 服务地址',{type:'url'})}</div><p className="fine-print">如服务需要认证，在部署机器设置 MOTE_EMBEDDING_API_KEY。</p></>}
      {category==='connectors'&&<>{choice('MOTE_CONNECTOR_SYNC_INTERVAL_SECONDS','检查来源的间隔',[['300','5 分钟'],['900','15 分钟'],['1800','30 分钟'],['3600','1 小时']])}{toggle('MOTE_MCP_ENABLED','允许外部应用检索','需在部署机器设置独立的 MCP 读令牌。')}{toggle('MOTE_MCP_WRITE_ENABLED','允许指定来源写回','写入还需要独立令牌与明确允许的来源。')}<fieldset className="source-permissions"><legend>允许外部应用写入的来源</legend><p className="fine-print">只授权你勾选的来源。此选择随部署配置重启后生效。</p>{sources.map(source=><label className="source-permission" key={source.id}><input type="checkbox" checked={writeSourceIds.includes(source.id)} onChange={e=>set('MOTE_MCP_WRITE_SOURCE_IDS',(e.target.checked?[...new Set([...writeSourceIds,source.id])]:writeSourceIds.filter(id=>id!==source.id)).join(','))}/><span><strong>{source.name}</strong><small>{source.enabled?'已启用':'已暂停'}</small></span></label>)}{!sources.length&&<p className="fine-print">{sourcesError||'暂无已注册来源。先在“来源”页面添加内容。'}</p>}{writeSourceIds.filter(id=>!sources.some(s=>s.id===id)).length>0&&<p className="fine-print">保留了当前配置中未列出的来源 ID；可在高级选项检查。</p>}</fieldset><details className="preference-advanced"><summary>高级来源 ID 与授权回调</summary>{text('MOTE_MCP_WRITE_SOURCE_IDS','可写来源 ID',{hint:'保留自定义值；多个已注册来源 ID 以英文逗号分隔。'})}{text('MOTE_GOOGLE_REDIRECT_URI','Google 授权回调地址',{type:'url',hint:'须与 Google Cloud 配置完全一致。OAuth 凭据在部署机器设置。'})}</details></>}
      {category==='diagnostics'&&<>{toggle('MOTE_DIAGNOSTICS_ENABLED','记录运行诊断','仅记录固定事件、状态和数值，不包含个人正文。')}{choice('MOTE_LOG_LEVEL','日志详细程度',[['silent','关闭'],['error','仅错误'],['warn','警告与错误'],['info','标准'],['debug','调试']])}{toggle('MOTE_DEBUG','启用调试模式','会增加诊断事件；不会开放任意正文日志。')}</>}
      {error&&<p className="notice error" role="alert">{error}</p>}
      <div className="config-draft-footer"><span>{count?`${count} 项修改待应用`:'当前没有修改'}</span><div><button className="button subtle" type="button" disabled={!count} onClick={()=>{setChanges({});setProviderChoice(undefined);setReview(false);}}><RotateCcw size={15}/>还原草稿</button><button className="button primary" disabled={!count}><FileCheck2 size={16}/>检查配置草稿</button></div></div>
    </form>
    {review&&<div className="config-review" role="status"><h3><Check size={17}/>草稿已准备好，当前节点尚未改变</h3><ol><li>下载本次修改，将这些变量合并到 <code>{config.envFile||'此节点的部署环境配置'}</code>。</li><li>保留原配置中的令牌、密钥与目录设置，再重启此环境。</li><li>刷新“当前生效值”，确认新的配置已加载。</li></ol><button className="button primary" onClick={download}><Download size={16}/>下载配置变更</button><details><summary>预览环境变量</summary><pre>{environmentFragment(changes)}</pre></details></div>}
  </section>;
}
