import { moteText, getLocale } from '@mote/shared/i18n';
import {ArrowLeft, ArrowRight, CheckCircle2, Clock3, HardDrive, Info, Monitor, QrCode, Smartphone} from 'lucide-react';
import {ago,dateTime,deviceState,deviceLabels,type Device} from './api';
import {Metadata} from './Metadata';
import {MediaSnapshot} from './Media';
const modes={realtime:moteText("实时同步"),interval:moteText("定时同步"),batch:moteText("批量同步"),manual:moteText("手动同步")};
const states={unconfigured:moteText("尚未配置节点"),idle:moteText("等待新记录"),waiting:moteText("等待同步条件"),uploading:moteText("正在上传"),error:moteText("同步需要处理"),manual:moteText("等待手动同步")};
export function DeviceOverview({devices,onConnect}:{devices:Device[];onConnect:()=>void}) {
 return <div className="device-overview"><div className="page-heading split-heading"><div><div className="eyebrow">{moteText("记录各自发生，资料在此汇合")}</div><h1>{moteText("你的设备")}</h1><p>{moteText("采集在设备本机运行，同步按每台设备的偏好进行。")}</p></div><button className="button primary" onClick={onConnect}><QrCode size={17}/>{moteText("扫码连接设备")}</button></div>
 <div className="device-observation-note"><Clock3 size={18}/><p>{moteText("这里显示设备最近一次上报。较久未联系可能是定时、手动同步或网络变化，不能据此判断本机是否正在采集。")}</p></div>
 {!devices.length?<section className="panel device-empty"><Monitor size={34}/><h2>{moteText("从你的第一台设备开始")}</h2><p>{moteText("生成一次性邀请，在手机或 Mac 的连接设置中确认。客户端也可以先在本机记录，稍后再连接。")}</p><button className="button primary" onClick={onConnect}>{moteText("生成设备二维码")}<ArrowRight size={16}/></button></section>:<div className="device-grid">{devices.map(device=>{const fresh=deviceState(device)!=='stale',Icon=device.platform==='android'?Smartphone:device.platform==='import'?HardDrive:Monitor;return <article className="panel device-card" key={device.deviceId}>
  <div className="device-top"><div className="device-icon"><Icon size={24}/></div><span className={`badge ${fresh?'green':'muted'}`}><span className="dot"/>{fresh?moteText("刚刚联系"):moteText("上次上报")}</span></div><h2>{device.deviceName}</h2><p className="device-platform">{({macos:'macOS',android:'Android',import:moteText("导入来源"),windows:'Windows',linux:'Linux'} as Record<string,string>)[device.platform]||device.platform}</p>
  <dl><div><dt>{moteText("最后联系")}</dt><dd title={dateTime(device.lastSeenAt)}>{ago(device.lastSeenAt)}</dd></div><div><dt>{moteText("上报的采集状态")}</dt><dd>{deviceLabels[device.status]||device.status}</dd></div><div><dt>{moteText("最近采集")}</dt><dd>{ago(device.lastCaptureAt)}</dd></div><div><dt>{moteText("上报的待同步记录")}</dt><dd>{(device.sync?.pendingRecords??device.queueDepth).toLocaleString(getLocale())}{' '}{moteText("条")}</dd></div></dl>
  {device.sync?<div className="device-sync-summary"><div><CheckCircle2 size={16}/><strong>{modes[device.sync.mode]}</strong><span>{states[device.sync.state]}</span></div><p>{device.sync.mode==='interval'?moteText("约每 {0} 分钟检查一次", device.sync.intervalMinutes) : device.sync.mode==='batch'?moteText("累计 {0} 条，或最长等待 {1} 分钟后同步", device.sync.batchSize, device.sync.intervalMinutes):device.sync.mode==='manual'?moteText("在客户端点击同步后发送记录"):moteText("有新记录时尝试同步")}</p>{device.sync.blockedRecords!==undefined&&<p>{moteText("上报的需处理记录 ·")}{' '}{device.sync.blockedRecords}{' '}{moteText("条")}</p>}{device.sync.awaitingOcrRecords!==undefined&&<p>{moteText("等待本机 OCR ·")}{' '}{device.sync.awaitingOcrRecords}{' '}{moteText("条")}</p>}{device.sync.retainedRecords!==undefined&&<p>{moteText("手机保留副本 ·")}{' '}{device.sync.retainedRecords}{' '}{moteText("条（不等于待上传数）")}</p>}{device.sync.lastUploadAt&&<p>{moteText("上次上传 ·")}{' '}{ago(device.sync.lastUploadAt)}</p>}{device.sync.nextUploadAt&&<p>{moteText("计划检查 ·")}{' '}{dateTime(device.sync.nextUploadAt)}<small>{moteText("系统调度、网络与电量条件可能推迟。")}</small></p>}</div>:<p className="fine-print">{moteText("此客户端尚未上报同步策略。采集与同步偏好请在客户端设置。")}</p>}
  {(device.platform==='android'||device.metadata?.media)&&<MediaSnapshot media={device.metadata?.media} observedAt={device.metadata?.observedAt} screenLocked={device.metadata?.state?.screenLocked} compact/>}
  {device.error&&<div className="device-note warn"><Info size={15}/><span>{moteText("上次报告：")}{device.error}</span></div>}<details className="device-details"><summary>{moteText("设备详情与元数据")}</summary><code className="record-id">{device.deviceId}</code><Metadata metadata={device.metadata}/></details>
 </article>;})}</div>}
 <button className="button subtle manage-authorizations" onClick={onConnect}>{moteText("管理连接授权")}<ArrowRight size={15}/></button></div>;
}
export function PageBack({title,onBack}:{title:string;onBack:()=>void}) {return <button className="back-link" onClick={onBack}><ArrowLeft size={16}/>{title}</button>;}
