import {useEffect,useState} from 'react';
import {type Api,errorMessage} from './api';

export async function downloadFileExport(api:Api,id:string){const response=await api.raw('/api/files/'+id+'/export'),url=URL.createObjectURL(await response.blob());try{const a=document.createElement('a');a.href=url;a.download='mote-recording-'+id+'.tar.gz';a.click();}finally{setTimeout(()=>URL.revokeObjectURL(url),60000);}}
function SpeakerSample({api,id,artifactId,sample}:{api:Api;id:string;artifactId:string;sample:any}){
 const [url,setUrl]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let active=true,created='';void api.raw('/api/files/'+id+'/assets?'+new URLSearchParams({artifactId,name:'speaker_samples/'+sample.speaker+'.wav'})).then(r=>r.blob()).then(blob=>{if(active){created=URL.createObjectURL(blob);setUrl(created);}}).catch(e=>{if(active)setError(errorMessage(e));});return()=>{active=false;if(created)URL.revokeObjectURL(created);};},[api,id,artifactId,sample.speaker]);
 return <div className="source-item"><strong>{sample.speaker}</strong>{url&&<audio controls preload="metadata" src={url}/>}<span>{error}</span></div>;
}
export function FileReview({api,id,artifacts,onChanged}:{api:Api;id:string;artifacts:any[];onChanged:()=>Promise<void>}){
 const [reviews,setReviews]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[selected,setSelected]=useState<Record<string,boolean>>({}),[replacements,setReplacements]=useState<Record<string,string>>({}),[names,setNames]=useState<Record<string,string>>({});
 const diarization=artifacts.find(a=>a.kind==='diarization'),dialogue=artifacts.find(a=>a.kind==='corrected-dialogue')??artifacts.find(a=>a.kind==='dialogue');
 async function load(){setReviews((await api.request<any>('/api/files/'+id+'/reviews')).items);}
 useEffect(()=>{setReviews([]);setNames(artifacts.find(a=>a.kind==='speaker-names')?.names??{});void load().catch(e=>setMessage(errorMessage(e)));},[api,id]);
 async function action(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();await load();}catch(e){setMessage(errorMessage(e));}finally{setBusy(false);}}
 async function propose(kind:string,offset=0){await api.request('/api/files/'+id+'/reviews',{method:'POST',body:JSON.stringify({kind,offset})});}
 async function confirm(review:any,accept:boolean){const ids=review.suggestions?.filter((s:any)=>selected[s.id]).map((s:any)=>s.id)??[];await api.request('/api/files/'+id+'/reviews/'+review.id,{method:'POST',body:JSON.stringify({action:accept?'accept':'reject',selected:ids,replacements:Object.fromEntries(ids.filter((x:string)=>replacements[x]).map((x:string)=>[x,replacements[x]]))})});await onChanged();}
 return <><div className="source-toolbar"><button className="button" disabled={busy} onClick={()=>void action(async()=>downloadFileExport(api,id))}>导出转写与说话人记录</button></div>
 {diarization&&<details><summary>说话人试听与命名</summary><p>标签为匿名声纹分组。请试听后自行填写名称；不确定或重叠片段需要回听。</p>{diarization.warnings?.map((w:string,i:number)=><p key={i}>{w}</p>)}{diarization.samples?.map((s:any)=><div key={s.speaker}><SpeakerSample api={api} id={id} artifactId={diarization.id} sample={s}/><label>{s.speaker} 名称<input value={names[s.speaker]??''} onChange={e=>setNames(v=>({...v,[s.speaker]:e.target.value}))}/></label></div>)}<button className="button" disabled={busy||!dialogue} onClick={()=>void action(async()=>{await api.request('/api/files/'+id+'/speakers',{method:'POST',body:JSON.stringify({artifactId:dialogue.id,names:Object.fromEntries(Object.entries(names).filter(([,v])=>v.trim()))})});await onChanged();setMessage('说话人名称已保存。');})}>确认说话人名称</button></details>}
 <details><summary>场次关联与术语复核</summary><p>模型只提出建议，确认后生成单独的校正版；未校正原文始终保留。本地多人录音使用已配置的本地语言模型。</p><div className="source-toolbar"><button className="button" disabled={busy} onClick={()=>void action(()=>propose('calendar'))}>建议匹配日程场次</button><button className="button" disabled={busy} onClick={()=>void action(()=>propose('terms'))}>检查可能的识别错误</button></div>
 {reviews.map(r=><div className="source-item" key={r.id}><strong>{r.kind==='calendar'?'场次关联':'术语复核'} · {{proposed:'待确认',accepted:'已确认',rejected:'已忽略',stale:'原文已变化'}[r.status as string]??r.status}</strong>{r.reason&&<p>{r.reason}</p>}{r.calendar?.map((c:any)=><p key={c.captureId}>{c.title}</p>)}{r.suggestions?.map((s:any)=><label key={s.id}><span><input type="checkbox" disabled={r.status!=='proposed'} checked={!!selected[s.id]} onChange={e=>setSelected(v=>({...v,[s.id]:e.target.checked}))}/>{s.original} → </span><input disabled={r.status!=='proposed'} value={replacements[s.id]??s.replacement} onChange={e=>setReplacements(v=>({...v,[s.id]:e.target.value}))}/><span>{s.reason}</span></label>)}{r.suggestions?.length===0&&<p>本批未提出需要校正的词。</p>}{r.status==='proposed'&&<div className="source-toolbar"><button className="button" disabled={busy||(r.kind==='calendar'?!r.calendarId:!r.suggestions?.some((s:any)=>selected[s.id]))} onClick={()=>void action(()=>confirm(r,true))}>确认{r.kind==='calendar'?'关联':'所选校正'}</button><button className="button" disabled={busy} onClick={()=>void action(()=>confirm(r,false))}>忽略本次建议</button></div>}{r.scope?.nextOffset!=null&&<button className="button" disabled={busy} onClick={()=>void action(()=>propose(r.kind,r.scope.nextOffset))}>检查下一批片段</button>}</div>)}</details>{busy&&<p role="status">正在处理…</p>}{message&&<p role="status">{message}</p>}</>;
}
