import {useEffect,useState} from 'react';
import {matchesFileType,type ProcessorParameter,type ProcessingProfile} from '@mote/shared';
import {type Api,errorMessage} from './api';

const types=[['audio/*','录音'],['image/*','图片'],['text/*','文本'],['application/pdf','PDF'],['*/*','其他 / 全部类型']];
const uid=(prefix:string)=>prefix+'.'+crypto.randomUUID();
export function FileProcessingSettings({api}:{api:Api}){
 const [saved,setSaved]=useState<any>(null),[dirty,setDirty]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[sources,setSources]=useState<{id:string;name:string}[]>([]),[preview,setPreview]=useState<any>(null),[scope,setScope]=useState({sourceId:'',type:'*/*'}),[match,setMatch]=useState<any>(null),[mime,setMime]=useState('audio/wav');
 useEffect(()=>{void api.request('/api/file-processing').then(setSaved).catch(e=>setMessage(errorMessage(e)));void api.request<any>('/api/sources').then(r=>setSources(r.items)).catch(()=>{});},[api]);
 const policy=saved?.policy,settings=saved?.settings,processors=saved?.processors??[];
 function edit(fn:(v:any)=>void){setSaved((v:any)=>{const next=structuredClone(v);fn(next);return next;});setDirty(true);setPreview(null);setMatch(null);}
 async function action(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(errorMessage(e));}finally{setBusy(false);}}
 const compatible=(p:ProcessingProfile,type:string)=>p.processorId==='archive'||processors.find((x:any)=>x.id===p.processorId)?.mediaTypes.some((t:string)=>matchesFileType(t.endsWith('/')?t+'*':t,type));
 const profileOptions=(type:string,current?:string)=>policy.profiles.filter((p:ProcessingProfile)=>p.id===current||compatible(p,type)).map((p:ProcessingProfile)=><option key={p.id} value={p.id}>{p.name}{compatible(p,type)?'':'（类型不兼容 / 插件不可用）'}</option>);
 const sourceOptions=<><option value="">全部来源</option>{sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</>;
 function parameter(profile:any,index:number,d:ProcessorParameter){const value=profile.parameters[d.key]??d.default??'',change=(v:unknown)=>edit(s=>{s.policy.profiles[index].parameters[d.key]=v;});
  return <label key={d.key}>{d.type==='boolean'?<><input type="checkbox" checked={value===true} onChange={e=>change(e.target.checked)}/>{d.label}</>:<>{d.label}{d.options?<select aria-label={d.label} value={String(value)} onChange={e=>change(e.target.value)}>{d.options.map(o=><option key={o}>{o}</option>)}</select>:<input aria-label={d.label} type={d.type==='number'?'number':'text'} value={String(value)} min={d.min} max={d.max} step={d.integer?1:'any'} required={!d.nullable&&d.type==='number'} onChange={e=>change(d.type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>}</>}{d.description&&<small>{d.description}</small>}</label>;
 }
 return <details className="source-item file-processing-settings"><summary>中央文件处理设置</summary><p>按文件类型选择处理方案。服务保存地址和密钥；方案保存独立参数；同一目录可对录音和图片采用不同方案。处理均由中央节点调度。</p>
 {saved&&<><form onSubmit={e=>{e.preventDefault();void action(async()=>{setSaved(await api.request('/api/file-processing',{method:'PUT',body:JSON.stringify({revision:saved.revision,settings,policy})}));setDirty(false);setPreview(null);setMessage('设置已保存。新文件和未完成任务使用新配置；已完成文件保留原结果。');});}}>
 <fieldset disabled={busy}><legend>处理开关与预算</legend><label><input type="checkbox" checked={settings.enabled} onChange={e=>edit(s=>{s.settings.enabled=e.target.checked;})}/>启用中央文件处理</label><div className="policy-grid"><label>每天音频预算（分钟）<input aria-label="每天音频预算（分钟）" type="number" min="1" max="100000" value={settings.dailyAudioMinutes} onChange={e=>edit(s=>{s.settings.dailyAudioMinutes=Number(e.target.value);})}/></label><label>单文件超时（秒）<input aria-label="单文件超时（秒）" type="number" min="1" max="3600" value={settings.timeoutMs/1000} onChange={e=>edit(s=>{s.settings.timeoutMs=Number(e.target.value)*1000;})}/></label></div></fieldset>
 <fieldset disabled={busy}><legend>1. 类型策略</legend><p>具体 MIME 类型优先于类型通配符；未配置的格式按“其他”处理。PDF 处理插件可由管理员接入 Cordis，接入后可在此选择。</p>
 <div className="policy-rules">{policy.rules.map((r:any,i:number)=>!r.sourceId&&<div className="policy-rule" key={i}><label>文件类型{types.some(([t])=>t===r.type)?<strong>{types.find(([t])=>t===r.type)?.[1]}</strong>:<input aria-label="精确 MIME 类型" value={r.type} placeholder="application/json" onChange={e=>edit(s=>{s.policy.rules[i].type=e.target.value;})}/>}</label><label>处理方案<select aria-label="处理方案" value={r.profileId} onChange={e=>edit(s=>{s.policy.rules[i].profileId=e.target.value;})}>{profileOptions(r.type,r.profileId)}</select></label>{r.type!=='*/*'&&<button type="button" className="text-button" onClick={()=>edit(s=>{s.policy.rules.splice(i,1);})}>删除规则</button>}</div>)}</div>
 <button type="button" className="button" onClick={()=>edit(s=>{s.policy.rules.push({type:'application/json',profileId:s.policy.profiles.find((p:any)=>p.processorId==='archive')?.id??s.policy.profiles[0].id});})}>添加类型规则</button>
 </fieldset>
 <fieldset disabled={busy}><legend>2. 处理方案</legend><p>每个方案拥有自己的参数。界面字段来自已加载的 Cordis 插件；密钥在下方服务中统一管理。本地多人录音保留未校正逐字记录，不自动调用云端摘要。</p>
 {policy.profiles.map((p:any,i:number)=>{const plugin=processors.find((x:any)=>x.id===p.processorId);return <details className="policy-card" key={p.id}><summary>{p.name} · {p.processorId==='archive'?'仅归档':plugin?.name??'插件不可用'}</summary><div className="policy-grid">
 <label>方案名称<input aria-label="方案名称" required value={p.name} onChange={e=>edit(s=>{s.policy.profiles[i].name=e.target.value;})}/></label>
 <label>处理插件<select aria-label="处理插件" value={p.processorId} onChange={e=>edit(s=>{const x=s.policy.profiles[i];x.processorId=e.target.value;x.parameters={};delete x.serviceId;delete x.modelServiceId;x.summarize=false;})}><option value="archive">仅归档原件</option>{processors.filter((x:any)=>x.stage==='extract').map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}{!plugin&&p.processorId!=='archive'&&<option value={p.processorId}>不可用：{p.processorId}</option>}</select></label>
 {plugin?.serviceKind&&<label>处理服务<select aria-label="处理服务" value={p.serviceId??''} onChange={e=>edit(s=>{s.policy.profiles[i].serviceId=e.target.value||undefined;})}><option value="">未配置（任务将等待）</option>{policy.services.filter((x:any)=>x.kind===plugin.serviceKind&&(p.processorId!=='audio.local-dialogue'||x.execution==='local')).map((x:any)=><option key={x.id} value={x.id}>{x.name} · {x.execution==='local'?'本地':'远程'}</option>)}</select></label>}
 {(plugin?.parameters??[]).map((d:ProcessorParameter)=>parameter(p,i,d))}
 {p.processorId==='audio.local-dialogue'&&<label>说话人分离插件<select aria-label="说话人分离插件" value={p.diarizationProcessor} onChange={e=>edit(s=>{s.policy.profiles[i].diarizationProcessor=e.target.value;})}>{processors.filter((x:any)=>x.stage==='diarize'&&x.localOnly).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
 {p.processorId!=='archive'&&<label>分析语言模型<select aria-label="分析语言模型" value={p.modelServiceId??''} onChange={e=>edit(s=>{s.policy.profiles[i].modelServiceId=e.target.value||undefined;})}><option value="">{p.processorId==='audio.local-dialogue'?'未配置（语义分组 / 校正建议需本地模型）':'使用中央模型设置'}</option>{policy.services.filter((x:any)=>x.kind==='model'&&(p.processorId!=='audio.local-dialogue'||x.execution==='local')).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
 {p.processorId!=='archive'&&p.processorId!=='audio.local-dialogue'&&<label><input type="checkbox" checked={p.summarize} onChange={e=>edit(s=>{s.policy.profiles[i].summarize=e.target.checked;})}/>提取后生成摘要（可能调用所选云端模型）</label>}
 </div><div className="source-toolbar"><button type="button" className="button" onClick={()=>edit(s=>{s.policy.profiles.push({...structuredClone(p),id:uid('profile'),name:p.name+' 副本'});})}>复制方案</button><button type="button" className="text-button" disabled={policy.rules.some((r:any)=>r.profileId===p.id)} onClick={()=>edit(s=>{s.policy.profiles.splice(i,1);})}>删除方案{policy.rules.some((r:any)=>r.profileId===p.id)?'（请先移除规则引用）':''}</button></div></details>;})}
 <button type="button" className="button" onClick={()=>edit(s=>{s.policy.profiles.push({id:uid('profile'),name:'新处理方案',processorId:'archive',parameters:{},diarizationProcessor:'audio.diarize',summarize:false});})}>添加处理方案</button>
 </fieldset>
 <fieldset disabled={busy}><legend>3. 来源覆盖</legend><p>仅覆盖选中的来源和文件类型；其他文件继续使用全局类型策略。匹配顺序：来源具体类型 → 来源通配类型 → 全局具体类型 → 全局通配类型 → 其他。</p>
 {policy.rules.map((r:any,i:number)=>r.sourceId&&<div className="policy-rule" key={i}><label>来源<select aria-label="来源" value={r.sourceId} onChange={e=>edit(s=>{s.policy.rules[i].sourceId=e.target.value;})}>{sources.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}{!sources.some(x=>x.id===r.sourceId)&&<option value={r.sourceId}>{r.sourceId}（来源未连接）</option>}</select></label><label>类型<input aria-label="类型" list="mote-policy-types" value={r.type} onChange={e=>edit(s=>{s.policy.rules[i].type=e.target.value;})}/></label><label>处理方案<select aria-label="处理方案" value={r.profileId} onChange={e=>edit(s=>{s.policy.rules[i].profileId=e.target.value;})}>{profileOptions(r.type,r.profileId)}</select></label><button type="button" className="text-button" onClick={()=>edit(s=>{s.policy.rules.splice(i,1);})}>移除覆盖</button></div>)}
 <button type="button" className="button" disabled={!sources.length} onClick={()=>edit(s=>{s.policy.rules.push({sourceId:sources[0].id,type:'audio/*',profileId:s.policy.rules.find((r:any)=>!r.sourceId&&r.type==='audio/*')?.profileId??s.policy.profiles[0].id});})}>添加来源覆盖</button>
 </fieldset>
 <fieldset disabled={busy}><legend>服务连接</legend><p>地址和密钥只需配置一次。共享服务的方案仍保留各自参数。远程服务需显式选择“远程 HTTPS”；本地多人录音只能绑定本地服务。</p>
 {policy.services.map((s:any,i:number)=><details className="policy-card" key={s.id}><summary>{s.name} · {s.execution==='local'?'本地':'远程'}</summary><div className="policy-grid"><label>服务名称<input aria-label="服务名称" required value={s.name} onChange={e=>edit(v=>{v.policy.services[i].name=e.target.value;})}/></label><label>服务类型<select aria-label="服务类型" value={s.kind} onChange={e=>edit(v=>{v.policy.services[i].kind=e.target.value;})}><option value="asr">录音转写 / 分离</option><option value="image">图片提取</option><option value="file">通用文件处理</option><option value="model">语言模型（OpenAI 兼容接口）</option></select></label><label>运行位置<select aria-label="运行位置" value={s.execution} onChange={e=>edit(v=>{v.policy.services[i].execution=e.target.value;})}><option value="local">中央本机</option><option value="remote">远程 HTTPS</option></select></label><label>服务地址<input aria-label="服务地址" required type="url" value={s.endpoint} onChange={e=>edit(v=>{v.policy.services[i].endpoint=e.target.value;})}/></label>{s.kind==='model'&&<label>模型名称<input aria-label="模型名称" required value={s.model} onChange={e=>edit(v=>{v.policy.services[i].model=e.target.value;})}/></label>}<label>服务密钥<input aria-label="服务密钥" type="password" autoComplete="off" value={s.apiKey??''} placeholder={s.apiKeyConfigured?'已配置，留空保留':'可留空'} onChange={e=>edit(v=>{v.policy.services[i].apiKey=e.target.value||undefined;})}/>{s.apiKeyConfigured&&<button type="button" className="text-button" onClick={()=>edit(v=>{v.policy.services[i].apiKey=null;v.policy.services[i].apiKeyConfigured=false;})}>清除已保存密钥</button>}</label></div>{s.kind==='asr'&&s.execution==='local'&&<button type="button" className="button" disabled={dirty} onClick={()=>void action(async()=>{const r=await api.request<any>('/api/file-processing/test-local',{method:'POST',body:JSON.stringify({serviceId:s.id})});setMessage(`已保存服务检测：转写${r.asr?'就绪':'未就绪'}，说话人分离${r.diarization?'就绪':'未就绪'}。`);})}>检测已保存本地服务</button>}<button type="button" className="text-button" disabled={policy.profiles.some((p:any)=>p.serviceId===s.id||p.modelServiceId===s.id)} onClick={()=>edit(v=>{v.policy.services.splice(i,1);})}>删除服务{policy.profiles.some((p:any)=>p.serviceId===s.id||p.modelServiceId===s.id)?'（正在被方案使用）':''}</button></details>)}
 <button type="button" className="button" onClick={()=>edit(s=>{s.policy.services.push({id:uid('service'),name:'新服务',kind:'asr',execution:'local',endpoint:'http://127.0.0.1:9009/transcribe',model:''});})}>添加服务</button>
 </fieldset>
 <datalist id="mote-policy-types">{types.map(([type,label])=><option key={type} value={type}>{label}</option>)}</datalist>
 <div className="source-toolbar"><button className="button" disabled={busy}>保存处理设置</button><span>{dirty?'有未保存修改':saved.policyConfigured?'已保存类型方案':'旧配置已转换为方案预览，保存后启用'}</span><button className="text-button" type="button" disabled={busy} onClick={()=>void action(async()=>{setSaved(await api.request('/api/file-processing'));setDirty(false);setPreview(null);})}>重新加载</button></div>
 </form>
 <fieldset disabled={busy||dirty}><legend>规则试算与已有文件</legend><p>以下操作使用已保存设置。仅归档和 Shadow 文件不会进入内容处理；每次最多重新处理 100 份当前版本原件，预览有效期 10 分钟。</p><div className="policy-grid"><label>目标来源<select aria-label="目标来源" value={scope.sourceId} onChange={e=>{setScope(v=>({...v,sourceId:e.target.value}));setPreview(null);setMatch(null);}}>{sourceOptions}</select></label><label>目标文件类型<select aria-label="目标文件类型" value={scope.type} onChange={e=>{setScope(v=>({...v,type:e.target.value}));setPreview(null);}}>{types.map(([t,label])=><option key={t} value={t}>{label}</option>)}</select></label><label>试算 MIME 类型<input aria-label="试算 MIME 类型" value={mime} onChange={e=>{setMime(e.target.value);setMatch(null);}}/></label></div>
 <div className="source-toolbar"><button className="button" type="button" onClick={()=>void action(async()=>setMatch(await api.request('/api/file-processing/match',{method:'POST',body:JSON.stringify({sourceId:scope.sourceId||'global-preview',mimeType:mime})})))}>查看匹配规则</button><button className="button" type="button" disabled={!settings.enabled} onClick={()=>void action(async()=>setPreview(await api.request('/api/file-processing/preview',{method:'POST',body:JSON.stringify({revision:saved.revision,type:scope.type,...(scope.sourceId?{sourceId:scope.sourceId}:{})})})))}>预览已有文件重处理</button></div>
 {match&&<p role="status">命中{match.rule.sourceId?'来源覆盖':'全局规则'} {match.rule.type} → {match.profile.name}</p>}
 {preview&&<div className="policy-preview"><strong>本批将重新处理 {preview.count} 份原件</strong><p>扫描范围内跳过 {preview.skipped} 份仅归档或正在处理的文件。{preview.bounded?'已达到预览上限，请缩小来源或类型范围。':''}重新处理将生成新的派生结果，已有校正会标为过期，原件继续保留。</p><ul>{preview.items.map((f:any)=><li key={f.id}>{f.title} → {f.profileName}（{f.rule.type}）</li>)}</ul><button className="button" type="button" disabled={!preview.count} onClick={()=>void action(async()=>{const r=await api.request<any>('/api/file-processing/reprocess',{method:'POST',body:JSON.stringify({token:preview.token})});setPreview(null);setMessage(`已加入重处理队列：${r.queued} 份文件。`);})}>确认重新处理这 {preview.count} 份文件</button></div>}
 </fieldset></>}
 {message&&<p role="status" className="policy-message">{message}</p>}</details>;
}
