import {useUnsavedChanges} from './unsaved';
import { moteText } from '@mote/shared/i18n';
import {useEffect,useState} from 'react';
import {type Api,errorMessage,dateTime} from './api';
type Policy={enabled:boolean;intervalHours:number;maxWaitHours?:number;minChanges:number;maxItems:number};
type Settings={drainWindows:number;extraction:Policy;consolidation:Policy;insights:Policy;working:Policy;batchCharacters:number;recentTurns:number;contextCharacters:number;summaryCharacters:number};
type View={settings:Settings;extensions:{id:string;version:string;status:string;pendingChanges:number;dueAt:number;failures:number;cursor:number}[]};
const names={extraction:moteText("资料记忆提取"),consolidation:moteText("长期记忆整理"),insights:moteText("周期洞察"),working:moteText("对话工作记忆")};
const statuses:Record<string,string>={disabled:moteText("已关闭"),pending:moteText("处理中或等待重试"),waiting_for_model:moteText("等待配置模型"),waiting_for_interval:moteText("等待周期"),waiting_for_increment:moteText("等待新增变化"),retry_wait:moteText('等待自动重试'),queued:moteText('排队等待执行名额'),running:moteText('正在执行'),paused:moteText('已暂停'),pausing:moteText('当前批次结束后暂停'),cancelled:moteText('已取消'),failed:moteText('失败，等待重试'),ready:moteText("等待下一次检查")};
export function MemorySettings({api}:{api:Api}){
  const [view,setView]=useState<View>(),[draft,setDraft]=useState<Settings>(),[error,setError]=useState(''),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false);
  useUnsavedChanges(!!view && JSON.stringify(draft) !== JSON.stringify(view.settings));
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;async function load(){try{const v=await api.request<View>('/api/memory-settings',{signal:controller.signal});if(controller.signal.aborted)return;setView(v);setDraft(current=>current??v.settings);setError('');}catch(e){if(!controller.signal.aborted)setError(errorMessage(e));}finally{if(!controller.signal.aborted)timer=setTimeout(()=>void load(),5000);}}void load();return()=>{controller.abort();clearTimeout(timer);};},[api]);
  async function save(){setBusy(true);setSaved(false);setError('');try{const v=await api.request<View>('/api/memory-settings',{method:'PUT',body:JSON.stringify(draft)});setView(v);setDraft(v.settings);setSaved(true);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <section className="panel memory-settings"><div className="section-heading"><div><h2>{moteText("记忆与洞察的节奏")}</h2><p>{moteText("新增变化达到门槛，或有新增资料且达到最大等待时间时运行。每分钟检查一次；进行中的窗口沿用启动时的设置。")}</p></div></div>
    {error&&<p className="notice error" role="alert">{error}</p>}{saved&&<p role="status">{moteText("设置已保存。")}</p>}
    {draft&&<form onSubmit={e=>{e.preventDefault();void save();}}>
      {(Object.keys(names) as (keyof typeof names)[]).map(id=>{const p=draft[id],state=view?.extensions.find(e=>e.id===id);return <fieldset key={id} disabled={busy}><legend>{names[id]}</legend><label><input type="checkbox" checked={p.enabled} onChange={e=>{setSaved(false);setDraft({...draft,[id]:{...p,enabled:e.target.checked}});}}/>{moteText("启用自动整理")}</label><div className="memory-settings-grid">{([['maxWaitHours',moteText("最大等待（小时）"),1/60,8760],['minChanges',id==='working'?moteText("新增对话轮次"):moteText("新增变化数"),1,100000],['maxItems',moteText("每个窗口最多处理变化"),1,id==='consolidation'?50:2000]] as const).map(([key,label,min,max])=><label key={key}>{label}<input type="number" min={min} max={max} step={key==='maxWaitHours'?'any':1} required value={p[key]??Math.min(p.intervalHours,1)} onChange={e=>{setSaved(false);setDraft({...draft,[id]:{...p,[key]:Number(e.target.value)}});}}/></label>)}</div>{state&&<p className="muted">{statuses[state.status]??state.status}{' '}{moteText("· 待处理")}{' '}{state.pendingChanges}{' '}{moteText("次变化 · 周期到达时间")}{' '}{dateTime(new Date(state.dueAt).toISOString())}{state.failures>0?moteText(" · 已失败 {0} 次，自动退避重试", state.failures):''}</p>}</fieldset>;})}
      <fieldset disabled={busy}><legend>{moteText("每次披露的内容量")}</legend><div className="memory-settings-grid">{([['drainWindows',moteText("每轮积压处理窗口上限"),1,1000],['batchCharacters',moteText("提取批次字符上限"),256,12000],['recentTurns',moteText("至少保留近期对话轮数"),2,20],['contextCharacters',moteText("对话上下文字符上限"),4000,60000],['summaryCharacters',moteText("工作记忆字符上限"),1000,12000]] as const).map(([key,label,min,max])=><label key={key}>{label}<input type="number" min={min} max={max} step="1" required value={draft[key]} onChange={e=>{setSaved(false);setDraft({...draft,[key]:Number(e.target.value)});}}/></label>)}</div></fieldset>
      <p>{moteText("记忆以文本保存，按“概览 → 内容与边界 → 原始证据”逐层展开，全文索引可从文本重建。自动生成的长期记忆需要你确认。提取轮次启动后，按窗口持续处理已圈定的积压，每轮窗口上限控制成本。")}</p><button className="button primary" disabled={busy} type="submit">{busy?moteText("正在保存…"):moteText("保存记忆设置")}</button>
    </form>}
  </section>;
}
