import {useEffect,useState} from 'react';
import {AnswerMarkdown} from './AnswerMarkdown';
import {type Api,errorMessage,dateTime,type Range} from './api';
interface Memory {id:string;title:string;statement?:string;uncertainty?:string;evidenceIds?:string[];status:string;createdAt:string;model?:string}
export function Memories({api,range,onOpen}:{api:Api;range:Range;onOpen:(id:string)=>void}){
 const [items,setItems]=useState<Memory[]>([]),[detail,setDetail]=useState<Memory|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){try{setItems((await api.request<{items:Memory[]}>('/api/memories?includeStale=true')).items);}catch(e){setError(errorMessage(e));}}
 useEffect(()=>{void refresh();},[api]);
 async function extract(){setBusy(true);setError('');try{await api.request('/api/memories/extract',{method:'POST',body:JSON.stringify({...range,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone})});await refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <section><div className="section-heading"><div><h2>记忆</h2><p className="muted">模型从当前时间范围的证据中提取候选记忆。先浏览标题，再展开内容和原始证据；来源修订后旧记忆会标记为需要重验。</p></div><button className="button primary" disabled={busy} onClick={()=>void extract()}>{busy?'正在读取证据并提取…':'提取记忆'}</button></div>{error&&<div className="error-banner" role="alert">{error}</div>}
 {!items.length&&<p className="muted">尚无记忆。接入资料并配置模型后，可以开始提取。</p>}
 <div className="source-grid"><aside>{items.map(m=><button className="source-select" key={m.id} onClick={()=>void api.request<Memory>('/api/memories/'+m.id).then(setDetail).catch(e=>setError(errorMessage(e)))}><strong>{m.title}</strong><small>{m.status==='stale'?'证据已更新，需重新提取':m.status==='published'?'已确认':'模型候选'} · {dateTime(m.createdAt)}</small></button>)}</aside><div>{detail&&<article className="source-item"><h3>{detail.title}</h3><AnswerMarkdown answer={{answer:detail.statement??'',runId:detail.id,trace:[],citations:(detail.evidenceIds??[]).map(id=>({id,capturedAt:detail.createdAt,appName:'原始证据',excerpt:''}))}} onOpen={onOpen}/><p className="muted">不确定性：{detail.uncertainty||'模型未补充；仍需核对原始证据。'}</p><p className="muted">由 {detail.model} 提取 · {detail.status==='stale'?'证据已变化':'模型推断'}，不是原始输入。</p><details><summary>展开原始证据（{detail.evidenceIds?.length??0}）</summary>{detail.evidenceIds?.map((id,i)=><p key={id}><button className="button" onClick={()=>onOpen(id)}>证据 {i+1}</button></p>)}</details><div className="source-toolbar">{detail.status==='proposed'&&<button className="button" onClick={()=>void api.request<Memory>('/api/memories/'+detail.id+'/publish',{method:'POST'}).then(async m=>{setDetail(m);await refresh();}).catch(e=>setError(errorMessage(e)))}>确认记忆</button>}<button className="button" onClick={()=>void api.request('/api/memories/'+detail.id,{method:'DELETE'}).then(async()=>{setDetail(null);await refresh();}).catch(e=>setError(errorMessage(e)))}>删除这条记忆</button></div></article>}</div></div></section>;
}
