import {currentMemoryMaterial,currentMemorySource,memoryMaterialId,memorySourceId,subscribeMemorySource} from './memory-source-route';
import {useSyncExternalStore} from 'react';
import {FeaturePanels} from './features/runtime';
import {useResource} from './useResource';
import {resources} from './resource-cache';
import {useOperationUpdates} from './useOperationUpdates';
import { moteText } from '@mote/shared/i18n';
import {ExecutionQueueOverview} from './RuntimeSettings';
import {ModelSelector} from './ModelSelector';
import {useEffect,useRef,useState} from 'react';
import {Layers3,LoaderCircle,RefreshCw,Sparkles,Trash2} from 'lucide-react';
import {AnswerMarkdown} from './AnswerMarkdown';
import {ArchivedFileButton} from './ArchivedFileButton';
import {MemoryProgress,useMemoryJob,memoryJobLabels,type MemoryJob} from './MemoryProgress';
import {ManualMemoryRecipes} from './ManualMemoryRecipes';
import {MemoryIntegration,currentIntegrationCandidate} from './MemoryIntegration';
import type {Material} from './Materials';
import type {MemoryRecipeRef} from './memory-recipes';
import {type Api,errorMessage,dateTime,type Range,type FileEvidence} from './api';

interface MemoryEvidence {
  id:string;sourceId?:string;externalId?:string;revision?:string;capturedAt:string;receivedAt:string;
  recordedAt?:string;occurredAt?:string;fileId?:string;path?:string;uri?:string;timeBasis?:string;
  contentRole?:string;offset?:number;length?:number;quote?:string;contentHash:string;
  fileEvidence?:FileEvidence;
}
interface Memory {
  version?:number;fingerprint?:string;relations?:{kind:"contradicts"|"supersedes";memoryId:string}[];supersededBy?:string;supersededAt?:string;validFrom?:string;validUntil?:string;correction?:{noteId:string};
  reviewReceipt?:{decision:"independent"|"reused"|"empty";checkedAt:string;reviewRunId?:string;draftRunId:string};
  admission?:{layer:'observation'|'memory';reason:string;scope:string;attribution:string};
  scopeRefs?:{projectName?:string;projectIdentity?:'workspace'|'session'|'unknown';sessionId:string;projectKey:string}[];
  domain?:'personal'|'coding';coding?:{kind:string;scope:string;applicability:string;validation:string};
  id:string;title:string;statement?:string;uncertainty?:string;evidenceIds?:string[];evidenceCount?:number;evidence?:MemoryEvidence[];
  tier?:string;kind?:string;status:string;createdAt:string;updatedAt?:string;model?:string;skillVersion?:string;staleReason?:string;
}
const codingLabels:Record<string,string>={pitfall:moteText("踩坑经验"),decision:moteText("设计决策"),principle:moteText("可复用原则"),preference:moteText("编码偏好"),session:moteText("本次会话"),project:moteText("项目内适用"),shared:moteText("可跨项目参考"),observed:moteText("已观察"),user_confirmed:moteText("用户已确认"),tested:moteText("有测试证据"),unverified:moteText("尚未验证")};
function sourceProjects(item:Memory){return [...new Set((item.scopeRefs??[]).map(ref=>ref.projectIdentity==='workspace'?(ref.projectName??moteText("已关联项目（名称未知）")):moteText("项目未知（仅关联会话）")))].join(' · ');}
const labels:Record<string,string>={proposed:moteText("待重新处理"),published:moteText("已生效"),stale:moteText("需要重验")};
function memoryStatus(item:Memory,at:number){if(item.status==='published'){if(item.supersededBy&&(!item.supersededAt||Date.parse(item.supersededAt)<=at))return moteText("已由新版本替代");if(item.validUntil&&Date.parse(item.validUntil)<=at)return moteText("已过期");if(item.validFrom&&Date.parse(item.validFrom)>at)return moteText("尚未生效");}return labels[item.status]||item.status;}
export function Memories({api,range,rangeSelectionKey,onOpen,refreshVersion=0,embedded=false,onChanged}:{onChanged?:()=>void;embedded?:boolean;refreshVersion?:number;api:Api;range:Range;rangeSelectionKey?:string;onOpen:(id:string)=>void}){
  const requestedSource=useSyncExternalStore(subscribeMemorySource,currentMemorySource,()=>null),sourceId=memorySourceId(requestedSource);
  const requestedMaterial=useSyncExternalStore(subscribeMemorySource,currentMemoryMaterial,()=>null),materialId=memoryMaterialId(requestedMaterial);
  const source=useResource<import('./api').Capture>(api,sourceId?'/api/capture-browser/'+encodeURIComponent(sourceId):null);
  const material=useResource<Material>(api,materialId?'/api/materials/'+encodeURIComponent(materialId):null);
  const explicitMaterial=requestedMaterial!==null,explicitSource=requestedSource!==null||explicitMaterial;
  const materialReady=!!materialId&&!!material.data&&material.data.ref===requestedMaterial&&material.data.memorySource?.status==='ready'&&!!material.data.memorySource.evidenceIds.length&&!material.error&&!material.loading;
  const sourceReady=!explicitMaterial&&!!sourceId&&!!source.data&&!source.error&&!source.loading;
  const selectionReady=explicitMaterial?materialReady:sourceReady;
  const Heading=embedded?'h2':'h1';
  const preserveSelection=useRef(false);const [createdMemoryId,setCreatedMemoryId]=useState<string>();
  const selectionApi=useRef(api);
  // A rolling window advances on shell polls without becoming a new user
  // selection. Exact callers still fence changes to either range endpoint.
  const selectionScope=JSON.stringify([rangeSelectionKey??[range.after,range.before],range.deviceId]);
  const [modelProfileId,setModelProfileId]=useState('');
  const [recipes,setRecipes]=useState<MemoryRecipeRef[]>([]);
  const [selectedId,setSelectedId]=useState<string|null>(null),[selectedReadScope,setSelectedReadScope]=useState(''),[mutationError,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[confirmDelete,setConfirmDelete]=useState(false);
  const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[tier,setTier]=useState(''),[layer,setLayer]=useState('memory'),[cursor,setCursor]=useState<string>();
  const [jobId,setJobId]=useState<string>();
  const [history,setHistory]=useState(false),[asOf,setAsOf]=useState(''),[correcting,setCorrecting]=useState(false),[correction,setCorrection]=useState({title:'',statement:'',uncertainty:'',validFrom:'',validUntil:''});
  const {job,error:jobError,reload:reloadJob}=useMemoryJob(api,jobId);
  const page=useResource<{items:Memory[];nextCursor:string|null}>(api,'/api/memories?'+new URLSearchParams({...range,includeStale:'true',includeHistory:String(history),...(asOf?{asOf:new Date(asOf).toISOString()}:{}),limit:'30',...(layer?{layer}:{}),...(query?{query}:{}),...(tier?{tier}:{}),...(cursor?{cursor}:{}),...(filter!=='all'?{status:filter}:{})}));
  const jobList=useResource<{items:MemoryJob[]}>(api,'/api/memory-jobs');
  // Keep a selected card in the scope in which the owner opened it. The shell
  // advances rolling endpoints on every poll; that does not change the choice.
  const selected=useResource<Memory>(api,selectedId?'/api/memories/'+encodeURIComponent(selectedId)+'?'+(selectedId===createdMemoryId?'':selectedReadScope):null);
  const detail=selected.data,items=page.data?.items??[],nextCursor=page.data?.nextCursor,jobs=jobList.data?.items??[],loading=page.loading;
  const error=mutationError||([page.error,selected.error,jobList.error].find(Boolean)?errorMessage([page.error,selected.error,jobList.error].find(Boolean)):'');
  useOperationUpdates(api);
  function refresh(){resources(api).invalidate(key=>/^\/api\/(memories|memory-jobs)([/?]|$)/.test(key));}
  useEffect(()=>{if(refreshVersion)refresh();},[api,refreshVersion]);
  useEffect(()=>{setJobId(current=>current??jobs.find(item=>['queued','running','pausing','paused','failed','waiting_for_model','waiting_for_input'].includes(item.status))?.id);},[jobList.data]);
  useEffect(()=>{const sameSession=selectionApi.current===api;selectionApi.current=api;setCursor(undefined);if(!(sameSession&&preserveSelection.current)){setSelectedId(null);setSelectedReadScope('');setCreatedMemoryId(undefined);}preserveSelection.current=false;},[api,selectionScope,query,tier,layer,filter,history,asOf]);
  useEffect(()=>{if(job?.status==='completed'||job?.status==='failed')refresh();},[job?.id,job?.status]);
  async function extract(){
    if(explicitSource&&!selectionReady)return;
    setBusy(true);setError('');
    try{const result=await api.request<MemoryJob>('/api/memory-jobs',{method:'POST',body:JSON.stringify({... (explicitMaterial?{evidenceIds:material.data!.memorySource!.evidenceIds}:explicitSource?{evidenceIds:[sourceId]}:range),...(recipes.length?{recipes}:{}),modelProfileId:modelProfileId||undefined,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone})});setJobId(result.id);reloadJob();refresh();}
    catch(e){setError(errorMessage(e));}finally{setBusy(false);}
  }
  function open(id:string,readScope:Range=range){setCreatedMemoryId(undefined);setCorrecting(false);setError('');setConfirmDelete(false);setSelectedReadScope(new URLSearchParams({...readScope}).toString());setSelectedId(id);}
  function openJobResult(){
    // A single-source job can legitimately use evidence outside the list's
    // time filter. Read its exact result ID while keeping the device filter.
    if(job?.memoryIds[0])open(job.memoryIds[0],range.deviceId?{deviceId:range.deviceId}:{});
  }
  async function saveCorrection(){if(!detail)return;setBusy(true);setError('');try{const result=await api.request<Memory>('/api/memories/'+encodeURIComponent(detail.id)+'/correct',{method:'POST',body:JSON.stringify({...correction,version:detail.version??1,validFrom:correction.validFrom?new Date(correction.validFrom).toISOString():undefined,validUntil:correction.validUntil?new Date(correction.validUntil).toISOString():undefined})});setCorrecting(false);setCreatedMemoryId(result.id);setSelectedId(result.id);if(onChanged){preserveSelection.current=rangeSelectionKey===undefined;onChanged();}refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function remove(){if(!detail)return;setBusy(true);setError('');try{await api.request('/api/memories/'+encodeURIComponent(detail.id),{method:'DELETE'});setSelectedId(current=>current===detail.id?null:current);setConfirmDelete(false);refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function download(){if(!detail)return;try{const blob=new Blob([moteText("# {0}\n\n{1}\n\n## 判断边界\n\n{2}\n\n## 原始证据\n\n{3}\n", detail.title, detail.statement??'', detail.uncertainty??'', JSON.stringify(detail.evidence??[],null,2))],{type:'text/markdown'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='memory.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(errorMessage(e));}}
  async function control(action:'pause'|'resume'|'cancel'){if(!job)return;setBusy(true);setError('');try{await api.request('/api/memory-jobs/'+job.id+'/'+action,{method:'POST'});reloadJob();refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function retry(){if(!job)return;setBusy(true);setError('');try{await api.request('/api/memory-jobs/'+encodeURIComponent(job.id)+'/retry',{method:'POST'});reloadJob();refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  const visible=items.filter(item=>filter==='all'||item.status===filter),statusAt=asOf&&!history?new Date(asOf).getTime():Date.now();
  const evidence:MemoryEvidence[]=detail?.evidence?.length?detail.evidence:(detail?.evidenceIds??[]).map(id=>({id,capturedAt:detail!.createdAt,receivedAt:detail!.createdAt,contentHash:''}));
  const citations=evidence.map(item=>({id:item.id,capturedAt:item.capturedAt,appName:item.path||moteText("原始证据"),excerpt:item.quote??''}));
  return <section className="memories-page"><div className="page-heading split-heading"><div><div className="eyebrow">{moteText("有依据，才值得记住")}</div><Heading>{moteText("记忆")}</Heading><p>{moteText("记忆通过自动审核和证据校验后直接生效，辅助问答。你可以随时查看来源、纠正或删除。")}</p></div></div>
    {explicitSource&&<section className="panel panel-pad memory-source-selection"><h2>{explicitMaterial?moteText('仅这份正式资料'):moteText("仅这条资料")}</h2><p>{moteText("本次提取只使用下方资料，不使用顶部的时间范围。")} </p>{explicitMaterial?<>{materialReady&&<><strong>{material.data!.title}</strong><p>{moteText('当前正式资料 · {0} 个证据片段',material.data!.memorySource!.evidenceIds.length)}</p><button className="button" onClick={()=>onOpen(material.data!.ref)}>{moteText('查看正式资料')}</button></>}{material.loading&&<p role="status">{moteText("正在读取…")}</p>}{(material.error||!materialId||material.data&&!materialReady)&&<p role="alert">{material.error?errorMessage(material.error):moteText('所选正式资料已变化或暂不可提取，请重新打开当前版本。')}</p>}</>:<>{source.data&&!source.error&&<><strong>{source.data.windowTitle||source.data.appName||moteText("原始记录")}</strong><p>{dateTime(source.data.capturedAt)}</p><p className="file-text">{source.data.ocrText?.slice(0,300)}</p><button className="button" onClick={()=>onOpen(sourceId!)}>{moteText("查看原始记录")}</button></>}{source.loading&&<p role="status">{moteText("正在读取…")}</p>}{(source.error||!sourceId)&&<p role="alert">{source.error?errorMessage(source.error):moteText("所选资料无效，请重新打开原始记录。")}</p>}</>}<button className="button subtle" onClick={()=>{window.location.hash='#/library/memories';}}>{moteText("清除资料选择，恢复时间范围")}</button></section>}
    <ModelSelector api={api} feature="memory" value={modelProfileId} onChange={setModelProfileId} disabled={busy||job?.status==='running'||job?.status==='queued'}/>
    <ManualMemoryRecipes api={api} value={recipes} onChange={setRecipes} disabled={busy}/>
    <div className="memory-actions"><button className="button primary" disabled={busy||(explicitSource&&!selectionReady)||job?.status==='running'||job?.status==='queued'} onClick={()=>void extract()}>{busy?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>}{explicitSource?moteText("提取所选资料的记忆"):moteText("提取当前范围的记忆")}</button></div>
    {error&&<div className="error-banner" role="alert">{error}</div>}{jobError&&<div className="error-banner" role="alert">{moteText("记忆进度暂时无法更新：")}{jobError}</div>}
    <ExecutionQueueOverview api={api}/>
    {job&&<MemoryProgress job={job} onAction={action=>void control(action)} onRetry={()=>void retry()} onView={openJobResult} onOpen={onOpen} busy={busy}/>}
    <MemoryIntegration api={api} candidate={selectedId===detail?.id&&!selected.error?detail:undefined} verificationPending={selected.loading}/>
    {jobs.length>0&&<details className="memory-job-history"><summary>{moteText("整理任务与排队（")}{jobs.length}）</summary><div className="evidence-buttons">{jobs.map(item=><button className="button subtle" key={item.id} onClick={()=>setJobId(item.id)}>{item.importJobId?.startsWith('lifecycle:')?moteText('自动整理'):moteText('手动整理')} · {memoryJobLabels[item.status]} · {item.completedBatches}/{item.totalBatches} · {dateTime(item.createdAt)}{item.memoryCount!==undefined&&<> · {item.memoryCount}{' '}{moteText("条记忆")}</>}</button>)}</div></details>}
    <form className="memory-search" onSubmit={e=>{e.preventDefault();setQuery(search);setCursor(undefined);}}><label>{moteText("检索记忆")}<input aria-label={moteText("检索记忆")} value={search} onChange={e=>setSearch(e.target.value)} placeholder={moteText("搜索中文或英文原文")} maxLength={500}/></label><label>{moteText("内容分类")}<select aria-label={moteText("内容分类")} value={layer} onChange={e=>{setLayer(e.target.value);setCursor(undefined);}}><option value="memory">{moteText("精选记忆")}</option><option value="observation">{moteText("事件与资料")}</option><option value="legacy">{moteText("旧版未审核")}</option><option value="">{moteText("全部")}</option></select></label><label>{moteText("记忆层级")}<select value={tier} onChange={e=>{setTier(e.target.value);setCursor(undefined);}}><option value="">{moteText("全部层级")}</option><option value="episode">{moteText("初次提取")}</option><option value="consolidated">{moteText("整合产物")}</option></select></label><button className="button subtle" type="submit">{moteText("搜索")}</button></form>
    <div className="memory-search"><label><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/>{moteText("包括已替代和过期的历史记忆")}</label><label>{moteText("查看当时有效的记忆")}<input type="datetime-local" value={asOf} disabled={history} onChange={e=>setAsOf(e.target.value)}/></label>{asOf&&<button className="button subtle" onClick={()=>setAsOf('')}>{moteText("回到当前")}</button>}</div>
    <nav className="segmented-nav memory-filters" aria-label={moteText("记忆状态")}>{[['all',moteText("全部")],['published',moteText("已生效")],['stale',moteText("需要重验")]].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>{setFilter(id);setCursor(undefined);}}>{label}</button>)}</nav>
    <div className="workspace-layout"><aside className="workspace-list" aria-label={moteText("记忆列表")}><div className="workspace-list-heading"><h2>{filter==='all'?moteText("全部记忆"):labels[filter]}</h2><button className="icon-button" aria-label={moteText("刷新记忆")} onClick={refresh}><RefreshCw size={15}/></button></div>{loading&&<p className="muted">{moteText("正在读取…")}</p>}{!loading&&!page.error&&!visible.length&&<p className="muted">{moteText("当前筛选下没有匹配的记忆。可切换内容分类或调整筛选条件。")}</p>}{visible.map(item=><button className={'workspace-select '+(detail?.id===item.id?'active':'')} key={item.id} onClick={()=>void open(item.id)}><strong>{item.title}</strong><small>{item.admission?.layer==='memory'?moteText("精选记忆"):item.admission?.layer==='observation'?moteText("事件与资料"):moteText("旧版未审核")}</small>{item.coding&&<small>{moteText("编码经验 ·")}{' '}{codingLabels[item.coding.kind]} · {codingLabels[item.coding.scope]}</small>}{!!item.scopeRefs?.length&&<small>{moteText("会话项目：{0}",sourceProjects(item))}</small>}<span>{item.tier==='consolidated'?moteText("整合产物"):moteText("初次提取")}</span><span className={'status-label '+(item.status==='stale'?'attention':'')}>{memoryStatus(item,statusAt)}</span><small>{dateTime(item.createdAt)} · {item.evidenceCount??item.evidenceIds?.length??0}{' '}{moteText("条证据")}</small></button>)}<div className="memory-actions">{cursor&&<button className="button subtle" onClick={()=>setCursor(undefined)}>{moteText("返回第一页")}</button>}{nextCursor&&<button className="button subtle" onClick={()=>setCursor(nextCursor)}>{moteText("下一页")}</button>}</div></aside>
    <div className="workspace-content">{selected.loading&&!detail?<p role="status">{moteText("正在读取…")}</p>:detail?<article className="panel memory-detail"><div className="section-heading"><div><span className={'status-label '+(detail.status==='stale'?'attention':'')}>{memoryStatus(detail,statusAt)}</span><h2>{detail.title}</h2></div><button className="button" onClick={()=>onOpen("memory:"+detail.id)}>{moteText("展开证据")}</button></div>
      {detail.status==='proposed'&&<p className="notice" role="status">{moteText("这条旧版记忆尚未通过当前的自动生效校验。重新提取当前范围可重新处理，无需逐条确认。")}</p>}
      {(detail.validFrom||detail.validUntil||detail.supersededBy||detail.relations?.length||detail.correction)&&<div className="review-notes"><h3>{moteText("版本与有效期")}</h3><p>{moteText("版本 {0}",detail.version??1)}{detail.validFrom&&<> · {moteText("生效于")}{' '}{dateTime(detail.validFrom)}</>}{detail.validUntil&&<> · {moteText("失效于")}{' '}{dateTime(detail.validUntil)}</>}</p>{detail.correction&&<p>{moteText("这是用户主动纠正的版本，原始说明已保留。")}</p>}{detail.supersededBy&&<button className="button subtle" onClick={()=>open(detail.supersededBy!)}>{moteText("查看替代版本")}</button>}{detail.relations?.map((relation,index)=><p key={index}><button className="button subtle" onClick={()=>open(relation.memoryId)}>{relation.kind==='supersedes'?moteText("替代的旧记忆"):moteText("存在矛盾的记忆")}</button></p>)}</div>}
      {detail.admission&&<div className="review-notes"><h3>{detail.admission.layer==='memory'?moteText("精选记忆"):moteText("事件与资料")}</h3><p>{detail.admission.reason}</p><p>{detail.admission.scope}</p></div>}
      {detail.reviewReceipt&&<details className="run-details"><summary>{moteText("审核记录")}</summary><p>{detail.reviewReceipt.decision==='reused'?moteText("复用了相同候选与证据版本的独立审核结果，并重新校验了引用和范围。"):moteText("已通过独立模型审核和引用校验。")}</p><p>{dateTime(detail.reviewReceipt.checkedAt)}</p>{detail.reviewReceipt.reviewRunId&&<p><span>{moteText("审核编号")}</span> <code>{detail.reviewReceipt.reviewRunId}</code></p>}</details>}
      {!!detail.scopeRefs?.length&&<p>{moteText("会话项目：{0}",sourceProjects(detail))}</p>}
      {detail.coding&&<div className="review-notes"><h3>{codingLabels[detail.coding.kind]} · {codingLabels[detail.coding.scope]}</h3><p>{detail.coding.applicability}</p><small>{codingLabels[detail.coding.validation]}</small></div>}
      <AnswerMarkdown answer={{answer:detail.statement??'',runId:detail.id,trace:[],citations}} onOpen={onOpen}/>
      <div className="review-notes"><h3>{detail.status==='stale'?moteText("证据发生了变化"):moteText("判断的边界")}</h3>{detail.status==='stale'?<p>{moteText("来源已更新或移除，旧记忆需要重新核对。")}</p>:detail.uncertainty?<AnswerMarkdown answer={{answer:detail.uncertainty,runId:detail.id,trace:[],citations}} onOpen={onOpen}/>:<p>{detail.correction?moteText("未补充判断边界；可查看下方原始说明。"):moteText("模型未补充不确定性；可查看下方证据核对。")}</p>}</div>
      <section className="memory-evidence"><h3>{moteText("支持这条记忆的证据")}</h3>{evidence.map((item,index)=><article className="memory-evidence-item" key={item.id+':'+index}><button className="evidence-card" onClick={()=>onOpen(item.id)}><span className="evidence-number">{index+1}</span><div><strong>{item.path||moteText("查看原始记录")}</strong><small>{dateTime(item.occurredAt||item.recordedAt||item.capturedAt)}</small>{item.quote&&<p>{item.quote}</p>}</div></button><div className="evidence-meta">{item.fileId&&<ArchivedFileButton api={api} id={item.fileId} name={item.path?.split('/').pop()}/>}<details><summary>{moteText("来源与定位")}</summary><dl>{item.sourceId&&<><dt>{moteText("来源")}</dt><dd>{item.sourceId}</dd></>}{item.externalId&&<><dt>{moteText("原始记录")}</dt><dd>{item.externalId}</dd></>}{item.revision&&<><dt>{moteText("来源版本")}</dt><dd>{item.revision}</dd></>}{item.uri&&<><dt>{moteText("原件位置")}</dt><dd>{item.uri}</dd></>}<dt>{moteText("观察时间")}</dt><dd>{dateTime(item.capturedAt)}</dd>{item.receivedAt&&<><dt>{moteText("归档时间")}</dt><dd>{dateTime(item.receivedAt)}</dd></>}{item.offset!==undefined&&<><dt>{moteText("引用片段")}</dt><dd>{moteText("从第 {0} 个字符开始", item.offset+1)}{item.length!==undefined?moteText("，共 {0} 个字符", item.length):''}</dd></>}</dl></details></div></article>)}</section>
      <FeaturePanels api={api} onOpen={onOpen} value={{kind:'mote.memory',schemaVersion:1,representation:'saved-record',ref:'memory:'+detail.id,revision:detail.updatedAt??detail.createdAt,title:detail.title,text:JSON.stringify(detail,null,2)}}/><div className="memory-actions">{currentIntegrationCandidate(detail)&&<button className="button subtle" onClick={()=>document.getElementById('manual-memory-integration')?.scrollIntoView?.({behavior:'smooth'})}>{moteText('从这条记忆开始整理')}</button>}<button className="button subtle" onClick={()=>void download()}>{moteText("下载文本")}</button>{!detail.supersededBy&&<button className="button subtle" disabled={busy} onClick={()=>{setCorrecting(true);setCorrection({title:detail.title,statement:'',uncertainty:'',validFrom:'',validUntil:''});}}>{moteText("纠正记忆")}</button>}{confirmDelete?<><span className="muted">{moteText("删除这条记忆？原始资料保留；不会再用同一批旧证据生成这个结论，有新证据时可重新判断。")}</span><button className="button danger" disabled={busy} onClick={()=>void remove()}>{moteText("确认删除")}</button><button className="button subtle" onClick={()=>setConfirmDelete(false)}>{moteText("取消")}</button></>:<button className="button subtle" disabled={busy} onClick={()=>setConfirmDelete(true)}><Trash2 size={14}/>{moteText("删除记忆")}</button>}</div>
      {correcting&&<form className="review-notes" onSubmit={e=>{e.preventDefault();void saveCorrection();}}><h3>{moteText("纠正记忆")}</h3><p>{moteText("填写纠正后的内容，保存后直接生效。你的说明会作为原始证据保存；旧记忆及其证据仍可查看，适用项目保持不变。")}</p><label>{moteText("标题")}<input value={correction.title} maxLength={160} required onChange={e=>setCorrection(v=>({...v,title:e.target.value}))}/></label><label>{moteText("纠正后的内容")}<textarea value={correction.statement} maxLength={6000} required rows={4} onChange={e=>setCorrection(v=>({...v,statement:e.target.value}))}/></label><label>{moteText("判断的边界")}<textarea value={correction.uncertainty} maxLength={2000} onChange={e=>setCorrection(v=>({...v,uncertainty:e.target.value}))}/></label><label>{moteText("生效时间（留空为现在）")}<input type="datetime-local" value={correction.validFrom} onChange={e=>setCorrection(v=>({...v,validFrom:e.target.value}))}/></label><label>{moteText("失效时间（可选）")}<input type="datetime-local" value={correction.validUntil} onChange={e=>setCorrection(v=>({...v,validUntil:e.target.value}))}/></label><div className="memory-actions"><button className="button primary" type="submit" disabled={busy||!correction.statement.trim()}>{moteText("保存纠正并替代旧版本")}</button><button type="button" className="button subtle" onClick={()=>setCorrecting(false)}>{moteText("取消")}</button></div></form>}
      <details className="run-details"><summary>{moteText("生成信息")}</summary><dl><dt>{moteText("生成时间")}</dt><dd>{dateTime(detail.createdAt)}</dd><dt>{moteText("模型")}</dt><dd>{detail.model||moteText("未记录")}</dd>{detail.skillVersion&&<><dt>{moteText("Skill 版本")}</dt><dd>{detail.skillVersion}</dd></>}</dl><p className="muted">{detail.correction?moteText("这是你的主动纠正；原始说明和旧版本均已保留。"):moteText("这是从原始资料中提取的模型判断。")}</p></details>
    </article>:<div className="panel workspace-empty"><Layers3 size={32}/><h2>{moteText("把有用的事实和经验，留给下一次。")}</h2><p>{moteText("选择一条记忆，查看内容、来源和判断的边界。")}</p></div>}</div></div>
  </section>;
}
