import {useResource} from './useResource';
import {resources} from './resource-cache';
import {ApiError} from './api';
import {useUnsavedChanges} from './unsaved';
import {moteText} from '@mote/shared/i18n';
import {useEffect,useState} from 'react';
import {MODEL_FEATURES,MODEL_FEATURE_LABELS,type ModelFeature,type ModelFeatureDefaults,type ModelFeatureModels,type ModelSettingsView} from '@mote/shared/models';
import {type Api,errorMessage} from './api';

function ModuleModel({api,feature,profileId,value,onChange,disabled,fallback}:{api:Api;feature:ModelFeature;profileId:string;value:string;onChange:(value:string)=>void;disabled:boolean;fallback:string}){
  const [custom,setCustom]=useState(Boolean(value));
  useEffect(()=>{setCustom(Boolean(value));},[profileId]);
  const {data,error,loading}=useResource<{items:{id:string;name:string}[]}>(api,custom?`/api/model-settings/profiles/${encodeURIComponent(profileId)}/models`:null),models=data?.items??[];
  return <div className="module-model"><label className="preference-field">{moteText("模型")}<select aria-label={MODEL_FEATURE_LABELS[feature]+moteText("模型方式")} disabled={disabled} value={custom?'custom':'inherit'} onChange={e=>{const next=e.target.value==='custom';setCustom(next);if(!next)onChange('');}}><option value="inherit">{moteText("跟随预设默认")}{fallback?' · '+fallback:''}</option><option value="custom">{moteText("指定此 Provider 下的模型")}</option></select></label>{custom&&<label className="preference-field">{moteText("指定模型 ID")}<input aria-label={MODEL_FEATURE_LABELS[feature]+moteText("指定模型 ID")} list={'module-models-'+feature} value={value} maxLength={512} disabled={disabled} placeholder={loading?moteText("正在读取模型列表…"):fallback||moteText("选择或填写模型 ID")} onChange={e=>onChange(e.target.value)}/><datalist id={'module-models-'+feature}>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</datalist>{error!==undefined&&<small role="status">{errorMessage(error)}</small>}</label>}</div>;
}

export function ModelAssignments({api,revision,onApplied,onManage}:{api:Api;revision:number;onApplied:()=>void;onManage:()=>void}){
  const [view,setView]=useState<ModelSettingsView>(),[defaults,setDefaults]=useState<ModelFeatureDefaults>(),[models,setModels]=useState<ModelFeatureModels>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const dirty=!!view&&(JSON.stringify(defaults)!==JSON.stringify(view.defaults)||JSON.stringify(models)!==JSON.stringify(view.defaultModels??{}));
  useUnsavedChanges(dirty);
  const read=useResource<ModelSettingsView>(api,'/api/model-settings');
 useEffect(()=>{setView(undefined);setDefaults(undefined);setModels({});setError('');setNotice('');},[api]);
 useEffect(()=>{if(read.data&&!dirty){setView(read.data);setDefaults(read.data.defaults);setModels(read.data.defaultModels??{});}if(read.error instanceof ApiError&&[401,403,404,410].includes(read.error.status)){setView(undefined);setDefaults(undefined);setModels({});}},[api,read.data,read.error]);
  async function save(){if(!view||!defaults)return;setBusy(true);setError('');setNotice('');try{const next=await api.request<ModelSettingsView>('/api/model-settings/defaults',{method:'PUT',body:JSON.stringify({revision:view.revision,defaults,defaultModels:models})});setView(next);setDefaults(next.defaults);setModels(next.defaultModels??{});resources(api).invalidate(key=>key.startsWith('/api/model-settings'));setNotice(moteText("模块分配已保存，新请求立即生效。"));onApplied();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <section className="panel module-assignments"><div className="section-heading"><div><h2>{moteText("模块使用的模型")}</h2><p>{moteText("跟随预设的默认模型，或为模块指定同一连接下的其他模型。单次请求的选择优先。")}</p></div><button className="button subtle" onClick={onManage}>{moteText("管理 Provider")}</button></div>{Boolean(error||read.error)&&<p role="alert" className="notice error">{error||errorMessage(read.error)}</p>}{view&&defaults&&<><div className="module-assignment-list">{MODEL_FEATURES.map(feature=><div className="module-assignment-row" key={feature}><div><h3>{MODEL_FEATURE_LABELS[feature]}</h3>{feature==='file'&&<small>{moteText("文件处理器的显式模型与本地处理限制优先。")}</small>}</div><label className="preference-field">{moteText("Provider 预设")}<select aria-label={MODEL_FEATURE_LABELS[feature]+moteText("默认模型")} value={defaults[feature]} disabled={busy} onChange={e=>{setDefaults({...defaults,[feature]:e.target.value});setModels(prev=>{const next={...prev};delete next[feature];return next;});setNotice('');}}>{view.profiles?.map(p=><option key={p.id} value={p.id}>{p.name}{p.readOnly?moteText(" · 只读"):''}</option>)}</select></label><ModuleModel key={feature+defaults[feature]+view.revision} api={api} feature={feature} profileId={defaults[feature]} fallback={view.profiles?.find(p=>p.id===defaults[feature])?.settings.model??''} value={models[feature]??''} disabled={busy} onChange={value=>{setModels(prev=>{const next={...prev};if(value.trim())next[feature]=value.trim();else delete next[feature];return next;});setNotice('');}}/></div>)}</div><div className="module-assignment-footer"><button className="button primary" disabled={busy||(JSON.stringify(defaults)===JSON.stringify(view.defaults)&&JSON.stringify(models)===JSON.stringify(view.defaultModels??{}))} onClick={()=>void save()}>{moteText("保存模块分配")}</button>{notice&&<span role="status">{notice}</span>}</div></>}</section>;
}
