export type ModelBudgetLimits={dailyTokens:number|null;dailyCost:number|null;operationTokens:number|null;operationCost:number|null;providerDailyTokens:Record<string,number>;providerDailyCost:Record<string,number>;currency:'USD'|'CNY'};
export type ModelBudgetView={minimumInputReservationTokens?:number;revision:number;limits:ModelBudgetLimits;day:string;timeZone:'UTC';usage:{provider:string;currency:string;tokens:number;cost:number|null;active:number;unknown:number;runs:number}[]};
export type BudgetDraft={revision:number;dailyTokens:string;dailyCost:string;operationTokens:string;operationCost:string;currency:'USD'|'CNY';providers:{id:string;tokens:string;cost:string}[]};
export function budgetDraft(view:ModelBudgetView):BudgetDraft{const l=view.limits;return {revision:view.revision,dailyTokens:String(l.dailyTokens??''),dailyCost:String(l.dailyCost??''),operationTokens:String(l.operationTokens??''),operationCost:String(l.operationCost??''),currency:l.currency,providers:[...new Set([...Object.keys(l.providerDailyTokens),...Object.keys(l.providerDailyCost)])].sort().map(id=>({id,tokens:String(l.providerDailyTokens[id]??''),cost:String(l.providerDailyCost[id]??'')}))};}
/** Empty means unlimited, never zero; the revision belongs to the edited draft. */
export function budgetPayload(draft:BudgetDraft):{revision:number;limits:ModelBudgetLimits}{
 const amount=(value:string,integer:boolean)=>{if(!value.trim())return null;const number=Number(value);if(!Number.isFinite(number)||number<=0||number>(integer?1e12:1e9)||integer&&!Number.isSafeInteger(number))throw Error('invalid_budget');return number;};
 const providerDailyTokens:Record<string,number>={},providerDailyCost:Record<string,number>={},seen=new Set<string>();
 for(const row of draft.providers){const id=row.id.trim();if(!id||seen.has(id))throw Error('invalid_provider');seen.add(id);const tokens=amount(row.tokens,true),cost=amount(row.cost,false);if(tokens!==null)Object.defineProperty(providerDailyTokens,id,{value:tokens,enumerable:true,configurable:true,writable:true});if(cost!==null)Object.defineProperty(providerDailyCost,id,{value:cost,enumerable:true,configurable:true,writable:true});}
 return {revision:draft.revision,limits:{dailyTokens:amount(draft.dailyTokens,true),dailyCost:amount(draft.dailyCost,false),operationTokens:amount(draft.operationTokens,true),operationCost:amount(draft.operationCost,false),providerDailyTokens,providerDailyCost,currency:draft.currency}};
}
