import {useEffect,useRef,useState} from 'react';
import {moteText} from '@mote/shared/i18n';
import {type Api,errorMessage,ApiError} from './api';
import {useResource} from './useResource';
import {useUnsavedChanges} from './unsaved';
import {budgetDraft,budgetPayload,type BudgetDraft,type ModelBudgetView} from './model-budget-form';
export function ModelBudgets({api}:{api:Api}){
 const {data,error:readError,loading,refresh}=useResource<ModelBudgetView>(api,'/api/model-budgets');
 const [draft,setDraft]=useState<BudgetDraft>(),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useUnsavedChanges(dirty);
 const incoming=useRef<ModelBudgetView|undefined>(undefined);
 useEffect(()=>{if(data!==incoming.current){incoming.current=data;if(data&&!dirty)setDraft(budgetDraft(data));}},[data,dirty]);
 function edit(change:(value:BudgetDraft)=>void){setDraft(value=>{const next=structuredClone(value!);change(next);return next;});setDirty(true);setNotice('');}
 async function save(){if(!draft)return;setBusy(true);setError('');setNotice('');try{const payload=budgetPayload(draft),saved=await api.request<ModelBudgetView>('/api/model-budgets',{method:'PUT',body:JSON.stringify(payload)});setDraft(budgetDraft(saved));setDirty(false);setNotice(moteText('已保存，立即生效。'));refresh();}catch(e){setError(e instanceof ApiError&&e.status===409?moteText('预算设置已在其他页面更新。当前修改已保留，请重新加载后再保存。'):e instanceof Error&&e.message==='invalid_provider'?moteText('服务 ID 不能为空或重复。'):e instanceof Error&&e.message==='invalid_budget'?moteText('预算须为正数；token 须为整数，留空表示不限。'):errorMessage(e));}finally{setBusy(false);}}
 const failure=error||(readError?errorMessage(readError):'');
 return <section className="panel model-budgets"><div className="section-heading"><div><h2>{moteText('模型预算')}</h2><p>{moteText('默认不限。可按每日、单个任务及服务设置 token 或金额上限。')}</p></div><button className="button subtle" disabled={busy||dirty} onClick={refresh}>{moteText('刷新')}</button></div>
 <p className="fine-print">{moteText('每日预算按 UTC 结算；跨午夜运行仍归属首次模型请求所在日期。未知用量保留预留额度，不按零消耗释放。')}</p><p className="fine-print">{moteText('金额预算需要配置相同币种的模型价格。Codex 内置循环暂不支持逐请求硬预算；启用相关限制后，该运行时会等待配置。')}</p>
 {loading&&!data&&<p role="status">{moteText('正在读取…')}</p>}{failure&&<p className="notice error" role="alert">{failure}</p>}
 {draft&&<form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}><div className="preference-grid">{([['dailyTokens','每日 token 上限'],['operationTokens','单个任务 token 上限'],['dailyCost','每日金额上限'],['operationCost','单个任务金额上限']] as const).map(([key,label])=><label key={key}>{moteText(label)}<input aria-label={moteText(label)} type="number" min={key.endsWith('Tokens')?1:0} max={key.endsWith('Tokens')?1e12:1e9} step={key.endsWith('Tokens')?1:'any'} placeholder={moteText('不限')} value={draft[key]} onChange={e=>edit(value=>{value[key]=e.target.value;})}/></label>)}<label>{moteText('预算币种')}<select aria-label={moteText('预算币种')} value={draft.currency} onChange={e=>edit(value=>{value.currency=e.target.value as 'USD'|'CNY';})}><option>USD</option><option>CNY</option></select></label></div>
 <h3>{moteText('各服务每日预算')}</h3>{draft.providers.map((provider,index)=><div className="source-toolbar" key={index}><label>{moteText('服务 ID')}<input aria-label={moteText('预算服务 ID')} required maxLength={128} value={provider.id} onChange={e=>edit(value=>{value.providers[index].id=e.target.value;})}/></label><label>{moteText('每日 token 上限')}<input aria-label={moteText('服务每日 token 上限')} type="number" min={1} max={1e12} step={1} placeholder={moteText('不限')} value={provider.tokens} onChange={e=>edit(value=>{value.providers[index].tokens=e.target.value;})}/></label><label>{moteText('每日金额上限')}<input aria-label={moteText('服务每日金额上限')} type="number" min={0} max={1e9} step="any" placeholder={moteText('不限')} value={provider.cost} onChange={e=>edit(value=>{value.providers[index].cost=e.target.value;})}/></label><button className="button subtle" type="button" onClick={()=>edit(value=>{value.providers.splice(index,1);})}>{moteText('移除')}</button></div>)}<button className="button subtle" type="button" onClick={()=>edit(value=>{value.providers.push({id:'',tokens:'',cost:''});})}>{moteText('添加服务预算')}</button>
 <div className="source-toolbar"><button className="button primary" disabled={!dirty||busy}>{busy?moteText('保存中…'):moteText('保存预算')}</button>{dirty&&<button className="button subtle" type="button" onClick={()=>{setDirty(false);setError('');refresh();}}>{moteText('放弃修改并重新加载')}</button>}</div></fieldset></form>}{notice&&<p role="status">{notice}</p>}
 {data&&<div className="usage-table-scroll"><table className="usage-table"><caption>{moteText('当日计入预算的用量与预留')} · {data.day} UTC</caption><thead><tr>{['服务 ID','币种','Token','已知金额与预留','进行中','用量待确认'].map(label=><th key={label}>{moteText(label)}</th>)}</tr></thead><tbody>{data.usage.map(row=><tr key={row.provider+':'+row.currency}><td>{row.provider}</td><td>{row.currency}</td><td>{row.tokens.toLocaleString()}</td><td>{row.cost===null?moteText('未估算'):row.cost.toLocaleString(undefined,{maximumFractionDigits:6})}</td><td>{row.active}</td><td>{row.unknown}</td></tr>)}</tbody></table></div>}
 </section>;
}
