import {useResource} from './useResource';
import {ApiError} from './api';
import {failureMessage} from './failure-message';
import {useUnsavedChanges} from './unsaved';
import {moteText} from '@mote/shared/i18n';
import {useEffect,useState} from 'react';
import {type Api,errorMessage} from './api';
type Settings={providerRevision:string;enabled:boolean;ocrEndpoint:string;semanticEndpoint:string;semanticMode:'manual'|'realtime'|'batch';batchMinutes:number;batchSize:number;allowExternalProcessing:boolean;allowQueryImages:boolean};
type View={recent:{id:string;kind:string;state:string;error?:string;autoEligible:number}[];settings:Settings;jobs:{kind:string;state:string;count:number;autoEligible:number}[]};
type ModelState={state:string;bytes:number;totalBytes:number;source:string;error?:string;runtimeReady:boolean};
export function PerceptionSettings({api}:{api:Api}){
 const [settings,setSettings]=useState<Settings>(),[error,setError]=useState(''),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 const [historical,setHistorical]=useState<{token:string;count:number;bounded:boolean}|null>(null);
 const read=useResource<View>(api,'/api/perception'),view=read.data;
 const models=useResource<{ocr:ModelState;dialogue:ModelState}>(api,'/api/media-models'),ocr=models.data?.ocr;
 useEffect(()=>{if(ocr&&(['downloading','verifying','installing'].includes(ocr.state)||ocr.state==='ready'&&!ocr.runtimeReady)){const timer=setInterval(models.refresh,2000);return()=>clearInterval(timer);}},[ocr?.state,ocr?.runtimeReady,models.refresh]);
 useUnsavedChanges(dirty);
 useEffect(()=>{setSettings(undefined);setDirty(false);setError('');setSaved(false);setHistorical(null);},[api]);
 useEffect(()=>{if(read.data&&!dirty)setSettings(read.data.settings);if(read.error instanceof ApiError&&[401,403,404,410].includes(read.error.status)){setSettings(undefined);setDirty(false);}},[api,read.data,read.error]);
 const change=<K extends keyof Settings>(key:K,value:Settings[K])=>{setSettings(s=>s?{...s,[key]:value}:s);setSaved(false);setDirty(true);};
 return <section className="panel perception-settings"><h2>{moteText("中央感知")}</h2><p>{moteText("截图先可靠归档，再独立生成 L1 OCR 与 L2 语义结果。识别失败不影响原图归档，语义失败不阻塞已完成的文字检索。")}</p>{Boolean(error||read.error)&&<p role="alert">{error||errorMessage(read.error)}</p>}{settings&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const v=await api.request<View>('/api/perception',{method:'PUT',body:JSON.stringify(settings)});setSettings(v.settings);setDirty(false);setSaved(true);read.refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>
 <div className="policy-card"><strong>{moteText("本地 OCR 模型：")}{ocr?.state??moteText("读取中")}</strong>{ocr?.state==='ready'&&<p role="status">{ocr.runtimeReady?moteText("OCR Worker 已就绪"):moteText("模型已安装，等待 OCR Worker 启动或安装 Native 运行时")}</p>}{ocr&&ocr.totalBytes>0&&['downloading','verifying','installing'].includes(ocr.state)&&<p role="status">{Math.round(100*ocr.bytes/ocr.totalBytes)}% · {ocr.source}</p>}{ocr?.error&&<p role="alert">{ocr.error}</p>}{ocr?.state!=='ready'&&<button type="button" className="button" disabled={busy||['downloading','verifying','installing'].includes(ocr?.state??'')} onClick={async()=>{setBusy(true);try{await api.request('/api/media-models/ocr/install',{method:'POST',body:JSON.stringify({source:'auto'})});models.refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>{moteText("下载并安装 OCR 模型")}</button>}<p>{moteText("新截图先归档，模型就绪后自动识别；升级前的旧截图不会自动回扫。模型下载不上传截图。")}</p></div>
 <label><input type="checkbox" checked={settings.enabled} onChange={e=>change('enabled',e.target.checked)}/>{moteText("启用中央截图处理")}</label>
 <details><summary>{moteText("高级 OCR 服务配置")}</summary><label>{moteText("处理模型／配置版本")}<input value={settings.providerRevision} maxLength={128} required onChange={e=>change('providerRevision',e.target.value)}/></label><label>{moteText("OCR Worker 地址")}<input type="url" value={settings.ocrEndpoint} onChange={e=>change('ocrEndpoint',e.target.value)}/></label><p>{moteText("默认由中央管理本地 Worker；改为远程地址会把已归档截图发送给该服务。")}</p></details>
 <label>{moteText("语义理解 Worker 地址")}<input type="url" value={settings.semanticEndpoint} onChange={e=>change('semanticEndpoint',e.target.value)}/></label>
 <label>{moteText("语义理解时机")}<select value={settings.semanticMode} onChange={e=>change('semanticMode',e.target.value as Settings['semanticMode'])}><option value="manual">{moteText("手动处理（默认）")}</option><option value="realtime">{moteText("实时后台处理")}</option><option value="batch">{moteText("分批处理")}</option></select></label>
 <label>{moteText("分批等待（分钟）")}<input type="number" min="1" max="1440" value={settings.batchMinutes} onChange={e=>change('batchMinutes',e.target.valueAsNumber)}/></label>
 <label>{moteText("每轮最多处理数")}<input type="number" min="1" max="100" value={settings.batchSize} onChange={e=>change('batchSize',e.target.valueAsNumber)}/></label>
 <label><input type="checkbox" checked={settings.allowExternalProcessing} onChange={e=>change('allowExternalProcessing',e.target.checked)}/>{moteText("允许将截图发往上述非本机 Worker（默认关闭）")}</label>
 <label><input type="checkbox" checked={settings.allowQueryImages} onChange={e=>change('allowQueryImages',e.target.checked)}/>{moteText("允许查询模型按需读取已发现记录的原图（可能发往所选模型服务）")}</label><p>{moteText("查询先读取 OCR／语义派生结果。只有模型显式调用读图工具才披露图片；不自动附加图像。截图中的文字始终作为不可信证据。")}</p>
 <button className="button primary" disabled={busy} type="submit">{busy?moteText("保存中…"):moteText("保存中央感知设置")}</button>{saved&&<span role="status">{moteText("已保存")}</span>}
 </form>}<ul>{view?.jobs.map(j=><li key={j.kind+j.state+j.autoEligible}>{j.kind==='ocr'?'OCR':moteText("语义理解")} · {j.autoEligible?j.state:moteText("历史未安排")} · {j.count}</li>)}</ul><div className="policy-card"><h3>{moteText("历史截图补识别")}</h3><p>{moteText("升级前的截图不会自动识别。先预览数量，再手动安排；每次最多 100 张。")}</p><button type="button" className="button" disabled={busy} onClick={async()=>{setBusy(true);try{setHistorical(await api.request('/api/perception/ocr/historical-preview',{method:'POST',body:'{}'}));}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>{moteText("预览待补识别截图")}</button>{historical&&<p role="status">{moteText("本批 {0} 张{1}",historical.count,historical.bounded?moteText("；还有更多可在本批完成后预览"):"")}{historical.count>0&&<button type="button" className="button" disabled={busy} onClick={async()=>{setBusy(true);try{await api.request('/api/perception/ocr/historical-process',{method:'POST',body:JSON.stringify({token:historical.token})});setHistorical(null);read.refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>{moteText("确认安排本批 OCR")}</button>}</p>}</div><h3>{moteText("最近处理任务")}</h3><button className="button" type="button" disabled={busy} onClick={read.refresh}>{moteText("刷新")}</button>{view?.recent.map(j=><div className="perception-task" key={j.id+j.kind}><code>{j.id}</code> · {j.kind} · {j.autoEligible?j.state:moteText("历史未安排")} {j.error&&`· ${failureMessage(j.error)}`} <button type="button" disabled={busy||j.state==='running'} onClick={async()=>{setBusy(true);try{await api.request(`/api/perception/${j.id}/retry`,{method:'POST',body:JSON.stringify({kind:j.kind})});read.refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>{j.state==='succeeded'?moteText("重新处理"):moteText("立即处理／重试")}</button></div>)}</section>;
}
