import {useEffect,useState} from 'react';
import {moteText} from '@mote/shared/i18n';
import {type Api,errorMessage,ApiError} from './api';
import {AnswerMarkdown} from './AnswerMarkdown';
type ReadItem={id:string;ref:string;title?:string;kind:string;text:string;status?:string;applicability?:string;textRange:{offset:number;total:number;nextOffset:number|null};evidenceRefs?:string[];evidenceCount?:number;evidenceRefsTruncated?:boolean;expansion?:{kind:'search';scope:Record<string,string>;refs:string[]}};
type Card={ref:string;title:string;snippet?:string};
/** Non-capture references keep their type and pinned revision through every read. */
export function ReferenceDetail({api,reference,onOpen}:{api:Api;reference:string;onOpen:(id:string)=>void}){
 const [item,setItem]=useState<ReadItem>(),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(true),[revision,setRevision]=useState(0),[offset,setOffset]=useState(0);
 const [members,setMembers]=useState<Card[]>([]),[cursor,setCursor]=useState<string|null>(null),[nextCursor,setNextCursor]=useState<string|null>(null),[loadingMembers,setLoadingMembers]=useState(false);
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');
  void api.request<{items:ReadItem[];missingRefs:string[]}>('/api/context/read',{method:'POST',body:JSON.stringify({refs:[reference],offset,length:4000}),signal:controller.signal}).then(page=>{if(controller.signal.aborted)return;const next=page.items[0];if(!next){setItem(undefined);setText('');setError(moteText('资料不存在或已删除。'));return;}setItem(next);setText(previous=>previous.slice(0,offset)+next.text);}).catch(e=>{if(!controller.signal.aborted){if(e instanceof ApiError&&[401,403,404,410].includes(e.status)){setItem(undefined);setText('');setMembers([]);}setError(errorMessage(e));}}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();
 },[api,reference,offset,revision]);
 useEffect(()=>{if(!item?.expansion)return;const controller=new AbortController();setLoadingMembers(true);
  void api.request<{items:Card[];nextCursor:string|null}>('/api/context/search?'+new URLSearchParams({...item.expansion.scope,limit:'30',...(cursor?{cursor}:{})}),{signal:controller.signal}).then(page=>{if(!controller.signal.aborted){setMembers(page.items);setNextCursor(page.nextCursor);}}).catch(e=>{if(!controller.signal.aborted){if(e instanceof ApiError&&[401,403,404,410].includes(e.status)){setItem(undefined);setText('');setMembers([]);}setError(errorMessage(e));}}).finally(()=>{if(!controller.signal.aborted)setLoadingMembers(false);});return()=>controller.abort();
 },[api,item?.expansion,cursor]);
 return <div className="panel-pad reference-detail">{error&&<p className="error-banner" role="alert">{error} <button className="button" onClick={()=>setRevision(v=>v+1)}>{moteText('重新读取')}</button></p>}{busy&&<p role="status">{moteText('正在读取…')}</p>}{item&&<><h3>{item.title||moteText(item.kind==='memory'?'记忆':'上下文证据')}</h3>{item.status&&<p>{({proposed:moteText('待确认'),published:moteText('已确认'),stale:moteText('需要重验')} as Record<string,string>)[item.status]??item.status}</p>}{item.applicability&&<p>{item.applicability}</p>}{text&&<AnswerMarkdown answer={{answer:text,trace:[],runId:reference,citations:[]}} onOpen={onOpen}/>}<code className="record-id">{reference}</code>{item.textRange.nextOffset!==null&&<button className="button" disabled={busy} onClick={()=>setOffset(item.textRange.nextOffset!)}>{moteText('继续展开')}</button>}{item.evidenceRefs?.length? <section><h4>{moteText('原始证据')}</h4>{item.evidenceRefs.map(ref=><button className="button" key={ref} onClick={()=>onOpen(ref)}>{moteText('查看原始记录')} · {ref.slice(-8)}</button>)}{item.evidenceRefsTruncated&&<p>{moteText('部分证据未展示')} · {item.evidenceCount}</p>}</section>:null}{item.expansion&&<section><h4>{moteText('来源资料')}</h4>{loadingMembers&&<p role="status">{moteText('正在读取…')}</p>}{members.map(member=><button key={member.ref} className="source-item" onClick={()=>onOpen(member.ref)}><strong>{member.title}</strong><p>{member.snippet}</p></button>)}{cursor&&<button className="button" disabled={loadingMembers} onClick={()=>setCursor(null)}>{moteText('返回第一页')}</button>}{nextCursor&&<button className="button" disabled={loadingMembers} onClick={()=>setCursor(nextCursor)}>{moteText('下一页')}</button>}</section>}</>}</div>;
}
