import {useEffect,useState} from 'react';
import {RefreshCw,FolderInput,Layers3,Plus,X} from 'lucide-react';
import type {SourceConnection,SourceItemRecord} from '@mote/shared';
import {type Api,errorMessage,dateTime} from './api';
import {sourceMetadataSchema} from '@mote/shared';
import {Metadata} from './Metadata';
const layerNames:Record<string,string>={reference:'引用 / Shadow',snapshot:'内容快照',original:'原始文本',derived:'派生记录'};
const kindNames:Record<string,string>={'local-files':'客户端文件','local-calendar':'本地日历','google-calendar':'Google Calendar',mcp:'MCP 来源',upload:'文件导入',custom:'自定义来源'};
export function Sources({api,onOpen,onImport}:{api:Api;onOpen:(id:string)=>void;onImport:()=>void}){
 const [sources,setSources]=useState<SourceConnection[]>([]),[items,setItems]=useState<SourceItemRecord[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState<SourceItemRecord[]|null>(null),[cursor,setCursor]=useState<string|null>(null);
 const [adding,setAdding]=useState(false),[addKind,setAddKind]=useState<'files'|'reference'|'connectors'>('files');
 const [catalog,setCatalog]=useState<Record<string,unknown>|null>(null);
 async function refresh(source=selected){setError('');try{const [s,p]=await Promise.all([api.request<{items:SourceConnection[]}>('/api/sources'),api.request<{items:SourceItemRecord[];nextCursor:string|null}>('/api/source-items?limit=30'+(source?'&sourceId='+encodeURIComponent(source):''))]);setSources(s.items);setItems(p.items);setCursor(p.nextCursor);}catch(e){setError(errorMessage(e));}}
 useEffect(()=>{void refresh();void api.request<Record<string,unknown>>('/api/connectors/status').then(setCatalog).catch(()=>{});},[api]);
 async function run(task:()=>Promise<void>){setBusy(true);setError('');try{await task();await refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <section className="sources-page"><div className="page-heading split-heading"><div><div className="eyebrow">只连接你选择的内容</div><h1>来源</h1><p>连接文件与日历，管理保存方式和同步版本。</p></div><div className="source-heading-actions"><button className="button subtle" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={15}/>刷新</button><button className="button primary" onClick={()=>setAdding(v=>!v)}>{adding?<X size={16}/>:<Plus size={16}/>} {adding?'收起添加':'添加来源'}</button></div></div>
 {error&&<div className="error-banner" role="alert">{error}</div>}
 <div className="source-explainer"><Layers3 size={20}/><div><strong>保留原文，或只留下引用</strong><p>快照保存当次文字，引用只保存原件位置。资料后续变化会成为新版本，方便查看来处。</p></div></div>
 <section hidden={!adding} className="panel add-source-panel"><nav className="segmented-nav" aria-label="添加来源方式">{([['files','导入文件'],['reference','添加引用'],['connectors','连接服务']] as const).map(([id,label])=><button key={id} className={addKind===id?'active':''} onClick={()=>setAddKind(id)}>{label}</button>)}</nav><div hidden={addKind!=='files'}>
 <div className="source-toolbar"><button className="button" onClick={onImport}><FolderInput size={16}/>打开导入</button><span className="muted">提交文件、ZIP 或服务器目录，先查看解析预览，再确认写入。导入后的资料会显示在来源列表中。</span></div>
 </div><div hidden={addKind!=='reference'}><ReferenceEntry api={api} refresh={()=>refresh()}/></div>
 <div hidden={addKind!=='connectors'}><ConnectorPanel api={api} catalog={catalog} refresh={()=>refresh()} /></div></section>
 <div className="source-grid"><aside aria-label="筛选来源"><h2 className="source-list-title">已连接来源 <span>{sources.length}</span></h2><button className={!selected?'button active':'button'} onClick={()=>{setSelected('');void refresh('');}}>所有来源</button>{sources.map(s=><article key={s.id}><button className={selected===s.id?"source-select active":"source-select"} onClick={()=>{setSelected(s.id);setHistory(null);void refresh(s.id);}}><strong>{s.name}</strong><small>{kindNames[s.kind]} · {s.enabled?'已启用':'已暂停'}</small></button><small>{({idle:'等待下次同步',syncing:'同步中',error:'需要处理',permission_required:'需要重新授权'} as Record<string,string>)[s.status?.state??'']??'等待同步'}{s.status?.lastSyncAt?' · '+dateTime(s.status.lastSyncAt):''}</small><button className="button" disabled={busy} onClick={()=>void run(async()=>{await api.request('/api/sources/'+encodeURIComponent(s.id),{method:'PATCH',body:JSON.stringify({enabled:!s.enabled})});})}>{s.enabled?'暂停接入':'恢复接入'}</button></article>)}</aside>
 <div>{items.length===0?<p className="muted">还没有资料。连接来源或导入文件后，它们会出现在这里。</p>:items.map(item=><article className="source-item" key={item.captureId}><div><strong>{item.title||'未命名记录'}</strong><span className="badge">{layerNames[item.layer]}</span></div><p className="muted">采集于 {dateTime(item.observedAt)} · {item.current?'当前版本':'历史版本'}</p>{item.calendar&&<p>日历安排：{dateTime(item.calendar.start)} — {dateTime(item.calendar.end)}{item.calendar.allDay?'（全天）':''} · {item.calendar.status==='cancelled'?'已取消':'计划'}，不代表实际参加。</p>}<p>{item.layer==='reference'?'原文仍在外部来源，此处没有收集正文。':item.text.slice(0,300)}</p>{item.uri&&<details><summary>原件位置</summary><code>{item.uri}</code><p className="muted">这里只展示定位信息，不会自动读取远程地址。</p></details>}<Metadata source={item.metadata} modifiedAt={item.modifiedAt}/><div className="source-toolbar"><button className="button" onClick={()=>onOpen(item.captureId)}>展开证据</button><button className="button" onClick={()=>void api.request<{items:SourceItemRecord[]}>('/api/sources/'+encodeURIComponent(item.sourceId)+'/history?externalId='+encodeURIComponent(item.externalId)).then(v=>setHistory(v.items)).catch(e=>setError(errorMessage(e)))}>查看版本</button></div></article>)}{cursor&&<button className="button" onClick={()=>void api.request<{items:SourceItemRecord[];nextCursor:string|null}>('/api/source-items?limit=30&cursor='+cursor+(selected?'&sourceId='+encodeURIComponent(selected):'')).then(p=>{setItems(v=>[...v,...p.items]);setCursor(p.nextCursor);}).catch(e=>setError(errorMessage(e)))}>更多资料</button>}</div></div>
 {history&&<div className="source-history"><h3>版本记录</h3><button className="button" onClick={()=>setHistory(null)}>关闭</button>{history.map(h=><p key={h.captureId}><button className="button" onClick={()=>onOpen(h.captureId)}>{dateTime(h.observedAt)} · {h.deleted?'来源报告已移除':h.current?'当前版本':'历史快照'}</button></p>)}</div>}
 </section>;
}
function ConnectorPanel({api,catalog,refresh}:{api:Api;catalog:Record<string,unknown>|null;refresh:()=>Promise<void>}){
 const [status,setStatus]=useState<any>(catalog),[calendars,setCalendars]=useState<{id:string;summary:string;selected:boolean}[]>([]),[chosen,setChosen]=useState<string[]>([]),[auth,setAuth]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[url,setUrl]=useState(''),[token,setToken]=useState(''),[name,setName]=useState('MCP 导入资料'),[remote,setRemote]=useState<{uri:string;name:string}[]>([]),[uris,setUris]=useState<string[]>([]),[message,setMessage]=useState('');
 async function load(){const s=await api.request<any>('/api/connectors/status');setStatus(s);if(s.google?.connected){const c=await api.request<{calendars:typeof calendars}>('/api/connectors/google/calendars');setCalendars(c.calendars);setChosen(c.calendars.filter(v=>v.selected).map(v=>v.id));}}
 useEffect(()=>{void load().catch(()=>{});},[api]);
 async function action(f:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await f();await refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <div className="source-connectors">
 <details className="source-item"><summary>连接 Google Calendar</summary><p>由中央节点定时同步你选定的日历，只申请读取权限。取消连接会移除本机授权，历史资料仍保留。</p>{error&&<p role="alert" className="error-banner">{error}</p>}
 {!status?.google?.configured?<p className="muted">请先在设置 → 来源与外部应用中准备 Google OAuth 客户端与回调地址，然后重启节点。</p>:<><p>{status.google.connected?'账户已连接':'尚未授权'} · {({idle:'等待下次同步',syncing:'同步中',error:'同步需要处理',permission_required:'需要重新授权'} as Record<string,string>)[status.google.state]??''}</p><div className="source-toolbar"><button className="button" disabled={busy} onClick={()=>void action(async()=>{const r=await api.request<{authorizationUrl:string}>('/api/connectors/google/start',{method:'POST',body:'{}'});const u=new URL(r.authorizationUrl);if(u.protocol!=='https:'||u.hostname!=='accounts.google.com')throw Error('授权地址不符合预期。');setAuth(u.href);})}>开始授权</button><button className="button" disabled={busy} onClick={()=>void action(load)}>刷新授权状态</button>{status.google.connected&&<><button className="button" disabled={busy} onClick={()=>void action(async()=>{const r=await api.request<{imported:number;duplicates:number}>('/api/connectors/google/sync',{method:'POST',body:'{}'});setMessage(`已同步 ${r.imported} 条新版本，${r.duplicates} 条已存在。`);await load();})}>立即同步</button><button className="button" disabled={busy} onClick={()=>void action(async()=>{await api.request('/api/connectors/google',{method:'DELETE'});await load();setCalendars([]);})}>断开账户</button></>}</div>{auth&&<p><a href={auth} target="_blank" rel="noreferrer noopener">在系统浏览器打开 Google 授权页面</a>，完成后返回此处刷新。</p>}{calendars.length>0&&<fieldset><legend>选择允许读取的日历</legend>{calendars.map(c=><label key={c.id} className="source-toolbar"><input type="checkbox" checked={chosen.includes(c.id)} onChange={e=>setChosen(v=>e.target.checked?[...v,c.id]:v.filter(id=>id!==c.id))}/>{c.summary}</label>)}<button className="button" disabled={busy} onClick={()=>void action(async()=>{await api.request('/api/connectors/google/calendars',{method:'PUT',body:JSON.stringify({calendarIds:chosen})});await load();})}>保存选择</button></fieldset>}</>}{message&&<p>{message}</p>}
 </details>
 <details className="source-item"><summary>其他 Chatbot 与 MCP</summary><p>支持自定义 Bearer 令牌的 Chatbot 可连接本节点的 <code>/mcp</code> 地址。只读连接可检索资料；写回需单独开启写令牌和允许写入的来源。</p><p className="muted">状态：{status?.mcp?.enabled?'MCP 已启用':'MCP 尚未启用'}；{status?.mcp?.writeEnabled?'已开放指定来源写回':'写回已关闭'}。配置入口在“设置 → 来源与外部应用”。仅支持 OAuth 的 Chatbot 不能直接使用 Bearer 接入。</p>
 <h3>从 MCP 服务导入可见资料</h3><p className="muted">选择资源后执行一次导入；不会迁移其他 Chatbot 的隐藏记忆，不会自动调用外部写入工具。</p>
 <label>服务地址<input aria-label="MCP 服务地址" type="url" value={url} placeholder="https://example.com/mcp" onChange={e=>{setUrl(e.target.value);setRemote([]);setUris([]);}}/></label><label>来源名称<input aria-label="MCP 来源名称" value={name} onChange={e=>setName(e.target.value)}/></label><label>远端 Bearer 令牌（如需）<input aria-label="远端 MCP 令牌" type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label>
 <button className="button" disabled={busy||!url.trim()} onClick={()=>void action(async()=>{const r=await api.request<{resources:typeof remote}>('/api/connectors/mcp/discover',{method:'POST',body:JSON.stringify({url,token:token||undefined})});setRemote(r.resources);setUris([]);if(!r.resources.length)setMessage('这个服务没有列出可直接读取的资源。可通过支持的 Chatbot 显式写回资料。');})}>列出可读取资源</button>
 {remote.map(r=><label className="source-toolbar" key={r.uri}><input type="checkbox" checked={uris.includes(r.uri)} onChange={e=>setUris(v=>e.target.checked?[...v,r.uri]:v.filter(u=>u!==r.uri))}/>{r.name}</label>)}{uris.length>0&&<button className="button primary" disabled={busy||!name.trim()} onClick={()=>void action(async()=>{const sourceId='mcp-'+crypto.randomUUID();await api.request('/api/sources',{method:'POST',body:JSON.stringify({id:sourceId,name,kind:'mcp',deviceId:'mcp-import',platform:'import',retention:'snapshot',enabled:true})});const r=await api.request<{imported:number;duplicates:number}>('/api/connectors/mcp/import',{method:'POST',body:JSON.stringify({sourceId,url,token:token||undefined,resourceUris:uris})});setToken('');setMessage(`导入完成：${r.imported} 条新资料，${r.duplicates} 条已存在。`);})}>导入选定资源</button>}{error&&<p role="alert" className="error-banner">{error}</p>}{message&&<p>{message}</p>}
 </details></div>;
}

function ReferenceEntry({api,refresh}:{api:Api;refresh:()=>Promise<void>}){
 const [title,setTitle]=useState(''),[uri,setUri]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <details open className="source-item"><summary>添加 NAS 或外部文件引用</summary><p className="muted">保存原件位置、标题和观察时间，不读取正文。需要分析内容时，可在能访问原件的客户端选择该文件或目录以保存快照。</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const sourceId='manual-references';await api.request('/api/sources',{method:'POST',body:JSON.stringify({id:sourceId,name:'外部文件引用',kind:'custom',deviceId:'web-reference',platform:'import',retention:'reference',enabled:true})});const hash=await itemRevision(api,sourceId,uri,{title,text:'',uri,kind:'file',layer:'reference',deleted:false});await api.request('/api/sources/'+sourceId+'/items',{method:'PUT',body:JSON.stringify({externalId:uri,revision:hash,observedAt:new Date().toISOString(),title,uri,text:'',kind:'file',layer:'reference'})});setTitle('');setUri('');await refresh();}catch(err){setError(errorMessage(err));}finally{setBusy(false);}}}><label>文件标题<input aria-label="引用文件标题" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={2000}/></label><label>原件位置<input aria-label="原件位置" value={uri} onChange={e=>setUri(e.target.value)} placeholder="nas://home/documents/notes.pdf" required maxLength={1000}/></label><button className="button" disabled={busy}>保存引用</button>{error&&<p className="error-banner" role="alert">{error}</p>}</form></details>;
}

async function itemRevision(api:Api,sourceId:string,externalId:string,item:Record<string,unknown>){
 const {item:prior}=await api.request<{item:SourceItemRecord|null}>('/api/sources/'+encodeURIComponent(sourceId)+'/item?externalId='+encodeURIComponent(externalId));
 const fields=['title','text','kind','layer','mimeType','modifiedAt','uri','deleted'];
 const sameMetadata=JSON.stringify(sourceMetadataSchema.optional().parse(prior?.metadata))===JSON.stringify(sourceMetadataSchema.optional().parse(item.metadata));
 return prior&&sameMetadata&&fields.every(key=>(prior as unknown as Record<string,unknown>)[key]===item[key])?prior.revision:crypto.randomUUID();
}
