import {useEffect,useState,useRef} from 'react';
import {moteText} from '@mote/shared/i18n';
import {type Api,errorMessage,dateTime} from './api';
type Todo={id:string;version:number;title:string;dueAt:string|null;status:'open'|'completed'|'cancelled';evidenceIds:string[]};
export function Todos({api,onOpen}:{api:Api;onOpen:(id:string)=>void}){
 const operation=useRef<{key:string;id:string}|undefined>(undefined);
 const [items,setItems]=useState<Todo[]>([]),[title,setTitle]=useState(''),[due,setDue]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[filter,setFilter]=useState('open'),[cursor,setCursor]=useState<string>(),[next,setNext]=useState<string|null>(null);
 useEffect(()=>{const c=new AbortController();void api.request<{items:Todo[];nextCursor:string|null}>('/api/todos?'+new URLSearchParams({status:filter,...cursor?{cursor}:{}}),{signal:c.signal}).then(p=>{if(!c.signal.aborted){setItems(p.items);setNext(p.nextCursor);}}).catch(e=>{if(!c.signal.aborted)setError(errorMessage(e));});return()=>c.abort();},[api,revision,filter,cursor]);
 async function run(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();setRevision(v=>v+1);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <section className="panel" aria-label={moteText('待办')}><h2>{moteText('待办')}</h2><p>{moteText('待办可以没有截止时间；完成待办不会创建日历事件。')}</p>{error&&<p role="alert">{error}</p>}
 <form className="source-toolbar" onSubmit={e=>{e.preventDefault();void run(async()=>{await api.request('/api/todos',{method:'POST',body:JSON.stringify({id:(operation.current?.key===JSON.stringify([title,due])?operation.current:operation.current={key:JSON.stringify([title,due]),id:crypto.randomUUID()}).id,title,dueAt:due?new Date(due).toISOString():null})});operation.current=undefined;setTitle('');setDue('');setCursor(undefined);});}}><label>{moteText('待办标题')}<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{moteText('截止时间（选填）')}<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label><button className="button" disabled={busy}>{moteText('添加待办')}</button></form>
 <nav className="section-tabs">{(['open','completed','cancelled'] as const).map((state,i)=><button key={state} aria-current={state===filter?'page':undefined} onClick={()=>{setFilter(state);setCursor(undefined);}}>{moteText(['未完成','已完成','已取消'][i])}</button>)}</nav>
 {items.map(item=><article className="source-item" key={item.id}><strong>{item.title}</strong><p>{item.dueAt?dateTime(item.dueAt):moteText('无截止时间')}</p>{item.evidenceIds.map(id=><button className="button" key={id} onClick={()=>onOpen(id)}>{moteText('展开证据')}</button>)}<div className="source-toolbar">{(['open','completed','cancelled'] as const).filter(status=>status!==item.status).map(status=><button className="button" key={status} disabled={busy} onClick={()=>void run(()=>api.request('/api/todos/'+item.id,{method:'PATCH',body:JSON.stringify({version:item.version,status})}))}>{moteText(status==='open'?'重新打开':status==='completed'?'标记完成':'取消待办')}</button>)}</div></article>)}
 <div className="source-toolbar">{cursor&&<button className="button" onClick={()=>setCursor(undefined)}>{moteText('返回')}</button>}{next&&<button className="button" onClick={()=>setCursor(next)}>{moteText('更多')}</button>}</div></section>;
}
