import { moteText, getLocale } from '@mote/shared/i18n';
import {useEffect,useState} from 'react';
import {RefreshCw} from 'lucide-react';
import {usageIdentity,usageLabel,type UsageReceipt,type ModelPrice,type UsageSummary,type UsageFilters,type UsageGroupBy,type UsageGroup} from '@mote/shared';
import type {ModelSettingsView} from '@mote/shared/models';
import {dateTime,errorMessage,type Api} from './api';
const number=(n:number)=>n.toLocaleString(getLocale());
const money=(n:number|null,currency:string)=>n===null?moteText("{0} 未估算", currency):new Intl.NumberFormat(getLocale(),{style:'currency',currency,minimumFractionDigits:2,maximumFractionDigits:6}).format(n);
export function TurnUsage({usage}:{usage?:UsageReceipt}) {
  if(!usage)return <p className="fine-print">{moteText("此历史回答未记录用量。")}</p>;
  const identity=usageIdentity(usage);
  const t=usage.tokens,complete=t&&t.requests>0&&t.reportedRequests===t.requests;
  return <details className="turn-usage"><summary>{t?`${number(t.totalTokens)} tokens${complete?'':moteText("（已知部分）")}`:moteText("用量未上报")} · {money(usage.estimatedCost,usage.currency)} · {(usage.durationMs/1000).toFixed(1)}{' '}{moteText("秒")}</summary>
    <p className="fine-print">{usageLabel('agent',identity.agentId)} · {usageLabel('module',identity.moduleId)} · {usageLabel('skill',identity.skillId)}</p>
    <div className="usage-facts"><span>{moteText("模型")}{' '}<strong>{usage.model||moteText("未知")}</strong></span><span>{moteText("输入")}{' '}<strong>{t?number(t.inputTokens):'—'}</strong></span><span>{moteText("输出")}{' '}<strong>{t?number(t.outputTokens):'—'}</strong></span><span>{moteText("缓存读取")}{' '}<strong>{t?.cacheReadTokens===undefined?moteText("未上报"):number(t.cacheReadTokens)}</strong></span><span>{moteText("缓存命中率")}{' '}<strong>{t?.inputTokens&&t.cacheReadTokens!==undefined?`${(100*t.cacheReadTokens/t.inputTokens).toFixed(1)}%`:'—'}</strong></span><span>{moteText("缓存写入")}{' '}<strong>{t?.cacheWriteTokens===undefined?moteText("未上报"):number(t.cacheWriteTokens)}</strong></span><span>{moteText("推理 token（已含在输出）")}{' '}<strong>{t?.reasoningTokens===undefined?moteText("未上报"):number(t.reasoningTokens)}</strong></span><span>{moteText("模型请求")}{' '}<strong>{t?moteText("{0} / {1} 次已计量", t.reportedRequests, t.requests):moteText("未上报")}</strong></span></div>
    <p className="fine-print">{moteText("费用按请求开始时的价格估算，实际账单以服务商为准；未估算表示缺少用量或价格。")}</p>
  </details>;
}
const percent=(n:number|null)=>n===null?'—':`${(n*100).toFixed(1)}%`;
const seconds=(n:number|null)=>n===null?'—':moteText("{0} 秒", (n/1000).toFixed(1));
const dimensions:Record<UsageGroupBy,string>={agent:'Agent',module:moteText("模块"),skill:'Skill',model:moteText("模型"),provider:'Provider'};
export function UsageGroups({groups,totalTokens,onSelect}:{groups:UsageGroup[];totalTokens:number;onSelect:(filter:UsageFilters)=>void}) {
  return <div className="usage-table-scroll"><table className="usage-table usage-groups"><caption>{moteText("消耗分布 · 按 token 排序 · 点击名称筛选")}</caption><thead><tr><th>{moteText("归属")}</th><th>{moteText("运行 / 模型请求")}</th><th>{moteText("Token / 占比")}</th><th>{moteText("缓存命中")}</th><th>{moteText("成功率")}</th><th>{moteText("耗时 均值 / P95")}</th><th>{moteText("已知费用")}</th></tr></thead><tbody>{groups.map(g=><tr key={g.id}>
    <td><button className="text-button" onClick={()=>onSelect(g.filter)}>{g.label}</button><small>{g.filter.model??g.id}</small></td>
    <td>{number(g.runs)} / {number(g.requests)}<small>{g.running}{' '}{moteText("进行中 ·")}{' '}{g.failed}{' '}{moteText("失败")}</small></td>
    <td><strong>{number(g.totalTokens)}</strong> · {percent(totalTokens?g.totalTokens/totalTokens:null)}<div className="usage-bar"><i style={{width:`${totalTokens?100*g.totalTokens/totalTokens:0}%`}}/></div><small>{moteText("输入")}{' '}{number(g.inputTokens)}{' '}{moteText("/ 输出")}{' '}{number(g.outputTokens)}</small>{g.unknownUsage>0&&<small>{g.unknownUsage}{' '}{moteText("次用量不完整")}</small>}</td>
    <td>{percent(g.cacheHitRate)}{g.unknownCache>0&&<small>{g.unknownCache}{' '}{moteText("次未上报")}</small>}</td><td>{percent(g.successRate)}<small>{g.completed}{' '}{moteText("次完成")}</small></td>
    <td>{seconds(g.averageDurationMs)} / {seconds(g.p95DurationMs)}</td>
    <td>{money(g.costs.USD,'USD')}<small>{money(g.costs.CNY,'CNY')}</small>{g.unpriced>0&&<small>{g.unpriced}{' '}{moteText("次未估算")}</small>}</td>
  </tr>)}</tbody></table></div>;
}
const localDate=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export function Usage({api}:{api:Api}) {
  const [from,setFrom]=useState(()=>localDate(new Date(Date.now()-6*86400000))),[to,setTo]=useState(()=>localDate(new Date()));
  const [data,setData]=useState<UsageSummary>(),[error,setError]=useState(''),[loading,setLoading]=useState(false),[reload,setReload]=useState(0),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
  const [price,setPrice]=useState<ModelPrice>({provider:'',model:'',currency:'USD',input:NaN,output:NaN,cacheRead:NaN,cacheWrite:NaN});
  const [groupBy,setGroupBy]=useState<UsageGroupBy>('agent'),[filters,setFilters]=useState<UsageFilters>({});
  const [facets,setFacets]=useState<UsageSummary['facets']>({agentId:[],moduleId:[],skillId:[]});
  const [page,setPage]=useState(1),[pageSize,setPageSize]=useState(20);
  useEffect(()=>setPage(1),[from,to,groupBy,filters,pageSize]);
  const timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone;
  useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setData(undefined);
    void api.request<UsageSummary>(`/api/usage?${new URLSearchParams({from,to,timeZone,groupBy,page:String(page),pageSize:String(pageSize),...filters})}`,{signal:c.signal}).then(v=>{if(!c.signal.aborted){setData(v);setFacets(v.facets);}}).catch(e=>{if(!c.signal.aborted)setError(errorMessage(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();
  },[api,from,to,timeZone,reload,groupBy,filters,page,pageSize]);
  useEffect(()=>{const c=new AbortController();void api.request<ModelSettingsView>('/api/model-settings',{signal:c.signal}).then(v=>{if(!c.signal.aborted)setPrice(p=>({...p,provider:v.settings.provider,model:v.settings.model}));}).catch(()=>{});return()=>c.abort();},[api]);
  function preset(days:number){setFrom(localDate(new Date(Date.now()-(days-1)*86400000)));setTo(localDate(new Date()));}
  async function savePrice(){setSaving(true);setNotice('');try{await api.request('/api/usage/prices',{method:'PUT',body:JSON.stringify(price)});setNotice(moteText("价格已保存，后续请求将按此估算；历史费用保持原值。"));setReload(n=>n+1);}catch(e){setNotice(errorMessage(e));}finally{setSaving(false);}}
  function filter(field:keyof UsageFilters,value:string){setFilters(old=>{const next={...old};if(value)next[field]=value as never;else delete next[field];return next;});}
  return <div className="usage-page"><section className="panel"><div className="section-heading"><div><h2>{moteText("用量与费用")}</h2><p>{moteText("按执行 Agent、功能模块、主 Skill 或模型查看消耗，覆盖问答、洞察、记忆、文件分析和资料导入。")}</p></div><button className="button subtle" disabled={loading} onClick={()=>setReload(n=>n+1)}><RefreshCw size={16}/>{moteText("刷新")}</button></div>
    <div className="usage-filter"><label>{moteText("开始日期")}<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>{moteText("结束日期")}<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label>{[1,7,30].map(n=><button className="button subtle" key={n} onClick={()=>preset(n)}>{n===1?moteText("今天"):moteText("近 {0} 天", n)}</button>)}<small>{timeZone}</small></div>
    <div className="usage-filter usage-dimensions">{([['agentId','agent','Agent'],['moduleId','module',moteText("模块")],['skillId','skill','Skill']] as const).map(([field,dimension,label])=><label key={field}>{label}<select value={filters[field]??''} onChange={e=>filter(field,e.target.value)}><option value="">{moteText("全部")}{label}</option>{filters[field]&&!facets[field].some(v=>v.id===filters[field])&&<option value={filters[field]}>{usageLabel(dimension,filters[field]!)}</option>}{facets[field].map(v=><option value={v.id} key={v.id}>{v.label}</option>)}</select></label>)}
      <label>{moteText("运行状态")}<select value={filters.status??''} onChange={e=>filter('status',e.target.value)}><option value="">{moteText("全部状态")}</option><option value="completed">{moteText("已完成")}</option><option value="failed">{' '}{moteText("失败")}</option><option value="running">{moteText("进行中")}</option></select></label>
      {Object.keys(filters).length>0&&<button className="button subtle" onClick={()=>setFilters({})}>{moteText("清除筛选")}</button>}
    </div>
    {(filters.provider!==undefined||filters.model!==undefined)&&<p className="fine-print">{moteText("模型筛选：")}{filters.provider} · {filters.model}<button className="text-button" onClick={()=>setFilters(({provider,model,...rest})=>rest)}>{moteText("移除")}</button></p>}
    <div className="usage-tabs" role="group" aria-label={moteText("聚合维度")}>{(Object.keys(dimensions) as UsageGroupBy[]).map(key=><button key={key} className={`button ${groupBy===key?'primary':'subtle'}`} aria-pressed={groupBy===key} onClick={()=>setGroupBy(key)}>{moteText("按")}{' '}{dimensions[key]}</button>)}</div>
    {loading&&<p role="status">{moteText("正在读取用量…")}</p>}{error&&<p className="notice error" role="alert">{error}</p>}
    {data&&<><div className="usage-metrics"><div><span>{moteText("已上报 token")}</span><strong>{number(data.total.totalTokens)}</strong><small>{moteText("输入")}{' '}{number(data.total.inputTokens)}{' '}{moteText("· 输出")}{' '}{number(data.total.outputTokens)}</small></div><div><span>{moteText("缓存命中率")}{' '}</span><strong>{data.total.cacheHitRate===null?'—':`${(data.total.cacheHitRate*100).toFixed(1)}%`}</strong><small>{moteText("读取")}{' '}{number(data.total.cacheReadTokens)} tokens</small></div><div><span>{moteText("已知费用估算")}</span><strong>{money(data.total.costs.USD,'USD')}</strong><small>{money(data.total.costs.CNY,'CNY')}{' '}{moteText("· 不混合币种")}</small></div><div><span>{moteText("运行次数")}</span><strong>{number(data.total.runs)}</strong><small>{data.total.requests}{' '}{moteText("次模型请求 ·")}{' '}{data.total.running}{' '}{moteText("进行中 ·")}{' '}{data.total.failed}{' '}{moteText("失败")}</small></div></div>
      <p className="fine-print">{data.total.unknownUsage}{' '}{moteText("次用量缺失或不完整 ·")}{' '}{data.total.unknownCache}{' '}{moteText("次未提供缓存数据 ·")}{' '}{data.total.unpriced}{' '}{moteText("次费用未估算。缓存率按已上报缓存数据的输入 token 加权；未知部分不按零计算。")}</p>
      <div className="usage-quality"><span>{moteText("运行成功率")}{' '}<strong>{percent(data.total.successRate)}</strong></span><span>{moteText("平均耗时")}{' '}<strong>{seconds(data.total.averageDurationMs)}</strong></span><span>{moteText("P95 耗时")}{' '}<strong>{seconds(data.total.p95DurationMs)}</strong></span><span>{moteText("已计量模型请求")}{' '}<strong>{data.total.reportedRequests} / {data.total.requests}</strong></span></div>
      <p className="fine-print">{moteText("成功率与耗时仅统计已结束运行；失败运行的已上报消耗仍计入。Skill 指运行入口指定的主流程，每笔消耗只归属一次，不拆分动态调用的子 Skill。")}</p>
      <div className="usage-trend" role="group" aria-label={moteText("每日趋势")}>{[...data.days].reverse().map(d=><button key={d.date} title={`${d.date}: ${number(d.totalTokens)} tokens / ${d.runs}`} onClick={()=>{setFrom(d.date);setTo(d.date);}}><i style={{height:`${Math.max(2,100*d.totalTokens/Math.max(...data.days.map(v=>v.totalTokens),1))}%`}}/><small>{d.date.slice(5)}</small></button>)}</div>
      {data.groups.length>0&&<UsageGroups groups={data.groups} totalTokens={data.total.totalTokens} onSelect={selected=>{setFilters(old=>({...old,...selected}));if(groupBy==='provider')setGroupBy('model');}}/>}
      {!data.days.length?<p className="notice">{moteText("当前日期和筛选条件下没有用量记录。功能启用前的历史对话无法补算。")}</p>:<div className="usage-table-scroll"><table className="usage-table"><caption>{moteText("每日用量 · 点击日期查看当天")}</caption><thead><tr><th>{moteText("日期")}</th><th>{moteText("运行")}</th><th>{moteText("输入 / 输出")}</th><th>{moteText("缓存命中")}</th><th>{moteText("已知费用")}</th></tr></thead><tbody>{data.days.map(d=><tr key={d.date}><td><button className="text-button" onClick={()=>{setFrom(d.date);setTo(d.date);}}>{d.date}</button><div className="usage-bar"><i style={{width:`${Math.max(2,100*d.totalTokens/Math.max(...data.days.map(v=>v.totalTokens),1))}%`}}/></div></td><td>{d.runs}</td><td>{number(d.inputTokens)} / {number(d.outputTokens)}</td><td>{d.cacheHitRate===null?'—':`${(100*d.cacheHitRate).toFixed(1)}%`}</td><td>{money(d.costs.USD,'USD')} / {money(d.costs.CNY,'CNY')}{d.unpriced>0&&<small> · {d.unpriced}{' '}{moteText("次未估算")}</small>}</td></tr>)}</tbody></table></div>}
    </>}
  </section>
  <details className="panel usage-pricing"><summary>{moteText("模型价格与计费设置")}</summary><p className="fine-print">{moteText("填写服务商或你的套餐单价（每百万 tokens）。包括缓存折扣；订阅套餐无法据此推算实际扣费。价格在每次运行开始时固定。")}</p>
    {data?.prices.map(p=><button className="button subtle" key={`${p.provider}/${p.model}`} onClick={()=>setPrice(p)}>{p.provider} · {p.model}</button>)}
    <form onSubmit={e=>{e.preventDefault();void savePrice();}}><fieldset disabled={saving} className="usage-price-fields"><label>{moteText("服务 ID")}<input required value={price.provider} onChange={e=>setPrice(p=>({...p,provider:e.target.value}))}/></label><label>{moteText("模型 ID")}<input required value={price.model} onChange={e=>setPrice(p=>({...p,model:e.target.value}))}/></label><label>{moteText("币种")}<select value={price.currency} onChange={e=>setPrice(p=>({...p,currency:e.target.value as 'USD'|'CNY'}))}><option>USD</option><option>CNY</option></select></label>{(['input','output','cacheRead','cacheWrite'] as const).map(k=><label key={k}>{{input:moteText("未缓存输入"),output:moteText("输出"),cacheRead:moteText("缓存读取"),cacheWrite:moteText("缓存写入")}[k]}<input required type="number" min="0" max="1000000" step="any" value={Number.isFinite(price[k])?price[k]:''} onChange={e=>setPrice(p=>({...p,[k]:e.target.value===''?NaN:Number(e.target.value)}))}/></label>)}<button className="button primary">{saving?moteText("正在保存…"):moteText("保存价格")}</button></fieldset></form>{notice&&<p role="status">{notice}</p>}
  </details>
  {data&&<section className="panel"><h2>{moteText("运行明细")}</h2><p className="fine-print">{moteText("符合筛选的")}{' '}{data.itemsTotal}{' '}{moteText("次运行，显示最近")}{' '}{data.items.length}{' '}{moteText("次；所有统计覆盖全部符合条件的记录。")}</p><nav className="usage-filter" aria-label={moteText("运行明细分页")}><button className="button subtle" disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}>{moteText("上一页")}</button><span>{page} / {Math.max(1,Math.ceil(data.itemsTotal/pageSize))}</span><button className="button subtle" disabled={page*pageSize>=data.itemsTotal||loading} onClick={()=>setPage(p=>p+1)}>{moteText("下一页")}</button><select aria-label={moteText("每页条数")} value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}>{[10,20,50,100].map(n=><option key={n} value={n}>{n}</option>)}</select></nav>{data.items.map(item=><article className="usage-run" key={item.id}><div><strong>{item.model||moteText("未知模型")}</strong><span>{usageLabel('module',usageIdentity(item).moduleId)} · {dateTime(item.createdAt)} · {{completed:moteText("已完成"),running:moteText("进行中"),failed:moteText("失败")}[item.status]}</span></div><TurnUsage usage={item}/></article>)}</section>}
  </div>;
}
