import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createAgent,createImportAgent,AgentProviderError} from '../dist/index.js';import {observeModelTransport} from '../dist/model-transport-observer.js';
const reader={search:async()=>[],timeline:async()=>[],evidence:async()=>[],activity:async()=>({}),devices:async()=>[]};
test('private transport reporter rejects unauthorized or unstructured reports',async()=>{
 const observer=await observeModelTransport();try{const {url,token}=observer.configuration;assert.equal((await fetch(url,{method:'POST',body:'{}'})).status,403);assert.equal((await fetch(url,{method:'POST',headers:{Authorization:'Bearer '+token},body:JSON.stringify({status:429,body:'private text'})})).status,400);
 const failure=assert.rejects(observer.failure,error=>error instanceof AgentProviderError&&error.details.code==='rate_limited'&&error.details.retryAfterMs===9000);assert.equal((await fetch(url,{method:'POST',headers:{Authorization:'Bearer '+token},body:JSON.stringify({status:429,retryAfter:'9'})})).status,200);await failure;}finally{await observer.close();}
});
test('real Harness preserves HTTP recovery facts and does not retry opaque provider failures', {timeout:90000},async()=>{
 let status=401,calls=0;const provider=createServer(async(req,res)=>{for await(const _ of req){}calls++;res.writeHead(status,{'Content-Type':'application/json','Retry-After':'13'}).end(JSON.stringify({error:{message:'generated-private-provider-text'}}));});await new Promise(r=>provider.listen(0,'127.0.0.1',r));
 try{for(const protocol of ['openai-completions','deepseek'])for(const code of [401,429,503]){status=code;const before=calls,agent=createAgent({reader,protocol,model:'fixture',apiKey:'synthetic-key',baseUrl:'http://127.0.0.1:'+provider.address().port,timeoutMs:15000});try{await assert.rejects(agent.query({question:'Generated transport fixture'}),error=>{assert.ok(error instanceof AgentProviderError);assert.equal(error.details.category,code===401?'blocked':'transient');assert.equal(error.details.code,code===401?'provider_authentication':code===429?'rate_limited':'provider_unavailable');if(code!==401)assert.equal(error.details.retryAfterMs,13000);assert.doesNotMatch(String(error),/generated-private-provider-text/);return true;});assert.equal(calls-before,1);}finally{await agent.close();}}
 const workspace=await mkdtemp(join(tmpdir(),'mote-import-transport-'));status=429;const before=calls,agent=createImportAgent({protocol:'openai-completions',model:'fixture',apiKey:'synthetic-key',baseUrl:'http://127.0.0.1:'+provider.address().port});try{await assert.rejects(agent.prepare({workspace,inputPaths:[],helperPath:join(workspace,'helper.py'),instruction:'Generated transport check',manifestSchema:{}}),error=>error instanceof AgentProviderError&&error.details.code==='rate_limited'&&error.details.retryAfterMs===13000);assert.equal(calls-before,1);}finally{await agent.close();await rm(workspace,{recursive:true,force:true});}
 }finally{provider.closeAllConnections();await new Promise(r=>provider.close(r));}
});

test('host admission failures cross query and import adapters without becoming generic SDK errors',async()=>{
 const {ProviderFailure}=await import('@mote/shared'),failure=new ProviderFailure({category:'transient',code:'rate_limited',retryAfterMs:23000});const options={protocol:'openai-completions',model:'fixture',apiKey:'synthetic-key',baseUrl:'http://127.0.0.1:1',runModel:async()=>{throw failure;}};
 const agent=createAgent({...options,reader});try{await assert.rejects(agent.query({question:'Generated admission check'}),error=>error===failure);}finally{await agent.close();}
 const workspace=await mkdtemp(join(tmpdir(),'mote-admission-import-')),importer=createImportAgent(options);try{await assert.rejects(importer.prepare({workspace,inputPaths:[],instruction:'Generated admission check',helperPath:join(workspace,'helper.py'),manifestSchema:{}}),error=>error===failure);}finally{await importer.close();await rm(workspace,{recursive:true,force:true});}
});
