import { contextBridge, ipcRenderer } from 'electron';
import type { DesktopApi, Status } from './contracts';

const api: DesktopApi = {
  ask: (command, input) => ipcRenderer.invoke('mote:ask', command, input),
  storageStatistics: () => ipcRenderer.invoke('mote:storage-statistics'),
  language: () => ipcRenderer.invoke('mote:language'),
  setLanguage: preference => ipcRenderer.invoke('mote:set-language', preference),
  compressionPreview: (quality, maxSide) => ipcRenderer.invoke('mote:compression-preview', quality, maxSide),
  browseCaptures: input => ipcRenderer.invoke('mote:captures-browse', input),
  captureDetail: (location, id) => ipcRenderer.invoke('mote:captures-detail', location, id),
  captureImage: (location, id, thumbnail) => ipcRenderer.invoke('mote:captures-image', location, id, thumbnail),
  installedApplications: () => ipcRenderer.invoke('mote:installed-applications'),
  onNavigate: callback => {
    const handler = (_event: Electron.IpcRendererEvent, page: 'overview' | 'notes' | 'sources' | 'settings') => callback(page);
    ipcRenderer.on('mote:navigate', handler);
    return () => ipcRenderer.removeListener('mote:navigate', handler);
  },
  previewConnection: input => ipcRenderer.invoke('mote:connection-preview', input),
  importConnection: kind => ipcRenderer.invoke('mote:connection-import', kind),
  cancelConnection: () => ipcRenderer.invoke('mote:connection-cancel'),
  confirmConnection: (id, origin, deviceName) => ipcRenderer.invoke('mote:connection-confirm', id, origin, deviceName),
  connectionStatus: () => ipcRenderer.invoke('mote:connection-status'),
  testConnection: () => ipcRenderer.invoke('mote:connection-test'),
  updateStatus: () => ipcRenderer.invoke('mote:update-status'),
  updateChannel: channel => ipcRenderer.invoke('mote:update-channel', channel),
  checkUpdate: () => ipcRenderer.invoke('mote:update-check'),
  downloadUpdate: () => ipcRenderer.invoke('mote:update-download'),
  cancelUpdate: () => ipcRenderer.invoke('mote:update-cancel'),
  installUpdate: () => ipcRenderer.invoke('mote:update-install'),
  revealUpdate: () => ipcRenderer.invoke('mote:update-reveal'),
  releaseNotes: () => ipcRenderer.invoke('mote:update-notes'),
  openFeedback: () => ipcRenderer.invoke('mote:feedback'),
  codingAgents: () => ipcRenderer.invoke('mote:coding-agents'),
  addCodingAgent: (provider, options) => ipcRenderer.invoke('mote:source-coding', provider, options),
  sources: () => ipcRenderer.invoke('mote:sources'),
  chooseSourceFiles: (mode, options) => ipcRenderer.invoke('mote:source-files', mode, options),
  authorizeCalendar: () => ipcRenderer.invoke('mote:calendar-authorize'),
  addCalendarSource: (id, options) => ipcRenderer.invoke('mote:source-calendar', id, options),
  updateSource: (id, options) => ipcRenderer.invoke('mote:source-update', id, options),
  syncSources: () => ipcRenderer.invoke('mote:source-sync'),
  openCalendarPermissions: () => ipcRenderer.invoke('mote:calendar-permissions'),
  exportSupport: hours => ipcRenderer.invoke('mote:support-export', hours),
  sampleDiagnostics: () => ipcRenderer.invoke('mote:diagnostics-sample'),
  exportDiagnostics: () => ipcRenderer.invoke('mote:diagnostics-export'),
  readRawEvents: () => ipcRenderer.invoke('mote:events-raw'),
  readEvents: () => ipcRenderer.invoke('mote:events-read'),
  noteDraft: () => ipcRenderer.invoke('mote:note-draft'),
  updateNoteDraft: input => ipcRenderer.invoke('mote:note-draft-update', input),
  saveNote: input => ipcRenderer.invoke('mote:note', input),
  openCentral: (page?: string) => ipcRenderer.invoke('mote:central',page),
  status: () => ipcRenderer.invoke('mote:get-status'),
  restartForStorageRecovery: () => ipcRenderer.invoke('mote:storage-restart'),
  chooseCaptureDirectory: () => ipcRenderer.invoke('mote:storage-choose'),
  openCaptureDirectory: () => ipcRenderer.invoke('mote:storage-open'),
  configure: update => ipcRenderer.invoke('mote:configure', update),
  start: () => ipcRenderer.invoke('mote:start'),
  stop: () => ipcRenderer.invoke('mote:stop'),
  reviewPending: () => ipcRenderer.invoke('mote:review-pending'),
  rejectReview: id => ipcRenderer.invoke('mote:review-reject',id),
  approveReview: id => ipcRenderer.invoke('mote:review-approve',id),
  retry: () => ipcRenderer.invoke('mote:retry'),
  permissionStatus: () => ipcRenderer.invoke('mote:permission-status'),
  permissionSettings: kind => ipcRenderer.invoke('mote:permission-settings', kind),
  openPermissions: () => ipcRenderer.invoke('mote:permissions'),
  openDataFolder: () => ipcRenderer.invoke('mote:data-folder'),
  exportMetadata: () => ipcRenderer.invoke('mote:export-metadata'),
  exportQueue: () => ipcRenderer.invoke('mote:export-queue'),
  importQueue: () => ipcRenderer.invoke('mote:import-queue'),
  downloadModel: () => ipcRenderer.invoke('mote:model-download'),
  cancelModelDownload: () => ipcRenderer.invoke('mote:model-cancel'),
  importModel: () => ipcRenderer.invoke('mote:model-import'),
  reloadModel: () => ipcRenderer.invoke('mote:model-reload'),
  onStatus: callback => {
    const handler = (_event: Electron.IpcRendererEvent, status: Status) => callback(status);
    ipcRenderer.on('mote:status', handler);
    return () => ipcRenderer.removeListener('mote:status', handler);
  },
};
contextBridge.exposeInMainWorld('mote', api);
