import {register as filesEntry} from './files.js';
import type { ServerFeatureHost } from '../feature-host.js';
import { featureInventory } from '../feature-inventory.js';
import type { FeatureServices } from '../feature-services.js';
import { register as actionsEntry } from './actions.js';
import { register as agentView } from './agent-view.js';
import { register as askEntry } from './ask.js';
import { register as captureEntry } from './capture.js';
import { register as codingEntry } from './coding.js';
import { register as connectionsEntry } from './connections.js';
import { register as contextEntry } from './context.js';
import { register as devicesEntry } from './devices.js';
import { register as diagnosticsEntry } from './diagnostics.js';
import { register as importsEntry } from './imports.js';
import { register as insightsEntry } from './insights.js';
import { register as materialsEntry } from './materials.js';
import { register as mediaEntry } from './media.js';
import { register as memoryEntry } from './memory.js';
import { register as modelsEntry } from './models.js';
import { register as notesEntry } from './notes.js';
import { register as processingEntry } from './processing.js';
import { register as sourcesEntry } from './sources.js';
import { register as storageEntry } from './storage.js';
import { register as systemEntry } from './system.js';
import { register as usageEntry } from './usage.js';
export async function installServerFeatures(host:ServerFeatureHost,services:FeatureServices){
  await host.install({id:'mote.files',version:'1',components:[]},app=>filesEntry(app,services));
  await host.install({id:'mote.actions',version:'1',components:[]},app=>actionsEntry(app,services));
  await host.install({id:'mote.connections',version:'1',components:[]},app=>connectionsEntry(app,services));
  await host.install({id:'mote.system',version:'1',components:[]},app=>systemEntry(app,services));
  await host.install({id:'mote.storage',version:'1',components:[]},app=>storageEntry(app,services));
  await host.install({id:'mote.capture',version:'1',components:[]},app=>captureEntry(app,services));
  await host.install({id:'mote.context',version:'1',components:[]},app=>contextEntry(app,services));
  await host.install({id:'mote.materials',version:'1',components:[]},app=>materialsEntry(app,services));
  await host.install({id:'mote.coding',version:'1',components:[]},app=>codingEntry(app,services));
  await host.install({id:'mote.sources',version:'1',components:[]},app=>sourcesEntry(app,services));
  await host.install({id:'mote.models',version:'1',components:[]},app=>modelsEntry(app,services));
  await host.install({id:'mote.processing',version:'1',components:[]},app=>processingEntry(app,services));
  await host.install({id:'mote.notes',version:'1',components:[]},app=>notesEntry(app,services));
  await host.install({id:'mote.devices',version:'1',components:[]},app=>devicesEntry(app,services));
  await host.install({id:'mote.media',version:'1',components:[]},app=>mediaEntry(app,services));
  await host.install({id:'mote.memory',version:'1',components:[]},app=>memoryEntry(app,services));
  await host.install({id:'mote.imports',version:'1',components:[]},app=>importsEntry(app,services));
  await host.install({id:'mote.ask',version:'1',components:[]},app=>askEntry(app,services));
  await host.install({id:'mote.usage',version:'1',components:[]},app=>usageEntry(app,services));
  await host.install({id:'mote.insights',version:'1',components:[]},app=>insightsEntry(app,services));
  await host.install({id:'mote.diagnostics',version:'1',components:[]},app=>diagnosticsEntry(app,services));
  await host.install({id:'mote.agent-view',version:'1',components:[]},app=>agentView(app,services));
  await host.install({id:'mote.features',version:'1',components:[]},app=>{app.get('/api/features',async()=>featureInventory(host,services));});
}
