// Generated by scripts/generate-design-tokens.mjs.
package dev.mote.collector

object DesignTokens {
    val background = android.graphics.Color.parseColor("#f5f6f8")
    val surface = android.graphics.Color.parseColor("#ffffff")
    val sidebar = android.graphics.Color.parseColor("#f0f2f5")
    val ink = android.graphics.Color.parseColor("#202936")
    val muted = android.graphics.Color.parseColor("#5e6b7d")
    val accent = android.graphics.Color.parseColor("#315ed0")
    val accentHover = android.graphics.Color.parseColor("#2449aa")
    val tint = android.graphics.Color.parseColor("#e8eefc")
    val border = android.graphics.Color.parseColor("#dce1e8")
    val success = android.graphics.Color.parseColor("#28734d")
    val warning = android.graphics.Color.parseColor("#966017")
    val danger = android.graphics.Color.parseColor("#b83c45")
}
