package dev.mote.collector

import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Test
import java.io.File
import java.nio.file.Files
import java.util.UUID

class QueueLocationStoreTest {
    // Generated bytes with reversible transformation: migration must preserve sealed bytes exactly.
    private val cipher = object : ByteCipher {
        override fun seal(bytes: ByteArray) = bytes.map { (it.toInt() xor 0x5a).toByte() }.toByteArray()
        override fun open(bytes: ByteArray) = seal(bytes)
    }
    private fun screen() = JSONObject().put("id", UUID.randomUUID().toString()).put("source", "screen").put("capturedAt", "2026-09-14T00:00:00Z")
        .put("privacy", JSONObject().put("excluded", false)).put("imageMime", "image/jpeg").put("ocrText", "")
        .put("ocr", JSONObject().put("status", "pending").put("reason", "charging"))
    private fun note() = JSONObject().put("id", UUID.randomUUID().toString()).put("source", "note").put("ocrText", "generated fixture")
        .put("capturedAt", "2026-09-14T00:00:01Z").put("privacy", JSONObject().put("excluded", false))
    private class Interrupted : Error()
    private fun fixture(test: (File, File, File) -> Unit) {
        val root = Files.createTempDirectory("mote-storage-fixture").toFile()
        try { test(File(root, "control").apply { mkdirs() }, File(root, "internal/queue").apply { mkdirs() }, File(root, "card").apply { mkdirs() }) }
        finally { root.deleteRecursively() }
    }
    @Test fun migrationPreservesEncryptedQueueAndOcrStateAndRejectsStaleInstances() = fixture { control, legacy, card ->
        val store = QueueLocationStore(control, legacy, cipher); val original = store.current()
        val queue = DurableQueue(legacy, cipher).apply { assertCurrent = { store.assertCurrent(original) } }
        val image = screen(); val note = note(); val id = image.getString("id")
        queue.enqueue(image, byteArrayOf(1, 2, 3), 2000000); queue.acknowledge(id); queue.completeOcr(id, "generated OCR", "completed", 2000000)
        queue.enqueue(note, null, 2000000)
        val old = legacy.listFiles()!!.filter { it.extension in setOf("event", "blob") }.associate { it.name to it.readBytes().toList() }
        val target = store.migrate("card", card)
        assertFalse(legacy.exists()); assertEquals(target, QueueLocationStore(control, legacy, cipher).current())
        val reopened = DurableQueue(File(target.path), cipher)
        reopened.verifyIntegrity(); assertEquals(2, reopened.depth()); assertEquals(id, reopened.nextOcrUpdate()!!.getString("id"))
        assertEquals(note.getString("id"), reopened.peek()!!.getString("id")); assertArrayEquals(byteArrayOf(1, 2, 3), reopened.image(id))
        assertEquals(old, File(target.path).listFiles()!!.filter { it.extension in setOf("event", "blob") }.associate { it.name to it.readBytes().toList() })
        assertThrows(IllegalStateException::class.java) { queue.acknowledgeOcr(id) }
        reopened.acknowledgeOcr(id); assertNull(reopened.image(id))
    }
    @Test fun crashBeforePointerCommitKeepsOriginalAndRemovesOnlyUncommittedCopy() = fixture { control, legacy, card ->
        val store = QueueLocationStore(control, legacy, cipher, checkpoint = { if (it == "verified") throw Interrupted() })
        val original = store.current(); DurableQueue(legacy, cipher).enqueue(screen(), byteArrayOf(3), 2000000)
        assertThrows(Interrupted::class.java) { store.migrate("card", card) }
        assertEquals(original, QueueLocationStore(control, legacy, cipher).current()); assertEquals(1, DurableQueue(legacy, cipher).depth())
        assertTrue(card.listFiles()!!.isEmpty()); assertFalse(File(control, "queue-migration.json").exists())
    }
    @Test fun crashAfterPointerCommitUsesNewDirectoryAndNeverReplaysOldAckedData() = fixture { control, legacy, card ->
        val store = QueueLocationStore(control, legacy, cipher, checkpoint = { if (it == "committed") throw Interrupted() })
        store.current(); val event = note(); DurableQueue(legacy, cipher).enqueue(event, null, 2000000)
        assertThrows(Interrupted::class.java) { store.migrate("card", card) }
        val selected = store.selected(); assertEquals("card", selected.baseId); assertTrue(legacy.exists())
        val recovered = QueueLocationStore(control, legacy, cipher).current(); assertEquals(selected, recovered); assertFalse(legacy.exists())
        DurableQueue(File(selected.path), cipher).acknowledge(event.getString("id"))
        assertEquals(0, DurableQueue(File(QueueLocationStore(control, legacy, cipher).current().path), cipher).depth())
    }
    @Test fun committedTargetMissingBlobFailsRecoveryAndPreservesOldCopy() = fixture { control, legacy, card ->
        val store = QueueLocationStore(control, legacy, cipher, checkpoint = { if (it == "committed") throw Interrupted() })
        store.current(); DurableQueue(legacy, cipher).enqueue(screen(), byteArrayOf(9), 2000000)
        assertThrows(Interrupted::class.java) { store.migrate("card", card) }
        File(store.selected().path).listFiles()!!.single { it.extension == "blob" }.delete()
        assertThrows(IllegalStateException::class.java) { QueueLocationStore(control, legacy, cipher).current() }
        assertTrue(legacy.exists()); assertTrue(File(control, "queue-migration.json").exists()); assertEquals("card", store.selected().baseId)
    }
    @Test fun unavailableSelectedVolumeNeverFallsBackOrCreatesEmptyQueue() = fixture { control, legacy, card ->
        var mounted = true
        val store = QueueLocationStore(control, legacy, cipher, validate = { if (it.baseId == "card") check(mounted) })
        store.current(); DurableQueue(legacy, cipher).enqueue(note(), null, 2000000); val selected = store.migrate("card", card)
        mounted = false
        assertThrows(IllegalStateException::class.java) { store.current() }; assertEquals(selected, store.selected()); assertFalse(legacy.exists())
        mounted = true; assertEquals(selected, store.current())
    }
    @Test fun unknownPointerAfterCommitNeverDeletesEitherCopy() = fixture { control, legacy, card ->
        val store = QueueLocationStore(control, legacy, cipher, checkpoint = { if (it == "committed") { File(control, "queue-location.json").writeText("unreadable"); error("disk failure") } })
        store.current(); DurableQueue(legacy, cipher).enqueue(note(), null, 2000000)
        assertThrows(IllegalStateException::class.java) { store.migrate("card", card) }
        assertTrue(legacy.exists()); assertEquals(1, card.listFiles()!!.size); assertTrue(File(control, "queue-migration.json").exists())
    }
}
