/** Independent generated plumbing fixtures. Never parses the heldout corpus/eval. */
import {after,test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import type {ContextReader,QueryInput} from '@mote/agent';
import type {QueryResult} from '@mote/shared';
import {base,check,json,hashObject,cloneClosed,SafeFailure} from './test-heldout-memory-replay.js';
import {sha256} from '../apps/server/src/store.js';
import {AdmissionLedger,inspectAdmissionLedger} from './test-heldout-memory-replay-ledger.js';
import {freezeStage,newOutput,runBatch,codeHashes,executorPins,treeHash,openNode,drain} from './test-heldout-memory-replay-stage.js';
import {freezeAsk,runAsk,ablateAsk,inventory,rows,assertOrdinaryInput,assertAskPlan,type AskPlan,validateAsk} from './test-heldout-memory-replay-ask.js';
import {phaseCursor} from './test-heldout-memory-replay-sequence.js';
const root=process.env.MOTE_HELDOUT_ASK_TEST_OUTPUT??join(base,'heldout-ask-offline-'+Date.now());await mkdir(root,{mode:0o700});
const checks:unknown[]=[];let stubs=0;const originalFetch=globalThis.fetch;globalThis.fetch=async()=>{throw Error('Generated tests forbid all network');};
const log=async(name:string,details:Record<string,unknown>={})=>{checks.push({name,passed:true,...details});await writeFile(join(root,'ROOT_SAFE_progress.json'),json({realModelCalls:0,checks}));};
const code=(e:unknown)=>e instanceof SafeFailure?e.code:e instanceof Error?e.message:'unknown';
const use=(i:QueryInput)=>{i.onTrace?.({type:'model.started',payload:{}});i.onUsage?.({measurement:'thread_cumulative',complete:true,requests:0,reportedRequests:0,inputTokens:7,outputTokens:3,totalTokens:10});};
let cached:Awaited<ReturnType<typeof seed>>|undefined;
async function seed(){
 const output=await newOutput(join(root,'mechanical-seed')),m=await freezeStage(output,true),rootManifest=join(output,'ROOT_SAFE_manifest.json'),ledgerDirectory=join(root,'seed-ledger');let parent=m.seed;
 const stub=async(reader:ContextReader,input:QueryInput):Promise<QueryResult>=>{stubs++;use(input);const records=await reader.evidence({ids:input.evidenceIds!}),r=records[0];const domain=input.skill==='coding-memory'?'coding':'personal';return {runId:randomUUID(),trace:[],citations:records.map(r=>({id:r.id,appName:r.appName,capturedAt:r.capturedAt,excerpt:r.ocrText})),answer:JSON.stringify({memories:[0,1,2].map(n=>({domain,title:'Generated memory '+n,statement:'Generated mechanical memory ['+r.id+']',uncertainty:'Fixture only',admission:{layer:n===2?'observation':'memory',reason:'Generated',scope:'Generated',attribution:'observed'},evidenceIds:[r.id],evidence:[{id:r.id,quote:r.ocrText}],...(n===1?{validUntil:'2025-12-01T00:00:00+08:00'}:{}),...(domain==='coding'?{coding:{kind:'decision',scope:'session',applicability:'Generated',validation:'observed'}}:{})}))})};};
 for(let i=0;i<2;i++){const run=await runBatch({manifest:m,manifestHash:sha256(await readFile(rootManifest)),output:await newOutput(join(root,'seed-batch-'+i)),ledgerDirectory,parent,index:i,stub});check(run.succeeded,'ask_fixture_extraction');parent=run.snapshot;}
 const times=['','2025-11-30T23:59:59+08:00','2025-12-31T23:59:59+08:00','2026-01-31T23:59:59+08:00','2026-02-28T23:59:59+08:00','2026-03-31T23:59:59+08:00','2026-04-30T23:59:59+08:00'];
 const questions=[2,3,4,5,6,6,6,6].map((wave,i)=>({questionId:'generated-'+i,scenario:'fact_lookup',question:'GENERATED_QUESTION_SENTINEL_'+i,checkpointWave:wave,contextTime:times[wave]}));
 const plan:AskPlan={schema:'mote-heldout-ask-plan@1',experimentHash:m.experimentHash,questionsHash:hashObject(questions),pairs:questions.map(q=>({...q,slots:[true,false].map((removeMemory,i)=>({id:randomUUID(),removeMemory,label:'Response '+(i+1)}))}))};const planPath=join(root,'generated-plan.json');await writeFile(planPath,json(plan));
 const ledger=new AdmissionLedger(ledgerDirectory,m.experimentHash),head=await treeHash(parent);ledger.begin('fixture-integration-1',head,0);ledger.finish(head,true,{kind:'integration',wave:1,contextTime:m.contextTime,archiveHeadHash:head,totalBatches:2,nextBatch:2,evaluatedPairs:0});advance(ledger,head,2,times[2]);ledger.close();
 return {m,rootManifest,previousManifest:rootManifest,parent,ledgerDirectory,planPath,times};
}
// Synthetic zero-provider phase closures set up the Ask unit boundary, not integration/ingress validation.
function advance(ledger:AdmissionLedger,head:string,wave:number,time:string){const common={wave,contextTime:time,archiveHeadHash:head,totalBatches:1,evaluatedPairs:0};ledger.begin('fixture-ingress-'+wave,head,0);ledger.finish(head,true,{...common,kind:'ingress',nextBatch:0,wavePlan:{path:'/generated-fixture-not-read',sha256:'a'.repeat(64)}});ledger.begin('fixture-extraction-'+wave,head,0);ledger.finish(head,true,{...common,kind:'extraction',nextBatch:1});ledger.begin('fixture-integration-'+wave,head,0);ledger.finish(head,true,{...common,kind:'integration',nextBatch:1});}
async function setup(name:string){cached??=await seed();const data=cached,ledgerDirectory=join(root,name+'-ledger');await cp(data.ledgerDirectory,ledgerDirectory,{recursive:true});const validation=join(root,name+'-validation.json');await writeFile(validation,json({schema:'mote-heldout-sequence-validation@1',status:'passed',realModelCalls:0,heldoutSemanticInputsRead:false,validatedPhases:['evaluation'],executorCodeHashes:executorPins(await codeHashes()),note:'Generated shape fixture; actual acceptance is ROOT_SAFE_ask.json.'}));const supervisorPath=join(base,'run-heldout-ask-supervised.py'),output=await newOutput(join(root,name+'-freeze'));const manifest=await freezeAsk({...data,ledgerDirectory,validation,supervisorPath,output});return {...data,ledgerDirectory,validation,supervisorPath,manifest,manifestPath:join(output,'ROOT_SAFE_manifest.json'),manifestHash:sha256(await readFile(join(output,'ROOT_SAFE_manifest.json')))};}
const observations:Array<{count:number;question:string;operation:string}> = [];
const normal: (reader:ContextReader,input:QueryInput)=>Promise<QueryResult>=async(reader,input)=>{stubs++;use(input);check(!input.conversation&&!input.taskContext&&!input.skill&&!input.evidenceIds,'ask_fixture_special_input');const page=await reader.memories!({limit:100,layer:'memory'}),catalog=await reader.catalog!({path:'/context/memory',limit:100});observations.push({count:page.items.length,question:input.question,operation:input.traceContext!.operationId!});check((catalog as any).entries.length===page.items.length,'ask_fixture_clock_mismatch');const pageRecords=await reader.timeline({limit:100}),evidence=Array.isArray(pageRecords)?pageRecords:pageRecords.items;check(evidence.length>0,'ask_fixture_original_missing');return {answer:'GENERATED_ANSWER_SENTINEL',citations:evidence.map(r=>({id:r.id,appName:r.appName,capturedAt:r.capturedAt,excerpt:r.ocrText})),trace:[],runId:randomUUID()};};
test('two ordinary paired questions use independent clones and preserve canonical',async()=>{const data=await setup('normal'),before=await treeHash(data.parent);const first=await runAsk({...data,output:await newOutput(join(root,'normal-run')),stub:normal});assert.ok(first.succeeded,JSON.stringify(first.report.failure));assert.equal(first.report.stubModelCalls,2);let events=inspectAdmissionLedger(data.ledgerDirectory,data.m.experimentHash);assert.equal(phaseCursor(events,data.m).evaluatedPairs,1);const ledger=new AdmissionLedger(data.ledgerDirectory,data.m.experimentHash);advance(ledger,before,3,data.times[3]);ledger.close();const secondFreeze=await newOutput(join(root,'normal-next-freeze'));const manifest=await freezeAsk({...data,previousManifest:data.manifestPath,output:secondFreeze});const second=await runAsk({...data,manifest,manifestHash:sha256(json(manifest)),output:await newOutput(join(root,'normal-next-run')),stub:normal});assert.ok(second.succeeded,JSON.stringify(second.report.failure));assert.equal(await treeHash(data.parent),before);assert.equal(new Set(observations.map(o=>o.operation)).size,4);assert.deepEqual(observations.map(o=>o.count===0),[true,false,true,false]);assert.ok(observations.every(o=>o.count<6));for(const name of ['normal-run','normal-next-run']){const safe=await readFile(join(root,name,'ROOT_SAFE_stage.json'),'utf8');assert.ok(!safe.includes('GENERATED_QUESTION')&&!safe.includes('GENERATED_ANSWER')&&!safe.includes('removeMemory'));}await log('two-pairs',{outer:4,freshQueries:4,nonemptyMemory:true,canonicalUnchanged:true,receiptReadAfterClose:true});});

for(const failAt of [1,2])test('failure at anonymous slot '+failAt+' stops the pair',async()=>{const data=await setup('failure-'+failAt);let calls=0;const result=await runAsk({...data,output:await newOutput(join(root,'failure-'+failAt+'-run')),stub:async(reader,input)=>{calls++;if(calls===failAt){stubs++;use(input);throw Error('GENERATED_ERROR_SENTINEL');}return normal(reader,input);}});assert.equal(result.succeeded,false);assert.equal(calls,failAt);assert.equal(result.report.stubModelCalls,failAt);assert.equal(result.report.cumulative.failed,1);assert.equal(result.report.cumulative.unreconciledReceipts,0);assert.throws(()=>inspectAdmissionLedger(data.ledgerDirectory,data.m.experimentHash));const publicText=await readFile(join(root,'failure-'+failAt+'-run/ROOT_SAFE_stage.json'),'utf8');assert.ok(!publicText.includes('GENERATED_'));await assert.rejects(async()=>freezeAsk({...data,output:await newOutput(join(root,'failure-'+failAt+'-refreeze'))}));await log('failure-'+failAt,{outer:failAt,newAdmissionsAfterFailure:0,pairNotAdvanced:true});});
test('deadline stops before the second slot and retains terminal failed usage',async()=>{const data=await setup('deadline');let calls=0;const result=await runAsk({...data,output:await newOutput(join(root,'deadline-run')),perOuterMs:10,stub:async(_reader,input)=>{calls++;stubs++;use(input);return new Promise((_r,reject)=>input.signal!.addEventListener('abort',()=>reject(Error('Generated deadline')),{once:true}));}});assert.ok(!result.succeeded);assert.equal(calls,1);assert.equal(result.report.cumulative.failed,1);assert.equal(result.report.cumulative.unreconciledReceipts,0);await log('deadline',{outer:1,postFailureAdmissions:0});});
test('nonempty unknown derivatives and schema are rejected without deletion or provider',async()=>{const data=await setup('inventory');const mutations=[(db:DatabaseSync)=>db.exec("UPDATE captures SET summary='GENERATED_UNKNOWN_SUMMARY'"),(db:DatabaseSync)=>db.exec('CREATE TABLE generated_unknown_cache(x TEXT)'),(db:DatabaseSync)=>db.exec("UPDATE material_organizer_groups SET version='unknown'"),(db:DatabaseSync)=>db.exec("INSERT INTO perception_results SELECT 'generated',id,'unknown','generated','{}',1 FROM captures LIMIT 1")];for(const [i,mutate] of mutations.entries()){const clone=join(root,'inventory-clone-'+i);await cloneClosed(data.parent,clone);const db=new DatabaseSync(join(clone,'mote.sqlite'));mutate(db);db.close();const before=await treeHash(clone);await assert.rejects(()=>ablateAsk(clone,true));assert.equal(await treeHash(clone),before);}await log('unknown-cache',{cases:mutations.length,admissions:0,noDeletion:true});});
test('source mutation and unexpected read-only contribution stop before admission',async()=>{for(const contribution of [false,true]){const name=contribution?'contribution':'source-change',data=await setup(name);let calls=0;const result=await runAsk({...data,output:await newOutput(join(root,name+'-run')),stub:async(reader,input)=>{calls++;return normal(reader,input);},mechanicalHook:node=>{if(contribution)node.featureServices.archiveReader.contextTools=()=>[{} as any];else node.store.db.prepare("UPDATE captures SET summary='GENERATED_UNKNOWN_SUMMARY'").run();}});assert.ok(!result.succeeded);assert.equal(calls,0);assert.equal(result.report.stubModelCalls,0);}await log('admission-source-capability-guards',{admissions:0,cases:2});});
for(const receipt of ['missing','running','conflict'] as const)test('closed '+receipt+' receipt stops accounting and second admission',async()=>{const data=await setup('receipt-'+receipt);let calls=0;const result=await runAsk({...data,output:await newOutput(join(root,'receipt-'+receipt+'-run')),stub:async(reader,input)=>{calls++;return normal(reader,input);},mechanicalHook:node=>{const close=node.app.close.bind(node.app);node.app.close=(async()=>{const rows=node.store.db.prepare("SELECT id,json FROM model_usage WHERE json_extract(json,'$.operation')='query'").all();for(const row of rows){if(receipt==='missing')node.store.db.prepare('DELETE FROM model_usage WHERE id=?').run(row.id);else{const value=JSON.parse(String(row.json));value.status=receipt==='running'?'running':'failed';node.store.db.prepare('UPDATE model_usage SET json=? WHERE id=?').run(JSON.stringify(value),row.id);}}await close();}) as typeof node.app.close;}});assert.ok(!result.succeeded);assert.equal(calls,1);assert.equal(result.report.cumulative.unreconciledReceipts,receipt==='conflict'?0:1);assert.equal(result.report.cumulative.terminalReceiptConflicts,receipt==='running'||receipt==='conflict'?1:0);await log('receipt-'+receipt,{outer:1,postFailureAdmissions:0});});
test('plan commitment survives failed freeze and prevents a new draw or replacement',async()=>{const data=await setup('plan');data.ledgerDirectory=join(root,'first-plan-failure-ledger');await cp(cached!.ledgerDirectory,data.ledgerDirectory,{recursive:true});const admissions=await readFile(join(data.ledgerDirectory,'admissions.ndjson'));const failed=await newOutput(join(root,'plan-failed-freeze'));const mechanicalQuestions=(JSON.parse(await readFile(data.planPath,'utf8')) as AskPlan).pairs.map(({slots,...q})=>q);await assert.rejects(async()=>freezeAsk({...data,planPath:undefined,mechanicalQuestions,output:failed,validation:'/generated-missing-validation'}));const second=await freezeAsk({...data,output:await newOutput(join(root,'plan-new-output')),planPath:undefined});assert.equal(second.task.plan.sha256,sha256(await readFile(join(failed,'DO_NOT_OPEN','ask-plan.json'))));assert.equal(second.task.commitment.sha256,sha256(await readFile(second.task.commitment.path)));const changedPlan=JSON.parse(await readFile(data.planPath,'utf8'));changedPlan.pairs[0].slots.reverse();const path=join(root,'replacement-plan.json');await writeFile(path,json(changedPlan));await assert.rejects(async()=>freezeAsk({...data,output:await newOutput(join(root,'plan-replacement')),planPath:path}),e=>code(e)==='ask_committed_plan_changed');await writeFile(second.task.commitment.path,'{"partial":');await assert.rejects(async()=>freezeAsk({...data,output:await newOutput(join(root,'plan-corrupt'))}));assert.deepEqual(await readFile(join(data.ledgerDirectory,'admissions.ndjson')),admissions);await log('plan-commitment',{admissionsUnchanged:true,failedFreezeReused:true,newDrawRejected:true,corruptionRejected:true});});
test('wrong cursor, changed pins and nonliteral questions fail before execution',async()=>{const data=await setup('boundary');for(const mutate of [(m:any)=>m.task.index++,(m:any)=>m.parent.treeHash='b'.repeat(64),(m:any)=>m.runtime.nodeVersion='bad',(m:any)=>m.codeHashes['scripts/test-heldout-memory-replay-ask.ts']='c'.repeat(64)]){const manifest=structuredClone(data.manifest);mutate(manifest);await assert.rejects(()=>validateAsk(manifest,data.ledgerDirectory));}const source=JSON.parse(await readFile(data.planPath,'utf8'));source.pairs[0].question=' '+source.pairs[0].question;const path=join(root,'whitespace-plan.json');await writeFile(path,json(source));const freshLedger=join(root,'boundary-fresh-ledger');await cp(cached!.ledgerDirectory,freshLedger,{recursive:true});await assert.rejects(async()=>freezeAsk({...data,ledgerDirectory:freshLedger,planPath:path,output:await newOutput(join(root,'whitespace-freeze'))}));await log('fixed-boundaries',{cases:5,admissions:0});});
test('freeze CLI succeeds and live CLI/supervisor reject mechanical or wrong scope',async()=>{const data=await setup('cli');const ledgerBefore=await readFile(join(data.ledgerDirectory,'admissions.ndjson'));const freezeOutput=join(root,'cli-entry-freeze');const frozen=spawnSync(process.execPath,['--import','tsx','scripts/test-heldout-memory-replay.ts'],{encoding:'utf8',env:{...process.env,MOTE_HELDOUT_MODE:'stage-ask-freeze',MOTE_HELDOUT_ROOT_MANIFEST:data.rootManifest,MOTE_HELDOUT_MANIFEST:data.previousManifest,MOTE_HELDOUT_PARENT:data.parent,MOTE_HELDOUT_LEDGER:data.ledgerDirectory,MOTE_HELDOUT_VALIDATION:data.validation,MOTE_HELDOUT_SUPERVISOR:data.supervisorPath,MOTE_HELDOUT_ASK_PLAN:data.planPath,MOTE_HELDOUT_OUTPUT:freezeOutput}});assert.equal(frozen.status,0,frozen.stdout+frozen.stderr);const supervised=spawnSync('python3',[data.supervisorPath,'--repo',process.cwd(),'--manifest',data.manifestPath,'--ledger',data.ledgerDirectory,'--output',join(root,'supervisor-reject')],{encoding:'utf8'});assert.notEqual(supervised.status,0);for(const [name,manifest] of [['mechanical',data.manifest],['scope',{...data.manifest,kind:'heldout',task:{...data.manifest.task,kind:'extraction'}}]] as const){const path=join(root,'cli-'+name+'.json');await writeFile(path,json(manifest));const output=join(root,'cli-'+name+'-run'),result=spawnSync(process.execPath,['--import','tsx','scripts/test-heldout-memory-replay.ts'],{encoding:'utf8',env:{...process.env,MOTE_HELDOUT_MODE:'stage-ask-live',MOTE_HELDOUT_MANIFEST:path,MOTE_HELDOUT_LEDGER:data.ledgerDirectory,MOTE_HELDOUT_OUTPUT:output}});assert.equal(result.status,1);const report=JSON.parse(await readFile(join(output,'ROOT_SAFE_status.json'),'utf8'));assert.equal(report.code,name==='mechanical'?'ask_cli_requires_heldout':'ask_cli_scope_invalid');assert.ok(!(result.stdout+result.stderr).includes('GENERATED_QUESTION'));}assert.deepEqual(await readFile(join(data.ledgerDirectory,'admissions.ndjson')),ledgerBefore);await log('freeze-live-cli',{freezeSucceeded:true,liveRejectCases:2,supervisorReject:true,admissions:0});});

test('ordinary input allows opening differences but rejects all oracle/task context fields',async()=>{const input={question:'Generated',contextTime:'2025-12-31T23:59:59+08:00',timeZone:'Asia/Shanghai',executionLane:'interactive' as const,openingMemories:[]};assertOrdinaryInput(input,input.question,input.contextTime);for(const key of ['conversation','taskContext','skill','evidenceIds','availableIds','expectedFacts','rubric','scenario'])assert.throws(()=>assertOrdinaryInput({...input,[key]:'GENERATED_ORACLE'} as QueryInput,input.question,input.contextTime));await log('minimal-input',{oracleFieldsRejected:8,admissions:0});});
test('coding archive revisions and literal original text survive both ablations',async()=>{const data=await setup('coding'),vault=join(root,'coding-canonical');await cloneClosed(data.parent,vault);const {node,request}=await openNode(vault,data.m.model,data.times[2],async()=>{throw Error('Coding fixture prohibits provider');});try{await request('POST','/api/sources',{id:'generated-coding',name:'Generated Coding',kind:'coding-agent',deviceId:'generated-device',platform:'macos'});for(const revision of ['1','2']){await request('PUT','/api/sources/generated-coding/items',{externalId:'event-1',revision,kind:'message',layer:'snapshot',observedAt:'2025-12-01T10:00:00+08:00',text:'Literal authored summary keyword and generated revision '+revision,document:{contentRole:'transcript',coding:{version:1,provider:'codex',sessionId:'generated-session',projectKey:'generated-project',eventId:'000001',role:'user',part:0,parts:1}}});await drain(node);}}finally{await node.app.close();}const db=new DatabaseSync(join(vault,'mote.sqlite'),{readOnly:true});let original:Record<string,unknown>;try{const snapshot=rows(db);assert.equal(snapshot.source_archive_versions.length,2);assert.ok(snapshot.material_revisions.length>=3);original=Object.fromEntries(['source_archive_versions','material_heads','material_revisions','material_block_payloads','material_members','source_archive_heads'].map(k=>[k,snapshot[k]]));}finally{db.close();}for(const remove of [true,false]){const clone=join(root,'coding-arm-'+remove);await cloneClosed(vault,clone);const result=await ablateAsk(clone,remove);for(const [name,value] of Object.entries(original))assert.deepEqual(result[name],value);}await log('coding-original-history',{revisions:2,sourceHistoryPreserved:true,admissions:0});});

test('all eight blind pairs require exact booleans, safe unique IDs and anonymous labels before commitment',async()=>{const data=await setup('plan-shape'),original=JSON.parse(await readFile(data.planPath,'utf8'));const mutations=[(p:any)=>{p.pairs[0].slots[0].removeMemory='yes';p.pairs[0].slots[1].removeMemory='no';},(p:any)=>p.pairs[7].slots[0].id='../outside',(p:any)=>p.pairs[7].slots[0].id=p.pairs[0].slots[0].id,(p:any)=>p.pairs[6].slots[0].label='Memory arm',(p:any)=>p.pairs[6].slots[0].extra='unknown'];for(const mutate of mutations){const plan=structuredClone(original);mutate(plan);assert.throws(()=>assertAskPlan(plan,data.m.experimentHash));}const invalid=structuredClone(original);mutations[0](invalid);const path=join(root,'invalid-slot-plan.json');await writeFile(path,json(invalid));const ledgerDirectory=join(root,'invalid-slot-ledger');await cp(cached!.ledgerDirectory,ledgerDirectory,{recursive:true});const before=await readFile(join(ledgerDirectory,'admissions.ndjson'));await assert.rejects(async()=>freezeAsk({...data,planPath:path,ledgerDirectory,output:await newOutput(join(root,'invalid-slot-freeze'))}));assert.deepEqual(await readFile(join(ledgerDirectory,'admissions.ndjson')),before);await assert.rejects(()=>readFile(join(ledgerDirectory,'ask-plan-commitment.json')));await log('blind-plan-schema',{cases:5,allPairsValidated:true,invalidCommitmentNotWritten:true,admissions:0});});
after(async()=>{globalThis.fetch=originalFetch;await writeFile(join(root,'ROOT_SAFE_ask.json'),json({schema:'mote-heldout-sequence-validation@1',validatedPhases:['evaluation'],status:checks.length===15?'passed':'incomplete',realModelCalls:0,heldoutSemanticInputsRead:false,stubModelCalls:stubs,checks,executorCodeHashes:executorPins(await codeHashes())}));});
