/** CLI-only mechanical smoke: no heldout input and no live/provider execution. */
import {after,test} from 'node:test';
import {spawnSync} from 'node:child_process';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import type {QueryInput} from '@mote/agent';
import type {QueryResult} from '@mote/shared';
import {base,check,equal,json} from './test-heldout-memory-replay.js';
import {sha256} from '../apps/server/src/store.js';
import {repositoryRoot} from '../apps/server/src/config.js';
import {freezeStage,runBatch,newOutput,treeHash,codeHashes,executorPins} from './test-heldout-memory-replay-stage.js';
const directory=process.env.MOTE_HELDOUT_TEST_OUTPUT??join(base,'heldout-integration-cli-'+Date.now());await mkdir(directory,{mode:0o700});await mkdir(join(directory,'DO_NOT_OPEN'),{mode:0o700});const checks:unknown[]=[];let stubCalls=0;
const seedOutput=await newOutput(join(directory,'seed')),root=await freezeStage(seedOutput,true),rootManifest=join(seedOutput,'ROOT_SAFE_manifest.json'),ledgerDirectory=join(directory,'ledger');let parent=root.seed;
const stub=async(_reader:unknown,input:QueryInput):Promise<QueryResult>=>{stubCalls++;input.onTrace?.({type:'model.started',payload:{}});input.onUsage?.({measurement:'thread_cumulative',complete:true,requests:0,reportedRequests:0,inputTokens:13,outputTokens:5,totalTokens:18});return {answer:'{"memories":[]}',citations:[],trace:[],runId:randomUUID()};};
for(let index=0;index<root.batchPlan.length;index++){const result=await runBatch({manifest:root,manifestHash:sha256(await readFile(rootManifest)),output:await newOutput(join(directory,'extraction-'+index)),ledgerDirectory,parent,index,stub});check(result.succeeded,'cli_fixture_extraction_failed');parent=result.snapshot;}
const validation=join(directory,'ROOT_SAFE_validation-fixture.json'),supervisor=join(directory,'supervisor-fixture.txt');await writeFile(validation,json({schema:'mote-heldout-sequence-validation@1',validatedPhases:['integration'],status:'passed',realModelCalls:0,heldoutSemanticInputsRead:false,executorCodeHashes:executorPins(await codeHashes()),note:'Mechanical validation-shape fixture; this does not stand in for integration acceptance.'}));await writeFile(supervisor,'Literal generated supervisor fingerprint only; no executable provider or timeout behavior.\n');
const stableLedger=sha256(await readFile(join(ledgerDirectory,'admissions.ndjson'))),stableParent=await treeHash(parent),stableRoot=sha256(await readFile(rootManifest));
async function cli(name:string,mode:string,manifest=rootManifest){const output=join(directory,name),env=Object.fromEntries(Object.entries(process.env).filter(([key])=>!key.startsWith('MOTE_')));Object.assign(env,{MOTE_HELDOUT_MODE:mode,MOTE_HELDOUT_ROOT_MANIFEST:rootManifest,MOTE_HELDOUT_MANIFEST:manifest,MOTE_HELDOUT_PARENT:parent,MOTE_HELDOUT_LEDGER:ledgerDirectory,MOTE_HELDOUT_VALIDATION:validation,MOTE_HELDOUT_SUPERVISOR:supervisor,MOTE_HELDOUT_OUTPUT:output});const processResult=spawnSync(process.execPath,['--import','tsx','scripts/test-heldout-memory-replay.ts'],{cwd:repositoryRoot,env,encoding:'utf8',timeout:30000,maxBuffer:1024*1024});await writeFile(join(directory,'DO_NOT_OPEN',name+'-process.log'),String(processResult.stdout??'')+String(processResult.stderr??''),{mode:0o600});check(!processResult.error,'cli_process_error');const status=JSON.parse(await readFile(join(output,'ROOT_SAFE_status.json'),'utf8'));equal(sha256(await readFile(join(ledgerDirectory,'admissions.ndjson'))),stableLedger,'cli_mutated_ledger');equal(await treeHash(parent),stableParent,'cli_mutated_parent');equal(sha256(await readFile(rootManifest)),stableRoot,'cli_mutated_root');return {exitCode:processResult.status,status,output};}
let frozen='';
test('integration freeze CLI creates a mechanical manifest without admission or ledger mutation',async()=>{const result=await cli('freeze','stage-integration-freeze');equal(result.exitCode,0,'cli_freeze_failed');equal(result.status.status,'integration-frozen','cli_freeze_status_wrong');equal(result.status.realModelCalls,0,'cli_freeze_called_model');frozen=join(result.output,'ROOT_SAFE_manifest.json');const m=JSON.parse(await readFile(frozen,'utf8'));equal(m.task.kind,'integration','cli_freeze_scope_wrong');equal([m.limits.stageOuter,m.limits.perOuterMs,m.limits.stageProcessMs],[4,300000,1320000],'cli_freeze_limits_wrong');checks.push({name:'freeze',passed:true,admissions:0,ledgerAndParentUnchanged:true});});
test('integration live CLI refuses a mechanical manifest before execution',async()=>{const result=await cli('reject-mechanical','stage-integration-live',frozen);equal(result.exitCode,1,'cli_mechanical_not_refused');equal(result.status.code,'integration_cli_requires_heldout','cli_mechanical_gate_wrong');checks.push({name:'mechanical-live-rejected',passed:true,admissions:0,ledgerAndParentUnchanged:true,code:result.status.code});});
test('integration live CLI refuses an unrelated task before execution',async()=>{const m=JSON.parse(await readFile(frozen,'utf8'));m.kind='heldout';m.task.kind='extraction';const wrong=join(directory,'ROOT_SAFE_wrong-scope.json');await writeFile(wrong,json(m));const result=await cli('reject-scope','stage-integration-live',wrong);equal(result.exitCode,1,'cli_wrong_scope_not_refused');equal(result.status.code,'integration_cli_scope_invalid','cli_scope_gate_wrong');checks.push({name:'wrong-scope-rejected',passed:true,admissions:0,ledgerAndParentUnchanged:true,code:result.status.code});});
after(async()=>{await writeFile(join(directory,'ROOT_SAFE_cli.json'),json({schema:'mote-heldout-integration-cli-validation@1',status:checks.length===3?'passed':'incomplete',realModelCalls:0,stubModelCalls:stubCalls,heldoutSemanticInputsRead:false,checks,executorCodeHashes:executorPins(await codeHashes()),scope:'CLI mechanical freeze and pre-provider rejection only; no successful live integration or supervisor timing claim.'}),{mode:0o600});});
