/** Host-only, append-only admission accounting. Never accepts semantic data. */
import {closeSync,existsSync,fsyncSync,mkdirSync,openSync,readFileSync,unlinkSync,writeSync} from 'node:fs';
import {randomUUID,createHash} from 'node:crypto';
import {join} from 'node:path';
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
export class StageSafetyError extends Error{constructor(readonly code:string){super(code);}}
const need=(ok:unknown,code:string)=>{if(!ok)throw new StageSafetyError(code);};
/** Structural phase cursor only; never source identities or arm mappings. */
export type PhaseClosure={kind:'ingress'|'extraction'|'integration'|'evaluation';wave:number;contextTime:string;archiveHeadHash:string;totalBatches:number;nextBatch:number;evaluatedPairs:number;wavePlan?:{path:string;sha256:string}};
export type LedgerEvent={index:number;at:string;previous:string;kind:string;data:Record<string,any>;sha256:string};


export type RecoveryRef={path:string;sha256:string};
export type RecoveryLineage={plan:RecoveryRef;eventHash:string};
export type RecoveryPlan={schema:'mote-heldout-recovery-d-plan@1';policy:'D-preserve-six-batches@1';experimentHash:string;recoveryId:string;stoppedHeadHash:string;stopHashes:string[];failedCloseHash:string;failedTerminalHash:string;failedReceiptHash:string;failedAdmissionHash:string;canonicalHeadHash:string;failedSnapshotHash:string;preparedSnapshotHash:string;oldWavePlan:RecoveryRef;newWavePlan:RecoveryRef;wave:2;contextTime:string;inheritedAdmissions:13;effectiveCap:121;remainingCap:108;remainingExtractionBatches:36;targetRetryCap:2;targetStage:string;validation:RecoveryRef;rootManifest:RecoveryRef;previousManifest:RecoveryRef;preparedPath:string;preparationCommitment:RecoveryRef;preparationExecutorHash:string;supervisor:RecoveryRef;runtimeHash:string;productionHash:string;settingsHash:string;bindingsHash:string;expectedTraceAttempts:[2,1,1,1,1,1]};
const isHash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
export function readRecoveryPlan(ref:RecoveryRef):RecoveryPlan{need(ref&&isHash(ref.sha256),'recovery_ref_invalid');const bytes=readFileSync(ref.path);need(createHash('sha256').update(bytes).digest('hex')===ref.sha256,'recovery_plan_changed');const p=JSON.parse(bytes.toString()) as RecoveryPlan;need(p.schema==='mote-heldout-recovery-d-plan@1'&&p.policy==='D-preserve-six-batches@1'&&p.wave===2&&/^[0-9a-f-]{36}$/.test(p.recoveryId),'recovery_plan_invalid');need(p.inheritedAdmissions===13&&p.effectiveCap===121&&p.remainingCap===108&&p.remainingExtractionBatches===36&&p.targetRetryCap===2&&p.effectiveCap===p.inheritedAdmissions+p.remainingExtractionBatches*2+5*4+16,'recovery_budget_changed');need(JSON.stringify(p.expectedTraceAttempts)==='[2,1,1,1,1,1]'&&p.targetStage===`wave2-recovery-D-${p.recoveryId}-batch-0`,'recovery_execution_order_changed');return p;}
/** Used only against the immutable stopped prefix, before the one authorized event. */
export function validateRecoveryPrefix(events:LedgerEvent[],ref:RecoveryRef){const p=readRecoveryPlan(ref);const commitmentBytes=readFileSync(p.preparationCommitment.path);need(createHash('sha256').update(commitmentBytes).digest('hex')===p.preparationCommitment.sha256,'recovery_commitment_changed');const commitment=JSON.parse(commitmentBytes.toString());need(commitment.schema==='mote-heldout-recovery-d-preparation@1'&&commitment.experimentHash===p.experimentHash&&commitment.stoppedHeadHash===p.stoppedHeadHash&&commitment.recoveryId===p.recoveryId,'recovery_commitment_mismatch');need(events[0]?.data.manifestHash===p.experimentHash&&events[0]?.data.cumulativeCap===124,'recovery_ancestor_changed');need(events.at(-1)?.sha256===p.stoppedHeadHash&&!events.some(e=>e.kind==='recovery-authorized'),'recovery_not_original_stopped_head');const admits=events.filter(e=>e.kind==='admit'),failed=events.filter(e=>e.kind==='terminal'&&e.data.status==='failed'),stops=events.filter(e=>e.kind==='stop'),closes=events.filter(e=>e.kind==='stage-close');need(admits.length===13&&failed.length===1&&failed[0].sha256===p.failedTerminalHash&&failed[0].data.safeCode==='outer_deadline_exceeded','recovery_failed_call_changed');need(stops.length===1&&stops[0].data.code==='outer_deadline_exceeded'&&JSON.stringify(stops.map(e=>e.sha256))===JSON.stringify(p.stopHashes),'recovery_stop_set_changed');need(events.filter(e=>e.kind==='stage-open').every(e=>closes.filter(c=>c.data.stage===e.data.stage).length===1),'recovery_unclosed_stage');const admission=admits.find(e=>e.sha256===p.failedAdmissionHash),receipt=events.find(e=>e.sha256===p.failedReceiptHash),closure=closes.at(-1);need(admission&&admission.data.stage==='wave2-batch-0'&&failed[0].data.callId===admission.data.callId&&receipt?.kind==='receipt'&&receipt.data.id===admission.data.receiptId&&receipt.data.status==='failed'&&receipt.data.tokens?.complete===false,'recovery_failed_receipt_changed');need(closure?.sha256===p.failedCloseHash&&closure.data.stage===admission!.data.stage&&closure.data.succeeded===false&&closure.data.snapshotHash===p.failedSnapshotHash&&closes.slice(0,-1).every(e=>e.data.succeeded===true),'recovery_failed_snapshot_changed');need(events.find(e=>e.kind==='stage-open'&&e.data.stage===admission!.data.stage)?.data.parentHash===p.canonicalHeadHash,'recovery_canonical_parent_changed');need(!events.some(e=>e.kind==='host-rejection-receipt'),'recovery_host_rejection_present');for(const a of admits){const ts=events.filter(e=>e.kind==='terminal'&&e.data.callId===a.data.callId),rs=events.filter(e=>e.kind==='receipt'&&e.data.id===a.data.receiptId);need(ts.length===1&&rs.length===1&&rs[0].data.status!=='running'&&ts[0].data.status===rs[0].data.status,'recovery_unknown_accounting');}return p;}
/** Default callers do not pass a lineage and therefore still reject every historic stop. */
export function recoveryAuthorization(events:LedgerEvent[],lineage?:RecoveryLineage){if(!lineage)return undefined;const matches=events.filter(e=>e.kind==='recovery-authorized');need(matches.length===1&&matches[0].sha256===lineage.eventHash,'recovery_event_missing_or_changed');const event=matches[0];need(JSON.stringify(event.data.plan)===JSON.stringify(lineage.plan),'recovery_event_plan_changed');const p=validateRecoveryPrefix(events.slice(0,event.index),lineage.plan);need(event.previous===p.stoppedHeadHash&&event.data.preparedSnapshotHash===p.preparedSnapshotHash,'recovery_event_parent_changed');need(!events.slice(event.index+1).some(e=>e.kind==='stop'),'recovery_new_stop_forbidden');return p;}
export function readAdmissionChain(directory:string){const bytes=readFileSync(join(directory,'admissions.ndjson'),'utf8');need(bytes.endsWith('\n'),'ledger_partial_record_unknown');const events:LedgerEvent[]=[];for(const line of bytes.trimEnd().split('\n')){const row=JSON.parse(line) as LedgerEvent;const {sha256,...body}=row;need(row.index===events.length&&row.previous===(events.at(-1)?.sha256??'genesis')&&sha256===hash(body),'ledger_chain_invalid');events.push(row);}return events;}
/** Only this operation may append an initial recovery event; validation and append share the writer lock. */
export function authorizeRecovery(directory:string,plan:RecoveryRef):RecoveryLineage{let lock:number;try{lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}let file:number|undefined,writing=false;try{const events=readAdmissionChain(directory),p=validateRecoveryPrefix(events,plan);const body={index:events.length,at:new Date().toISOString(),previous:p.stoppedHeadHash,kind:'recovery-authorized',data:{plan,preparedSnapshotHash:p.preparedSnapshotHash}};const row={...body,sha256:hash(body)};file=openSync(join(directory,'admissions.ndjson'),'a',0o600);writing=true;writeSync(file,JSON.stringify(row)+'\n');fsyncSync(file);writing=false;return {plan,eventHash:row.sha256};}finally{if(file!==undefined)closeSync(file);closeSync(lock);if(!writing)unlinkSync(join(directory,'writer.lock'));}}

/** Non-mutating checkpoint inspection; a live writer or uncertain stage is not resumable. */
export function inspectAdmissionLedger(directory:string,experimentHash:string,lineage?:RecoveryLineage){
  need(!existsSync(join(directory,'writer.lock')),'ledger_locked_unknown_interruption');
  const bytes=readFileSync(join(directory,'admissions.ndjson'),'utf8');need(bytes.endsWith('\n'),'ledger_partial_record_unknown');const events:LedgerEvent[]=[];
  for(const line of bytes.trimEnd().split('\n')){const row=JSON.parse(line) as LedgerEvent;const {sha256,...body}=row;need(row.index===events.length&&row.previous===(events.at(-1)?.sha256??'genesis')&&sha256===hash(body),'ledger_chain_invalid');events.push(row);}
  need(events[0]?.kind==='manifest'&&events[0].data.manifestHash===experimentHash&&events[0].data.cumulativeCap===124,'ledger_manifest_mismatch');
  const recovery=recoveryAuthorization(events,lineage);need(!events.some(row=>row.kind==='stop'&&!recovery?.stopHashes.includes(row.sha256)),'ledger_persistently_stopped');const closed=new Set(events.filter(row=>row.kind==='stage-close').map(row=>row.data.stage));
  need(events.filter(row=>row.kind==='stage-open').every(row=>closed.has(row.data.stage)),'unknown_interrupted_stage');
  for(const admission of events.filter(row=>row.kind==='admit')){const terminal=events.filter(row=>row.kind==='terminal'&&row.data.callId===admission.data.callId),receipt=events.filter(row=>row.kind==='receipt'&&row.data.id===admission.data.receiptId);need(terminal.length===1&&receipt.length===1&&receipt[0].data.status!=='running','admission_receipt_unknown');need(terminal[0].data.status===receipt[0].data.status,'terminal_receipt_conflict');}
  return events;
}
/** Holding an exclusive lock for the complete stage makes check+reserve one writer operation.
 * A crash leaves that lock intentionally. No stale-lock reclamation or automatic retry. */
export class AdmissionLedger{
  readonly events:LedgerEvent[]=[];private lock:number;private file=-1;private busy=false;private stage?:string;private recovery?:RecoveryPlan;
  constructor(readonly directory:string,readonly manifestHash:string,readonly cumulativeCap=124,readonly recoveryLineage?:RecoveryLineage){
    mkdirSync(directory,{recursive:true,mode:0o700});
    try{this.lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}
    try{
      const path=join(directory,'admissions.ndjson');if(existsSync(path)){
        const bytes=readFileSync(path,'utf8');need(bytes.endsWith('\n'),'ledger_partial_record_unknown');
        for(const line of bytes.trimEnd().split('\n')){const row=JSON.parse(line) as LedgerEvent;const {sha256,...body}=row;need(row.index===this.events.length&&row.previous===(this.events.at(-1)?.sha256??'genesis')&&sha256===hash(body),'ledger_chain_invalid');this.events.push(row);}
      }
      this.file=openSync(path,'a',0o600);if(!this.events.length)this.append('manifest',{manifestHash,cumulativeCap});
      need(this.events[0].data.manifestHash===manifestHash&&this.events[0].data.cumulativeCap===cumulativeCap,'ledger_manifest_mismatch');
      const opens=this.events.filter(e=>e.kind==='stage-open'),closes=new Set(this.events.filter(e=>e.kind==='stage-close').map(e=>e.data.stage));
      if(opens.some(e=>!closes.has(e.data.stage))||this.pending().length){this.append('stop',{code:'unknown_interrupted_stage'});throw new StageSafetyError('unknown_interrupted_stage');}
      this.recovery=recoveryAuthorization(this.events,recoveryLineage);need(!this.stopped,'ledger_persistently_stopped');
    }catch(e){if(this.file!>=0)closeSync(this.file!);closeSync(this.lock!);unlinkSync(join(directory,'writer.lock'));throw e;}
  }
  private append(kind:string,data:Record<string,any>){const body={index:this.events.length,at:new Date().toISOString(),previous:this.events.at(-1)?.sha256??'genesis',kind,data};const row={...body,sha256:hash(body)};writeSync(this.file,JSON.stringify(row)+'\n');fsyncSync(this.file);this.events.push(row);return row;}
  get stopped(){return this.events.some(e=>e.kind==='stop'&&!this.recovery?.stopHashes.includes(e.sha256));}
  get admitted(){return this.events.filter(e=>e.kind==='admit');}
  pending(){const done=new Set(this.events.filter(e=>e.kind==='terminal').map(e=>e.data.callId));return this.admitted.filter(e=>!done.has(e.data.callId));}
  bindExecutor(manifestHash:string,priorManifestHash?:string,offlineValidationHash?:string){const prior=this.events.filter(e=>e.kind==='executor-freeze').at(-1);if(prior?.data.manifestHash===manifestHash)return;if(prior)need(prior.data.manifestHash===priorManifestHash&&typeof offlineValidationHash==='string'&&/^[a-f0-9]{64}$/.test(offlineValidationHash),'executor_transition_not_validated');this.append('executor-freeze',{manifestHash,priorManifestHash:prior?.data.manifestHash??null,offlineValidationHash:offlineValidationHash??null});}
  begin(stage:string,parentHash:string,maxCalls:number){need(!this.stage&&!this.stopped,'stage_cannot_start');need(!this.events.some(e=>e.kind==='stage-open'&&e.data.stage===stage),'stage_already_started');this.stage=stage;this.append('stage-open',{stage,parentHash,maxCalls});}
  stop(code:string){if(!this.stopped)this.append('stop',{code});}
  reserve(logicalKey:string,inputHash:string,receiptId:string){
    try{need(this.stage&&!this.stopped,'admission_closed');need(!this.busy,'global_concurrency_exceeded');need(!this.admitted.some(e=>e.data.logicalKey===logicalKey),'outer_retry_forbidden');
      const begin=this.events.find(e=>e.kind==='stage-open'&&e.data.stage===this.stage)!;
      need(this.admitted.length<Math.min(this.cumulativeCap,this.recovery?.effectiveCap??this.cumulativeCap)&&this.admitted.filter(e=>e.data.stage===this.stage).length<begin.data.maxCalls,'admission_budget_exceeded');
      if(this.recovery&&this.stage===this.recovery.targetStage)need(this.admitted.filter(e=>e.data.stage===this.recovery!.targetStage).length<this.recovery.targetRetryCap,'recovery_target_budget_exceeded');
      const callId=randomUUID();this.append('admit',{stage:this.stage,callId,logicalKey,inputHash,receiptId});this.busy=true;return callId;
    }catch(e){this.stop(e instanceof StageSafetyError?e.code:'admission_internal_failure');throw e;}
  }
  terminal(callId:string,status:'completed'|'failed',safeCode:string,counts:{modelRunStarts:number|null;repairs:number|null}){need(this.busy&&this.pending().some(e=>e.data.callId===callId),'terminal_without_admission');this.append('terminal',{callId,status,safeCode,...counts});this.busy=false;if(status==='failed')this.stop(safeCode);}
  receipts(rows:Array<{id:string;status:string;tokens?:unknown;estimatedCost?:unknown;currency?:unknown;durationMs?:number}>){
    const previous=new Set(this.events.filter(e=>e.kind==='receipt').map(e=>e.data.id));for(const row of rows){need(this.admitted.some(e=>e.data.receiptId===row.id),'receipt_without_admission');need(!previous.has(row.id),'receipt_counted_twice');this.append('receipt',row);previous.add(row.id);}
  }
  rejectedReceipts(rows:Array<Record<string,any>>){for(const row of rows){need(!this.admitted.some(e=>e.data.receiptId===row.id),'rejected_receipt_was_admitted');need(!this.events.some(e=>e.kind==='host-rejection-receipt'&&e.data.id===row.id),'rejection_receipt_duplicate');this.append('host-rejection-receipt',row);}}
  finish(snapshotHash:string,succeeded:boolean,phase?:PhaseClosure){need(this.stage&&!this.busy&&!this.pending().length,'stage_has_unknown_call');const counted=new Map(this.events.filter(e=>e.kind==='receipt').map(e=>[e.data.id,e]));need(this.admitted.every(e=>counted.has(e.data.receiptId)&&counted.get(e.data.receiptId)!.data.status!=='running'),'admission_receipt_unknown');need(this.admitted.every(e=>{const terminal=this.events.find(t=>t.kind==='terminal'&&t.data.callId===e.data.callId);return terminal?.data.status===counted.get(e.data.receiptId)!.data.status;}),'terminal_receipt_conflict');if(!succeeded)this.stop('stage_technical_failure');this.append('stage-close',{stage:this.stage,snapshotHash,succeeded,...(phase?{phase}:{})});this.stage=undefined;}
  summary(){return {effectiveCap:this.recovery?.effectiveCap??this.cumulativeCap,historicalStops:this.events.filter(e=>e.kind==='stop').length,recoveryPlanHash:this.recoveryLineage?.plan.sha256??null,admitted:this.admitted.length,completed:this.events.filter(e=>e.kind==='terminal'&&e.data.status==='completed').length,failed:this.events.filter(e=>e.kind==='terminal'&&e.data.status==='failed').length,unknown:this.pending().length,unreconciledReceipts:this.admitted.filter(a=>!this.events.some(e=>e.kind==='receipt'&&e.data.id===a.data.receiptId&&e.data.status!=='running')).length,terminalReceiptConflicts:this.admitted.filter(a=>{const t=this.events.find(e=>e.kind==='terminal'&&e.data.callId===a.data.callId),r=this.events.find(e=>e.kind==='receipt'&&e.data.id===a.data.receiptId);return t&&r&&t.data.status!==r.data.status;}).length,hostRejectedReceipts:this.events.filter(e=>e.kind==='host-rejection-receipt').length,receipts:this.events.filter(e=>e.kind==='receipt').length,failedReceipts:this.events.filter(e=>e.kind==='receipt'&&e.data.status==='failed').length,incompleteReceipts:this.events.filter(e=>e.kind==='receipt'&&(!e.data.tokens||e.data.tokens.complete!==true)).length,modelRunStarts:this.events.some(e=>e.kind==='terminal'&&e.data.modelRunStarts===null)?null:this.events.filter(e=>e.kind==='terminal').reduce((sum,e)=>sum+e.data.modelRunStarts,0),repairs:this.events.some(e=>e.kind==='terminal'&&e.data.repairs===null)?null:this.events.filter(e=>e.kind==='terminal').reduce((sum,e)=>sum+e.data.repairs,0),stopped:this.stopped,headHash:this.events.at(-1)!.sha256};}
  close(){closeSync(this.file);closeSync(this.lock);unlinkSync(join(this.directory,'writer.lock'));}
}

/** Explicit read-only diagnostic for recovery preparation; never used by normal live callers. */
export function inspectStoppedRecoveryLedger(directory:string,experimentHash:string){need(!existsSync(join(directory,'writer.lock')),'ledger_locked_unknown_interruption');const events=readAdmissionChain(directory);need(events[0]?.data.manifestHash===experimentHash&&events[0]?.data.cumulativeCap===124,'ledger_manifest_mismatch');need(events.some(e=>e.kind==='stop')&&!events.some(e=>e.kind==='recovery-authorized'),'recovery_original_stop_required');need(events.at(-1)?.kind==='stage-close'&&events.at(-1)?.data.succeeded===false,'recovery_failed_closed_boundary_required');return events;}
/** A partial or existing preparation is never overwritten, moved, or automatically resumed. */
export function reserveRecoveryPreparation(directory:string,experimentHash:string,stoppedHeadHash:string,recoveryId:string,output:string):RecoveryRef{let lock:number;try{lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}let fd:number|undefined,writing=false;try{const events=readAdmissionChain(directory);need(events[0]?.data.manifestHash===experimentHash&&events.at(-1)?.sha256===stoppedHeadHash&&!events.some(e=>e.kind==='recovery-authorized'),'recovery_preparation_head_changed');const path=join(directory,'recovery-preparation.json');need(!existsSync(path),'recovery_preparation_already_reserved');const bytes=JSON.stringify({schema:'mote-heldout-recovery-d-preparation@1',experimentHash,stoppedHeadHash,recoveryId,output})+'\n';fd=openSync(path,'wx',0o600);writing=true;writeSync(fd,bytes);fsyncSync(fd);writing=false;return {path,sha256:createHash('sha256').update(bytes).digest('hex')};}finally{if(fd!==undefined)closeSync(fd);closeSync(lock);if(!writing)unlinkSync(join(directory,'writer.lock'));}}
