/** Explicit one-time recovery plumbing. No live entry point. Source content stays sealed. */
import {DatabaseSync} from 'node:sqlite';
import {join} from 'node:path';
import {check,equal,hashObject,closed,cloneClosed,tables} from './test-heldout-memory-replay.js';
import {openNode,treeHash,protectedTables,settings,bindings,type Manifest} from './test-heldout-memory-replay-stage.js';
export const recoveryPolicy={version:'native-single-timeout-split@1',originalCap:124,effectiveCap:123,inheritedAdmissions:13,remainingCap:110,recoveryHalfCap:4,stageOuter:2,perOuterMs:300000,stageProcessMs:720000,order:[0,1,2,3,4,5,6],expectedTraceAttempts:[2,1,1,1,1,1,1],automaticOuterRetries:0} as const;
const rows=(db:DatabaseSync,id:string)=>db.prepare('SELECT json FROM memory_batches WHERE job_id=? ORDER BY idx').all(id).map(row=>JSON.parse(String(row.json)));
const count=(db:DatabaseSync,table:string)=>Number(db.prepare('SELECT count(*) n FROM '+table).get()!.n);
function unchangedPending(batch:any){const value=structuredClone(batch);if(value.errorCode==='paused')delete value.errorCode;return value;}
function frozenJob(job:any){return {id:job.id,batchCharacters:job.batchCharacters,contextTime:job.contextTime,timeZone:job.timeZone,language:job.language,evidenceIds:job.evidenceIds,recipes:job.recipes,configuration:job.configuration,materialInputs:job.materialInputs,materialRefs:job.materialRefs,artifactRefs:job.artifactRefs,skillVersion:job.skillVersion};}
function immutableRows(db:DatabaseSync,jobId:string){const snapshot=tables(db);const named=['memories','memory_catalog','memory_scopes','memory_dependencies','memory_artifact_dependencies','memory_checkpoints','memory_extraction_drafts','memory_extraction_draft_dependencies','model_usage'];return {protected:protectedTables(db),inherited:Object.fromEntries(named.filter(name=>name in snapshot).map(name=>[name,snapshot[name]])),otherJobs:db.prepare('SELECT * FROM memory_jobs WHERE id<>? ORDER BY id').all(jobId),otherBatches:db.prepare('SELECT * FROM memory_batches WHERE job_id<>? ORDER BY id').all(jobId)};}
function noTargetDraft(db:DatabaseSync,batchId:string){check(!db.prepare('SELECT batch_id FROM memory_extraction_drafts WHERE batch_id=?').get(batchId),'recovery_target_draft_present');}

export async function prepareNativeSplit(input:{parent:string;destination:string;model:Manifest['model'];contextTime:string;jobId:string}){
 await closed(input.parent);const beforeTree=await treeHash(input.parent);await cloneClosed(input.parent,input.destination);let providerAttempts=0;const initialDb=new DatabaseSync(join(input.destination,'mote.sqlite'),{readOnly:true});let inherited:unknown;try{inherited=immutableRows(initialDb,input.jobId);}finally{initialDb.close();}
 const {node}=await openNode(input.destination,input.model,input.contextTime,async()=>{providerAttempts++;throw new Error('recovery_prepare_provider_forbidden');});
 let result:{beforeTree:string;preparedTree:string;protectedHash:string;settingsHash:string;bindingsHash:string;planHash:string;batchCount:number;providerAttempts:number;usageDelta:number};
 try{
  const db=node.store.db;equal(immutableRows(db,input.jobId),inherited,'recovery_startup_changed_inherited');const prior=rows(db,input.jobId),job=JSON.parse(String(db.prepare('SELECT json FROM memory_jobs WHERE id=?').get(input.jobId)!.json));
  check(prior.length===6&&prior.every((b,i)=>b.index===i),'recovery_old_plan_shape');
  check(prior[0].status==='failed'&&prior[0].errorCode==='provider_timeout'&&prior[0].phase==='extract'&&prior[0].attempts===1&&prior[0].chunks.length===8&&!prior[0].splitDepth,'recovery_failed_batch_shape');
  check(prior.slice(1).every(b=>b.status==='pending'&&b.attempts===0&&!b.splitDepth),'recovery_other_batches_changed');
  check(job.contextTime===input.contextTime&&job.batchCharacters===12000,'recovery_frozen_clock_or_budget');
  check(prior.every(b=>!b.availableAt||b.availableAt<=Date.now())&&(!job.availableAt||job.availableAt<=Date.now()),'recovery_cooldown_pending');
  noTargetDraft(db,prior[0].id);check(prior[0].chunks.every((c:any)=>!db.prepare('SELECT key FROM memory_checkpoints WHERE key=?').get(c.key)),'recovery_checkpoint_present');
  check(count(db,'run_execution_owners')===0,'recovery_active_execution');
  const protectedHash=hashObject(protectedTables(db)),settingsHash=hashObject(settings(node)),bindingsHash=hashObject(bindings(node)),usageBefore=count(db,'model_usage');
  // Keep these two calls in the same JS stack: retry schedules its run via microtask.
  const pending=node.memoryPipeline.retry(input.jobId);node.memoryPipeline.pause(input.jobId);await pending;
  const after=rows(db,input.jobId),now=JSON.parse(String(db.prepare('SELECT json FROM memory_jobs WHERE id=?').get(input.jobId)!.json));
  check(node.memoryPipeline.get(input.jobId).status==='paused','recovery_prepare_not_paused');check(after.length===7&&after.every((b,i)=>b.index===i),'recovery_native_order_changed');
  equal(frozenJob(now),frozenJob(job),'recovery_job_pins_changed');equal(hashObject(protectedTables(db)),protectedHash,'recovery_protected_changed');equal(hashObject(settings(node)),settingsHash,'recovery_settings_changed');equal(hashObject(bindings(node)),bindingsHash,'recovery_bindings_changed');
  equal(after.slice(1,6).map(unchangedPending),prior.slice(1).map(unchangedPending),'recovery_untargeted_batches_changed');
  check(after[0].id===prior[0].id&&after[6].id!==prior[0].id&&after[0].attempts===1&&after[6].attempts===0&&after[0].chunks.length===4&&after[6].chunks.length===4,'recovery_split_identity_changed');
  equal([...after[0].chunks,...after[6].chunks],prior[0].chunks,'recovery_split_chunks_changed');
  for(const part of [after[0],after[6]]){check(part.status==='pending'&&part.splitDepth===1&&part.splitHistory?.length===1,'recovery_split_history_invalid');equal(part.splitHistory[0].evidenceRanges,prior[0].evidenceRanges,'recovery_history_ranges_changed');check(part.splitHistory[0].attempts===1&&part.splitHistory[0].errorCode==='provider_timeout','recovery_history_attempt_changed');equal(part.strategy,prior[0].strategy,'recovery_recipe_changed');}
  equal(immutableRows(db,input.jobId),inherited,'recovery_retry_changed_inherited');check(providerAttempts===0&&count(db,'model_usage')===usageBefore,'recovery_prepare_called_model');result={beforeTree,preparedTree:'pending',protectedHash,settingsHash,bindingsHash,planHash:hashObject(after),batchCount:7,providerAttempts,usageDelta:0};
 }finally{await node.app.close();}
 await closed(input.destination);const finalDb=new DatabaseSync(join(input.destination,'mote.sqlite'),{readOnly:true});try{equal(immutableRows(finalDb,input.jobId),inherited,'recovery_close_changed_inherited');}finally{finalDb.close();}equal(await treeHash(input.parent),beforeTree,'recovery_parent_mutated');result!.preparedTree=await treeHash(input.destination);return result!;
}

import {readFile,open,realpath} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {sha256} from '../apps/server/src/store.js';
import {batchPin,codeHashes,executorPins,privateWrite} from './test-heldout-memory-replay-stage.js';
import {type Ref,type WavePlan,type PhaseManifest,ref,readRef,rootAndRuntime,validation,phaseCursor,freezePhase} from './test-heldout-memory-replay-sequence.js';
import {type RecoveryPlan,type RecoveryLineage,inspectStoppedRecoveryLedger,reserveRecoveryPreparation,validateRecoveryPrefix,authorizeRecovery,readRecoveryPlan} from './test-heldout-memory-replay-ledger.js';
const production=(pins:Record<string,string>)=>Object.fromEntries(Object.entries(pins).filter(([name])=>!name.startsWith('scripts/')));
/** Zero provider calls; this explicit operation reserves once and appends one authorized lineage event. */
export async function freezeRecovery(options:{rootManifest:string;previousManifest:string;failedSnapshot:string;ledgerDirectory:string;validation:string;supervisorPath:string;output:string}){
 const rootRef=await ref(options.rootManifest),root=await rootAndRuntime(rootRef),previousRef=await ref(options.previousManifest),previous=await readRef<PhaseManifest>(previousRef),hashes=await codeHashes(),validationRef=await ref(options.validation);await validation(validationRef,hashes,'recovery');
 check(previous.experimentHash===root.experimentHash&&previous.kind===root.kind&&!previous.recoveryLineage&&previous.task.kind==='extraction'&&previous.task.wave===2&&previous.task.index===0,'recovery_previous_scope_invalid');
 equal(previous.runtime,root.runtime,'recovery_runtime_changed');equal(production(previous.codeHashes),production(root.codeHashes),'recovery_production_changed');equal(previous.limits,{...root.limits,stageOuter:2},'recovery_limits_changed');
 const events=inspectStoppedRecoveryLedger(options.ledgerDirectory,root.experimentHash),last=events.at(-1)!;check(events.filter(e=>e.kind==='executor-freeze').at(-1)?.data.manifestHash===previousRef.sha256,'recovery_previous_executor_changed');
 const firstStop=events.findIndex(e=>e.kind==='stop'),priorClosed=events.slice(0,firstStop).filter(e=>e.kind==='stage-close').at(-1),priorEnd=priorClosed?.index;check(priorEnd!==undefined,'recovery_prior_canonical_missing');const cursor=phaseCursor(events.slice(0,priorEnd+1),root);
 check(cursor.wave===2&&cursor.nextBatch===0&&cursor.totalBatches===6&&!cursor.integrationDone&&cursor.archiveHeadHash===previous.parent.treeHash,'recovery_cursor_not_first_wave2_batch');equal(cursor.wavePlan,previous.task.wavePlan,'recovery_old_plan_mismatch');const oldPlan=await readRef<WavePlan>(previous.task.wavePlan);check(oldPlan.wave===2&&oldPlan.batchPlan.length===6&&oldPlan.contextTime===previous.task.contextTime,'recovery_wave_plan_invalid');
 const failedSnapshot=await realpath(options.failedSnapshot);await closed(failedSnapshot);check(await treeHash(failedSnapshot)===last.data.snapshotHash,'recovery_failed_parent_changed');const failed=events.filter(e=>e.kind==='terminal'&&e.data.status==='failed');check(failed.length===1,'recovery_failure_count_changed');const admission=events.find(e=>e.kind==='admit'&&e.data.callId===failed[0].data.callId),receipt=events.find(e=>e.kind==='receipt'&&e.data.id===admission?.data.receiptId);check(admission&&receipt,'recovery_failed_accounting_missing');check(admission.data.logicalKey===hashObject([oldPlan.jobId,oldPlan.batchPlan[0].id,'extract']),'recovery_failed_phase_changed');
 const recoveryId=randomUUID(),preparedPath=join(options.output,'DO_NOT_OPEN','prepared-checkpoint'),newPlanPath=join(options.output,'ROOT_SAFE_wave-plan.json');
 const draft:RecoveryPlan={schema:'mote-heldout-recovery-plan@1',experimentHash:root.experimentHash,recoveryId,stoppedHeadHash:last.sha256,stopHashes:events.filter(e=>e.kind==='stop').map(e=>e.sha256),failedCloseHash:last.sha256,failedTerminalHash:failed[0].sha256,failedReceiptHash:receipt.sha256,failedAdmissionHash:admission.sha256,canonicalHeadHash:cursor.archiveHeadHash,failedSnapshotHash:last.data.snapshotHash,preparedSnapshotHash:'pending',oldWavePlan:previous.task.wavePlan,newWavePlan:{path:newPlanPath,sha256:'pending'},wave:2,contextTime:oldPlan.contextTime,inheritedAdmissions:13,effectiveCap:123,remainingCap:110,remainingExtractionBatches:37,recoveryHalfCap:4,halfStages:[`wave2-recovery-${recoveryId}-batch-0`,`wave2-recovery-${recoveryId}-batch-6`],validation:validationRef,rootManifest:rootRef,previousManifest:previousRef,preparedPath,preparationCommitment:{path:'pending',sha256:'pending'},preparationExecutorHash:hashObject(executorPins(hashes)),supervisor:await ref(options.supervisorPath),runtimeHash:hashObject(root.runtime),productionHash:hashObject(production(root.codeHashes)),settingsHash:root.settingsHash,bindingsHash:root.bindingsHash,expectedTraceAttempts:[2,1,1,1,1,1,1]};
 // Check the paid ledger and old batch pins before reserving the only preparation.
 check(failed[0].data.safeCode==='outer_deadline_exceeded'&&events.filter(e=>e.kind==='stop').length===1&&events.find(e=>e.kind==='stop')?.data.code==='outer_deadline_exceeded'&&admission.data.stage==='wave2-batch-0'&&last.data.stage===admission.data.stage&&receipt.data.status==='failed'&&receipt.data.tokens?.complete===false,'recovery_approved_timeout_required');check(events.filter(e=>e.kind==='admit').length===13&&events.filter(e=>e.kind==='terminal').length===13&&events.filter(e=>e.kind==='receipt').length===13,'recovery_inherited_count_changed');
 const beforeDb=new DatabaseSync(join(failedSnapshot,'mote.sqlite'),{readOnly:true});try{const storedUsage=beforeDb.prepare('SELECT json FROM model_usage').all().map(r=>JSON.parse(String(r.json)));check(storedUsage.length===13,'recovery_snapshot_usage_count_changed');for(const entry of events.filter(e=>e.kind==='receipt')){const stored=storedUsage.find(r=>r.id===entry.data.id);check(stored,'recovery_snapshot_receipt_missing');equal({id:stored.id,status:stored.status,tokens:stored.tokens,estimatedCost:stored.estimatedCost,currency:stored.currency,durationMs:stored.durationMs},entry.data,'recovery_snapshot_receipt_changed');}equal(hashObject(protectedTables(beforeDb)),oldPlan.protectedHash,'recovery_failed_protected_changed');const oldRows=rows(beforeDb,oldPlan.jobId);check(oldRows.length===6&&oldRows.every((b,i)=>b.id===oldPlan.batchPlan[i].id),'recovery_failed_plan_ids_changed');for(let i=1;i<6;i++)equal(batchPin(oldRows[i]),oldPlan.batchPlan[i].sha256,'recovery_pending_pin_changed');const storedJob=JSON.parse(String(beforeDb.prepare('SELECT json FROM memory_jobs WHERE id=?').get(oldPlan.jobId)!.json));check(storedJob.contextTime===oldPlan.contextTime,'recovery_failed_clock_changed');}finally{beforeDb.close();}
 draft.preparationCommitment=reserveRecoveryPreparation(options.ledgerDirectory,root.experimentHash,last.sha256,recoveryId,options.output);
 const prepared=await prepareNativeSplit({parent:failedSnapshot,destination:preparedPath,model:root.model,contextTime:oldPlan.contextTime,jobId:oldPlan.jobId});equal(prepared.protectedHash,oldPlan.protectedHash,'recovery_prepared_protected_changed');equal(prepared.settingsHash,oldPlan.settingsHash,'recovery_prepared_settings_changed');equal(prepared.bindingsHash,oldPlan.bindingsHash,'recovery_prepared_bindings_changed');
 const db=new DatabaseSync(join(preparedPath,'mote.sqlite'),{readOnly:true});let batchPlan:WavePlan['batchPlan'];try{batchPlan=rows(db,oldPlan.jobId).map(b=>({id:b.id,index:b.index,sha256:batchPin(b),recipe:b.strategy?.recipe}));}finally{db.close();}
 const nextPlan:WavePlan={...oldPlan,batchPlan,ingressSnapshot:{path:preparedPath,treeHash:prepared.preparedTree}};await privateWrite(newPlanPath,nextPlan);draft.newWavePlan=await ref(newPlanPath);draft.preparedSnapshotHash=prepared.preparedTree;
 const planPath=join(options.output,'ROOT_SAFE_recovery-plan.json');const planHandle=await open(planPath,'wx',0o600);try{await planHandle.writeFile(JSON.stringify(draft,null,2)+'\n');await planHandle.sync();}finally{await planHandle.close();}const planRef=await ref(planPath);validateRecoveryPrefix(events,planRef);const lineage=authorizeRecovery(options.ledgerDirectory,planRef);
 await privateWrite(join(options.output,'ROOT_SAFE_recovery-lineage.json'),lineage);const manifest=await freezePhase({rootManifest:options.rootManifest,previousManifest:options.previousManifest,parent:preparedPath,ledgerDirectory:options.ledgerDirectory,validation:options.validation,output:options.output,kind:'extraction',index:0,recoveryLineage:lineage,supervisorPath:options.supervisorPath});
 await privateWrite(join(options.output,'ROOT_SAFE_recovery.json'),{schema:'mote-heldout-recovery-preparation-report@1',status:'prepared',realModelCalls:0,providerAttempts:prepared.providerAttempts,usageDelta:prepared.usageDelta,experimentHash:root.experimentHash,recoveryPlanHash:planRef.sha256,recoveryEventHash:lineage.eventHash,stoppedHeadHash:last.sha256,preparedTreeHash:prepared.preparedTree,originalBatches:6,newBatches:7,nativeOrder:recoveryPolicy.order,expectedTraceAttempts:recoveryPolicy.expectedTraceAttempts,inheritedAdmissions:13,effectiveCap:123,remainingCap:110,recoveryHalfCap:4,semanticContentExposed:false});return {manifest,lineage,plan:draft};
}
/** Explicit file supplied by the caller. Never discovers or silently inherits the latest event. */
export async function loadRecoveryLineage(path?:string):Promise<RecoveryLineage|undefined>{if(!path)return undefined;const value=JSON.parse((await readFile(path)).toString()) as RecoveryLineage;check(value&&Object.keys(value).sort().join(',')==='eventHash,plan'&&/^[a-f0-9]{64}$/.test(value.eventHash),'recovery_lineage_shape_invalid');readRecoveryPlan(value.plan);return value;}
