/** Later-wave orchestration. No integration or Ask execution is implemented here. */
import {readFile,realpath} from 'node:fs/promises';
import {join,resolve,relative} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {sourceItemSchema,type SourceItem,type UsageReceipt} from '@mote/shared';
import type {ContextReader,QueryInput} from '@mote/agent';
import type {QueryResult} from '@mote/shared';
import {sha256} from '../apps/server/src/store.js';
import {usageTotals} from '../apps/server/src/usage.js';
import {archiveHash,sourceReceiptId} from '../apps/server/src/source-archive.js';
import {corpus,evaluation,recipes,check,equal,hashObject,parse,lines,verifyFreeze,closed,cloneClosed,sqliteCheck,externalNew} from './test-heldout-memory-replay.js';
import {AdmissionLedger,inspectAdmissionLedger,type LedgerEvent,type PhaseClosure,type RecoveryLineage,recoveryAuthorization,readRecoveryPlan,type RecoveryELineage,recoveryELimits,recoveryEAuthorization,readAdmissionChain,readRecoveryEPlan,type NormalContinuation,normalAuthorization,normalLimits,readNormalPlan,type NormalReviewRecovery,normalReviewAuthorization,readNormalReviewPlan,normalReviewLimits,normalReviewCorrection} from './test-heldout-memory-replay-ledger.js';
import {type Manifest,experimentHash,codeHashes,executorPins,assertRuntimePin,treeHash,protectedTables,privateWrite,sealedError,safeCode,batchPin,bindings,settings,openNode,drain,noProvider,supervisor,runBatch} from './test-heldout-memory-replay-stage.js';

export type Ref={path:string;sha256:string};
type BatchPlan=Manifest['batchPlan'];
export type WavePlan={schema:'mote-heldout-wave-plan@1';experimentHash:string;wave:number;contextTime:string;jobId:string;batchPlan:BatchPlan;settingsHash:string;bindingsHash:string;protectedHash:string;deliveries:number;materials:number;sourceInputHash:string;ingressSnapshot:{path:string;treeHash:string}};
export type PhaseManifest={normalReviewRecovery?:NormalReviewRecovery;normalContinuation?:NormalContinuation;recoveryLineage?:RecoveryLineage;schema:'mote-heldout-phase-manifest@1';kind:Manifest['kind'];experimentHash:string;rootManifest:Ref;previousManifest:Ref;validation:Ref;runtime:Manifest['runtime'];executor:Manifest['executor'];codeHashes:Record<string,string>;limits:{stageOuter:0|1|2;perOuterMs:300000|600000;stageProcessMs:720000|1320000;cumulativePlanningCap:124;automaticOuterRetries:0;concurrency:1};parent:{path:string;treeHash:string;ledgerHeadHash:string};task:{kind:'ingress';wave:number;contextTime:string;inputHash:string;deliveries:number;expectedBatches:number;mechanicalInput?:Ref}|{kind:'extraction';wave:number;contextTime:string;index:number;wavePlan:Ref}};
export type EPhaseManifest=Omit<PhaseManifest,'schema'|'limits'|'task'|'recoveryLineage'|'normalReviewRecovery'>&{schema:'mote-heldout-e-phase-manifest@1';recoveryE:RecoveryELineage;limits:typeof recoveryELimits;task:{kind:'extraction';wave:2;contextTime:string;index:0;wavePlan:Ref}};
export type Cursor={wave:number;contextTime:string;archiveHeadHash:string;totalBatches:number;nextBatch:number;integrationDone:boolean;evaluatedPairs:number;wavePlan?:Ref;recoveryInputHash?:string};
const questionCounts=[0,0,1,1,1,1,4],waveBatches=[0,6,6,10,6,8,6];
const production=(pins:Record<string,string>)=>Object.fromEntries(Object.entries(pins).filter(([file])=>!file.startsWith('scripts/')));
const isHash=(value:unknown)=>typeof value==='string'&&/^[a-f0-9]{64}$/.test(value);
export async function ref(path:string):Promise<Ref>{return {path:await realpath(path),sha256:sha256(await readFile(path))};}
export async function readRef<T>(value:Ref):Promise<T>{check(isHash(value.sha256),'phase_ref_invalid');const bytes=await readFile(value.path);check(sha256(bytes)===value.sha256,'phase_ref_changed');return JSON.parse(bytes.toString()) as T;}
/** Legacy wave-1 closures remain unchanged. Only successful canonical stages advance archiveHead. */
export function phaseCursor(events:LedgerEvent[],root:Manifest,lineage?:RecoveryLineage,normal?:NormalContinuation,review?:NormalReviewRecovery):Cursor{
  check((!lineage||!normal)&&(!review||normal),'normal_lineages_conflict');const reviewPlan=review?normalReviewAuthorization(events,normal!,review):undefined,normalPlan=normal?normalAuthorization(events,normal,review):undefined,recovery=normalPlan?undefined:recoveryAuthorization(events,lineage);check(!events.some(e=>e.kind==='stop'&&!(normalPlan??recovery)?.stopHashes.includes(e.sha256)),'ledger_persistently_stopped');
  let cursor:Cursor={wave:1,contextTime:root.contextTime,archiveHeadHash:root.seedTreeHash,totalBatches:root.batchPlan.length,nextBatch:0,integrationDone:false,evaluatedPairs:0};
  if(normalPlan)cursor={wave:2,contextTime:normalPlan.contextTime,archiveHeadHash:normalPlan.successSnapshotHash,totalBatches:6,nextBatch:1,integrationDone:false,evaluatedPairs:0,wavePlan:normalPlan.newWavePlan,recoveryInputHash:normalPlan.preparedSnapshotHash};
  const afterNormal=normal?events.find(e=>e.sha256===normal.eventHash)!.index:-1;
  for(const event of events.filter(row=>row.index>afterNormal&&(row.kind==='stage-close'||row.kind==='recovery-authorized'||row.kind==='normal-review-recovery-authorized'))){
    if(event.kind==='normal-review-recovery-authorized'){check(reviewPlan&&cursor.wave===2&&cursor.nextBatch===2&&!cursor.integrationDone&&cursor.totalBatches===6&&cursor.archiveHeadHash===reviewPlan.canonicalSnapshotHash,'normal_review_cursor_scope_changed');equal(cursor.wavePlan,reviewPlan.oldWavePlan,'normal_review_cursor_old_plan_changed');cursor={...cursor,wavePlan:reviewPlan.newWavePlan,recoveryInputHash:reviewPlan.preparedSnapshotHash};continue;}
    if(event.sha256===reviewPlan?.failedCloseHash){check(event.data.succeeded===false,'normal_review_failed_closure_changed');continue;}
    if(event.kind==='recovery-authorized'){check(recovery&&cursor.wave===2&&cursor.nextBatch===0&&!cursor.integrationDone&&cursor.totalBatches===6&&cursor.archiveHeadHash===recovery.canonicalHeadHash,'recovery_cursor_scope_changed');equal(cursor.wavePlan,recovery.oldWavePlan,'recovery_cursor_old_plan_changed');cursor={...cursor,totalBatches:6,wavePlan:recovery.newWavePlan,recoveryInputHash:recovery.preparedSnapshotHash};continue;}
    if(event.sha256===recovery?.failedCloseHash){check(event.data.succeeded===false,'recovery_failed_closure_changed');continue;}
    check(event.data.succeeded===true&&isHash(event.data.snapshotHash),'phase_prior_stage_failed');const opened=events.find(row=>row.kind==='stage-open'&&row.data.stage===event.data.stage);check(opened?.data.parentHash===(cursor.recoveryInputHash??cursor.archiveHeadHash),'phase_archive_lineage_changed');
    const phase=event.data.phase as PhaseClosure|undefined;
    if(!phase){const match=/^wave1-batch-(\d+)$/.exec(String(event.data.stage));check(match&&cursor.wave===1&&!cursor.integrationDone&&Number(match[1])===cursor.nextBatch,'phase_legacy_cursor_invalid');check(cursor.nextBatch<root.batchPlan.length,'phase_legacy_index_invalid');cursor={...cursor,nextBatch:cursor.nextBatch+1,archiveHeadHash:event.data.snapshotHash};continue;}
    check(Number.isInteger(phase.wave)&&phase.wave>=1&&phase.wave<=6&&isHash(phase.archiveHeadHash)&&Number.isInteger(phase.totalBatches)&&Number.isInteger(phase.nextBatch)&&Number.isInteger(phase.evaluatedPairs),'phase_cursor_shape_invalid');
    if(phase.kind==='ingress'){
      check(phase.wave===cursor.wave+1&&cursor.integrationDone&&cursor.evaluatedPairs===questionCounts[cursor.wave]&&phase.nextBatch===0&&phase.evaluatedPairs===0,'phase_ingress_out_of_order');check(phase.wavePlan&&phase.totalBatches>0,'phase_wave_plan_missing');cursor={wave:phase.wave,contextTime:phase.contextTime,archiveHeadHash:phase.archiveHeadHash,totalBatches:phase.totalBatches,nextBatch:0,integrationDone:false,evaluatedPairs:0,wavePlan:phase.wavePlan};
    }else{
      check(phase.wave===cursor.wave&&phase.contextTime===cursor.contextTime&&phase.totalBatches===cursor.totalBatches,'phase_cursor_changed');
      if(phase.kind==='extraction'){check(!cursor.integrationDone&&phase.nextBatch===cursor.nextBatch+1&&phase.nextBatch<=cursor.totalBatches&&phase.evaluatedPairs===0,'phase_batch_out_of_order');cursor={...cursor,nextBatch:phase.nextBatch,archiveHeadHash:phase.archiveHeadHash};delete cursor.recoveryInputHash;}
      else if(phase.kind==='integration'){check(!cursor.integrationDone&&cursor.nextBatch===cursor.totalBatches&&phase.nextBatch===cursor.nextBatch&&phase.evaluatedPairs===0,'phase_integration_out_of_order');cursor={...cursor,integrationDone:true,archiveHeadHash:phase.archiveHeadHash};}
      else if(phase.kind==='evaluation'){check(cursor.integrationDone&&phase.nextBatch===cursor.nextBatch&&phase.evaluatedPairs===cursor.evaluatedPairs+1&&phase.evaluatedPairs<=questionCounts[cursor.wave]&&phase.archiveHeadHash===cursor.archiveHeadHash,'phase_evaluation_out_of_order');cursor={...cursor,evaluatedPairs:phase.evaluatedPairs};}
      else check(false,'phase_kind_unknown');
    }
    check(phase.kind==='evaluation'||event.data.snapshotHash===cursor.archiveHeadHash,'phase_snapshot_mismatch');
  }
  return cursor;
}
export async function validation(value:Ref,hashes:Record<string,string>,phase?:string){const report=await readRef<any>(value);check(report.schema==='mote-heldout-sequence-validation@1'&&report.status==='passed'&&report.realModelCalls===0&&report.heldoutSemanticInputsRead===false,'phase_validation_not_passed');equal(report.executorCodeHashes,executorPins(hashes),'phase_validation_wrong_executor');if(phase)check(Array.isArray(report.validatedPhases)&&report.validatedPhases.includes(phase),'phase_validation_scope_missing');}
export async function rootAndRuntime(value:Ref){const root=await readRef<Manifest>(value);check(root.schema==='mote-heldout-first-batch-manifest@1'&&!root.continuation&&experimentHash(root)===root.experimentHash,'phase_root_invalid');await assertRuntimePin(root.runtime);equal(production(await codeHashes()),production(root.codeHashes),'phase_production_pins_changed');return root;}
export async function validateRecoveryRoot(lineage:RecoveryLineage|undefined,root:Manifest,rootRef:Ref,executor?:Manifest['executor']){if(!lineage)return;const p=readRecoveryPlan(lineage.plan);equal(p.rootManifest,rootRef,'recovery_root_ref_changed');check(p.experimentHash===root.experimentHash&&p.runtimeHash===hashObject(root.runtime)&&p.productionHash===hashObject(production(root.codeHashes))&&p.settingsHash===root.settingsHash&&p.bindingsHash===root.bindingsHash,'recovery_root_pins_changed');for(const value of [p.oldWavePlan,p.newWavePlan,p.validation,p.previousManifest])await readRef(value);check(sha256(await readFile(p.supervisor.path))===p.supervisor.sha256,'recovery_supervisor_changed');if(executor)equal(executor,{supervisorPath:p.supervisor.path,supervisorHash:p.supervisor.sha256},'recovery_supervisor_not_frozen');const proof=await readRef<any>(p.validation);check(proof.status==='passed'&&proof.realModelCalls===0&&proof.heldoutSemanticInputsRead===false&&proof.validatedPhases?.includes('recovery-D')&&hashObject(proof.executorCodeHashes)===p.preparationExecutorHash,'recovery_preparation_validation_changed');}
export async function validatePhase(m:PhaseManifest,ledgerDirectory:string){
  check(m.schema==='mote-heldout-phase-manifest@1'&&['ingress','extraction'].includes(m.task.kind),'phase_execution_unimplemented');const root=await rootAndRuntime(m.rootManifest);check(root.experimentHash===m.experimentHash&&root.kind===m.kind,'phase_experiment_changed');equal(m.runtime,root.runtime,'phase_runtime_changed');equal(m.limits,m.normalReviewRecovery&&m.task.kind==='extraction'&&m.task.wave===2&&m.task.index===2?normalReviewLimits:m.normalContinuation?normalLimits[m.task.kind]:{...root.limits,stageOuter:m.task.kind==='ingress'?0:2},'phase_limits_changed');equal(await codeHashes(),m.codeHashes,'phase_executor_changed');await validation(m.validation,m.codeHashes,m.normalReviewRecovery&&m.task.kind==='extraction'&&m.task.wave===2&&m.task.index===2?'normal-review-recovery':m.task.kind);check(sha256(await readFile(m.executor.supervisorPath))===m.executor.supervisorHash,'phase_supervisor_changed');
  if(root.kind==='heldout'){await verifyFreeze(corpus,root.corpusFreeze);await verifyFreeze(evaluation,root.evaluationFreeze);check(sha256(await readFile(root.model.codexBin))===root.model.codexBinHash,'phase_codex_changed');}
  await closed(m.parent.path);check(await treeHash(m.parent.path)===m.parent.treeHash,'phase_parent_changed');const events=inspectAdmissionLedger(ledgerDirectory,m.experimentHash,m.recoveryLineage,m.normalContinuation,m.normalReviewRecovery);check(events.at(-1)?.sha256===m.parent.ledgerHeadHash,'phase_ledger_advanced');const previous=await readRef<Manifest|PhaseManifest>(m.previousManifest);check(previous.experimentHash===m.experimentHash&&events.filter(row=>row.kind==='executor-freeze').at(-1)?.data.manifestHash===m.previousManifest.sha256,'phase_previous_executor_changed');const cursor=phaseCursor(events,root,m.recoveryLineage,m.normalContinuation,m.normalReviewRecovery);if(m.normalContinuation&&cursor.recoveryInputHash){const normal=m.normalReviewRecovery?readNormalReviewPlan(m.normalReviewRecovery.plan):readNormalPlan(m.normalContinuation.plan);const correction=m.normalReviewRecovery&&m.task.kind==='extraction'&&m.task.wave===2&&m.task.index===2?normalReviewCorrection(events,m.normalReviewRecovery):undefined;equal(hashObject(executorPins(m.codeHashes)),correction?hashObject(correction.newExecutors):normal.preparationExecutorHash,'normal_initial_executor_changed');equal(m.validation,correction?.validation??normal.validation,'normal_initial_validation_changed');equal(m.previousManifest,normal.previousManifest,'normal_initial_previous_changed');}if(m.recoveryLineage&&cursor.recoveryInputHash){const recovery=readRecoveryPlan(m.recoveryLineage.plan);equal(hashObject(executorPins(m.codeHashes)),recovery.preparationExecutorHash,'recovery_initial_executor_changed');equal(m.executor,{supervisorPath:recovery.supervisor.path,supervisorHash:recovery.supervisor.sha256},'recovery_initial_supervisor_changed');}await validateRecoveryRoot(m.recoveryLineage,root,m.rootManifest,m.executor);await validateNormalRoot(m.normalContinuation,root,m.rootManifest,m.executor,m.normalReviewRecovery);check(!m.normalContinuation||!m.recoveryLineage&&!Object.hasOwn(m,'recoveryE'),'normal_lineages_conflict');check((cursor.recoveryInputHash??cursor.archiveHeadHash)===m.parent.treeHash,'phase_parent_not_archive_head');
  if(m.task.kind==='ingress'){check(m.task.wave===cursor.wave+1&&m.task.wave<=6&&cursor.integrationDone&&cursor.evaluatedPairs===questionCounts[cursor.wave],'phase_ingress_not_ready');const input=await loadWave(root,m.task.wave,m.task.mechanicalInput);check(input.contextTime===m.task.contextTime&&input.deliveries.length===m.task.deliveries&&input.expectedBatches===m.task.expectedBatches&&hashObject(input)===m.task.inputHash,'phase_ingress_input_changed');}
  else{const plan=await readRef<WavePlan>(m.task.wavePlan);check(plan.schema==='mote-heldout-wave-plan@1'&&plan.experimentHash===m.experimentHash&&cursor.wave===m.task.wave&&cursor.contextTime===m.task.contextTime&&!cursor.integrationDone&&m.task.index===cursor.nextBatch&&m.task.index<cursor.totalBatches,'phase_extract_not_next');equal(cursor.wavePlan,m.task.wavePlan,'phase_wave_plan_changed');check(plan.wave===m.task.wave&&plan.contextTime===m.task.contextTime&&plan.batchPlan.length===cursor.totalBatches,'phase_plan_scope_changed');await pendingBoundary(m.parent.path,plan,m.task.index,m.recoveryLineage,undefined,Boolean(m.normalReviewRecovery));}
  return {root,cursor,ledgerHead:events.at(-1)!.sha256};
}
async function pendingBoundary(parent:string,plan:WavePlan,index:number,lineage?:RecoveryLineage,eAttempt?:2,review=false){const db=new DatabaseSync(join(parent,'mote.sqlite'),{readOnly:true});try{sqliteCheck(db);equal(hashObject(protectedTables(db)),plan.protectedHash,'phase_protected_source_changed');const row=db.prepare('SELECT json FROM memory_jobs WHERE id=?').get(plan.jobId);check(row,'phase_job_missing');const job=JSON.parse(String(row.json));check(job.status==='paused'&&job.contextTime===plan.contextTime&&job.failedBatches===0,'phase_job_not_clean');const batches=db.prepare('SELECT json FROM memory_batches WHERE job_id=? ORDER BY idx').all(plan.jobId).map(row=>JSON.parse(String(row.json)));check(batches.length===plan.batchPlan.length&&batches.every((batch,i)=>batch.id===plan.batchPlan[i].id&&(i<index?batch.status==='completed':batch.status==='pending'&&batch.attempts===(review&&plan.wave===2&&i===2?1:i===0&&eAttempt!==undefined?eAttempt:lineage&&plan.wave===2&&i===0?1:0)&&batchPin(batch)===plan.batchPlan[i].sha256)),'phase_batch_boundary_invalid');check(batches.slice(0,index).every(batch=>batch.chunks.every((chunk:any)=>db.prepare('SELECT key FROM memory_checkpoints WHERE key=?').get(chunk.key))),'phase_checkpoint_missing');}finally{db.close();}}

type WaveInput={contextTime:string;expectedBatches:number;sources:Array<{id:string;[key:string]:unknown}>;deliveries:Array<{sourceId:string;item:SourceItem;duplicate:boolean}>};
async function loadWave(root:Manifest,wave:number,mechanical?:Ref):Promise<WaveInput>{
  if(root.kind==='mechanical'){check(mechanical,'phase_mechanical_input_required');return readRef<WaveInput>(mechanical);}
  check(!mechanical,'phase_mechanical_input_forbidden');const transport=await parse(join(corpus,'transport-manifest.json')),items=await lines(join(corpus,'source-items.ndjson')),availability=await parse(join(evaluation,'checkpoint-availability.json'));const checkpoint=availability.checkpoints.find((row:any)=>row.checkpointWave===wave);check(checkpoint,'phase_checkpoint_missing');const selected=transport.deliveries.filter((row:any)=>row.wave===wave);check(selected.length>0,'phase_empty_wave');return {contextTime:checkpoint.contextTime,expectedBatches:waveBatches[wave],sources:transport.sources,deliveries:selected.map((delivery:any)=>{const line=items[delivery.sourceItemLine-1];check(line&&sha256(line.bytes)===delivery.sourceItemSha256,'phase_item_hash_mismatch');const item=sourceItemSchema.parse(line.value);for(const field of ['wave','availableAfter','eventGroups','receivedAt'])check(!Object.hasOwn(item,field),'phase_orchestration_leak');check(Date.parse(delivery.availableAfter)<=Date.parse(checkpoint.contextTime),'phase_future_delivery');return {sourceId:delivery.sourceId,item,duplicate:Boolean(delivery.aliasOf)};})};
}
export async function freezePhase(options:{rootManifest:string;previousManifest:string;parent:string;ledgerDirectory:string;validation:string;output:string;kind:'ingress'|'extraction';wave?:number;index?:number;mechanicalInput?:string;recoveryLineage?:RecoveryLineage;normalContinuation?:NormalContinuation;normalReviewRecovery?:NormalReviewRecovery;supervisorPath?:string}){
  check(!(options.recoveryLineage||options.normalContinuation)||options.supervisorPath,'recovery_explicit_supervisor_required');check(!options.recoveryLineage||!options.normalContinuation,'normal_lineages_conflict');const rootRef=await ref(options.rootManifest),root=await rootAndRuntime(rootRef),events=inspectAdmissionLedger(options.ledgerDirectory,root.experimentHash,options.recoveryLineage,options.normalContinuation,options.normalReviewRecovery),cursor=phaseCursor(events,root,options.recoveryLineage,options.normalContinuation,options.normalReviewRecovery);const hashes=await codeHashes();let task:PhaseManifest['task'];
  if(options.kind==='ingress'){check(options.wave===cursor.wave+1,'phase_ingress_not_next');const mechanicalInput=options.mechanicalInput?await ref(options.mechanicalInput):undefined,input=await loadWave(root,options.wave!,mechanicalInput);task={kind:'ingress',wave:options.wave!,contextTime:input.contextTime,inputHash:hashObject(input),deliveries:input.deliveries.length,expectedBatches:input.expectedBatches,...(mechanicalInput?{mechanicalInput}:{})};}
  else{check(cursor.wavePlan&&options.index===cursor.nextBatch,'phase_extract_not_next');task={kind:'extraction',wave:cursor.wave,contextTime:cursor.contextTime,index:options.index!,wavePlan:cursor.wavePlan};}
  const m:PhaseManifest={...(options.recoveryLineage?{recoveryLineage:options.recoveryLineage}:{}),...(options.normalContinuation?{normalContinuation:options.normalContinuation}:{}),...(options.normalReviewRecovery?{normalReviewRecovery:options.normalReviewRecovery}:{}),schema:'mote-heldout-phase-manifest@1',kind:root.kind,experimentHash:root.experimentHash,rootManifest:rootRef,previousManifest:await ref(options.previousManifest),validation:await ref(options.validation),runtime:root.runtime,executor:{supervisorPath:options.supervisorPath??supervisor,supervisorHash:sha256(await readFile(options.supervisorPath??supervisor))},codeHashes:hashes,limits:options.normalReviewRecovery&&task.kind==='extraction'&&task.wave===2&&task.index===2?normalReviewLimits:options.normalContinuation?normalLimits[options.kind]:{...root.limits,stageOuter:options.kind==='ingress'?0:2},parent:{path:await realpath(options.parent),treeHash:await treeHash(options.parent),ledgerHeadHash:events.at(-1)!.sha256},task};await validatePhase(m,options.ledgerDirectory);await privateWrite(join(options.output,'ROOT_SAFE_manifest.json'),m);return m;
}
export async function phaseBatchAuthority(m:PhaseManifest|EPhaseManifest,ledgerDirectory:string){if(m.schema==='mote-heldout-e-phase-manifest@1')return eBatchAuthority(m,ledgerDirectory);const checked=await validatePhase(m,ledgerDirectory);check(m.task.kind==='extraction','phase_not_extraction');const plan=await readRef<WavePlan>(m.task.wavePlan),reviewOnly=Boolean(m.normalReviewRecovery&&plan.wave===2&&m.task.index===2),reviewPlan=reviewOnly?readNormalReviewPlan(m.normalReviewRecovery!.plan):undefined;return {...checked,plan,manifest:m,index:m.task.index,reviewOnly,reviewPlan,expectedAttempt:reviewOnly?2:m.recoveryLineage&&plan.wave===2&&m.task.index===0?2:1,stage:reviewPlan?reviewPlan.targetStage:m.recoveryLineage&&plan.wave===2?`wave2-recovery-D-${readRecoveryPlan(m.recoveryLineage.plan).recoveryId}-batch-${m.task.index}`:`wave${plan.wave}-batch-${m.task.index}`};}
/** No model is admitted during ingress, including unexpected background callbacks. */
export async function runIngress(options:{manifest:PhaseManifest;manifestHash:string;output:string;ledgerDirectory:string}){
  const {manifest:m,output}=options,{root,cursor,ledgerHead}=await validatePhase(m,options.ledgerDirectory);check(m.task.kind==='ingress','phase_not_ingress');const input=await loadWave(root,m.task.wave,m.task.mechanicalInput);await externalNew(options.ledgerDirectory);for(const other of [output,m.parent.path])for(const [a,b] of [[other,options.ledgerDirectory],[options.ledgerDirectory,other]]){const part=relative(a,b);check(part==='..'||part.startsWith('../'),'ledger_must_be_outside_snapshots');}const ledger=new AdmissionLedger(options.ledgerDirectory,m.experimentHash,124,m.recoveryLineage,undefined,m.normalContinuation,m.normalReviewRecovery),stage=`wave${m.task.wave}-ingress`,vault=join(output,'DO_NOT_OPEN','working');let opened:Awaited<ReturnType<typeof openNode>>|undefined,succeeded=false,started=false,providerAttempts=0;let inheritedIds=new Set<string>();const report:Record<string,any>={schema:'mote-heldout-ingress-stage@1',stage,status:'running',manifestHash:options.manifestHash,experimentHash:m.experimentHash,realModelCalls:0,stubModelCalls:0,semanticContentExposed:false,startedAt:new Date().toISOString()};
  try{
    check(ledger.events.at(-1)?.sha256===ledgerHead,'phase_ledger_advanced');ledger.bindExecutor(options.manifestHash,m.previousManifest.sha256,m.validation.sha256);ledger.begin(stage,m.parent.treeHash,0);started=true;await cloneClosed(m.parent.path,vault);const initialDb=new DatabaseSync(join(vault,'mote.sqlite'),{readOnly:true});try{inheritedIds=new Set(initialDb.prepare('SELECT id FROM model_usage').all().map(row=>String(row.id)));}finally{initialDb.close();}opened=await openNode(vault,root.model,m.task.contextTime,async()=>{providerAttempts++;throw new Error('ingress_provider_forbidden');},m.normalContinuation?600000:300000);const {node,request}=opened;const inheritedUsage=node.store.db.prepare('SELECT id FROM model_usage ORDER BY id').all();const preservedTables=['captures','source_versions','source_archive_versions'];const preservedRows=preservedTables.map(name=>({name,rows:new Set(node.store.db.prepare('SELECT * FROM '+name).all().map(row=>JSON.stringify(row)))}));const oldArchive=node.store.db.prepare('SELECT source_id,version_key FROM source_archive_versions').all().map(row=>({sourceId:String(row.source_id),version:String(row.version_key),sha256:hashObject(node.sourcePipelines.archive.readVersion(String(row.source_id),String(row.version_key)))}));let newRecords=0,newArchived=0;const oldHeads=new Map(node.store.db.prepare('SELECT id,revision FROM material_heads WHERE retired=0').all().map(row=>[String(row.id),String(row.revision)]));let duplicateCount=0,revisedWithinWave=0;
    equal(hashObject(bindings(node)),root.bindingsHash,'phase_bindings_changed');if(m.normalContinuation){const {assertRecoveryESettings}=await import('./test-heldout-memory-replay-recovery.js');equal(assertRecoveryESettings(node,root.settingsHash),readNormalPlan(m.normalContinuation.plan).effectiveSettingsHash,'normal_ingress_settings_changed');}else equal(hashObject(settings(node)),root.settingsHash,'phase_settings_changed');
    for(const source of input.sources){const existing=node.sources.getSource(source.id);check(existing,'phase_source_missing');for(const field of ['kind','deviceId','platform'])equal((existing as any)[field],source[field],'phase_source_config_changed');}
    for(const delivery of input.deliveries){const item=sourceItemSchema.parse(delivery.item);for(const field of ['wave','availableAfter','eventGroups','receivedAt'])check(!Object.hasOwn(item,field),'phase_orchestration_leak');const source=node.sources.getSource(delivery.sourceId),archived=node.sourcePipelines.select(source)?.storage==='archive';const beforeHeads=new Map(node.store.db.prepare('SELECT id,revision FROM material_heads WHERE retired=0').all().map(row=>[String(row.id),String(row.revision)]));const prior=archived?node.sourcePipelines.archive.readVersion(delivery.sourceId,archiveHash([item.externalId,item.revision])):node.store.db.prepare('SELECT capture_id FROM source_versions WHERE source_id=? AND external_id=? AND revision=?').get(delivery.sourceId,item.externalId,item.revision);check(Boolean(prior)===delivery.duplicate,'phase_duplicate_prior_mismatch');const before=Date.now(),ack=await request('PUT','/api/sources/'+encodeURIComponent(delivery.sourceId)+'/items',item);check(Boolean(ack.duplicate)===delivery.duplicate,'phase_duplicate_ack_mismatch');
      if(archived){check(ack.id===sourceReceiptId(delivery.sourceId,item),'phase_archive_identity_changed');equal(node.sourcePipelines.archive.readVersion(delivery.sourceId,archiveHash([item.externalId,item.revision])),item,'phase_archive_original_changed');await drain(node);const changed=node.store.db.prepare('SELECT id,revision FROM material_heads WHERE retired=0').all().filter(row=>beforeHeads.has(String(row.id))&&beforeHeads.get(String(row.id))!==row.revision);if(delivery.duplicate)check(changed.length===0,'phase_duplicate_rebuilt_material');else revisedWithinWave+=changed.length;}
      else{const captured=node.store.evidence([ack.id])[0];check(captured,'phase_capture_missing');equal(captured.ocrText,item.text,'phase_original_changed');check(Date.parse(captured.capturedAt)===Date.parse(item.observedAt)&&captured.provenance?.document?.recordedAt===item.document?.recordedAt,'phase_original_time_changed');if(delivery.duplicate)check(ack.id===(prior as any).capture_id,'phase_duplicate_identity_changed');else check(Date.parse(captured.receivedAt)>=before&&Date.parse(captured.receivedAt)<=Date.now(),'phase_received_at_not_real');}
      if(delivery.duplicate)duplicateCount++;else if(archived)newArchived++;else newRecords++;
    }
    await drain(node);for(const table of preservedRows){const after=new Set(node.store.db.prepare('SELECT * FROM '+table.name).all().map(row=>JSON.stringify(row)));check([...table.rows].every(row=>after.has(row)),'phase_prior_original_mutated');}for(const prior of oldArchive)check(hashObject(node.sourcePipelines.archive.readVersion(prior.sourceId,prior.version))===prior.sha256,'phase_prior_archive_content_changed');for(const name of ['captures','source_versions','source_archive_versions']){const before=preservedRows.find(table=>table.name===name)!.rows.size,after=Number(node.store.db.prepare('SELECT count(*) n FROM '+name).get()!.n);check(after===before+(name==='source_archive_versions'?newArchived:newRecords),'phase_unplanned_original_imported');}check(providerAttempts===0,'phase_ingress_called_provider');equal(node.store.db.prepare('SELECT id FROM model_usage ORDER BY id').all(),inheritedUsage,'phase_ingress_usage_changed');const heads=node.store.db.prepare('SELECT id,revision,kind FROM material_heads WHERE retired=0 ORDER BY id').all(),changed=heads.filter(row=>oldHeads.get(String(row.id))!==row.revision),continued=changed.filter(row=>oldHeads.has(String(row.id)));check(continued.every(row=>row.kind==='mote.coding-session'),'phase_unexpected_material_rewrite');const ids=[...new Set(changed.flatMap(row=>node.materials.evidenceIds(node.materials.get(String(row.id))!.ref)))];check(ids.length>0,'phase_no_new_evidence');const job=node.memoryPipeline.create({evidenceIds:ids,recipes,contextTime:m.task.contextTime,timeZone:'Asia/Shanghai',batchCharacters:12000});node.memoryPipeline.pause(job.id);const rows=node.store.db.prepare('SELECT json FROM memory_batches WHERE job_id=? ORDER BY idx').all(job.id).map(row=>JSON.parse(String(row.json)));check(job.totalBatches===input.expectedBatches&&rows.every(row=>row.status==='pending'&&row.attempts===0),'phase_batch_plan_changed');
    const plan:WavePlan={schema:'mote-heldout-wave-plan@1',experimentHash:m.experimentHash,wave:m.task.wave,contextTime:m.task.contextTime,jobId:job.id,batchPlan:rows.map(row=>({id:row.id,index:row.index,sha256:batchPin(row),recipe:row.strategy?.recipe})),settingsHash:hashObject(settings(node)),bindingsHash:hashObject(bindings(node)),protectedHash:hashObject(protectedTables(node.store.db)),deliveries:input.deliveries.length,materials:heads.length,sourceInputHash:m.task.inputHash,ingressSnapshot:{path:join(output,'DO_NOT_OPEN','closed-checkpoint'),treeHash:'pending'}};await privateWrite(join(output,'DO_NOT_OPEN','batch-plan.json'),rows);await node.app.close();opened=undefined;await closed(vault);const db=new DatabaseSync(join(vault,'mote.sqlite'),{readOnly:true});try{sqliteCheck(db);equal(db.prepare('SELECT id FROM model_usage ORDER BY id').all(),inheritedUsage,'phase_ingress_terminal_usage_changed');equal(hashObject(protectedTables(db)),plan.protectedHash,'phase_ingress_closed_source_changed');}finally{db.close();}await cloneClosed(vault,plan.ingressSnapshot.path);plan.ingressSnapshot.treeHash=await treeHash(plan.ingressSnapshot.path);const planPath=join(output,'ROOT_SAFE_wave-plan.json');await privateWrite(planPath,plan);const planRef=await ref(planPath);check(await treeHash(m.parent.path)===m.parent.treeHash,'phase_parent_mutated');if(m.normalReviewRecovery)await (await import('./test-heldout-memory-replay-recovery.js')).normalReviewControls(m.normalReviewRecovery);ledger.finish(plan.ingressSnapshot.treeHash,true,{kind:'ingress',wave:plan.wave,contextTime:plan.contextTime,archiveHeadHash:plan.ingressSnapshot.treeHash,totalBatches:plan.batchPlan.length,nextBatch:0,evaluatedPairs:0,wavePlan:planRef});succeeded=true;report.checkpoint=plan.ingressSnapshot;report.wavePlan=planRef;report.counts={deliveries:input.deliveries.length,duplicates:duplicateCount,newMaterials:changed.length-continued.length,revisedCodingMaterials:continued.length,codingRevisionsWithinWave:revisedWithinWave,unchangedMaterials:heads.length-changed.length,batches:rows.length};
  }catch(error){if(started)ledger.stop(safeCode(error));report.failure={code:safeCode(error)};await sealedError(join(output,'DO_NOT_OPEN'),error);}
  finally{if(opened){try{await opened.node.app.close();}catch(error){ledger.stop('ingress_close_failed');await sealedError(join(output,'DO_NOT_OPEN'),error);}}try{await closed(vault);const finalDb=new DatabaseSync(join(vault,'mote.sqlite'),{readOnly:true});let added:UsageReceipt[];try{sqliteCheck(finalDb);added=finalDb.prepare('SELECT json FROM model_usage').all().map(row=>JSON.parse(String(row.json)) as UsageReceipt).filter(row=>!inheritedIds.has(row.id));}finally{finalDb.close();}report.terminalUsage={readAfterClose:true,inherited:inheritedIds.size,new:added.length,totals:usageTotals(added)};if(added.length){ledger.rejectedReceipts(added.map(row=>({id:row.id,status:row.status,tokens:row.tokens,estimatedCost:row.estimatedCost,currency:row.currency,durationMs:row.durationMs})));ledger.stop('ingress_unexpected_usage');succeeded=false;}}catch(error){succeeded=false;ledger.stop('ingress_terminal_accounting_failed');report.terminalUsageUnknown=true;await sealedError(join(output,'DO_NOT_OPEN'),error);}report.providerAdmissionAttempts=providerAttempts;report.status=succeeded?'ingress-success':'stopped';report.cumulative={...ledger.summary(),usage:usageTotals(ledger.events.filter(row=>row.kind==='receipt').map(row=>row.data as UsageReceipt))};report.finishedAt=new Date().toISOString();ledger.close();await privateWrite(join(output,'ROOT_SAFE_stage.json'),report);}
  return {succeeded,report};
}
export async function runPhase(options:{manifestPath:string;output:string;ledgerDirectory:string;stub?:(reader:ContextReader,input:QueryInput)=>Promise<QueryResult>}){const bytes=await readFile(options.manifestPath),m=JSON.parse(bytes.toString()) as PhaseManifest|EPhaseManifest;if(m.schema==='mote-heldout-phase-manifest@1'&&m.task.kind==='ingress')return runIngress({manifest:m,manifestHash:sha256(bytes),output:options.output,ledgerDirectory:options.ledgerDirectory});const root=await readRef<Manifest>(m.rootManifest);return runBatch({manifest:root,manifestHash:sha256(bytes),output:options.output,ledgerDirectory:options.ledgerDirectory,sequence:m,...(options.stub?{stub:options.stub}:{})});}

/** An E phase is intentionally not a general sequence cursor: no next phase is authorized. */
export async function eBatchAuthority(m:EPhaseManifest,ledgerDirectory:string){
 check(m.schema==='mote-heldout-e-phase-manifest@1'&&!Object.hasOwn(m,'recoveryLineage')&&!Object.hasOwn(m,'normalContinuation')&&!Object.hasOwn(m,'normalReviewRecovery')&&m.task?.kind==='extraction'&&m.task.wave===2&&m.task.index===0,'recovery_e_phase_scope_invalid');equal(m.limits,recoveryELimits,'recovery_e_limits_changed');check(m.recoveryE&&Object.keys(m.recoveryE).sort().join(',')==='eventHash,plan','recovery_e_lineage_invalid');
 const root=await rootAndRuntime(m.rootManifest);check(root.experimentHash===m.experimentHash&&root.kind===m.kind,'recovery_e_experiment_changed');equal(m.runtime,root.runtime,'recovery_e_runtime_changed');equal(await codeHashes(),m.codeHashes,'recovery_e_executor_changed');await validation(m.validation,m.codeHashes,'recovery-E');
 const events=readAdmissionChain(ledgerDirectory),p=recoveryEAuthorization(events,m.recoveryE);check(events.at(-1)?.sha256===m.parent.ledgerHeadHash,'recovery_e_ledger_advanced');equal(p.rootManifest,m.rootManifest,'recovery_e_root_ref_changed');equal(p.previousManifest,m.previousManifest,'recovery_e_previous_changed');equal(p.validation,m.validation,'recovery_e_validation_changed');equal(m.executor,{supervisorPath:p.supervisor.path,supervisorHash:p.supervisor.sha256},'recovery_e_supervisor_changed');check(sha256(await readFile(p.supervisor.path))===p.supervisor.sha256,'recovery_e_supervisor_changed');
 check(p.experimentHash===root.experimentHash&&p.runtimeHash===hashObject(root.runtime)&&p.productionHash===hashObject(production(root.codeHashes))&&p.oldSettingsHash===root.settingsHash&&p.bindingsHash===root.bindingsHash,'recovery_e_root_pins_changed');equal(p.preparationExecutorHash,hashObject(executorPins(m.codeHashes)),'recovery_e_preparation_executor_changed');equal(m.task.wavePlan,p.newWavePlan,'recovery_e_wave_plan_changed');const previous=await readRef<PhaseManifest>(m.previousManifest);check(previous.schema==='mote-heldout-phase-manifest@1'&&previous.experimentHash===root.experimentHash&&previous.task.kind==='extraction'&&previous.task.wave===2&&previous.task.index===0,'recovery_e_previous_scope_changed');equal(previous.recoveryLineage,p.parentD,'recovery_e_parent_lineage_changed');check(events.filter(e=>e.kind==='executor-freeze').at(-1)?.data.manifestHash===m.previousManifest.sha256,'recovery_e_previous_executor_changed');
 if(root.kind==='heldout'){await verifyFreeze(corpus,root.corpusFreeze);await verifyFreeze(evaluation,root.evaluationFreeze);check(sha256(await readFile(root.model.codexBin))===root.model.codexBinHash,'recovery_e_codex_changed');}
 await closed(m.parent.path);check(m.parent.path===p.preparedPath&&m.parent.treeHash===p.preparedSnapshotHash&&await treeHash(m.parent.path)===p.preparedSnapshotHash,'recovery_e_parent_changed');const plan=await readRef<WavePlan>(p.newWavePlan);check(plan.schema==='mote-heldout-wave-plan@1'&&plan.experimentHash===root.experimentHash&&plan.wave===2&&plan.contextTime===p.contextTime&&m.task.contextTime===p.contextTime&&plan.jobId===p.target.jobId&&plan.batchPlan.length===6&&plan.batchPlan[0].id===p.target.batchId&&plan.settingsHash===p.effectiveSettingsHash&&plan.bindingsHash===p.bindingsHash,'recovery_e_plan_scope_changed');await pendingBoundary(m.parent.path,plan,0,undefined,2);
 const cursor:Cursor={wave:2,contextTime:p.contextTime,archiveHeadHash:p.canonicalHeadHash,totalBatches:6,nextBatch:0,integrationDone:false,evaluatedPairs:0,wavePlan:p.newWavePlan,recoveryInputHash:p.preparedSnapshotHash};return {root,cursor,ledgerHead:events.at(-1)!.sha256,plan,manifest:m,index:0,expectedAttempt:3,stage:p.targetStage,reviewOnly:false,reviewPlan:undefined};
}

export async function validateNormalRoot(normal:NormalContinuation|undefined,root:Manifest,rootRef:Ref,executor:Manifest['executor'],review?:NormalReviewRecovery){check(!review||normal,'normal_review_normal_required');if(!normal)return;const p=readNormalPlan(normal.plan);equal(p.rootManifest,rootRef,'normal_root_ref_changed');check(p.experimentHash===root.experimentHash&&p.runtimeHash===hashObject(root.runtime)&&p.productionHash===hashObject(production(root.codeHashes))&&p.oldSettingsHash===root.settingsHash&&p.bindingsHash===root.bindingsHash,'normal_root_pins_changed');if(review){const r=await (await import('./test-heldout-memory-replay-recovery.js')).normalReviewControls(review);equal(r.normalContinuation,normal,'normal_review_normal_changed');equal(r.rootManifest,rootRef,'normal_review_root_changed');equal(r.oldSupervisor,p.supervisor,'normal_review_old_supervisor_changed');equal(executor,{supervisorPath:r.supervisor.path,supervisorHash:r.supervisor.sha256},'normal_review_supervisor_not_frozen');const v=await readRef<any>(r.validation);check(v.status==='passed'&&v.realModelCalls===0&&v.heldoutSemanticInputsRead===false&&v.validatedPhases?.includes('normal-review-recovery')&&hashObject(v.executorCodeHashes)===r.preparationExecutorHash,'normal_review_preparation_validation_changed');}else equal(executor,{supervisorPath:p.supervisor.path,supervisorHash:p.supervisor.sha256},'normal_supervisor_not_frozen');check(sha256(await readFile(p.supervisor.path))===p.supervisor.sha256,'normal_supervisor_changed');const proof=await readRef<any>(p.validation);check(proof.status==='passed'&&proof.realModelCalls===0&&proof.heldoutSemanticInputsRead===false&&proof.validatedPhases?.includes('normal-continuation')&&hashObject(proof.executorCodeHashes)===p.preparationExecutorHash,'normal_preparation_validation_changed');for(const r of [p.oldWavePlan,p.newWavePlan,p.previousManifest])await readRef(r);}
