/** Explicit owner-declared diary calibration on a copy of a closed generated vault.
 * Separate from the paired comparison; report quality requires manual review. */
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {cp,mkdir,readFile,writeFile} from 'node:fs/promises';
import {join,relative,resolve} from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
import {buildApp} from '../apps/server/src/app.js';
import {safeError} from '../apps/server/src/diagnostics.js';
import {usageTotals} from '../apps/server/src/usage.js';
import {AgentYieldError} from '@mote/agent';
import {repositoryRoot,type Config} from '../apps/server/src/config.js';
import type {CaptureRecord,UsageReceipt} from '@mote/shared';
function external(path:string){const absolute=resolve(path),part=relative(repositoryRoot,absolute);assert.ok(part==='..'||part.startsWith('../'),'Calibration files must remain outside Git');return absolute;}
assert.ok(process.env.MOTE_ATTRIBUTION_OWNER_INPUT,'Set MOTE_ATTRIBUTION_OWNER_INPUT to the completed generated report.json');
assert.ok(process.env.MOTE_ATTRIBUTION_OWNER_OUTPUT,'Set a fresh MOTE_ATTRIBUTION_OWNER_OUTPUT outside Git');
const inputPath=external(process.env.MOTE_ATTRIBUTION_OWNER_INPUT),output=external(process.env.MOTE_ATTRIBUTION_OWNER_OUTPUT);
const paired=JSON.parse(await readFile(inputPath,'utf8'));
assert.equal(paired.status,'execution-passed','Wait until the source run closes its vaults');assert.equal(paired.personalDataUsed,false);assert.equal(paired.model,'gpt-6.1-sol');assert.equal(paired.serviceTier,'fast');assert.equal(paired.uniformModelConfiguration,true);
const declared=paired.arms.find((arm:any)=>arm.arm==='declared');assert.ok(declared?.restartNoReplay&&declared.finishedAt);
const diary=declared.records.find((record:any)=>record.key==='unknown-diary');assert.ok(diary?.material&&diary?.memories?.length,'Source run must contain its generated diary observation');
await mkdir(output,{mode:0o700});const vault=join(output,'vault');await cp(external(declared.vault),vault,{recursive:true,errorOnExist:true,force:false});
const token=randomBytes(32).toString('hex'),started=Date.now(),maximumCalls=8,maximumDurationMs=20*60*1000,perCallTimeoutMs=900000;
const report:Record<string,any>={schema:'mote-owner-diary-calibration@1',comparison:'Separate explicit historical processing calibration, not a paired arm',sourceReport:inputPath,personalDataUsed:false,model:'gpt-6.1-sol',reasoningEffort:'high',serviceTier:'fast',perCallTimeoutMs,maximumCalls,maximumDurationMs,runnerRequestRetries:0,semanticQualityAccepted:false,screenshotsUsed:false,physicalDeviceTested:false,calls:[],status:'running',startedAt:new Date(started).toISOString()};
let node:Awaited<ReturnType<typeof buildApp>>|undefined,base='',explicitJobStarted=false,writes=Promise.resolve(),priorUsageIds=new Set<string>();
function save(){const bytes=JSON.stringify(report,null,2)+'\n';writes=writes.then(()=>writeFile(join(output,'report.json'),bytes,{mode:0o600}));return writes;}
async function request(method:string,path:string,body?:unknown){assert.ok(Date.now()-started<maximumDurationMs,'Calibration deadline exceeded');const response=await fetch(base+path,{method,headers:{authorization:'Bearer '+token,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(perCallTimeoutMs+10000)});const value=await response.json();assert.ok(response.ok,`${method} ${path}: ${response.status} ${JSON.stringify(value)}`);return value as any;}
const config:Config={dataKey:undefined,dataDir:vault,token,tokenPath:join(vault,'token'),host:'127.0.0.1',port:0,maxStorageBytes:100_000_000,maxExportBytes:1_000_000,retentionDays:0,insightIntervalHours:0,allowedOrigins:[],model:'gpt-6.1-sol',modelProvider:'codex',modelProtocol:'codex-app-server',modelReasoningEffort:'high',agentTimeoutMs:perCallTimeoutMs,modelBaseUrl:'',apiKey:'',allowUnauthenticatedLocal:false,embeddingModel:'',embeddingBaseUrl:'',embeddingApiKey:'',codexBin:process.env.MOTE_CODEX_BIN,codexHome:process.env.MOTE_CODEX_HOME,memoryConcurrency:1,diagnosticsEnabled:true,agentTraceEnabled:true,logLevel:'warn'};
try{
 node=await buildApp(config);priorUsageIds=new Set(node.store.db.prepare('SELECT id FROM model_usage').all().map(row=>String(row.id)));const selected=node.modelSettings.select('memory');assert.equal(selected.settings.model,'gpt-6.1-sol');assert.equal(selected.settings.reasoningEffort,'high');assert.equal(selected.settings.serviceTier,'fast');assert.equal(selected.settings.agentTimeoutMs,perCallTimeoutMs);report.modelSelection=selected;
 const query=node.agent.query.bind(node.agent);node.agent.query=async(input:any)=>{assert.ok(explicitJobStarted,'Correction or startup unexpectedly triggered paid work');assert.ok(report.calls.length<maximumCalls,'Calibration model call budget exceeded');assert.ok(Date.now()-started<maximumDurationMs);const selection=node!.modelSettings.select(input.traceContext?.phase?'memory':'chat',input.modelProfileId);if(input.modelOverride)selection.settings.model=input.modelOverride;assert.equal(selection.settings.model,'gpt-6.1-sol');assert.equal(selection.settings.reasoningEffort,'high');assert.equal(selection.settings.serviceTier,'fast');assert.equal(selection.settings.agentTimeoutMs,perCallTimeoutMs);const call:any={phase:input.traceContext?.phase??'query',startedAt:new Date().toISOString(),modelSelection:selection,backendTierConfirmation:'unknown'};report.calls.push(call);await save();try{const result=await query(input);call.status='completed';call.runId=result.runId;call.backendTierConfirmation=true;return result;}catch(error){const yielded=error instanceof AgentYieldError;call.status=yielded?'yielded':'failed';call.error=yielded?{name:'AgentYieldError',category:'control_yield',message:'Coordinator yielded to durable delegated work'}:{name:error instanceof Error?error.name:'UnknownError',...safeError(error)};throw error;}finally{call.durationMs=Date.now()-Date.parse(call.startedAt);await save();}};
 await node.app.listen({host:'127.0.0.1',port:0});base=node.app.listeningOrigin!;
 const grants=()=>JSON.stringify(node!.store.db.prepare('SELECT * FROM memory_input_authorizations ORDER BY source_id,input_key,scope').all());
 const jobIds=()=>node!.store.db.prepare('SELECT id FROM memory_jobs ORDER BY id').all().map(row=>String(row.id));
 const priorGrants=grants(),priorJobIds=jobIds(),before=await request('GET','/api/materials/'+diary.material.id),beforeRead=await request('GET',`/api/materials/${before.id}/read?revision=${before.revision}&length=12000`);
 report.before={material:before,read:beforeRead,oldObservations:diary.memories.map((memory:any)=>node!.memories.get(memory.id)),jobIds:priorJobIds};
 const corrected=await request('PATCH','/api/materials/'+before.id+'/context',{expectedRevision:before.revision,ownerRelation:'owner'}),afterRead=await request('GET',`/api/materials/${corrected.id}/read?revision=${corrected.revision}&length=12000`);
 assert.equal(corrected.attributionContext.ownerRelation,'owner');assert.equal(corrected.attributionContext.basis,'owner_material');assert.equal(afterRead.text,beforeRead.text);assert.equal(grants(),priorGrants);
 const oldObservations=diary.memories.map((memory:any)=>node!.memories.get(memory.id));assert.ok(oldObservations.every((memory:any)=>memory.status==='stale'));
 await delay(12000);assert.equal(report.calls.length,0);assert.deepEqual(jobIds(),priorJobIds);assert.equal(grants(),priorGrants);
 report.correction={material:corrected,read:afterRead,oldObservations,originalTextUnchanged:true,receiptGrantsUnchanged:true,automaticCalls:0,automaticJobsUnchanged:true};await save();
 const current=await request('GET','/api/materials/'+corrected.id);assert.equal(current.memorySource.status,'ready');assert.ok(current.memorySource.evidenceIds.length);
 explicitJobStarted=true;const job=await request('POST','/api/memory-jobs',{recipes:[{id:'mote.personal-memory',version:'2'}],evidenceIds:current.memorySource.evidenceIds,modelProfileId:selected.id,timeZone:'Asia/Shanghai'});report.explicitRequest={recipes:[{id:'mote.personal-memory',version:'2'}],evidenceIds:current.memorySource.evidenceIds,jobId:job.id};await save();
 while(true){report.job=await request('GET','/api/memory-jobs/'+job.id);assert.ok(!['failed','cancelled','waiting_for_model','paused'].includes(report.job.status),'Explicit historical job failed');if(report.job.status==='completed')break;assert.ok(Date.now()-started<maximumDurationMs,'Explicit processing deadline exceeded');await delay(5000);}
 report.memories=report.job.memoryIds.map((id:string)=>node!.memories.get(id));for(const memory of report.memories)for(const span of memory.evidence??[]){const evidence:CaptureRecord|undefined=node!.memories.readEvidence([span.id])[0];assert.ok(evidence);assert.equal(evidence.ocrText.slice(span.offset,span.offset+span.length),span.quote);}
 assert.equal(grants(),priorGrants);assert.deepEqual(jobIds(),[...priorJobIds,job.id].sort());report.explicitHistoricalOnly=true;
 if(process.env.MOTE_ATTRIBUTION_OWNER_QUERY==='1'&&report.calls.length<=4)report.answer=await request('POST','/api/query',{question:'What did I feel during the lantern prototype work, and have I expressed a preference for meetings at dawn?',deviceId:diary.sourceId,timeZone:'Asia/Shanghai'});
 report.status='execution-passed';report.manualReviewRubric='Verify owner-declared diary feelings are retained as selected personal Memory with appropriate uncertainty, exact citations and no transfer of Mira’s quoted dawn-meeting preference. Execution success alone is not semantic acceptance.';
}catch(error){report.status='failed';report.failure=error instanceof Error?error.message:String(error);process.exitCode=1;}
finally{if(node){const receipts=node.store.db.prepare('SELECT id,json FROM model_usage').all().filter(row=>!priorUsageIds.has(String(row.id))).map(row=>JSON.parse(String(row.json)) as UsageReceipt);report.usage=usageTotals(receipts);report.usageScope='Only new receipts from this calibration; inherited paired-vault usage excluded. Request counts may be unknown for cumulative Codex threads; unpriced costs are unknown.';}await node?.app.close();report.finishedAt=new Date().toISOString();await save();console.log(JSON.stringify({status:report.status,report:join(output,'report.json'),semanticQualityAccepted:false}));}
