/** Independent generated plumbing only; never reads heldout semantic files. */
import {test,after} from 'node:test';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import type {QueryInput,ContextReader} from '@mote/agent';
import type {QueryResult} from '@mote/shared';
import {sha256} from '../apps/server/src/store.js';
import {base,check,equal,cloneClosed,ablateClone,json} from './test-heldout-memory-replay.js';
import {AdmissionLedger,StageSafetyError} from './test-heldout-memory-replay-ledger.js';
import {freezeStage,newOutput,runBatch,treeHash} from './test-heldout-memory-replay-stage.js';
const root=process.env.MOTE_HELDOUT_TEST_OUTPUT??join(base,'heldout-stage-offline-'+Date.now());await mkdir(root,{mode:0o700});const metadata:Record<string,unknown>={schema:'mote-heldout-stage-mechanical-tests@1',realModelCalls:0,heldoutSemanticInputsRead:false,tests:[]};
const record=async(name:string,value:unknown)=>{(metadata.tests as unknown[]).push({name,...value as object});await writeFile(join(root,'ROOT_SAFE_tests.json'),json(metadata),{mode:0o600});};
async function setup(name:string){const output=await newOutput(join(root,name+'-freeze'));const manifest=await freezeStage(output,true),manifestHash=sha256(await readFile(join(output,'ROOT_SAFE_manifest.json')));return {manifest,manifestHash,ledgerDirectory:join(root,name+'-ledger')};}
function stub(options:{failure?:'extract'|'review';empty?:boolean;invalid?:boolean;timeout?:boolean;count:{value:number}}){return async(reader:ContextReader,input:QueryInput):Promise<QueryResult>=>{options.count.value++;input.onTrace?.({type:'model.started',payload:{}});input.onUsage?.({measurement:'thread_cumulative',complete:false,requests:0,reportedRequests:0,inputTokens:11,outputTokens:7,totalTokens:18});if(options.timeout)return new Promise((_resolve,reject)=>input.signal!.addEventListener('abort',()=>reject(new Error('Independent generated timeout marker')),{once:true}));if(input.traceContext?.phase===options.failure)throw new Error('Independent generated failure marker');
  input.onUsage?.({measurement:'thread_cumulative',complete:true,requests:0,reportedRequests:0,inputTokens:11,outputTokens:7,totalTokens:18});if(options.empty)return {answer:'{"memories":[]}',citations:[],trace:[],runId:randomUUID()};if(options.invalid)return {answer:'invalid generated mechanical output',citations:[],trace:[],runId:randomUUID()};
  const evidence=await reader.evidence({ids:input.evidenceIds!});check(evidence.length>0,'mechanical_evidence_missing');const original=evidence[0];const common={domain:input.traceContext?.batchIndex===1?'coding':'personal',...(input.traceContext?.batchIndex===1?{coding:{kind:'decision',scope:'session',applicability:'Independent generated fixture only',validation:'observed'}}:{}),title:'Mechanical fixture',statement:'Literal generated plumbing marker '+input.traceContext?.batchIndex+' ['+original.id+']',uncertainty:'Independent mechanical fixture only.',admission:{layer:'memory',reason:'Mechanical fixture',scope:'Independent fixture',attribution:'observed'},evidenceIds:[original.id],evidence:[{id:original.id,quote:original.ocrText}]};
  return {answer:JSON.stringify({memories:[common]}),citations:[{id:original.id,capturedAt:original.capturedAt,appName:original.appName,excerpt:original.ocrText}],trace:[],runId:randomUUID()};};}
test('two clean batches continue from closed clone without repeating completed work',async()=>{const setupData=await setup('resume'),count={value:0},fn=stub({count});const first=await runBatch({...setupData,output:await newOutput(join(root,'resume-stage1')),stub:fn});check(first.succeeded,'mechanical_first_stage_failed');equal(count.value,2,'mechanical_first_calls');const hash=await treeHash(first.snapshot);const second=await runBatch({...setupData,parent:first.snapshot,index:1,output:await newOutput(join(root,'resume-stage2')),stub:fn});check(second.succeeded,'mechanical_resume_failed');equal(count.value,3,'mechanical_resume_calls');equal(second.report.cumulative.admitted,3,'mechanical_cumulative_calls');equal(second.report.terminalUsage.inherited,2,'mechanical_inherited_receipts');equal(await treeHash(first.snapshot),hash,'mechanical_parent_mutated');
  const a=join(root,'ablation-a'),b=join(root,'ablation-b');await cloneClosed(second.snapshot,a);await cloneClosed(second.snapshot,b);const removed=ablateClone(a,true),retained=ablateClone(b,false);equal(removed.protectedHash,retained.protectedHash,'mechanical_nonempty_ablation_protected');const db=new DatabaseSync(join(b,'mote.sqlite'),{readOnly:true});const memories=Number(db.prepare('SELECT count(*) n FROM memories').get()!.n);db.close();check(memories>0,'mechanical_ablation_empty');await record('pause-close-clone-resume',{passed:true,stubCalls:count.value,cumulative:second.report.cumulative,inheritedReceipts:2,crossRecipeGenerationDraftReused:true,secondStageReviewCalls:1,nonemptyAblation:{cards:memories,protectedTables:removed.protectedTables},snapshotImmutable:true});});
for(const phase of ['extract','review'] as const)test(phase+' failure stops subsequent provider calls and restart',async()=>{const data=await setup('failure-'+phase),count={value:0};const result=await runBatch({...data,output:await newOutput(join(root,'failure-'+phase+'-stage')),stub:stub({count,failure:phase})});check(!result.succeeded,'mechanical_failure_not_stopped');equal(count.value,phase==='extract'?1:2,'mechanical_failure_later_call');check(result.report.cumulative.stopped&&result.report.cumulative.failed===1,'mechanical_failure_ledger');let blocked=false;try{new AdmissionLedger(data.ledgerDirectory,data.manifest.experimentHash);}catch(error){blocked=error instanceof StageSafetyError&&error.code==='ledger_persistently_stopped';}check(blocked,'mechanical_failure_restart_allowed');await record('failure-'+phase,{passed:true,stubCalls:count.value,cumulative:result.report.cumulative});});
test('empty draft consumes one outer and leaves spare capacity unused',async()=>{const data=await setup('empty'),count={value:0};const result=await runBatch({...data,output:await newOutput(join(root,'empty-stage')),stub:stub({count,empty:true})});check(result.succeeded,'mechanical_empty_stage_failed');equal(count.value,1,'mechanical_empty_budget_reused');await record('empty',{passed:true,stubCalls:count.value,cumulative:result.report.cumulative});});
test('invalid output fails before the pipeline can start a second generation',async()=>{const data=await setup('invalid'),count={value:0};const result=await runBatch({...data,output:await newOutput(join(root,'invalid-stage')),stub:stub({count,invalid:true})});check(!result.succeeded,'mechanical_invalid_not_stopped');equal(count.value,1,'mechanical_invalid_retried');await record('host-validation',{passed:true,stubCalls:count.value,cumulative:result.report.cumulative});});
test('outer deadline stops future admissions',async()=>{const data=await setup('timeout'),count={value:0};const result=await runBatch({...data,output:await newOutput(join(root,'timeout-stage')),stub:stub({count,timeout:true}),perOuterMs:10});check(!result.succeeded,'mechanical_timeout_not_stopped');equal(count.value,1,'mechanical_timeout_retried');await record('deadline',{passed:true,stubCalls:count.value,cumulative:result.report.cumulative});});
test('admitted interruption or successful outer without committed stage cannot be retried',async()=>{for(const terminal of [false,true]){const directory=join(root,'interrupted-'+terminal);const ledger=new AdmissionLedger(directory,'mechanical-manifest');ledger.begin('mechanical-stage','mechanical-parent',2);const id=ledger.reserve('logical-key','input-hash','receipt-id');if(terminal)ledger.terminal(id,'completed','ok',{modelRunStarts:null,repairs:null});ledger.close();let blocked=false;try{new AdmissionLedger(directory,'mechanical-manifest');}catch(error){blocked=error instanceof StageSafetyError&&error.code==='unknown_interrupted_stage';}check(blocked,'mechanical_unknown_replayed');}await record('interruption',{passed:true,stubCalls:0,cases:2,unknownBlocksResume:true});});
test('stage success requires a final usage receipt for every admission',async()=>{const directory=join(root,'missing-receipt'),ledger=new AdmissionLedger(directory,'mechanical-manifest');ledger.begin('mechanical-stage','mechanical-parent',2);const id=ledger.reserve('logical-key','input-hash','receipt-id');ledger.terminal(id,'completed','ok',{modelRunStarts:null,repairs:null});let blocked=false;try{ledger.finish('snapshot',true);}catch(error){blocked=error instanceof StageSafetyError&&error.code==='admission_receipt_unknown';}check(blocked,'mechanical_missing_receipt_success');ledger.close();await record('missing-receipt',{passed:true,stubCalls:0});});

test('executor upgrade keeps experiment identity and all existing admissions',async()=>{const path=join(root,'executor-upgrade'),ledger=new AdmissionLedger(path,'stable-experiment');ledger.bindExecutor('executor-one');ledger.begin('stage-one','parent-one',2);const id=ledger.reserve('first','input','receipt');ledger.terminal(id,'completed','ok',{modelRunStarts:1,repairs:0});ledger.receipts([{id:'receipt',status:'completed'}]);ledger.finish('checkpoint-one',true);ledger.close();const next=new AdmissionLedger(path,'stable-experiment');let blocked=false;try{next.bindExecutor('executor-two');}catch(error){blocked=error instanceof StageSafetyError&&error.code==='executor_transition_not_validated';}check(blocked,'mechanical_unvalidated_upgrade');next.bindExecutor('executor-two','executor-one','a'.repeat(64));check(next.summary().admitted===1,'mechanical_upgrade_reset_calls');next.close();await record('executor-upgrade',{passed:true,stubCalls:0,retainedAdmissions:1});});

for(const receiptStatus of ['running','failed'] as const)test('terminal receipt '+receiptStatus+' cannot commit a successful stage',async()=>{const path=join(root,'receipt-'+receiptStatus),ledger=new AdmissionLedger(path,'mechanical');ledger.begin('stage','parent',2);const id=ledger.reserve('logical','input','receipt');ledger.terminal(id,'completed','ok',{modelRunStarts:1,repairs:0});ledger.receipts([{id:'receipt',status:receiptStatus}]);let code='';try{ledger.finish('snapshot',true);}catch(error){code=error instanceof StageSafetyError?error.code:'other';}equal(code,receiptStatus==='running'?'admission_receipt_unknown':'terminal_receipt_conflict','mechanical_receipt_gate_wrong');check(receiptStatus==='running'?ledger.summary().unreconciledReceipts===1:ledger.summary().terminalReceiptConflicts===1,'mechanical_receipt_unknown_hidden');ledger.close();await record('receipt-'+receiptStatus,{passed:true,stubCalls:0});});
test('duplicate logical phase is refused before a second provider admission',async()=>{const path=join(root,'duplicate-phase'),ledger=new AdmissionLedger(path,'mechanical');ledger.begin('stage','parent',2);const id=ledger.reserve('same-batch-extract','input','receipt1');ledger.terminal(id,'completed','ok',{modelRunStarts:1,repairs:0});let code='';try{ledger.reserve('same-batch-extract','input','receipt2');}catch(error){code=error instanceof StageSafetyError?error.code:'other';}equal(code,'outer_retry_forbidden','mechanical_phase_guard');ledger.rejectedReceipts([{id:'receipt2',status:'failed'}]);check(ledger.summary().admitted===1&&ledger.summary().hostRejectedReceipts===1&&ledger.summary().stopped,'mechanical_phase_ledger_wrong');ledger.close();await record('duplicate-phase',{passed:true,stubCalls:0,admissions:1,hostRejectedReceipt:1});});

after(async()=>{metadata.status=(metadata.tests as unknown[]).length===12?'passed':'incomplete';metadata.stubModelCalls=(metadata.tests as Array<{stubCalls:number}>).reduce((sum,row)=>sum+row.stubCalls,0);metadata.testCount=(metadata.tests as unknown[]).length;await writeFile(join(root,'ROOT_SAFE_tests.json'),json(metadata),{mode:0o600});});
