/** Independent generated sources only. No heldout text, question, or live provider is read. */
import {after,test} from 'node:test';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import type {ContextReader,QueryInput} from '@mote/agent';
import type {QueryResult} from '@mote/shared';
import {sha256} from '../apps/server/src/store.js';
import {base,check,equal,json,SafeFailure} from './test-heldout-memory-replay.js';
import {StageSafetyError} from './test-heldout-memory-replay-ledger.js';
import {freezeStage,freezeContinuation,newOutput,runBatch,treeHash,codeHashes,executorPins,experimentHash,type Manifest} from './test-heldout-memory-replay-stage.js';
const root=process.env.MOTE_HELDOUT_TEST_OUTPUT??join(base,'heldout-continuation-offline-'+Date.now());await mkdir(root,{mode:0o700});const checks:unknown[]=[];let calls=0,emptyCalls=0;
const frozen=await newOutput(join(root,'mechanical-seed')),initial=await freezeStage(frozen,true,2),initialPath=join(frozen,'ROOT_SAFE_manifest.json'),ledgerDirectory=join(root,'ledger'),validation=join(root,'ROOT_SAFE_validation-fixture.json');
const hashes=executorPins(await codeHashes());await writeFile(validation,json({schema:'mote-heldout-continuation-validation@1',status:'passed',realModelCalls:0,heldoutSemanticInputsRead:false,executorCodeHashes:hashes,note:'Mechanical validator-shape fixture; final suite verdict is ROOT_SAFE_continuation.json.'}));
const stub=async(reader:ContextReader,input:QueryInput):Promise<QueryResult>=>{calls++;input.onTrace?.({type:'model.started',payload:{}});input.onUsage?.({measurement:'thread_cumulative',complete:true,requests:0,reportedRequests:0,inputTokens:13,outputTokens:5,totalTokens:18});const evidence=await reader.evidence({ids:input.evidenceIds!});check(evidence.length===1,'continuation_fixture_evidence');const original=evidence[0],index=input.traceContext!.batchIndex!,coding=(initial.batchPlan[index].recipe as {id:string}).id==='mote.coding-memory';return {answer:JSON.stringify({memories:[{domain:coding?'coding':'personal',...(coding?{coding:{kind:'decision',scope:'session',applicability:'Independent generated plumbing fixture',validation:'observed'}}:{}),title:'Mechanical continuation fixture',statement:'Generated marker for batch '+index+' ['+original.id+']',uncertainty:'Mechanical fixture only',admission:{layer:'memory',scope:'Mechanical fixture',reason:'Checkpoint plumbing only',attribution:'observed'},evidenceIds:[original.id],evidence:[{id:original.id,quote:original.ocrText}]}]}),citations:[{id:original.id,capturedAt:original.capturedAt,appName:original.appName,excerpt:original.ocrText}],trace:[],runId:randomUUID()};};
let first:Awaited<ReturnType<typeof runBatch>>,latest:Awaited<ReturnType<typeof runBatch>>;let latestManifest=initialPath;
const ledgerHash=async()=>sha256(await readFile(join(ledgerDirectory,'admissions.ndjson')));
async function rejection(name:string,args:Partial<Parameters<typeof freezeContinuation>[0]>,expected:string){const before=await ledgerHash(),parentHash=await treeHash(first.snapshot),count=calls;let code='';try{await freezeContinuation({previousManifest:initialPath,parent:first.snapshot,index:1,ledgerDirectory,validation,output:await newOutput(join(root,name)),...args});}catch(error){code=error instanceof SafeFailure||error instanceof StageSafetyError?error.code:'unknown';}equal(code,expected,'continuation_rejection_code');equal(await ledgerHash(),before,'rejection_mutated_ledger');equal(await treeHash(first.snapshot),parentHash,'rejection_mutated_parent');equal(calls,count,'rejection_called_provider');checks.push({name,passed:true,code,admissions:0});}
test('initial single batch creates a clean shared checkpoint',async()=>{first=await runBatch({manifest:initial,manifestHash:sha256(await readFile(initialPath)),output:await newOutput(join(root,'first-stage')),ledgerDirectory,stub});check(first.succeeded,'continuation_fixture_first_failed');equal(calls,2,'continuation_initial_calls');checks.push({name:'initial',passed:true,cumulative:calls});});
test('wrong parent and skipped/repeated indices leave ledger and snapshot unchanged',async()=>{await rejection('wrong-parent',{parent:initial.seed},'resume_parent_not_latest_checkpoint');await rejection('skip-index',{index:2},'resume_index_not_next');await rejection('repeat-index',{index:0},'resume_index_not_next');});
test('different production pins cannot migrate into the experiment',async()=>{const fake:Manifest=structuredClone(initial);fake.codeHashes['apps/server/src/app.ts']='0'.repeat(64);fake.experimentHash=experimentHash(fake);const path=join(root,'ROOT_SAFE_wrong-production.json');await writeFile(path,json(fake));await rejection('wrong-production',{previousManifest:path},'continuation_production_pins_changed');});
test('executor must refer to the actual latest manifest and matching offline report',async()=>{const fake:Manifest={...initial,revision:initial.revision+'-mechanical-change'},path=join(root,'ROOT_SAFE_wrong-executor.json');await writeFile(path,json(fake));await rejection('wrong-executor',{previousManifest:path},'resume_executor_not_latest');const invalid=join(root,'ROOT_SAFE_wrong-validation.json');await writeFile(invalid,json({schema:'mote-heldout-continuation-validation@1',status:'passed',realModelCalls:0,heldoutSemanticInputsRead:false,executorCodeHashes:{}}));await rejection('wrong-validation',{validation:invalid},'continuation_validation_wrong_executor');});
test('two consecutive clean resumptions keep experiment, usage, and generation drafts',async()=>{latest=first;const originalHash=await treeHash(first.snapshot),initialBytes=await readFile(initialPath),ledgerPrefix=await readFile(join(ledgerDirectory,'admissions.ndjson'));const counts:number[]=[];
  for(const index of [1,2]){const output=await newOutput(join(root,'executor-'+index)),before=await ledgerHash(),parentHash=await treeHash(latest.snapshot),next=await freezeContinuation({previousManifest:latestManifest,parent:latest.snapshot,index,ledgerDirectory,validation,output});equal(await ledgerHash(),before,'freeze_changed_ledger');equal(next.experimentHash,initial.experimentHash,'continuation_reset_experiment');const path=join(output,'ROOT_SAFE_manifest.json'),result=await runBatch({manifest:next,manifestHash:sha256(await readFile(path)),output:await newOutput(join(root,'stage-'+index)),ledgerDirectory,stub});check(result.succeeded,'continuation_stage_failed');equal(result.report.terminalUsage.inherited,index===1?2:4,'continuation_inherited_usage');equal(await treeHash(latest.snapshot),parentHash,'continuation_parent_mutated');counts.push(result.report.stubModelCalls);latest=result;latestManifest=path;}
  check((await readFile(join(ledgerDirectory,'admissions.ndjson'))).subarray(0,ledgerPrefix.length).equals(ledgerPrefix),'continuation_ledger_prefix_changed');equal(counts,[2,1],'continuation_draft_not_reused');equal(calls,5,'continuation_total_calls');equal(latest.report.cumulative.admitted,5,'continuation_ledger_reset');equal(latest.report.cumulative.receipts,5,'continuation_receipts_not_deduped');equal(await treeHash(first.snapshot),originalHash,'first_checkpoint_changed');equal(sha256(await readFile(initialPath)),sha256(initialBytes),'initial_manifest_changed');checks.push({name:'two-resumes',passed:true,stageCalls:counts,cumulative:latest.report.cumulative,initialSnapshotUnchanged:true,originalManifestUnchanged:true,priorLedgerBytesUnchanged:true,generationDraftReused:true});});
test('an earlier successful checkpoint cannot roll back later admitted work',async()=>{const before=await ledgerHash();let code='';try{await freezeContinuation({previousManifest:latestManifest,parent:first.snapshot,index:3,ledgerDirectory,validation,output:await newOutput(join(root,'rollback-rejection'))});}catch(error){code=error instanceof SafeFailure||error instanceof StageSafetyError?error.code:'unknown';}equal(code,'resume_parent_not_latest_checkpoint','continuation_rollback_not_blocked');equal(await ledgerHash(),before,'rollback_changed_ledger');checks.push({name:'rollback',passed:true,code,admissions:0});});
test('a cached empty batch pauses cleanly with zero new outer admissions',async()=>{const seedOutput=await newOutput(join(root,'empty-seed')),seed=await freezeStage(seedOutput,true,2),emptyLedger=join(root,'empty-ledger');let previous=join(seedOutput,'ROOT_SAFE_manifest.json');const empty=async():Promise<QueryResult>=>{emptyCalls++;return {answer:'{"memories":[]}',citations:[],trace:[],runId:randomUUID()};};let m=seed,result:Awaited<ReturnType<typeof runBatch>>|undefined;const admissions:number[]=[];
  for(const index of [0,1,2]){if(index){const frozen=await newOutput(join(root,'empty-executor-'+index));m=await freezeContinuation({previousManifest:previous,parent:result!.snapshot,index,ledgerDirectory:emptyLedger,validation,output:frozen});previous=join(frozen,'ROOT_SAFE_manifest.json');}result=await runBatch({manifest:m,manifestHash:sha256(await readFile(previous)),output:await newOutput(join(root,'empty-stage-'+index)),ledgerDirectory:emptyLedger,stub:empty});check(result.succeeded,'empty_continuation_stage_failed');admissions.push(result.report.stubModelCalls);}
  equal(admissions,[1,1,0],'empty_continuation_spent_spare_budget');equal(result!.report.terminalBatchCounts,{completed:3,total:4},'empty_continuation_ran_next_batch');checks.push({name:'cached-empty-boundary',passed:true,stageCalls:admissions,cumulative:result!.report.cumulative,remainingBatchPending:true});});
after(async()=>{await writeFile(join(root,'ROOT_SAFE_continuation.json'),json({schema:'mote-heldout-continuation-validation@1',status:checks.length===10?'passed':'incomplete',checks,realModelCalls:0,stubModelCalls:calls+emptyCalls,heldoutSemanticInputsRead:false,executorCodeHashes:executorPins(await codeHashes())}),{mode:0o600});});
