/** Bounded current-contract input-context comparison through real HTTP startup and
 * automatic background work. No old-code baseline and no semantic pass claim. */
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {join,relative,resolve} from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
import {execFileSync} from 'node:child_process';
import {z} from 'zod';
import {buildApp} from '../apps/server/src/app.js';
import {safeError} from '../apps/server/src/diagnostics.js';
import {AgentYieldError} from '@mote/agent';
import {repositoryRoot,type Config} from '../apps/server/src/config.js';
import {codexModels} from '../apps/server/src/model-catalog.js';
import {sha256} from '../apps/server/src/store.js';
import {usageTotals} from '../apps/server/src/usage.js';
import type {UsageReceipt} from '@mote/shared';
const recordSchema=z.object({key:z.string().min(1).max(80),text:z.string().min(1).max(12000),declared:z.enum(['owner','third_party','mixed','unknown']),question:z.string().min(1).max(2000),rubric:z.string().min(1).max(4000)}).strict();
const manifestSchema=z.object({personalDataUsed:z.boolean(),selectionMethod:z.string(),records:z.array(recordSchema).min(3).max(3)}).strict();
const generated={personalDataUsed:false,selectionMethod:'Three generated paired attribution journeys',records:[
 {key:'unknown-diary',declared:'unknown',text:'My diary, October 1: After debugging the lantern prototype for hours I felt exhausted. When my family tried it for the first time, I felt proud and happy. These are my feelings, not a verified claim about the prototype. My colleague Mira said, "I prefer meetings at dawn." I have not stated a meeting-time preference.',question:'What did I feel during the lantern prototype work, and have I expressed a preference for meetings at dawn?',rubric:'Preserve exhaustion and pride/happiness as owner subjective experiences even with unknown attribution. Do not transfer Mira\'s dawn meeting preference to owner.'},
 {key:'external-first-person',declared:'third_party',text:'External published article by researcher Mira, saved for reference: "I prefer meetings at dawn. I use region-level pricing for my shop because it stabilizes local demand." The archive owner has not expressed agreement with these views.',question:'Who prefers meetings at dawn and uses region-level pricing, and what reason does the article give? Have I endorsed these preferences?',rubric:'External body remains retrievable and article content accurate. No owner subjective Memory from Mira\'s first-person claims; no endorsement inferred.'},
 {key:'owner-interview-activity',declared:'mixed',text:'I asked an assistant to transcribe researcher Mira\'s interview. I received the completed transcript at generated://lantern/interview-transcript.md and saved it for later reference. Interview quotation: Mira said, "I favor user-level pricing after region-level pricing caused unstable demand." I have not adopted Mira\'s pricing opinion.',question:'What did I do with Mira\'s interview, what outcome was recorded, and where can I find the transcript? What pricing view did Mira express?',rubric:'Owner activity/outcome and exact artifact locator remain discoverable as an observation or original evidence. Quoted pricing view attributed to Mira, not owner preference/expertise.'}
]};
function external(path:string){const absolute=resolve(path),part=relative(repositoryRoot,absolute);assert.ok(part==='..'||part.startsWith('../'),'Reports, manifests and vaults must stay outside Git');return absolute;}
const mode=process.env.MOTE_ATTRIBUTION_MODE??'offline';assert.ok(['offline','live'].includes(mode));
assert.ok(process.env.MOTE_ATTRIBUTION_OUTPUT,'Set a fresh MOTE_ATTRIBUTION_OUTPUT outside Git');
const manifestBytes=process.env.MOTE_ATTRIBUTION_MANIFEST?await readFile(external(process.env.MOTE_ATTRIBUTION_MANIFEST)):Buffer.from(JSON.stringify(generated));
const manifest=manifestSchema.parse(JSON.parse(manifestBytes.toString()));assert.equal(new Set(manifest.records.map(r=>r.key)).size,3);
const directory=external(process.env.MOTE_ATTRIBUTION_OUTPUT),recover=process.env.MOTE_ATTRIBUTION_RECOVER==='1';
if(recover){assert.equal(await readFile(join(directory,'manifest.json'),'utf8'),manifestBytes.toString(),'Recovery manifest must match the original bytes');}
else{await mkdir(directory,{mode:0o700});await writeFile(join(directory,'manifest.json'),manifestBytes,{flag:'wx',mode:0o600});}
const model=process.env.MOTE_TEST_CODEX_MODEL??'gpt-6.1-sol',effort=process.env.MOTE_TEST_CODEX_EFFORT??'high',serviceTier='fast',perCallTimeoutMs=900000;
let started=Date.now();const maxDurationMs=90*60*1000,maxCalls=48,token=randomBytes(32).toString('hex');
const freshReport:Record<string,any>={schema:'mote-attribution-context-comparison@1',budgetStartedAt:new Date(started).toISOString(),mode,comparison:'same current code: no declaration versus explicit source declaration',oldCodeBaseline:false,personalDataUsed:manifest.personalDataUsed,selectionMethod:manifest.selectionMethod,manifestSha256:sha256(manifestBytes),model,reasoningEffort:effort,serviceTier,perCallTimeoutMs,uniformModelConfiguration:true,rerunReason:process.env.MOTE_ATTRIBUTION_RERUN_REASON??null,maximumOuterCalls:maxCalls,maximumDurationMs:maxDurationMs,automaticOuterRetries:0,runnerRequestRetries:0,productInternalRetries:'Existing product query/delegation retries are possible; each instrumented agent.query call counts against this budget.',semanticQualityAccepted:false,heldOut:false,browserTested:false,physicalDeviceTested:false,screenshotsUsed:false,fixtureScope:'Automatic source HTTP ingress, background Material/Memory work, queries and restart. Offline stubs prove plumbing only.',head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),calls:[],arms:[],status:'running'};
const report:Record<string,any>=recover?JSON.parse(await readFile(join(directory,'report.json'),'utf8')):freshReport;
if(recover){started=Date.parse(report.budgetStartedAt??report.arms[0]?.startedAt??report.calls[0]?.startedAt);assert.ok(Number.isFinite(started),'Recovery requires an original budget start time');report.budgetStartedAt=new Date(started).toISOString();assert.equal(report.mode,mode);assert.equal(report.manifestSha256,sha256(manifestBytes));const prior={model:report.model,reasoningEffort:report.reasoningEffort,serviceTier:report.serviceTier??'default',perCallTimeoutMs:report.perCallTimeoutMs??300000};const changed=JSON.stringify(prior)!==JSON.stringify({model,reasoningEffort:effort,serviceTier,perCallTimeoutMs});if(changed){report.configurationChanges??=[];report.configurationChanges.push({at:new Date().toISOString(),prior,next:{model,reasoningEffort:effort,serviceTier,perCallTimeoutMs},reason:process.env.MOTE_ATTRIBUTION_RERUN_REASON??'Owner requested gpt-6.1-sol FAST and 15 minute timeout'});report.uniformModelConfiguration=false;report.comparison='Current-contract execution reference with mixed model configurations; arms are not a uniform paired model comparison';}Object.assign(report,{model,reasoningEffort:effort,serviceTier,perCallTimeoutMs,maximumDurationMs:maxDurationMs});if(report.maximumOuterCalls!==maxCalls){assert.equal(report.maximumOuterCalls,32,'Recovery budget amendment is only permitted from32to48');report.budgetAmendments??=[];report.budgetAmendments.push({at:new Date().toISOString(),previousMaximumOuterCalls:32,maximumOuterCalls:maxCalls,reason:'Explicit owner task completion allowance for existing product delegation/query retries'});report.maximumOuterCalls=maxCalls;}report.runnerRequestRetries=0;report.productInternalRetries=freshReport.productInternalRetries;assert.equal(report.head,freshReport.head,'Recovery must use the same commit');report.recoveries??=[];report.recoveries.push({startedAt:new Date().toISOString(),priorStatus:report.status,priorCalls:report.calls.length});report.status='running';delete report.failure;for(const call of report.calls)if(!call.status)call.status='interrupted_unknown_outcome';}
const offlineGrouping=process.env.MOTE_ATTRIBUTION_OFFLINE_GROUPING??'separate';assert.ok(['separate','grouped'].includes(offlineGrouping));
let node:Awaited<ReturnType<typeof buildApp>>|undefined,base='',writes=Promise.resolve(),restarting=false;
function save(){const data=JSON.stringify(report,null,2)+'\n';writes=writes.then(()=>writeFile(join(directory,'report.json'),data,{mode:0o600}));return writes;}
async function request(method:string,path:string,body?:unknown){assert.ok(Date.now()-started<maxDurationMs,'Run deadline exceeded');const response=await fetch(base+path,{method,headers:{authorization:'Bearer '+token,'content-type':'application/json','x-mote-ingress-version':'2'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(perCallTimeoutMs+10000)});const value=await response.json();assert.ok(response.ok,`${method} ${path}: ${response.status} ${JSON.stringify(value)}`);return value as any;}
async function until(check:()=>Promise<boolean>,label:string){const stop=Date.now()+(mode==='offline'?90000:Math.max(0,started+maxDurationMs-Date.now()));while(!await check()){assert.ok(Date.now()<stop&&Date.now()-started<maxDurationMs,label+' timed out');await delay(5000);}}
function config(vault:string):Config{return {dataKey:undefined,dataDir:vault,token,tokenPath:join(vault,'token'),host:'127.0.0.1',port:0,maxStorageBytes:100_000_000,maxExportBytes:1_000_000,retentionDays:0,insightIntervalHours:0,allowedOrigins:[],model:mode==='live'?model:'generated-attribution-stub',modelProvider:'codex',modelProtocol:'codex-app-server',modelReasoningEffort:effort as Config['modelReasoningEffort'],modelBaseUrl:'',apiKey:'',allowUnauthenticatedLocal:false,embeddingModel:'',embeddingBaseUrl:'',embeddingApiKey:'',agentTimeoutMs:perCallTimeoutMs,codexBin:process.env.MOTE_CODEX_BIN,codexHome:process.env.MOTE_CODEX_HOME,memoryConcurrency:1,diagnosticsEnabled:true,agentTraceEnabled:true,logLevel:'warn'};}
async function open(vault:string){
 const stub=async(input:any)=>{if(!input.traceContext?.phase)return {answer:'Generated offline query response; semantic quality has not been tested.',citations:[],trace:[],runId:randomBytes(16).toString('hex')};const {fixtureMemoryPlan,fixtureMemoryWorkResult}=await import('../apps/server/test/fixtures/memory-planning.js');const catalog=input.taskContext?.memoryWork?.catalog;if(catalog&&offlineGrouping==='grouped'){await input.hostControlChannel.execute('delegation_submit',{units:[{id:'generated-group',capabilityId:'memory.package',title:'Generated grouped originals',goal:'Inspect all generated originals',input:{members:catalog.map((member:any)=>member.key),instruction:'Inspect every generated original preserving attribution'}}]});return {answer:'Generated grouped package submitted.',citations:[],trace:[],runId:'generated-grouped-plan'};}const plan=await fixtureMemoryPlan(input);if(plan)return plan;return fixtureMemoryWorkResult(input,{answer:input.traceContext?.phase?JSON.stringify({memories:[]}):'Generated offline query response; semantic quality has not been tested.',citations:[],trace:[],runId:randomBytes(16).toString('hex')});};
 node=await buildApp(config(vault),{...(mode==='offline'?{agent:{configured:true,close:async()=>{},query:stub}}:{})});
 const settings=node.lifecycle.settings();for(const id of ['working','consolidation','insights'] as const)settings[id].enabled=false;node.lifecycle.configure(settings);await node.app.listen({host:'127.0.0.1',port:0});base=node.app.listeningOrigin!;
 if(mode==='live'){
  let view=await request('GET','/api/model-settings');
  const settings={provider:'codex',protocol:'codex-app-server',baseUrl:'',model,reasoningEffort:effort,maxTokens:8192,serviceTier,modelRequestTimeoutMs:null,agentTimeoutMs:perCallTimeoutMs,allowUnauthenticatedLocal:false,apiKey:null,headers:null,extraBody:null};
  const prior=view.profiles.find((profile:any)=>profile.id==='attribution-fast');
  if(!prior||Object.entries(settings).filter(([key])=>!['apiKey','headers','extraBody'].includes(key)).some(([key,value])=>(prior.settings[key]??null)!==value))view=await request('PUT','/api/model-settings/profiles/attribution-fast',{revision:view.revision,name:'Isolated attribution evaluation FAST',settings});
  const defaults=Object.fromEntries(Object.keys(view.defaults).map(feature=>[feature,'attribution-fast']));
  if(Object.values(view.defaults).some(id=>id!=='attribution-fast')||Object.keys(view.defaultModels??{}).length)view=await request('PUT','/api/model-settings/defaults',{revision:view.revision,defaults,defaultModels:{}});
  report.modelSelections??=[];report.modelSelections.push({arm:report.currentArm,at:new Date().toISOString(),revision:view.revision,defaults:view.defaults,profile:node.modelSettings.select('memory')});await save();
 }
 const query=node.agent.query.bind(node.agent);node.agent.query=async(input:any)=>{assert.ok(!restarting,'Restart unexpectedly replayed model work');assert.ok(report.calls.length<maxCalls,'Outer model call budget exceeded');assert.ok(Date.now()-started<maxDurationMs);const call:any={phase:input.traceContext?.phase??'query',startedAt:new Date().toISOString(),arm:report.currentArm,stub:mode==='offline',modelSelection:node!.modelSettings.select(input.traceContext?.phase?'memory':'chat',input.modelProfileId),serviceTier,perCallTimeoutMs};if(input.modelOverride)call.modelSelection.settings.model=input.modelOverride;if(mode==='live'){assert.equal(call.modelSelection.settings.model,model);assert.equal(call.modelSelection.settings.serviceTier,'fast');assert.equal(call.modelSelection.settings.agentTimeoutMs,perCallTimeoutMs);}call.backendTierConfirmation={requested:serviceTier,adapter:'CodexSession checks normalized thread.serviceTier at thread start',confirmed:'unknown'};report.calls.push(call);await save();console.log(JSON.stringify({stage:'model-start',call:report.calls.length,phase:call.phase,arm:call.arm}));try{const result=await query(input);call.runId=result.runId;call.status='completed';call.backendTierConfirmation.confirmed=mode==='live';return result;}catch(error){const yielded=error instanceof AgentYieldError;call.status=yielded?'yielded':'failed';call.error=yielded?{name:'AgentYieldError',category:'control_yield',message:'Coordinator yielded to durable delegated work'}:{name:error instanceof Error?error.name:'UnknownError',...safeError(error)};throw error;}finally{call.durationMs=Date.now()-Date.parse(call.startedAt);await save();}};
}
async function close(){if(node){await node.app.close();node=undefined;}}
try{
 if(mode==='live'){assert.equal(model,'gpt-6.1-sol','Owner requested all future live runs use gpt-6.1-sol');const catalog=await codexModels(undefined,{executable:process.env.MOTE_CODEX_BIN,home:process.env.MOTE_CODEX_HOME});report.catalog=catalog.items.find(item=>item.id===model);assert.ok(report.catalog?.reasoningEfforts?.includes(effort),'Model/effort absent from local Codex Server catalog');}
 for(const arm of ['no-declaration','declared'] as const){
  let entry:any=report.arms.find((entry:any)=>entry.arm===arm);if(entry?.finishedAt&&entry.restartNoReplay)continue;report.currentArm=arm;const vault=join(directory,arm,'vault');await open(vault);if(!entry){entry={arm,vault,records:[],startedAt:new Date().toISOString()};report.arms.push(entry);}await save();
  for(const record of manifest.records){if(entry.records.some((saved:any)=>saved.key===record.key))continue;const sourceId='generated-'+record.key;await request('POST','/api/sources',{id:sourceId,name:record.key,kind:'custom',deviceId:sourceId,platform:'import',retention:'archive',...(arm==='declared'?{ownerRelation:record.declared}:{})});
   // Test-only timing override; the real registered source pipeline still schedules every stage.
   node!.sourcePipelines.configure(sourceId,{settleSeconds:0});
   const body={externalId:record.key,revision:sha256(record.text),observedAt:new Date().toISOString(),text:record.text,kind:'file',layer:'original',document:{contentRole:'authored',recordedAt:'2026-10-01T08:00:00Z'}};
   const ack=await request('PUT',`/api/sources/${sourceId}/items`,body);const again=await request('PUT',`/api/sources/${sourceId}/items`,body);assert.equal(again.duplicate,true);assert.equal(again.id,ack.id);entry.records.push({key:record.key,sourceId,captureId:ack.id,textSha256:sha256(record.text),rubric:record.rubric});await save();
  }
  await until(async()=>{const summaries=(await request('GET','/api/memory-jobs?limit=100')).items;assert.ok(!summaries.some((job:any)=>['failed','cancelled','waiting_for_model'].includes(job.status)),'Automatic job failed');if(!summaries.length||summaries.some((job:any)=>job.status!=='completed'))return false;entry.jobs=await Promise.all(summaries.map((job:any)=>request('GET','/api/memory-jobs/'+job.id)));assert.ok(!entry.jobs.some((job:any)=>['failed','cancelled','waiting_for_model'].includes(job.status)),'Automatic job failed');const covered=new Set(entry.jobs.filter((job:any)=>job.status==='completed').flatMap((job:any)=>(job.materialInputs??[]).map((input:any)=>input.materialId)));const materials=await Promise.all(entry.records.map((record:any)=>request('GET','/api/materials?sourceId='+record.sourceId)));return materials.every((page:any)=>page.items.length&&page.items.every((material:any)=>covered.has(material.id)))&&entry.jobs.every((job:any)=>job.status==='completed');},'automatic extraction and independent review of every material');await save();
  for(const record of entry.records){const material=(await request('GET','/api/materials?sourceId='+record.sourceId)).items[0];assert.ok(material);record.material=material;const read=await request('GET',`/api/materials/${material.id}/read?revision=${material.revision}&length=12000`);record.read=read;assert.ok(read.text.length>0);
   const original=manifest.records.find(r=>r.key===record.key)!;if(!record.answer){record.answer=await request('POST','/api/query',{question:original.question,deviceId:record.sourceId,timeZone:'Asia/Shanghai'});await save();}
   record.memories=entry.jobs.filter((job:any)=>job.materialInputs?.some((input:any)=>input.materialId===material.id)).flatMap((job:any)=>(job.memoryIds??[]).map((id:string)=>node!.memories.get(id))).filter((memory:any)=>memory.evidenceIds.some((id:string)=>node!.memories.dependencyIds(id).includes(record.captureId)));
   for(const memory of record.memories)for(const span of memory.evidence??[]){const evidence=node!.memories.readEvidence([span.id])[0];assert.ok(evidence);assert.equal(evidence.ocrText.slice(span.offset,span.offset+span.length),span.quote);}
  }
  const products=JSON.stringify(node!.memories.list({includeHistory:true})),callCount=report.calls.length;entry.usage=usageTotals(node!.store.db.prepare('SELECT json FROM model_usage').all().map(row=>JSON.parse(String(row.json)) as UsageReceipt));await close();restarting=true;await open(vault);await delay(6000);assert.equal(report.calls.length,callCount);assert.equal(JSON.stringify(node!.memories.list({includeHistory:true})),products);entry.restartNoReplay=true;await close();restarting=false;entry.finishedAt=new Date().toISOString();await save();
 }
 report.status='execution-passed';report.metricsToReview=['False owner-memory attribution','Owner subjective-memory retention with unknown declaration','External-body retrieval and answer accuracy','Owner activity/outcome/locator discovery','Citation validity','Per-arm latency, calls and usage'];
}catch(error){report.status='failed';report.failure=error instanceof Error?error.message:String(error);process.exitCode=1;}
finally{await close();report.finishedAt=new Date().toISOString();await save();console.log(JSON.stringify({stage:'finished',status:report.status,report:join(directory,'report.json'),semanticQualityAccepted:false}));}
