/** Generated SourceItem/Material fixture only; never opens the heldout dataset or ledger. */
import {test,after} from 'node:test';
import {mkdir,writeFile,readFile,cp} from 'node:fs/promises';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {AgentTimeoutError,type ContextReader,type QueryInput} from '@mote/agent';
import type {QueryResult} from '@mote/shared';
import {UsageLedger} from '../apps/server/src/usage.js';
import {sha256} from '../apps/server/src/store.js';
import {ProviderFailure} from '@mote/shared';
import {base,recipes,check,equal,json,cloneClosed,closed,hashObject,SafeFailure} from './test-heldout-memory-replay.js';
import {openNode,drain,treeHash,type Manifest,freezeStage,newOutput,batchPin,settings,bindings,protectedTables,codeHashes,executorPins,experimentHash} from './test-heldout-memory-replay-stage.js';
import {AdmissionLedger,inspectAdmissionLedger,StageSafetyError,readAdmissionChain,authorizeRecovery,readRecoveryPlan,validateRecoveryPrefix,type RecoveryLineage} from './test-heldout-memory-replay-ledger.js';
import {ref,freezePhase,runPhase,phaseCursor,type WavePlan} from './test-heldout-memory-replay-sequence.js';
import {freezeIntegration,runIntegration} from './test-heldout-memory-replay-integration.js';
import {freezeAsk,runAsk} from './test-heldout-memory-replay-ask.js';
import {prepareNativeSplit,freezeRecovery} from './test-heldout-memory-replay-recovery.js';
const output=process.env.MOTE_HELDOUT_RECOVERY_TEST_OUTPUT??join(base,'heldout-recovery-native-offline-'+Date.now());await mkdir(output,{mode:0o700});const checks:unknown[]=[];let calls=0,bootstrapCalls=0;
const recoverySupervisor=join(base,'run-heldout-phase-v2-supervised.py');
const model:Manifest['model']={provider:'codex',protocol:'codex-app-server',model:'gpt-6-sol',reasoningEffort:'max',codexBin:'/nonexistent-recovery-stub',codexBinHash:'stub',codexHome:'/nonexistent-recovery-home'},time='2025-12-31T23:59:59+08:00';
let failedSnapshot='',canonicalSnapshot='',jobId='',failing=false;let originalRows:any[]=[],frozenSettings='',frozenBindings='',frozenProtected='';let inheritedReceipts:any[]=[],failedReceipt:any;
test('normal generated inputs form six batches; first generation timeout leaves five pending',async()=>{
 const vault=join(output,'generated-seed');let node:Awaited<ReturnType<typeof openNode>>['node'];const stub=async(reader:ContextReader,input:QueryInput):Promise<QueryResult>=>{if(!failing){bootstrapCalls++;input.onUsage?.({measurement:'thread_cumulative',complete:true,requests:0,reportedRequests:0,inputTokens:5,outputTokens:3,totalTokens:8});const source=(await reader.evidence({ids:input.evidenceIds!}))[0];const domain=input.traceContext?.batchIndex===1?'coding':'personal';return {answer:JSON.stringify({memories:[{domain,...(domain==='coding'?{coding:{kind:'decision',scope:'session',applicability:'Generated fixture',validation:'observed'}}:{}),title:'Prior generated fixture',statement:'Prior literal ['+source.id+']',uncertainty:'Generated fixture',admission:{layer:'memory',reason:'Generated fixture',scope:'Fixture',attribution:'observed'},evidenceIds:[source.id],evidence:[{id:source.id,quote:source.ocrText}]}]}),citations:[{id:source.id,capturedAt:source.capturedAt,appName:source.appName,excerpt:source.ocrText}],trace:[],runId:randomUUID()};}calls++;node.memoryPipeline.pause(jobId);input.onUsage?.({measurement:'thread_cumulative',complete:false,requests:0,reportedRequests:0,inputTokens:11,outputTokens:0,totalTokens:11});throw new AgentTimeoutError();};const opened=await openNode(vault,model,time,stub);node=opened.node;
 try{await opened.request('POST','/api/sources',{id:'recovery-fixture',name:'Generated recovery fixture',kind:'custom',deviceId:'generated-recovery',platform:'import',retention:'archive'});
 await opened.request('PUT','/api/sources/recovery-fixture/items',{externalId:'prior-wave',revision:'1',kind:'message',layer:'original',observedAt:'2025-11-01T09:00:00+08:00',text:'Prior generated history literal.',document:{contentRole:'authored',recordedAt:'2025-11-01T09:00:00+08:00',timeBasis:'recorded'}});await drain(node);const priorIds=node.store.db.prepare('SELECT id FROM material_heads WHERE retired=0 ORDER BY id').all().flatMap(row=>node.materials.evidenceIds(node.materials.get(String(row.id))!.ref));const priorJob=node.memoryPipeline.create({evidenceIds:priorIds,recipes,contextTime:'2025-11-30T23:59:59+08:00',timeZone:'Asia/Shanghai',batchCharacters:12000});check((await node.memoryPipeline.run(priorJob.id)).status==='completed','fixture_prior_wave_failed');check(Number(node.store.db.prepare('SELECT count(*) n FROM memories').get()!.n)>0&&Number(node.store.db.prepare('SELECT count(*) n FROM memory_extraction_drafts WHERE shared=1').get()!.n)>0&&Number(node.store.db.prepare('SELECT count(*) n FROM memory_checkpoints').get()!.n)>0,'fixture_nonempty_history_missing');const meters=new UsageLedger(node.store);for(let i=0;i<9;i++){const meter=meters.start('codex','gpt-6-sol','generated-accounting-only');meter.update({complete:true,inputTokens:5,outputTokens:3,totalTokens:8,requests:0,reportedRequests:0});meter.finish('completed');}inheritedReceipts=node.store.db.prepare('SELECT json FROM model_usage ORDER BY created_at,id').all().map(r=>JSON.parse(String(r.json)));equal(inheritedReceipts.length,12,'fixture_inherited_count');failing=true;
 for(let i=0;i<24;i++)await opened.request('PUT','/api/sources/recovery-fixture/items',{externalId:'generated-'+String(i).padStart(2,'0'),revision:'1',kind:'message',layer:'original',observedAt:'2025-12-01T09:00:00+08:00',text:'Generated literal mechanical marker. '.repeat(30),document:{contentRole:'authored',recordedAt:'2025-12-01T09:00:00+08:00',timeBasis:'recorded'}});
 await drain(node);const ids=node.store.db.prepare('SELECT id FROM material_heads WHERE retired=0 ORDER BY id').all().flatMap(row=>node.materials.evidenceIds(node.materials.get(String(row.id))!.ref));const job=node.memoryPipeline.create({evidenceIds:ids.filter(id=>!priorIds.includes(id)),recipes,contextTime:time,timeZone:'Asia/Shanghai',batchCharacters:12000});jobId=job.id;
 const planned=node.store.db.prepare('SELECT json FROM memory_batches WHERE job_id=? ORDER BY idx').all(jobId).map(row=>JSON.parse(String(row.json)));await writeFile(join(output,'ROOT_SAFE_plan-shape.json'),json({batches:planned.length,chunks:planned.map(b=>b.chunks.length),chars:planned.map(b=>b.chunks.map((c:any)=>c.length))}));
 equal(planned.length,6,'fixture_six_batch_plan');equal(planned[0].chunks.length,8,'fixture_first_eight_chunks');
 originalRows=planned;frozenSettings=hashObject(settings(node));frozenBindings=hashObject(bindings(node));frozenProtected=hashObject(protectedTables(node.store.db));node.memoryPipeline.pause(jobId);await node.app.close();await closed(vault);canonicalSnapshot=join(output,'canonical-before-timeout');await cloneClosed(vault,canonicalSnapshot);node=(await openNode(vault,model,time,stub)).node;node.memoryPipeline.resume(jobId);const result=await node.memoryPipeline.run(jobId);check(result.status==='paused'&&result.failedBatches===1&&result.completedBatches===0,'fixture_failure_boundary');equal(calls,1,'fixture_later_provider_called');await new Promise(resolve=>setTimeout(resolve,Math.max(0,(result.availableAt??0)-Date.now())+10));failedReceipt=JSON.parse(String(node.store.db.prepare("SELECT json FROM model_usage WHERE json_extract(json,'$.status')='failed'").get()!.json));
 }finally{await node.app.close();}
 await closed(vault);failedSnapshot=join(output,'failed-closed');await cloneClosed(vault,failedSnapshot);checks.push({name:'six-batch-native-timeout',passed:true,stubCalls:1});
});
test('same-stack native retry pause closes and reopens with zero new calls',async()=>{
 check(failedSnapshot,'fixture_seed_required');const parentHash=await treeHash(failedSnapshot),destination=join(output,'prepared');const result=await prepareNativeSplit({parent:failedSnapshot,destination,model,contextTime:time,jobId});equal(result.providerAttempts,0,'fixture_prepare_admitted');
 let reopenedCalls=0;const {node}=await openNode(destination,model,time,async()=>{reopenedCalls++;throw new Error('fixture_reopen_forbidden');});try{await node.executor.tick();equal(node.memoryPipeline.get(jobId).status,'paused','fixture_restart_not_paused');equal(reopenedCalls,0,'fixture_restart_admitted');}finally{await node.app.close();}
 equal(await treeHash(failedSnapshot),parentHash,'fixture_failed_snapshot_mutated');checks.push({name:'retry-pause-closed-reopen',passed:true,...result,reopenedCalls});
});
let fixtureRoot:Manifest,rootPath='',previousPath='',ledgerDirectory='',validationPath='',lineage:RecoveryLineage,recoveryManifestPath='',recoveryParent='',lastSuccessParent='',lastSuccessManifest='';let syntheticHistoricalAdmissions=0,executionCalls=0;
const usageProjection=(r:any)=>({id:r.id,status:r.status,tokens:r.tokens,estimatedCost:r.estimatedCost,currency:r.currency,durationMs:r.durationMs});
const rejection=async(name:string,fn:()=>unknown|Promise<unknown>,expected:string)=>{let code='';try{await fn();}catch(error){code=error instanceof SafeFailure||error instanceof StageSafetyError?error.code:'unexpected_error';}equal(code,expected,'recovery_negative_code');checks.push({name,passed:true,code});};
test('explicit preparation authorizes only the closed timeout and preserves all 13 prior ledger admissions',async()=>{
 const seedOutput=await newOutput(join(output,'root-fixture'));const template=await freezeStage(seedOutput,true);fixtureRoot={...template,seed:canonicalSnapshot,seedTreeHash:await treeHash(canonicalSnapshot),jobId,contextTime:time,batchPlan:originalRows.map(b=>({id:b.id,index:b.index,sha256:batchPin(b),recipe:b.strategy?.recipe})),settingsHash:frozenSettings,bindingsHash:frozenBindings,protectedHash:frozenProtected};fixtureRoot.experimentHash=experimentHash(fixtureRoot);rootPath=join(output,'ROOT_SAFE_root-fixture.json');await writeFile(rootPath,json(fixtureRoot));
 const oldPlan:WavePlan={schema:'mote-heldout-wave-plan@1',experimentHash:fixtureRoot.experimentHash,wave:2,contextTime:time,jobId,batchPlan:fixtureRoot.batchPlan,settingsHash:frozenSettings,bindingsHash:frozenBindings,protectedHash:frozenProtected,deliveries:24,materials:25,sourceInputHash:'a'.repeat(64),ingressSnapshot:{path:canonicalSnapshot,treeHash:fixtureRoot.seedTreeHash}};const oldPlanPath=join(output,'ROOT_SAFE_old-wave-plan.json');await writeFile(oldPlanPath,json(oldPlan));const oldPlanRef=await ref(oldPlanPath);
 ledgerDirectory=join(output,'recovery-ledger');const ledger=new AdmissionLedger(ledgerDirectory,fixtureRoot.experimentHash);ledger.bindExecutor('fixture-history');
 // Twelve synthetic accounting records exercise historic budget retention. They are not model calls.
 for(let batch=0;batch<6;batch++){ledger.begin('wave1-batch-'+batch,fixtureRoot.seedTreeHash,2);for(let n=0;n<2;n++){const receipt=inheritedReceipts[batch*2+n],id=ledger.reserve('history-'+batch+'-'+n,'literal-input-hash',receipt.id);ledger.terminal(id,'completed','ok',{modelRunStarts:1,repairs:0});ledger.receipts([usageProjection(receipt)]);syntheticHistoricalAdmissions++;}ledger.finish(fixtureRoot.seedTreeHash,true);}
 ledger.begin('wave1-integration',fixtureRoot.seedTreeHash,0);ledger.finish(fixtureRoot.seedTreeHash,true,{kind:'integration',wave:1,contextTime:time,archiveHeadHash:fixtureRoot.seedTreeHash,totalBatches:6,nextBatch:6,evaluatedPairs:0});ledger.begin('wave2-ingress',fixtureRoot.seedTreeHash,0);ledger.finish(fixtureRoot.seedTreeHash,true,{kind:'ingress',wave:2,contextTime:time,archiveHeadHash:fixtureRoot.seedTreeHash,totalBatches:6,nextBatch:0,evaluatedPairs:0,wavePlan:oldPlanRef});
 const previous={schema:'mote-heldout-phase-manifest@1',kind:'mechanical',experimentHash:fixtureRoot.experimentHash,rootManifest:await ref(rootPath),previousManifest:{path:rootPath,sha256:'a'.repeat(64)},validation:{path:rootPath,sha256:'a'.repeat(64)},runtime:fixtureRoot.runtime,executor:fixtureRoot.executor,codeHashes:await codeHashes(),limits:fixtureRoot.limits,parent:{path:canonicalSnapshot,treeHash:fixtureRoot.seedTreeHash,ledgerHeadHash:ledger.summary().headHash},task:{kind:'extraction',wave:2,contextTime:time,index:0,wavePlan:oldPlanRef}};previousPath=join(output,'ROOT_SAFE_failed-manifest-fixture.json');await writeFile(previousPath,json(previous));ledger.bindExecutor(sha256(await readFile(previousPath)),'fixture-history','a'.repeat(64));ledger.begin('wave2-batch-0',fixtureRoot.seedTreeHash,2);const failedId=ledger.reserve(hashObject([jobId,originalRows[0].id,'extract']),'fixture-failed-input',failedReceipt.id);ledger.terminal(failedId,'failed','outer_deadline_exceeded',{modelRunStarts:1,repairs:0});ledger.receipts([usageProjection(failedReceipt)]);ledger.finish(await treeHash(failedSnapshot),false);ledger.close();
 const prefix=await readFile(join(ledgerDirectory,'admissions.ndjson'));validationPath=join(output,'ROOT_SAFE_validation-fixture.json');await writeFile(validationPath,json({schema:'mote-heldout-sequence-validation@1',validatedPhases:['recovery','extraction','ingress','integration','evaluation'],status:'passed',realModelCalls:0,heldoutSemanticInputsRead:false,executorCodeHashes:executorPins(await codeHashes()),note:'Validator-shape fixture; final verdict is the separate test report.'}));
 const freezeOutput=await newOutput(join(output,'recovery-freeze'));const frozen=await freezeRecovery({rootManifest:rootPath,previousManifest:previousPath,failedSnapshot,ledgerDirectory,validation:validationPath,supervisorPath:recoverySupervisor,output:freezeOutput});lineage=frozen.lineage;recoveryManifestPath=join(freezeOutput,'ROOT_SAFE_manifest.json');recoveryParent=frozen.plan.preparedPath;
 check((await readFile(join(ledgerDirectory,'admissions.ndjson'))).subarray(0,prefix.length).equals(prefix),'recovery_historical_prefix_mutated');const events=inspectAdmissionLedger(ledgerDirectory,fixtureRoot.experimentHash,lineage),cursor=phaseCursor(events,fixtureRoot,lineage);equal([cursor.nextBatch,cursor.totalBatches,cursor.archiveHeadHash,cursor.recoveryInputHash],[0,7,fixtureRoot.seedTreeHash,frozen.plan.preparedSnapshotHash],'recovery_cursor_wrong');await cp(ledgerDirectory,join(output,'authorized-ledger-baseline'),{recursive:true});checks.push({name:'explicit-single-lineage',passed:true,historicalAdmissions:13,newProviderCalls:0,immutablePrefix:true});
});
test('default APIs still reject old stop and wrong lineages never unlock it',async()=>{
 await rejection('default-reader',()=>inspectAdmissionLedger(ledgerDirectory,fixtureRoot.experimentHash),'ledger_persistently_stopped');await rejection('default-writer',()=>new AdmissionLedger(ledgerDirectory,fixtureRoot.experimentHash),'ledger_persistently_stopped');await rejection('default-cursor',()=>phaseCursor(readAdmissionChain(ledgerDirectory),fixtureRoot),'ledger_persistently_stopped');await rejection('wrong-event',()=>inspectAdmissionLedger(ledgerDirectory,fixtureRoot.experimentHash,{...lineage,eventHash:'b'.repeat(64)}),'recovery_event_missing_or_changed');await rejection('second-authorization',()=>authorizeRecovery(ledgerDirectory,lineage.plan),'recovery_not_original_stopped_head');
});
test('native index zero through six runs once, retaining inherited failure and consuming only needed calls',async()=>{
 let parent=recoveryParent,previous=recoveryManifestPath;const before=await readFile(join(ledgerDirectory,'admissions.ndjson')),seen:number[]=[];
 for(let index=0;index<7;index++){if(index){const next=await newOutput(join(output,'resume-'+index));await freezePhase({rootManifest:rootPath,previousManifest:previous,parent,ledgerDirectory,validation:validationPath,output:next,kind:'extraction',index,recoveryLineage:lineage,supervisorPath:recoverySupervisor});previous=join(next,'ROOT_SAFE_manifest.json');}
 const result=await runPhase({manifestPath:previous,ledgerDirectory,output:await newOutput(join(output,'run-'+index)),stub:async(_reader,input)=>{executionCalls++;seen.push(Number(input.traceContext?.batchIndex));equal(input.traceContext?.attempt,index===0?2:1,'recovery_trace_attempt_changed');input.onUsage?.({measurement:'thread_cumulative',complete:true,requests:0,reportedRequests:0,inputTokens:3,outputTokens:2,totalTokens:5});return {answer:'{"memories":[]}',citations:[],trace:[],runId:randomUUID()};}});check(result.succeeded,'recovery_batch_failed');parent=result.report.checkpoint.path;equal(result.report.cumulative.failed,1,'recovery_failed_history_lost');equal(result.report.cumulative.effectiveCap,123,'recovery_cap_changed');}
 check((await readFile(join(ledgerDirectory,'admissions.ndjson'))).subarray(0,before.length).equals(before),'recovery_prefix_changed_on_execution');const events=inspectAdmissionLedger(ledgerDirectory,fixtureRoot.experimentHash,lineage),cursor=phaseCursor(events,fixtureRoot,lineage);equal(cursor.nextBatch,7,'recovery_not_all_indices_complete');check(!cursor.recoveryInputHash&&!cursor.integrationDone,'recovery_cursor_advanced_too_far');equal(events.filter(e=>e.kind==='stage-close'&&e.data.succeeded&&String(e.data.stage).includes('recovery')).length,7,'recovery_stage_order_count');const db=new DatabaseSync(join(parent,'mote.sqlite'),{readOnly:true});try{const batches=db.prepare('SELECT json FROM memory_batches WHERE job_id=? ORDER BY idx').all(jobId).map(r=>JSON.parse(String(r.json)));equal(batches.map(b=>b.attempts),[2,1,1,1,1,1,1],'recovery_attempts_not_exact');}finally{db.close();}lastSuccessParent=parent;lastSuccessManifest=previous;checks.push({name:'seven-native-batches',passed:true,indices:[0,1,2,3,4,5,6],providerIndices:seen,stubCalls:executionCalls,emptyDraftSpareBudgetUnused:true});
});
test('any new failure permanently stops this lineage; unknown receipts and interruption are not replayed',async()=>{
 for(const mode of ['failed','unknown','missing-receipt'] as const){const directory=join(output,'second-'+mode);await cp(ledgerDirectory,directory,{recursive:true});const ledger=new AdmissionLedger(directory,fixtureRoot.experimentHash,124,lineage);ledger.begin('synthetic-next-'+mode,'c'.repeat(64),2);const id=ledger.reserve('synthetic-'+mode,'hash','receipt-'+mode);if(mode!=='unknown')ledger.terminal(id,mode==='failed'?'failed':'completed',mode==='failed'?'outer_deadline_exceeded':'ok',{modelRunStarts:1,repairs:0});if(mode==='failed'){ledger.receipts([{id:'receipt-'+mode,status:'failed',tokens:{complete:false,totalTokens:1}}]);ledger.finish('d'.repeat(64),false);}ledger.close();await rejection('second-'+mode,()=>inspectAdmissionLedger(directory,fixtureRoot.experimentHash,lineage),mode==='failed'?'recovery_new_stop_forbidden':'unknown_interrupted_stage');}
});
for(const phase of ['extract','review','commit'] as const)test('real pipeline recovery '+phase+' failure stops new admissions',async()=>{
 const directory=join(output,'pipeline-failure-'+phase);await cp(join(output,'authorized-ledger-baseline'),directory,{recursive:true});const runOutput=await newOutput(join(output,'pipeline-failure-run-'+phase));let stageCalls=0;
 const result=await runPhase({manifestPath:recoveryManifestPath,ledgerDirectory:directory,output:runOutput,stub:async(reader,input)=>{executionCalls++;stageCalls++;input.onUsage?.({measurement:'thread_cumulative',complete:input.traceContext?.phase!==phase,requests:0,reportedRequests:0,inputTokens:2,outputTokens:1,totalTokens:3});if(input.traceContext?.phase===phase)throw new Error('Generated failure marker');const evidence=(await reader.evidence({ids:input.evidenceIds!}))[0];if(phase==='commit'&&input.traceContext?.phase==='review'){const db=new DatabaseSync(join(runOutput,'DO_NOT_OPEN','working','mote.sqlite'));db.exec("CREATE TRIGGER generated_commit_failure BEFORE INSERT ON memories BEGIN SELECT RAISE(ABORT,'generated_commit_failure'); END");db.close();}return {answer:JSON.stringify({memories:[{domain:'personal',title:'Generated recovery marker',statement:'Literal generated observation ['+evidence.id+']',uncertainty:'Generated fixture only',admission:{layer:'memory',reason:'Generated',scope:'Fixture',attribution:'observed'},evidenceIds:[evidence.id],evidence:[{id:evidence.id,quote:evidence.ocrText}]}]}),citations:[{id:evidence.id,capturedAt:evidence.capturedAt,appName:evidence.appName,excerpt:evidence.ocrText}],trace:[],runId:randomUUID()};}});
 check(!result.succeeded&&result.report.cumulative.stopped,'recovery_failure_not_stopped');equal(stageCalls,phase==='extract'?1:2,'recovery_failure_later_call');equal(result.report.cumulative.admitted,13+stageCalls,'recovery_failure_count_reset');await rejection('pipeline-'+phase+'-resume',()=>inspectAdmissionLedger(directory,fixtureRoot.experimentHash,lineage),'recovery_new_stop_forbidden');
});
test('budget, error type, target phase and event authorization are narrow',async()=>{
 const all=readAdmissionChain(ledgerDirectory),event=all.find(e=>e.kind==='recovery-authorized')!,prefix=all.slice(0,event.index),plan=readRecoveryPlan(lineage.plan);
 for(const [name,mutate,expected] of [
  ['budget',(p:any)=>{p.effectiveCap=124;},'recovery_budget_changed'],
  ['attempt',(p:any)=>{p.expectedTraceAttempts[0]=1;},'recovery_execution_order_changed'],
  ['parent',(p:any)=>{p.failedSnapshotHash='e'.repeat(64);},'recovery_failed_snapshot_changed'],
 ] as const){const changed=structuredClone(plan);mutate(changed);const path=join(output,'negative-plan-'+name+'.json');await writeFile(path,json(changed));await rejection('plan-'+name,()=>validateRecoveryPrefix(prefix,{path,sha256:sha256(JSON.stringify(changed,null,2)+'\n')}),expected);}
 const otherFailure=structuredClone(prefix);otherFailure.find(e=>e.sha256===plan.failedTerminalHash)!.data.safeCode='outer_failed';await rejection('non-timeout-terminal',()=>validateRecoveryPrefix(otherFailure,lineage.plan),'recovery_failed_call_changed');const extraStop=structuredClone(prefix);extraStop.find(e=>e.kind==='stop')!.data.code='stage_technical_failure';await rejection('unapproved-stop',()=>validateRecoveryPrefix(extraStop,lineage.plan),'recovery_stop_set_changed');const wrongStage=structuredClone(prefix);wrongStage.find(e=>e.sha256===plan.failedAdmissionHash)!.data.stage='wave2-batch-1';await rejection('wrong-failed-stage',()=>validateRecoveryPrefix(wrongStage,lineage.plan),'recovery_failed_receipt_changed');
 const locked=join(output,'locked-ledger');await cp(join(output,'authorized-ledger-baseline'),locked,{recursive:true});await writeFile(join(locked,'writer.lock'),'generated stale lock');await rejection('lock-never-reclaimed',()=>new AdmissionLedger(locked,fixtureRoot.experimentHash,124,lineage),'ledger_locked_unknown_interruption');
 const partial=join(output,'partial-ledger');await cp(join(output,'authorized-ledger-baseline'),partial,{recursive:true});await writeFile(join(partial,'admissions.ndjson'),'{partial',{flag:'a'});await rejection('partial-event-never-repaired',()=>inspectAdmissionLedger(partial,fixtureRoot.experimentHash,lineage),'ledger_partial_record_unknown');
});

test('a historical shared half-draft is preserved and reused only by the native exact input key',async()=>{
 const vault=join(output,'half-cache-history');await cloneClosed(canonicalSnapshot,vault);let phase:'producer'|'timeout'|'recovered'='producer',count=0,seen:string[]=[];let node:Awaited<ReturnType<typeof openNode>>['node'];
 const stub=async(reader:ContextReader,input:QueryInput):Promise<QueryResult>=>{executionCalls++;count++;seen.push(phase+':'+input.traceContext?.phase);if(phase==='timeout'){node.memoryPipeline.pause(jobId);input.onUsage?.({measurement:'thread_cumulative',complete:false,requests:0,reportedRequests:0,inputTokens:1,outputTokens:0,totalTokens:1});throw new AgentTimeoutError();}input.onUsage?.({measurement:'thread_cumulative',complete:true,requests:0,reportedRequests:0,inputTokens:1,outputTokens:1,totalTokens:2});const evidence=(await reader.evidence({ids:input.evidenceIds!}))[0];const domain=phase==='producer'&&input.traceContext?.phase==='review'?'coding':'personal';return {answer:JSON.stringify({memories:[{domain,...(domain==='coding'?{coding:{kind:'decision',scope:'session',applicability:'Generated',validation:'observed'}}:{}),title:'Shared half fixture',statement:'Generated literal ['+evidence.id+']',uncertainty:'Fixture only',admission:{layer:'memory',reason:'Generated',scope:'Fixture',attribution:'observed'},evidenceIds:[evidence.id],evidence:[{id:evidence.id,quote:evidence.ocrText}]}]}),citations:[{id:evidence.id,capturedAt:evidence.capturedAt,appName:evidence.appName,excerpt:evidence.ocrText}],trace:[],runId:randomUUID()};};
 node=(await openNode(vault,model,time,stub)).node;try{const chunks=originalRows[0].chunks.slice(0,4),producer=node.memoryPipeline.create({evidenceIds:chunks.map((c:any)=>c.id),evidenceRanges:chunks.map(({id,offset,length}:any)=>({id,offset,length})),recipes:[recipes[1]],contextTime:time,timeZone:'Asia/Shanghai',batchCharacters:12000});check((await node.memoryPipeline.run(producer.id)).status==='completed','cache_producer_failed');equal(count,2,'cache_producer_call_count');phase='timeout';node.memoryPipeline.resume(jobId);const failed=await node.memoryPipeline.run(jobId);check(failed.failedBatches===1,'cache_fixture_timeout_failed');await new Promise(resolve=>setTimeout(resolve,Math.max(0,(failed.availableAt??0)-Date.now())+10));}finally{await node.app.close();}
 const parent=join(output,'half-cache-failed');await cloneClosed(vault,parent);const prepared=join(output,'half-cache-prepared');await prepareNativeSplit({parent,destination:prepared,model,contextTime:time,jobId});phase='recovered';node=(await openNode(prepared,model,time,stub)).node;try{const target=node.memoryPipeline.get(jobId).batches[0];const project=node.memoryPipeline.engine.project.bind(node.memoryPipeline.engine);node.memoryPipeline.engine.project=(id:string)=>{project(id);if(id===target.id&&node.memoryPipeline.engine.get(id)?.state==='running')node.memoryPipeline.pause(jobId);};node.memoryPipeline.resume(jobId);const result=await node.memoryPipeline.run(jobId);check(result.batches[0].status==='completed','cache_recovered_parent_failed');equal(seen.filter(s=>s.startsWith('recovered:')),['recovered:review'],'cache_draft_not_reused_exactly');equal(result.batches[0].attempts,2,'cache_attempt_reset');}finally{await node.app.close();}checks.push({name:'native-exact-half-draft-reuse',passed:true,producerStubCalls:2,originalTimeoutStubCalls:1,recoveredGenerationCalls:0,recoveredReviewCalls:1,historicalDraftRetained:true});
});

test('the same explicit lineage passes integration, fresh A/B and next-wave ingress without resetting accounting',async()=>{
 const prefix=await readFile(join(ledgerDirectory,'admissions.ndjson'));let previous=lastSuccessManifest,parent=lastSuccessParent;
 const integrationOutput=await newOutput(join(output,'integration-freeze')),integration=await freezeIntegration({rootManifest:rootPath,previousManifest:previous,parent,ledgerDirectory,validation:validationPath,supervisorPath:recoverySupervisor,output:integrationOutput,recoveryLineage:lineage});const integrated=await runIntegration({manifest:integration,manifestHash:sha256(await readFile(join(integrationOutput,'ROOT_SAFE_manifest.json'))),output:await newOutput(join(output,'integration-run')),ledgerDirectory,stub:async(_reader,input)=>{executionCalls++;input.onUsage?.({measurement:'thread_cumulative',complete:true,requests:0,reportedRequests:0,inputTokens:1,outputTokens:1,totalTokens:2});return {answer:'{"memories":[]}',citations:[],trace:[],runId:randomUUID()};}});check(integrated.succeeded,'recovery_integration_failed');previous=join(integrationOutput,'ROOT_SAFE_manifest.json');parent=integrated.report.checkpoint.path;
 const times=['','',time,'2026-01-31T23:59:59+08:00','2026-02-28T23:59:59+08:00','2026-03-31T23:59:59+08:00','2026-04-30T23:59:59+08:00'];const mechanicalQuestions=[2,3,4,5,6,6,6,6].map((wave,index)=>({questionId:'generated-'+index,scenario:'mechanical',question:'Read a generated literal record.',checkpointWave:wave,contextTime:times[wave]}));const askOutput=await newOutput(join(output,'ask-freeze')),ask=await freezeAsk({rootManifest:rootPath,previousManifest:previous,parent,ledgerDirectory,validation:validationPath,supervisorPath:recoverySupervisor,output:askOutput,recoveryLineage:lineage,mechanicalQuestions});const asked=await runAsk({manifest:ask,manifestHash:sha256(await readFile(join(askOutput,'ROOT_SAFE_manifest.json'))),output:await newOutput(join(output,'ask-run')),ledgerDirectory,stub:async(_reader,input)=>{executionCalls++;input.onUsage?.({measurement:'thread_cumulative',complete:true,requests:0,reportedRequests:0,inputTokens:1,outputTokens:1,totalTokens:2});return {answer:'Generated fixture answer.',citations:[],trace:[],runId:randomUUID()};}});check(asked.succeeded,'recovery_ask_failed');previous=join(askOutput,'ROOT_SAFE_manifest.json');const afterAsk=phaseCursor(inspectAdmissionLedger(ledgerDirectory,fixtureRoot.experimentHash,lineage),fixtureRoot,lineage);equal(afterAsk.archiveHeadHash,integrated.report.checkpoint.treeHash,'recovery_ask_replaced_archive');equal(afterAsk.evaluatedPairs,1,'recovery_ask_cursor_missing');
 const inputPath=join(output,'DO_NOT_OPEN_wave3-fixture.json');await writeFile(inputPath,json({contextTime:times[3],expectedBatches:2,sources:[{id:'recovery-fixture',kind:'custom',deviceId:'generated-recovery',platform:'import'}],deliveries:[{sourceId:'recovery-fixture',duplicate:false,item:{externalId:'new-wave3',revision:'1',kind:'message',layer:'original',observedAt:'2026-01-01T09:00:00+08:00',text:'Generated next-wave literal.',document:{contentRole:'authored',recordedAt:'2026-01-01T09:00:00+08:00',timeBasis:'recorded'}}}]}));const ingressOutput=await newOutput(join(output,'wave3-ingress-freeze'));await freezePhase({rootManifest:rootPath,previousManifest:previous,parent,ledgerDirectory,validation:validationPath,output:ingressOutput,kind:'ingress',wave:3,mechanicalInput:inputPath,recoveryLineage:lineage,supervisorPath:recoverySupervisor});const ingressed=await runPhase({manifestPath:join(ingressOutput,'ROOT_SAFE_manifest.json'),output:await newOutput(join(output,'wave3-ingress-run')),ledgerDirectory});check(ingressed.succeeded,'recovery_next_wave_failed');equal(ingressed.report.realModelCalls,0,'recovery_ingress_called_model');check((await readFile(join(ledgerDirectory,'admissions.ndjson'))).subarray(0,prefix.length).equals(prefix),'recovery_descendants_rewrote_history');checks.push({name:'explicit-descendant-lineage',passed:true,integration:true,pairedAsk:true,canonicalPreserved:true,nextWaveIngress:true,effectiveCap:ingressed.report.cumulative.effectiveCap,historicalFailed:ingressed.report.cumulative.failed});
});
test('CLI recovery preparation is zero model and ordinary live rejects a mechanical manifest',async()=>{
 const original=readAdmissionChain(join(output,'authorized-ledger-baseline')),index=original.findIndex(e=>e.kind==='recovery-authorized'),directory=join(output,'cli-stopped-ledger');await mkdir(directory);const prefix=original.slice(0,index).map(e=>JSON.stringify(e)).join('\n')+'\n';await writeFile(join(directory,'admissions.ndjson'),prefix);
 const freezeOutput=join(output,'cli-recovery-freeze'),env={...process.env,MOTE_HELDOUT_MODE:'stage-recovery-freeze',MOTE_HELDOUT_ROOT_MANIFEST:rootPath,MOTE_HELDOUT_MANIFEST:previousPath,MOTE_HELDOUT_PARENT:failedSnapshot,MOTE_HELDOUT_LEDGER:directory,MOTE_HELDOUT_VALIDATION:validationPath,MOTE_HELDOUT_SUPERVISOR:recoverySupervisor,MOTE_HELDOUT_OUTPUT:freezeOutput};delete (env as NodeJS.ProcessEnv).MOTE_HELDOUT_RECOVERY_LINEAGE;const prepared=spawnSync(process.execPath,['--import','tsx','scripts/test-heldout-memory-replay.ts'],{encoding:'utf8',env});equal(prepared.status,0,'recovery_cli_prepare_failed');const report=JSON.parse(await readFile(join(freezeOutput,'ROOT_SAFE_recovery.json'),'utf8'));equal([report.realModelCalls,report.providerAttempts,report.usageDelta],[0,0,0],'recovery_cli_called_provider');const bytes=await readFile(join(directory,'admissions.ndjson'));check(bytes.subarray(0,Buffer.byteLength(prefix)).equals(Buffer.from(prefix)),'recovery_cli_prefix_changed');const rejected=spawnSync(process.execPath,['--import','tsx','scripts/test-heldout-memory-replay.ts'],{encoding:'utf8',env:{...env,MOTE_HELDOUT_MODE:'stage-live',MOTE_HELDOUT_MANIFEST:join(freezeOutput,'ROOT_SAFE_manifest.json'),MOTE_HELDOUT_OUTPUT:join(output,'cli-live-rejected')}});equal(rejected.status,1,'recovery_cli_mechanical_live_allowed');const status=JSON.parse(await readFile(join(output,'cli-live-rejected','ROOT_SAFE_status.json'),'utf8'));equal(status.code,'stage_manifest_invalid','recovery_cli_wrong_rejection');check((await readFile(join(directory,'admissions.ndjson'))).equals(bytes),'recovery_cli_rejection_mutated_ledger');checks.push({name:'recovery-cli',passed:true,prepareProviderCalls:0,mechanicalLiveRejected:true});
});

after(async()=>{await writeFile(join(output,'ROOT_SAFE_recovery-native.json'),json({schema:'mote-heldout-sequence-validation@1',validatedPhases:['recovery','extraction','integration','evaluation','ingress'],status:checks.length===26?'passed':'incomplete',checks,realModelCalls:0,stubModelCalls:calls+bootstrapCalls+executionCalls,bootstrapCalls,syntheticHistoricalAdmissions,heldoutSemanticInputsRead:false,executorCodeHashes:executorPins(await codeHashes()),scope:'Generated native split, explicit recovery lineage and sequential extraction. Prior 12 ledger admissions are generated accounting fixtures (3 matching stub receipts and 9 standalone synthetic usage meters), separate from actual stub query counts. No heldout or real provider.'}),{mode:0o600});});
