/** Host-only, append-only admission accounting. Never accepts semantic data. */
import {closeSync,existsSync,fsyncSync,mkdirSync,openSync,readFileSync,unlinkSync,writeSync} from 'node:fs';
import {randomUUID,createHash} from 'node:crypto';
import {join} from 'node:path';
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
export class StageSafetyError extends Error{constructor(readonly code:string){super(code);}}
const need=(ok:unknown,code:string)=>{if(!ok)throw new StageSafetyError(code);};
/** Structural phase cursor only; never source identities or arm mappings. */
export type PhaseClosure={kind:'ingress'|'extraction'|'integration'|'evaluation';wave:number;contextTime:string;archiveHeadHash:string;totalBatches:number;nextBatch:number;evaluatedPairs:number;wavePlan?:{path:string;sha256:string}};
export type LedgerEvent={index:number;at:string;previous:string;kind:string;data:Record<string,any>;sha256:string};


export type RecoveryRef={path:string;sha256:string};
export type RecoveryLineage={plan:RecoveryRef;eventHash:string};
export type RecoveryPlan={schema:'mote-heldout-recovery-d-plan@1';policy:'D-preserve-six-batches@1';experimentHash:string;recoveryId:string;stoppedHeadHash:string;stopHashes:string[];failedCloseHash:string;failedTerminalHash:string;failedReceiptHash:string;failedAdmissionHash:string;canonicalHeadHash:string;failedSnapshotHash:string;preparedSnapshotHash:string;oldWavePlan:RecoveryRef;newWavePlan:RecoveryRef;wave:2;contextTime:string;inheritedAdmissions:13;effectiveCap:121;remainingCap:108;remainingExtractionBatches:36;targetRetryCap:2;targetStage:string;validation:RecoveryRef;rootManifest:RecoveryRef;previousManifest:RecoveryRef;preparedPath:string;preparationCommitment:RecoveryRef;preparationExecutorHash:string;supervisor:RecoveryRef;runtimeHash:string;productionHash:string;settingsHash:string;bindingsHash:string;expectedTraceAttempts:[2,1,1,1,1,1]};
const isHash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
export function readRecoveryPlan(ref:RecoveryRef):RecoveryPlan{need(ref&&isHash(ref.sha256),'recovery_ref_invalid');const bytes=readFileSync(ref.path);need(createHash('sha256').update(bytes).digest('hex')===ref.sha256,'recovery_plan_changed');const p=JSON.parse(bytes.toString()) as RecoveryPlan;need(p.schema==='mote-heldout-recovery-d-plan@1'&&p.policy==='D-preserve-six-batches@1'&&p.wave===2&&/^[0-9a-f-]{36}$/.test(p.recoveryId),'recovery_plan_invalid');need(p.inheritedAdmissions===13&&p.effectiveCap===121&&p.remainingCap===108&&p.remainingExtractionBatches===36&&p.targetRetryCap===2&&p.effectiveCap===p.inheritedAdmissions+p.remainingExtractionBatches*2+5*4+16,'recovery_budget_changed');need(JSON.stringify(p.expectedTraceAttempts)==='[2,1,1,1,1,1]'&&p.targetStage===`wave2-recovery-D-${p.recoveryId}-batch-0`,'recovery_execution_order_changed');return p;}
/** Used only against the immutable stopped prefix, before the one authorized event. */
export function validateRecoveryPrefix(events:LedgerEvent[],ref:RecoveryRef){const p=readRecoveryPlan(ref);const commitmentBytes=readFileSync(p.preparationCommitment.path);need(createHash('sha256').update(commitmentBytes).digest('hex')===p.preparationCommitment.sha256,'recovery_commitment_changed');const commitment=JSON.parse(commitmentBytes.toString());need(commitment.schema==='mote-heldout-recovery-d-preparation@1'&&commitment.experimentHash===p.experimentHash&&commitment.stoppedHeadHash===p.stoppedHeadHash&&commitment.recoveryId===p.recoveryId,'recovery_commitment_mismatch');need(events[0]?.data.manifestHash===p.experimentHash&&events[0]?.data.cumulativeCap===124,'recovery_ancestor_changed');need(events.at(-1)?.sha256===p.stoppedHeadHash&&!events.some(e=>e.kind==='recovery-authorized'),'recovery_not_original_stopped_head');const admits=events.filter(e=>e.kind==='admit'),failed=events.filter(e=>e.kind==='terminal'&&e.data.status==='failed'),stops=events.filter(e=>e.kind==='stop'),closes=events.filter(e=>e.kind==='stage-close');need(admits.length===13&&failed.length===1&&failed[0].sha256===p.failedTerminalHash&&failed[0].data.safeCode==='outer_deadline_exceeded','recovery_failed_call_changed');need(stops.length===1&&stops[0].data.code==='outer_deadline_exceeded'&&JSON.stringify(stops.map(e=>e.sha256))===JSON.stringify(p.stopHashes),'recovery_stop_set_changed');need(events.filter(e=>e.kind==='stage-open').every(e=>closes.filter(c=>c.data.stage===e.data.stage).length===1),'recovery_unclosed_stage');const admission=admits.find(e=>e.sha256===p.failedAdmissionHash),receipt=events.find(e=>e.sha256===p.failedReceiptHash),closure=closes.at(-1);need(admission&&admission.data.stage==='wave2-batch-0'&&failed[0].data.callId===admission.data.callId&&receipt?.kind==='receipt'&&receipt.data.id===admission.data.receiptId&&receipt.data.status==='failed'&&receipt.data.tokens?.complete===false,'recovery_failed_receipt_changed');need(closure?.sha256===p.failedCloseHash&&closure.data.stage===admission!.data.stage&&closure.data.succeeded===false&&closure.data.snapshotHash===p.failedSnapshotHash&&closes.slice(0,-1).every(e=>e.data.succeeded===true),'recovery_failed_snapshot_changed');need(events.find(e=>e.kind==='stage-open'&&e.data.stage===admission!.data.stage)?.data.parentHash===p.canonicalHeadHash,'recovery_canonical_parent_changed');need(!events.some(e=>e.kind==='host-rejection-receipt'),'recovery_host_rejection_present');for(const a of admits){const ts=events.filter(e=>e.kind==='terminal'&&e.data.callId===a.data.callId),rs=events.filter(e=>e.kind==='receipt'&&e.data.id===a.data.receiptId);need(ts.length===1&&rs.length===1&&rs[0].data.status!=='running'&&ts[0].data.status===rs[0].data.status,'recovery_unknown_accounting');}return p;}
/** Default callers do not pass a lineage and therefore still reject every historic stop. */
export function recoveryAuthorization(events:LedgerEvent[],lineage?:RecoveryLineage){if(!lineage)return undefined;const matches=events.filter(e=>e.kind==='recovery-authorized');need(matches.length===1&&matches[0].sha256===lineage.eventHash,'recovery_event_missing_or_changed');const event=matches[0];need(JSON.stringify(event.data.plan)===JSON.stringify(lineage.plan),'recovery_event_plan_changed');const p=validateRecoveryPrefix(events.slice(0,event.index),lineage.plan);need(event.previous===p.stoppedHeadHash&&event.data.preparedSnapshotHash===p.preparedSnapshotHash,'recovery_event_parent_changed');need(!events.slice(event.index+1).some(e=>e.kind==='stop'),'recovery_new_stop_forbidden');return p;}
export function readAdmissionChain(directory:string){const bytes=readFileSync(join(directory,'admissions.ndjson'),'utf8');need(bytes.endsWith('\n'),'ledger_partial_record_unknown');const events:LedgerEvent[]=[];for(const line of bytes.trimEnd().split('\n')){const row=JSON.parse(line) as LedgerEvent;const {sha256,...body}=row;need(row.index===events.length&&row.previous===(events.at(-1)?.sha256??'genesis')&&sha256===hash(body),'ledger_chain_invalid');events.push(row);}return events;}
/** Only this operation may append an initial recovery event; validation and append share the writer lock. */
export function authorizeRecovery(directory:string,plan:RecoveryRef):RecoveryLineage{let lock:number;try{lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}let file:number|undefined,writing=false;try{const events=readAdmissionChain(directory),p=validateRecoveryPrefix(events,plan);const body={index:events.length,at:new Date().toISOString(),previous:p.stoppedHeadHash,kind:'recovery-authorized',data:{plan,preparedSnapshotHash:p.preparedSnapshotHash}};const row={...body,sha256:hash(body)};file=openSync(join(directory,'admissions.ndjson'),'a',0o600);writing=true;writeSync(file,JSON.stringify(row)+'\n');fsyncSync(file);writing=false;return {plan,eventHash:row.sha256};}finally{if(file!==undefined)closeSync(file);closeSync(lock);if(!writing)unlinkSync(join(directory,'writer.lock'));}}

/** Non-mutating checkpoint inspection; a live writer or uncertain stage is not resumable. */
export function inspectAdmissionLedger(directory:string,experimentHash:string,lineage?:RecoveryLineage,normal?:NormalContinuation,review?:NormalReviewRecovery,ask?:AskRecovery){
  need(!existsSync(join(directory,'writer.lock')),'ledger_locked_unknown_interruption');
  const bytes=readFileSync(join(directory,'admissions.ndjson'),'utf8');need(bytes.endsWith('\n'),'ledger_partial_record_unknown');const events:LedgerEvent[]=[];
  for(const line of bytes.trimEnd().split('\n')){const row=JSON.parse(line) as LedgerEvent;const {sha256,...body}=row;need(row.index===events.length&&row.previous===(events.at(-1)?.sha256??'genesis')&&sha256===hash(body),'ledger_chain_invalid');events.push(row);}
  need(events[0]?.kind==='manifest'&&events[0].data.manifestHash===experimentHash&&events[0].data.cumulativeCap===124,'ledger_manifest_mismatch');
  need((!lineage||!normal)&&(!review||normal)&&(!ask||!lineage),'normal_lineages_conflict');const recovery=ask?askRecoveryAuthorization(events,ask,normal,review):normal?normalAuthorization(events,normal,review):recoveryAuthorization(events,lineage);need(!events.some(row=>row.kind==='stop'&&!recovery?.stopHashes.includes(row.sha256)),'ledger_persistently_stopped');const closed=new Set(events.filter(row=>row.kind==='stage-close').map(row=>row.data.stage));
  need(events.filter(row=>row.kind==='stage-open').every(row=>closed.has(row.data.stage)),'unknown_interrupted_stage');
  for(const admission of events.filter(row=>row.kind==='admit')){const terminal=events.filter(row=>row.kind==='terminal'&&row.data.callId===admission.data.callId),receipt=events.filter(row=>row.kind==='receipt'&&row.data.id===admission.data.receiptId);need(terminal.length===1&&receipt.length===1&&receipt[0].data.status!=='running','admission_receipt_unknown');need(terminal[0].data.status===receipt[0].data.status,'terminal_receipt_conflict');}
  return events;
}
/** Holding an exclusive lock for the complete stage makes check+reserve one writer operation.
 * A crash leaves that lock intentionally. No stale-lock reclamation or automatic retry. */
export class AdmissionLedger{
  readonly events:LedgerEvent[]=[];private lock:number;private file=-1;private busy=false;private stage?:string;private recovery?:RecoveryPlan;private recoveryE?:RecoveryEPlan;private normal?:NormalPlan;private reviewRecovery?:NormalReviewPlan;private askRecoveryPlan?:AskRecoveryPlan;
  constructor(readonly directory:string,readonly manifestHash:string,readonly cumulativeCap=124,readonly recoveryLineage?:RecoveryLineage,readonly recoveryELineage?:RecoveryELineage,readonly normalContinuation?:NormalContinuation,readonly normalReviewRecovery?:NormalReviewRecovery,readonly askRecovery?:AskRecovery){
    mkdirSync(directory,{recursive:true,mode:0o700});
    try{this.lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}
    try{
      const path=join(directory,'admissions.ndjson');if(existsSync(path)){
        const bytes=readFileSync(path,'utf8');need(bytes.endsWith('\n'),'ledger_partial_record_unknown');
        for(const line of bytes.trimEnd().split('\n')){const row=JSON.parse(line) as LedgerEvent;const {sha256,...body}=row;need(row.index===this.events.length&&row.previous===(this.events.at(-1)?.sha256??'genesis')&&sha256===hash(body),'ledger_chain_invalid');this.events.push(row);}
      }
      this.file=openSync(path,'a',0o600);if(!this.events.length)this.append('manifest',{manifestHash,cumulativeCap});
      need(this.events[0].data.manifestHash===manifestHash&&this.events[0].data.cumulativeCap===cumulativeCap,'ledger_manifest_mismatch');
      const opens=this.events.filter(e=>e.kind==='stage-open'),closes=new Set(this.events.filter(e=>e.kind==='stage-close').map(e=>e.data.stage));
      if(opens.some(e=>!closes.has(e.data.stage))||this.pending().length){this.append('stop',{code:'unknown_interrupted_stage'});throw new StageSafetyError('unknown_interrupted_stage');}
      need([recoveryLineage,recoveryELineage,normalContinuation].filter(Boolean).length<=1&&(!askRecovery||!recoveryLineage&&!recoveryELineage),'recovery_lineages_conflict');need(!normalReviewRecovery||normalContinuation,'normal_review_normal_required');if(askRecovery)this.askRecoveryPlan=askRecoveryAuthorization(this.events,askRecovery,normalContinuation,normalReviewRecovery);if(normalContinuation)this.normal=normalAuthorization(this.events,normalContinuation,normalReviewRecovery,askRecovery);if(normalReviewRecovery)this.reviewRecovery=normalReviewAuthorization(this.events,normalContinuation!,normalReviewRecovery,askRecovery);if(!normalContinuation&&recoveryELineage)this.recoveryE=recoveryEAuthorization(this.events,recoveryELineage);else if(!normalContinuation&&!askRecovery)this.recovery=recoveryAuthorization(this.events,recoveryLineage);need(!this.stopped,'ledger_persistently_stopped');
    }catch(e){if(this.file!>=0)closeSync(this.file!);closeSync(this.lock!);unlinkSync(join(directory,'writer.lock'));throw e;}
  }
  private append(kind:string,data:Record<string,any>){const body={index:this.events.length,at:new Date().toISOString(),previous:this.events.at(-1)?.sha256??'genesis',kind,data};const row={...body,sha256:hash(body)};writeSync(this.file,JSON.stringify(row)+'\n');fsyncSync(this.file);this.events.push(row);return row;}
  get stopped(){return this.events.some(e=>e.kind==='stop'&&!(this.askRecoveryPlan??this.normal??this.recoveryE??this.recovery)?.stopHashes.includes(e.sha256));}
  get admitted(){return this.events.filter(e=>e.kind==='admit');}
  pending(){const done=new Set(this.events.filter(e=>e.kind==='terminal').map(e=>e.data.callId));return this.admitted.filter(e=>!done.has(e.data.callId));}
  bindExecutor(manifestHash:string,priorManifestHash?:string,offlineValidationHash?:string){const prior=this.events.filter(e=>e.kind==='executor-freeze').at(-1);if(prior?.data.manifestHash===manifestHash)return;if(prior)need(prior.data.manifestHash===priorManifestHash&&typeof offlineValidationHash==='string'&&/^[a-f0-9]{64}$/.test(offlineValidationHash),'executor_transition_not_validated');this.append('executor-freeze',{manifestHash,priorManifestHash:prior?.data.manifestHash??null,offlineValidationHash:offlineValidationHash??null});}
  private reviewConsumed(){return Boolean(this.reviewRecovery&&this.events.some(e=>e.kind==='stage-close'&&e.data.stage===this.reviewRecovery!.targetStage&&e.data.succeeded===true));}
  private askConsumed(){return Boolean(this.askRecoveryPlan&&this.events.some(e=>e.kind==='stage-close'&&e.data.stage===this.askRecoveryPlan!.targetStage&&e.data.succeeded===true));}
  begin(stage:string,parentHash:string,maxCalls:number){if(this.askRecoveryPlan&&!this.askConsumed())need(stage===this.askRecoveryPlan.targetStage&&parentHash===this.askRecoveryPlan.canonicalSnapshotHash&&maxCalls===2,'ask_recovery_stage_scope_changed');if(this.reviewRecovery&&!this.reviewConsumed())need(stage===this.reviewRecovery.targetStage&&parentHash===this.reviewRecovery.preparedSnapshotHash&&maxCalls===1,'normal_review_stage_scope_changed');need(!this.stage&&!this.stopped,'stage_cannot_start');need(!this.events.some(e=>e.kind==='stage-open'&&e.data.stage===stage),'stage_already_started');if(this.recoveryE)need(stage===this.recoveryE.targetStage&&parentHash===this.recoveryE.preparedSnapshotHash&&maxCalls===2,'recovery_e_stage_scope_changed');this.stage=stage;this.append('stage-open',{stage,parentHash,maxCalls});}
  stop(code:string){if(!this.stopped)this.append('stop',{code});}
  reserve(logicalKey:string,inputHash:string,receiptId:string){
    try{need(this.stage&&!this.stopped,'admission_closed');need(!this.busy,'global_concurrency_exceeded');need(!this.admitted.some(e=>e.data.logicalKey===logicalKey),'outer_retry_forbidden');
      const begin=this.events.find(e=>e.kind==='stage-open'&&e.data.stage===this.stage)!;if(this.reviewRecovery&&!this.reviewConsumed())need(logicalKey===hash([this.reviewRecovery.target.jobId,this.reviewRecovery.target.batchId,'review',this.normalReviewRecovery!.plan.sha256,2]),'normal_review_admission_changed');
      if(this.askRecoveryPlan&&!this.askConsumed()){const ordinal=this.admitted.filter(e=>e.data.stage===this.stage).length;need(logicalKey===askRecoveryLogicalKeys(this.askRecoveryPlan)[ordinal],'ask_recovery_slot_changed');need(this.admitted.length<this.askRecoveryPlan.recoveryCumulativeCap,'ask_recovery_budget_exceeded');}
      need(this.admitted.length<Math.min(this.cumulativeCap,this.reviewRecovery&&!this.reviewConsumed()?this.reviewRecovery.recoveryCumulativeCap:this.recoveryE?.effectiveCap??this.recovery?.effectiveCap??this.cumulativeCap)&&this.admitted.filter(e=>e.data.stage===this.stage).length<begin.data.maxCalls,'admission_budget_exceeded');
      if(this.recovery&&this.stage===this.recovery.targetStage)need(this.admitted.filter(e=>e.data.stage===this.recovery!.targetStage).length<this.recovery.targetRetryCap,'recovery_target_budget_exceeded');
      const callId=randomUUID();this.append('admit',{stage:this.stage,callId,logicalKey,inputHash,receiptId});this.busy=true;return callId;
    }catch(e){this.stop(e instanceof StageSafetyError?e.code:'admission_internal_failure');throw e;}
  }
  terminal(callId:string,status:'completed'|'failed',safeCode:string,counts:{modelRunStarts:number|null;repairs:number|null}){need(this.busy&&this.pending().some(e=>e.data.callId===callId),'terminal_without_admission');this.append('terminal',{callId,status,safeCode,...counts});this.busy=false;if(status==='failed')this.stop(safeCode);}
  receipts(rows:Array<{id:string;status:string;tokens?:unknown;estimatedCost?:unknown;currency?:unknown;durationMs?:number}>){
    const previous=new Set(this.events.filter(e=>e.kind==='receipt').map(e=>e.data.id));for(const row of rows){need(this.admitted.some(e=>e.data.receiptId===row.id),'receipt_without_admission');need(!previous.has(row.id),'receipt_counted_twice');this.append('receipt',row);previous.add(row.id);}
  }
  rejectedReceipts(rows:Array<Record<string,any>>){for(const row of rows){need(!this.admitted.some(e=>e.data.receiptId===row.id),'rejected_receipt_was_admitted');need(!this.events.some(e=>e.kind==='host-rejection-receipt'&&e.data.id===row.id),'rejection_receipt_duplicate');this.append('host-rejection-receipt',row);}}
  finish(snapshotHash:string,succeeded:boolean,phase?:PhaseClosure){if(this.askRecoveryPlan&&succeeded&&this.stage===this.askRecoveryPlan.targetStage){askRecoveryAuthorization(this.events,this.askRecovery!,this.normalContinuation,this.normalReviewRecovery);need(this.admitted.filter(a=>a.data.stage===this.stage).length===2,'ask_recovery_success_admission_missing');same(phase,this.askRecoveryPlan.successPhase,'ask_recovery_success_cursor_changed');}if(this.normalReviewRecovery&&succeeded){normalReviewAuthorization(this.events,this.normalContinuation!,this.normalReviewRecovery,this.askRecovery);if(this.stage===this.reviewRecovery!.targetStage){need(!this.stopped&&this.admitted.filter(a=>a.data.stage===this.stage).length===1,'normal_review_success_admission_missing');same(phase,{kind:'extraction',wave:2,contextTime:this.reviewRecovery!.contextTime,archiveHeadHash:snapshotHash,totalBatches:6,nextBatch:3,evaluatedPairs:0,wavePlan:this.reviewRecovery!.newWavePlan},'normal_review_success_cursor_changed');}}need(this.stage&&!this.busy&&!this.pending().length,'stage_has_unknown_call');const counted=new Map(this.events.filter(e=>e.kind==='receipt').map(e=>[e.data.id,e]));need(this.admitted.every(e=>counted.has(e.data.receiptId)&&counted.get(e.data.receiptId)!.data.status!=='running'),'admission_receipt_unknown');need(this.admitted.every(e=>{const terminal=this.events.find(t=>t.kind==='terminal'&&t.data.callId===e.data.callId);return terminal?.data.status===counted.get(e.data.receiptId)!.data.status;}),'terminal_receipt_conflict');if(!succeeded)this.stop('stage_technical_failure');this.append('stage-close',{stage:this.stage,snapshotHash,succeeded,...(phase?{phase}:{})});this.stage=undefined;if(this.recoveryE&&succeeded)this.stop('recovery_e_complete');}
  summary(){return {effectiveCap:this.recoveryE?.effectiveCap??this.recovery?.effectiveCap??this.cumulativeCap,historicalStops:this.events.filter(e=>e.kind==='stop').length,recoveryPlanHash:this.recoveryELineage?.plan.sha256??this.recoveryLineage?.plan.sha256??null,admitted:this.admitted.length,completed:this.events.filter(e=>e.kind==='terminal'&&e.data.status==='completed').length,failed:this.events.filter(e=>e.kind==='terminal'&&e.data.status==='failed').length,unknown:this.pending().length,unreconciledReceipts:this.admitted.filter(a=>!this.events.some(e=>e.kind==='receipt'&&e.data.id===a.data.receiptId&&e.data.status!=='running')).length,terminalReceiptConflicts:this.admitted.filter(a=>{const t=this.events.find(e=>e.kind==='terminal'&&e.data.callId===a.data.callId),r=this.events.find(e=>e.kind==='receipt'&&e.data.id===a.data.receiptId);return t&&r&&t.data.status!==r.data.status;}).length,hostRejectedReceipts:this.events.filter(e=>e.kind==='host-rejection-receipt').length,receipts:this.events.filter(e=>e.kind==='receipt').length,failedReceipts:this.events.filter(e=>e.kind==='receipt'&&e.data.status==='failed').length,incompleteReceipts:this.events.filter(e=>e.kind==='receipt'&&(!e.data.tokens||e.data.tokens.complete!==true)).length,modelRunStarts:this.events.some(e=>e.kind==='terminal'&&e.data.modelRunStarts===null)?null:this.events.filter(e=>e.kind==='terminal').reduce((sum,e)=>sum+e.data.modelRunStarts,0),repairs:this.events.some(e=>e.kind==='terminal'&&e.data.repairs===null)?null:this.events.filter(e=>e.kind==='terminal').reduce((sum,e)=>sum+e.data.repairs,0),stopped:this.stopped,headHash:this.events.at(-1)!.sha256};}
  close(){closeSync(this.file);closeSync(this.lock);unlinkSync(join(this.directory,'writer.lock'));}
}

/** Explicit read-only diagnostic for recovery preparation; never used by normal live callers. */
export function inspectStoppedRecoveryLedger(directory:string,experimentHash:string){need(!existsSync(join(directory,'writer.lock')),'ledger_locked_unknown_interruption');const events=readAdmissionChain(directory);need(events[0]?.data.manifestHash===experimentHash&&events[0]?.data.cumulativeCap===124,'ledger_manifest_mismatch');need(events.some(e=>e.kind==='stop')&&!events.some(e=>e.kind==='recovery-authorized'),'recovery_original_stop_required');need(events.at(-1)?.kind==='stage-close'&&events.at(-1)?.data.succeeded===false,'recovery_failed_closed_boundary_required');return events;}
/** A partial or existing preparation is never overwritten, moved, or automatically resumed. */
export function reserveRecoveryPreparation(directory:string,experimentHash:string,stoppedHeadHash:string,recoveryId:string,output:string):RecoveryRef{let lock:number;try{lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}let fd:number|undefined,writing=false;try{const events=readAdmissionChain(directory);need(events[0]?.data.manifestHash===experimentHash&&events.at(-1)?.sha256===stoppedHeadHash&&!events.some(e=>e.kind==='recovery-authorized'),'recovery_preparation_head_changed');const path=join(directory,'recovery-preparation.json');need(!existsSync(path),'recovery_preparation_already_reserved');const bytes=JSON.stringify({schema:'mote-heldout-recovery-d-preparation@1',experimentHash,stoppedHeadHash,recoveryId,output})+'\n';fd=openSync(path,'wx',0o600);writing=true;writeSync(fd,bytes);fsyncSync(fd);writing=false;return {path,sha256:createHash('sha256').update(bytes).digest('hex')};}finally{if(fd!==undefined)closeSync(fd);closeSync(lock);if(!writing)unlinkSync(join(directory,'writer.lock'));}}

/** E is a separate, one-batch permission. It never broadens D's single-use policy. */
export const recoveryELimits={stageOuter:2,perOuterMs:600000,stageProcessMs:1320000,cumulativePlanningCap:124,automaticOuterRetries:0,concurrency:1} as const;
export type RecoveryERequest={schema:'mote-heldout-recovery-e-request@1';experimentHash:string;parentD:RecoveryLineage;stoppedHeadHash:string;failedSnapshotHash:string};
export type RecoveryEPlan={schema:'mote-heldout-recovery-e-plan@1';policy:'E-preserve-one-batch-600s@1';request:RecoveryRef;experimentHash:string;recoveryId:string;parentD:RecoveryLineage;stoppedHeadHash:string;stopHashes:string[];failedCloseHash:string;failedTerminalHash:string;failedReceiptHash:string;failedAdmissionHash:string;canonicalHeadHash:string;failedSnapshotHash:string;preparedSnapshotHash:string;oldWavePlan:RecoveryRef;newWavePlan:RecoveryRef;rootManifest:RecoveryRef;previousManifest:RecoveryRef;validation:RecoveryRef;supervisor:RecoveryRef;runtimeHash:string;productionHash:string;bindingsHash:string;oldSettingsHash:string;effectiveSettingsHash:string;target:{jobId:string;batchId:string;wave:2;index:0;chunks:8;priorAttempt:2;attempt:3};contextTime:string;targetStage:string;preparedPath:string;preparationCommitment:RecoveryRef;preparationExecutorHash:string;inheritedAdmissions:14;inheritedCompleted:12;inheritedFailed:2;inheritedUnknownUsage:2;effectiveCap:16;targetRetryCap:2;limits:typeof recoveryELimits};
export type RecoveryELineage={plan:RecoveryRef;eventHash:string};
const same=(a:unknown,b:unknown,code:string)=>need(JSON.stringify(a)===JSON.stringify(b),code);
function refJson(ref:RecoveryRef){need(ref&&Object.keys(ref).sort().join(',')==='path,sha256'&&typeof ref.path==='string'&&ref.path.startsWith('/')&&isHash(ref.sha256),'recovery_e_ref_invalid');const bytes=readFileSync(ref.path);need(createHash('sha256').update(bytes).digest('hex')===ref.sha256,'recovery_e_ref_changed');return JSON.parse(bytes.toString());}
export function readRecoveryERequest(ref:RecoveryRef):RecoveryERequest{const p=refJson(ref);need(p&&Object.keys(p).sort().join(',')==='experimentHash,failedSnapshotHash,parentD,schema,stoppedHeadHash'&&p.schema==='mote-heldout-recovery-e-request@1'&&isHash(p.experimentHash)&&isHash(p.stoppedHeadHash)&&isHash(p.failedSnapshotHash),'recovery_e_request_invalid');need(p.parentD&&Object.keys(p.parentD).sort().join(',')==='eventHash,plan'&&isHash(p.parentD.eventHash),'recovery_e_parent_invalid');readRecoveryPlan(p.parentD.plan);return p;}
export function readRecoveryEPlan(ref:RecoveryRef):RecoveryEPlan{const p=refJson(ref) as RecoveryEPlan;need(Object.keys(p).sort().join(',')==='bindingsHash,canonicalHeadHash,contextTime,effectiveCap,effectiveSettingsHash,experimentHash,failedAdmissionHash,failedCloseHash,failedReceiptHash,failedSnapshotHash,failedTerminalHash,inheritedAdmissions,inheritedCompleted,inheritedFailed,inheritedUnknownUsage,limits,newWavePlan,oldSettingsHash,oldWavePlan,parentD,policy,preparationCommitment,preparationExecutorHash,preparedPath,preparedSnapshotHash,previousManifest,productionHash,recoveryId,request,rootManifest,runtimeHash,schema,stopHashes,stoppedHeadHash,supervisor,target,targetRetryCap,targetStage,validation','recovery_e_plan_fields_changed');need(p.schema==='mote-heldout-recovery-e-plan@1'&&p.policy==='E-preserve-one-batch-600s@1'&&/^[0-9a-f-]{36}$/.test(p.recoveryId),'recovery_e_plan_invalid');same(p.limits,recoveryELimits,'recovery_e_limits_changed');need(p.inheritedAdmissions===14&&p.inheritedCompleted===12&&p.inheritedFailed===2&&p.inheritedUnknownUsage===2&&p.effectiveCap===16&&p.targetRetryCap===2,'recovery_e_budget_changed');need(p.target?.wave===2&&p.target.index===0&&p.target.chunks===8&&p.target.priorAttempt===2&&p.target.attempt===3&&typeof p.target.jobId==='string'&&typeof p.target.batchId==='string'&&Object.keys(p.target).sort().join(',')==='attempt,batchId,chunks,index,jobId,priorAttempt,wave','recovery_e_target_changed');need(p.targetStage===`wave2-recovery-E-${p.recoveryId}-batch-0`,'recovery_e_stage_changed');const request=readRecoveryERequest(p.request);same({experimentHash:p.experimentHash,parentD:p.parentD,stoppedHeadHash:p.stoppedHeadHash,failedSnapshotHash:p.failedSnapshotHash},{experimentHash:request.experimentHash,parentD:request.parentD,stoppedHeadHash:request.stoppedHeadHash,failedSnapshotHash:request.failedSnapshotHash},'recovery_e_request_binding_changed');return p;}
/** Read-only validation of exactly the D failure, including the entire old D prefix. */
export function stoppedRecoveryE(events:LedgerEvent[],request:RecoveryERequest){need(!events.some(e=>e.kind==='recovery-e-authorized'),'recovery_e_already_authorized');need(events[0]?.data.manifestHash===request.experimentHash&&events[0]?.data.cumulativeCap===124&&events.at(-1)?.sha256===request.stoppedHeadHash,'recovery_e_stopped_head_changed');need(!events.some(e=>e.kind==='recovery-e-authorized'),'recovery_e_already_authorized');const ds=events.filter(e=>e.kind==='recovery-authorized');need(ds.length===1&&ds[0].sha256===request.parentD.eventHash,'recovery_e_d_event_changed');const after=events.slice(ds[0].index+1),stops=after.filter(e=>e.kind==='stop');need(stops.length===1&&stops[0].data.code==='outer_deadline_exceeded','recovery_e_d_stop_changed');const d=recoveryAuthorization(events.slice(0,stops[0].index),request.parentD)!;const admits=events.filter(e=>e.kind==='admit'),terminals=events.filter(e=>e.kind==='terminal'),receipts=events.filter(e=>e.kind==='receipt'),closes=events.filter(e=>e.kind==='stage-close');need(admits.length===14&&terminals.length===14&&receipts.length===14&&terminals.filter(e=>e.data.status==='completed').length===12&&terminals.filter(e=>e.data.status==='failed').length===2&&receipts.filter(e=>!e.data.tokens||e.data.tokens.complete!==true).length===2,'recovery_e_history_changed');need(!events.some(e=>e.kind==='host-rejection-receipt'),'recovery_e_host_rejection_present');for(const a of admits){const ts=terminals.filter(t=>t.data.callId===a.data.callId),rs=receipts.filter(r=>r.data.id===a.data.receiptId);need(ts.length===1&&rs.length===1&&ts[0].data.status===rs[0].data.status&&['completed','failed'].includes(rs[0].data.status),'recovery_e_unknown_accounting');}need(events.filter(e=>e.kind==='stage-open').every(e=>closes.filter(c=>c.data.stage===e.data.stage).length===1),'recovery_e_unclosed_stage');const ad=after.filter(e=>e.kind==='admit'),ts=after.filter(e=>e.kind==='terminal'),rs=after.filter(e=>e.kind==='receipt'),cs=after.filter(e=>e.kind==='stage-close'),opens=after.filter(e=>e.kind==='stage-open');need(ad.length===1&&ts.length===1&&rs.length===1&&cs.length===1&&opens.length===1&&cs[0]===events.at(-1),'recovery_e_d_stage_changed');need(ad[0].data.stage===d.targetStage&&ts[0].data.callId===ad[0].data.callId&&ts[0].data.status==='failed'&&ts[0].data.safeCode==='outer_deadline_exceeded'&&rs[0].data.id===ad[0].data.receiptId&&rs[0].data.status==='failed'&&(!rs[0].data.tokens||rs[0].data.tokens.complete===false)&&cs[0].data.stage===d.targetStage&&cs[0].data.succeeded===false&&cs[0].data.snapshotHash===request.failedSnapshotHash&&opens[0].data.parentHash===d.preparedSnapshotHash,'recovery_e_d_failure_changed');return {d,admission:ad[0],terminal:ts[0],receipt:rs[0],closure:cs[0]};}
export function validateRecoveryEPrefix(events:LedgerEvent[],ref:RecoveryRef){const p=readRecoveryEPlan(ref),request=readRecoveryERequest(p.request),prior=stoppedRecoveryE(events,request);same(p.stopHashes,events.filter(e=>e.kind==='stop').map(e=>e.sha256),'recovery_e_stops_changed');same([p.failedAdmissionHash,p.failedTerminalHash,p.failedReceiptHash,p.failedCloseHash],[prior.admission.sha256,prior.terminal.sha256,prior.receipt.sha256,prior.closure.sha256],'recovery_e_failure_binding_changed');need(p.canonicalHeadHash===prior.d.canonicalHeadHash,'recovery_e_canonical_changed');same(p.oldWavePlan,prior.d.newWavePlan,'recovery_e_old_plan_changed');need(prior.admission.data.logicalKey===hash([p.target.jobId,p.target.batchId,'extract',p.parentD.plan.sha256,2]),'recovery_e_d_phase_changed');const commitment=refJson(p.preparationCommitment);same(commitment,{schema:'mote-heldout-recovery-e-preparation@1',experimentHash:p.experimentHash,stoppedHeadHash:p.stoppedHeadHash,recoveryId:p.recoveryId,request:p.request,output:commitment.output},'recovery_e_commitment_changed');need(typeof commitment.output==='string'&&join(commitment.output,'DO_NOT_OPEN','prepared-checkpoint')===p.preparedPath,'recovery_e_commitment_output_changed');return p;}
export function recoveryEAuthorization(events:LedgerEvent[],lineage:RecoveryELineage){const es=events.filter(e=>e.kind==='recovery-e-authorized');need(es.length===1&&es[0].sha256===lineage.eventHash,'recovery_e_event_changed');same(es[0].data.plan,lineage.plan,'recovery_e_event_plan_changed');const p=validateRecoveryEPrefix(events.slice(0,es[0].index),lineage.plan);need(es[0].previous===p.stoppedHeadHash&&es[0].data.preparedSnapshotHash===p.preparedSnapshotHash,'recovery_e_event_parent_changed');need(!events.slice(es[0].index+1).some(e=>['stop','stage-open','admit'].includes(e.kind)),'recovery_e_already_consumed');return p;}
export function reserveRecoveryEPreparation(directory:string,requestRef:RecoveryRef,recoveryId:string,output:string):RecoveryRef{let lock:number;try{lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}let fd:number|undefined,writing=false;try{const request=readRecoveryERequest(requestRef);stoppedRecoveryE(readAdmissionChain(directory),request);const path=join(directory,'recovery-e-preparation.json');need(!existsSync(path),'recovery_e_preparation_already_reserved');const bytes=JSON.stringify({schema:'mote-heldout-recovery-e-preparation@1',experimentHash:request.experimentHash,stoppedHeadHash:request.stoppedHeadHash,recoveryId,request:requestRef,output})+'\n';fd=openSync(path,'wx',0o600);writing=true;writeSync(fd,bytes);fsyncSync(fd);writing=false;return {path,sha256:createHash('sha256').update(bytes).digest('hex')};}finally{if(fd!==undefined)closeSync(fd);closeSync(lock);if(!writing)unlinkSync(join(directory,'writer.lock'));}}
export function authorizeRecoveryE(directory:string,plan:RecoveryRef):RecoveryELineage{let lock:number;try{lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}let fd:number|undefined,writing=false;try{const events=readAdmissionChain(directory),p=validateRecoveryEPrefix(events,plan);const body={index:events.length,at:new Date().toISOString(),previous:p.stoppedHeadHash,kind:'recovery-e-authorized',data:{plan,preparedSnapshotHash:p.preparedSnapshotHash}},row={...body,sha256:hash(body)};fd=openSync(join(directory,'admissions.ndjson'),'a',0o600);writing=true;writeSync(fd,JSON.stringify(row)+'\n');fsyncSync(fd);writing=false;return {plan,eventHash:row.sha256};}finally{if(fd!==undefined)closeSync(fd);closeSync(lock);if(!writing)unlinkSync(join(directory,'writer.lock'));}}

/** One explicit continuation after the completed E boundary. Old D/E APIs remain closed. */
export type NormalContinuation={plan:RecoveryRef;eventHash:string};
export type NormalRequest={schema:'mote-heldout-normal-continuation-request@1';experimentHash:string;parentE:RecoveryELineage;successCloseHash:string;stoppedHeadHash:string;successSnapshotHash:string};
export type NormalPlan={schema:'mote-heldout-normal-continuation-plan@1';policy:'normal-memory-600-ask-300@1';request:RecoveryRef;experimentHash:string;continuationId:string;parentE:RecoveryELineage;successCloseHash:string;stoppedHeadHash:string;successSnapshotHash:string;stopHashes:string[];rootManifest:RecoveryRef;previousManifest:RecoveryRef;validation:RecoveryRef;supervisor:RecoveryRef;runtimeHash:string;productionHash:string;bindingsHash:string;oldSettingsHash:string;effectiveSettingsHash:string;oldWavePlan:RecoveryRef;newWavePlan:RecoveryRef;contextTime:string;preparedPath:string;preparedSnapshotHash:string;preparationCommitment:RecoveryRef;preparationExecutorHash:string;inheritedAdmissions:16;inheritedCompleted:14;inheritedFailed:2;inheritedUnknownUsage:2;cumulativeCap:124;remainingOuterMax:106;backgroundPerOuterMs:600000;askPerOuterMs:300000;start:{wave:2;index:1;totalBatches:6}};
export const normalLimits={ingress:{stageOuter:0,perOuterMs:600000,stageProcessMs:720000,cumulativePlanningCap:124,automaticOuterRetries:0,concurrency:1},extraction:{stageOuter:2,perOuterMs:600000,stageProcessMs:1320000,cumulativePlanningCap:124,automaticOuterRetries:0,concurrency:1},integration:{stageOuter:4,perOuterMs:600000,stageProcessMs:2520000,cumulativePlanningCap:124,automaticOuterRetries:0,concurrency:1},evaluation:{stageOuter:2,perOuterMs:300000,stageProcessMs:720000,cumulativePlanningCap:124,automaticOuterRetries:0,concurrency:1}} as const;
export function readNormalRequest(ref:RecoveryRef):NormalRequest{const r=refJson(ref);need(r&&Object.keys(r).sort().join(',')==='experimentHash,parentE,schema,stoppedHeadHash,successCloseHash,successSnapshotHash'&&r.schema==='mote-heldout-normal-continuation-request@1'&&[r.experimentHash,r.stoppedHeadHash,r.successCloseHash,r.successSnapshotHash].every(isHash),'normal_request_invalid');need(r.parentE&&Object.keys(r.parentE).sort().join(',')==='eventHash,plan'&&isHash(r.parentE.eventHash),'normal_parent_invalid');readRecoveryEPlan(r.parentE.plan);return r;}
export function successfulE(events:LedgerEvent[],r:NormalRequest){need(!events.some(e=>e.kind==='normal-continuation-authorized'),'normal_already_authorized');need(events[0]?.data.manifestHash===r.experimentHash&&events.at(-1)?.sha256===r.stoppedHeadHash,'normal_success_head_changed');const es=events.filter(e=>e.kind==='recovery-e-authorized');need(es.length===1&&es[0].sha256===r.parentE.eventHash,'normal_e_event_changed');const ep=recoveryEAuthorization(events.slice(0,es[0].index+1),r.parentE),after=events.slice(es[0].index+1),by=(kind:string)=>after.filter(e=>e.kind===kind),ad=by('admit'),ts=by('terminal'),rs=by('receipt'),cs=by('stage-close'),ss=by('stop'),os=by('stage-open');need(ad.length===2&&ts.length===2&&rs.length===2&&cs.length===1&&ss.length===1&&os.length===1&&!by('host-rejection-receipt').length,'normal_e_accounting_changed');need(ss[0]===events.at(-1)&&ss[0].data.code==='recovery_e_complete'&&cs[0]===events.at(-2)&&cs[0].sha256===r.successCloseHash&&cs[0].data.succeeded===true&&cs[0].data.snapshotHash===r.successSnapshotHash&&cs[0].data.stage===ep.targetStage&&os[0].data.stage===ep.targetStage&&os[0].data.parentHash===ep.preparedSnapshotHash&&os[0].data.maxCalls===2,'normal_success_boundary_changed');same(cs[0].data.phase,{kind:'extraction',wave:2,contextTime:ep.contextTime,archiveHeadHash:r.successSnapshotHash,totalBatches:6,nextBatch:1,evaluatedPairs:0,wavePlan:ep.newWavePlan},'normal_success_phase_changed');for(let i=0;i<2;i++){need(ad[i].data.stage===ep.targetStage&&ad[i].data.logicalKey===hash([ep.target.jobId,ep.target.batchId,i===0?'extract':'review',r.parentE.plan.sha256,3]),'normal_e_call_scope_changed');need(ts.filter(t=>t.data.callId===ad[i].data.callId&&t.data.status==='completed').length===1&&rs.filter(v=>v.data.id===ad[i].data.receiptId&&v.data.status==='completed'&&v.data.tokens?.complete===true).length===1,'normal_e_receipt_changed');}const all=(kind:string)=>events.filter(e=>e.kind===kind);need(all('admit').length===16&&all('terminal').length===16&&all('receipt').length===16&&all('terminal').filter(e=>e.data.status==='completed').length===14&&all('terminal').filter(e=>e.data.status==='failed').length===2&&all('receipt').filter(e=>e.data.tokens?.complete!==true).length===2,'normal_history_changed');need(all('stop').length===3,'normal_stop_set_changed');return ep;}
export function readNormalPlan(ref:RecoveryRef):NormalPlan{const p=refJson(ref) as NormalPlan;need(Object.keys(p).sort().join(',')==='askPerOuterMs,backgroundPerOuterMs,bindingsHash,contextTime,continuationId,cumulativeCap,effectiveSettingsHash,experimentHash,inheritedAdmissions,inheritedCompleted,inheritedFailed,inheritedUnknownUsage,newWavePlan,oldSettingsHash,oldWavePlan,parentE,policy,preparationCommitment,preparationExecutorHash,preparedPath,preparedSnapshotHash,previousManifest,productionHash,remainingOuterMax,request,rootManifest,runtimeHash,schema,start,stopHashes,stoppedHeadHash,successCloseHash,successSnapshotHash,supervisor,validation','normal_plan_fields_changed');need(p.schema==='mote-heldout-normal-continuation-plan@1'&&p.policy==='normal-memory-600-ask-300@1'&&/^[0-9a-f-]{36}$/.test(p.continuationId),'normal_plan_invalid');need(p.inheritedAdmissions===16&&p.inheritedCompleted===14&&p.inheritedFailed===2&&p.inheritedUnknownUsage===2&&p.cumulativeCap===124&&p.remainingOuterMax===106&&p.backgroundPerOuterMs===600000&&p.askPerOuterMs===300000,'normal_policy_changed');same(p.start,{wave:2,index:1,totalBatches:6},'normal_start_changed');const r=readNormalRequest(p.request);for(const k of ['experimentHash','parentE','successCloseHash','stoppedHeadHash','successSnapshotHash'] as const)same(p[k],r[k],'normal_request_binding_changed');return p;}
export function validateNormalPrefix(events:LedgerEvent[],ref:RecoveryRef){const p=readNormalPlan(ref),ep=successfulE(events,readNormalRequest(p.request));same(p.stopHashes,events.filter(e=>e.kind==='stop').map(e=>e.sha256),'normal_stops_changed');same(p.rootManifest,ep.rootManifest,'normal_root_changed');same(p.oldWavePlan,ep.newWavePlan,'normal_old_plan_changed');need(p.oldSettingsHash===ep.oldSettingsHash&&p.effectiveSettingsHash===ep.effectiveSettingsHash&&p.bindingsHash===ep.bindingsHash&&p.contextTime===ep.contextTime&&p.runtimeHash===ep.runtimeHash&&p.productionHash===ep.productionHash,'normal_ancestor_pins_changed');const c=refJson(p.preparationCommitment);same(c,{schema:'mote-heldout-normal-preparation@1',experimentHash:p.experimentHash,stoppedHeadHash:p.stoppedHeadHash,continuationId:p.continuationId,request:p.request,output:c.output},'normal_commitment_changed');need(typeof c.output==='string'&&join(c.output,'DO_NOT_OPEN','prepared-checkpoint')===p.preparedPath,'normal_commitment_output_changed');return p;}
export function normalAuthorization(events:LedgerEvent[],lineage:NormalContinuation,review?:NormalReviewRecovery,ask?:AskRecovery){need(lineage&&Object.keys(lineage).sort().join(',')==='eventHash,plan'&&isHash(lineage.eventHash),'normal_lineage_invalid');const ns=events.filter(e=>e.kind==='normal-continuation-authorized');need(ns.length===1&&ns[0].sha256===lineage.eventHash,'normal_event_changed');same(ns[0].data.plan,lineage.plan,'normal_event_plan_changed');const p=validateNormalPrefix(events.slice(0,ns[0].index),lineage.plan);need(ns[0].previous===p.stoppedHeadHash&&ns[0].data.preparedSnapshotHash===p.preparedSnapshotHash,'normal_event_parent_changed');if(review){const r=normalReviewAuthorization(events,lineage,review,ask);return {...p,stopHashes:r.stopHashes};}need(!events.slice(ns[0].index+1).some(e=>e.kind==='stop'||e.kind==='recovery-authorized'||e.kind==='recovery-e-authorized'||e.kind==='normal-review-recovery-authorized'),'normal_new_stop_forbidden');return p;}
export function reserveNormalPreparation(directory:string,request:RecoveryRef,continuationId:string,output:string):RecoveryRef{let lock:number;try{lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}let fd:number|undefined,writing=false;try{const r=readNormalRequest(request);successfulE(readAdmissionChain(directory),r);const path=join(directory,'normal-preparation.json');need(!existsSync(path),'normal_preparation_already_reserved');const bytes=JSON.stringify({schema:'mote-heldout-normal-preparation@1',experimentHash:r.experimentHash,stoppedHeadHash:r.stoppedHeadHash,continuationId,request,output})+'\n';fd=openSync(path,'wx',0o600);writing=true;writeSync(fd,bytes);fsyncSync(fd);writing=false;return {path,sha256:createHash('sha256').update(bytes).digest('hex')};}finally{if(fd!==undefined)closeSync(fd);closeSync(lock);if(!writing)unlinkSync(join(directory,'writer.lock'));}}
export function authorizeNormal(directory:string,plan:RecoveryRef):NormalContinuation{let lock:number;try{lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}let fd:number|undefined,writing=false;try{const events=readAdmissionChain(directory),p=validateNormalPrefix(events,plan),body={index:events.length,at:new Date().toISOString(),previous:p.stoppedHeadHash,kind:'normal-continuation-authorized',data:{plan,preparedSnapshotHash:p.preparedSnapshotHash}},row={...body,sha256:hash(body)};fd=openSync(join(directory,'admissions.ndjson'),'a',0o600);writing=true;writeSync(fd,JSON.stringify(row)+'\n');fsyncSync(fd);writing=false;return {plan,eventHash:row.sha256};}finally{if(fd!==undefined)closeSync(fd);closeSync(lock);if(!writing)unlinkSync(join(directory,'writer.lock'));}}

/** One exact failed review may resume the existing normal sequence; no generic retry policy. */
export type NormalReviewRecovery={plan:RecoveryRef;eventHash:string};
type ReviewCallPin={admissionHash:string;terminalHash:string;receiptHash:string};
export type NormalReviewRequest={schema:'mote-heldout-normal-review-recovery-request@1';experimentHash:string;normalContinuation:NormalContinuation;previousManifest:RecoveryRef;stoppedHeadHash:string;failedCloseHash:string;failedStopHash:string;failedSnapshotHash:string;canonicalSnapshotHash:string;target:{wave:2;index:2;jobId:string;batchId:string;failedAttempt:1;retryAttempt:2;chunks:4;inputIdentityHash:string};draft:{inputHash:string;jsonSha256:string;bytes:number;shared:true;exactMatches:1;candidates:4};generation:ReviewCallPin;failedReview:ReviewCallPin};
export const normalReviewLimits={stageOuter:1,perOuterMs:600000,stageProcessMs:720000,cumulativePlanningCap:124,automaticOuterRetries:0,concurrency:1} as const;
export type NormalReviewPlan=Omit<NormalReviewRequest,'schema'>&{schema:'mote-heldout-normal-review-recovery-plan@1';policy:'normal-exact-review-once@1';request:RecoveryRef;recoveryId:string;stopHashes:string[];rootManifest:RecoveryRef;validation:RecoveryRef;oldSupervisor:RecoveryRef;supervisor:RecoveryRef;runtimeHash:string;productionHash:string;bindingsHash:string;settingsHash:string;oldWavePlan:RecoveryRef;newWavePlan:RecoveryRef;contextTime:string;failedSnapshotPath:string;canonicalSnapshotPath:string;preparedPath:string;preparedSnapshotHash:string;preparationCommitment:RecoveryRef;preparationExecutorHash:string;generationInput:RecoveryRef;generationResult:RecoveryRef;draftPayloadHash:string;targetStage:string;inheritedAdmissions:20;inheritedCompleted:17;inheritedFailed:3;inheritedUnknownUsage:3;targetRetryCap:1;recoveryCumulativeCap:21;cumulativeCap:124;completeRunPlanningCeiling:123;backgroundPerOuterMs:600000;askPerOuterMs:300000;limits:typeof normalReviewLimits};
const reviewRequestKeys='canonicalSnapshotHash,draft,experimentHash,failedCloseHash,failedReview,failedSnapshotHash,failedStopHash,generation,normalContinuation,previousManifest,schema,stoppedHeadHash,target';
const exactKeys=(value:any,keys:string,code:string)=>need(value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join(',')===keys,code);
export function readNormalReviewRequest(ref:RecoveryRef):NormalReviewRequest{
 const r=refJson(ref) as NormalReviewRequest;exactKeys(r,reviewRequestKeys,'normal_review_request_invalid');need(r.schema==='mote-heldout-normal-review-recovery-request@1'&&[r.experimentHash,r.stoppedHeadHash,r.failedCloseHash,r.failedStopHash,r.failedSnapshotHash,r.canonicalSnapshotHash].every(isHash),'normal_review_request_invalid');exactKeys(r.normalContinuation,'eventHash,plan','normal_review_parent_invalid');need(isHash(r.normalContinuation.eventHash),'normal_review_parent_invalid');readNormalPlan(r.normalContinuation.plan);refJson(r.previousManifest);
 exactKeys(r.target,'batchId,chunks,failedAttempt,index,inputIdentityHash,jobId,retryAttempt,wave','normal_review_target_invalid');need(r.target.wave===2&&r.target.index===2&&r.target.failedAttempt===1&&r.target.retryAttempt===2&&r.target.chunks===4&&[r.target.jobId,r.target.batchId].every(v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f-]{27}$/.test(v))&&isHash(r.target.inputIdentityHash),'normal_review_target_invalid');
 exactKeys(r.draft,'bytes,candidates,exactMatches,inputHash,jsonSha256,shared','normal_review_draft_invalid');need(r.draft.shared===true&&r.draft.exactMatches===1&&r.draft.candidates===4&&Number.isSafeInteger(r.draft.bytes)&&r.draft.bytes>0&&r.draft.bytes<=512*1024&&isHash(r.draft.inputHash)&&isHash(r.draft.jsonSha256),'normal_review_draft_invalid');for(const pin of [r.generation,r.failedReview]){exactKeys(pin,'admissionHash,receiptHash,terminalHash','normal_review_call_pin_invalid');need(Object.values(pin).every(isHash),'normal_review_call_pin_invalid');}return r;
}
export function stoppedNormalReview(events:LedgerEvent[],r:NormalReviewRequest){
 need(!events.some(e=>e.kind==='normal-review-recovery-authorized'),'normal_review_already_authorized');need(events[0]?.data.manifestHash===r.experimentHash&&events.at(-1)?.sha256===r.stoppedHeadHash,'normal_review_head_changed');const normalEvent=events.find(e=>e.sha256===r.normalContinuation.eventHash);need(normalEvent,'normal_review_parent_missing');const after=events.filter(e=>e.index>normalEvent!.index),stops=after.filter(e=>e.kind==='stop');need(stops.length===1&&stops[0].sha256===r.failedStopHash&&stops[0].data.code==='outer_failed','normal_review_stop_changed');const p=normalAuthorization(events.slice(0,stops[0].index),r.normalContinuation);
 const all=(kind:string)=>events.filter(e=>e.kind===kind),ad=all('admit'),ts=all('terminal'),rs=all('receipt'),opens=all('stage-open'),closes=all('stage-close');need(ad.length===20&&ts.length===20&&rs.length===20&&ts.filter(e=>e.data.status==='completed').length===17&&ts.filter(e=>e.data.status==='failed').length===3&&rs.filter(e=>e.data.tokens?.complete!==true).length===3,'normal_review_history_changed');need(!all('host-rejection-receipt').length&&opens.every(o=>closes.filter(c=>c.data.stage===o.data.stage).length===1),'normal_review_accounting_unknown');for(const a of ad){const t=ts.filter(t=>t.data.callId===a.data.callId),u=rs.filter(u=>u.data.id===a.data.receiptId);need(t.length===1&&u.length===1&&t[0].data.status===u[0].data.status&&['completed','failed'].includes(u[0].data.status),'normal_review_receipt_conflict');}
 const closure=closes.at(-1)!;need(closure===events.at(-1)&&closure.sha256===r.failedCloseHash&&closure.data.stage==='wave2-batch-2'&&closure.data.succeeded===false&&closure.data.snapshotHash===r.failedSnapshotHash,'normal_review_failed_close_changed');const open=opens.find(o=>o.data.stage===closure.data.stage)!;need(open&&open.data.parentHash===r.canonicalSnapshotHash&&open.data.maxCalls===2,'normal_review_canonical_changed');const stageAd=ad.filter(a=>a.data.stage===closure.data.stage);need(stageAd.length===2,'normal_review_failed_stage_changed');
 for(const [i,pin,status,code] of [[0,r.generation,'completed','ok'],[1,r.failedReview,'failed','outer_failed']] as const){const a=stageAd[i],t=ts.find(t=>t.data.callId===a.data.callId)!,u=rs.find(u=>u.data.id===a.data.receiptId)!;same([a.sha256,t.sha256,u.sha256],[pin.admissionHash,pin.terminalHash,pin.receiptHash],'normal_review_call_binding_changed');need(a.data.logicalKey===hash([r.target.jobId,r.target.batchId,i===0?'extract':'review'])&&t.data.status===status&&t.data.safeCode===code&&u.data.status===status,'normal_review_phase_binding_changed');if(i===0)need(u.data.tokens?.complete===true,'normal_review_generation_usage_unknown');}
 const before=closes.filter(c=>c.index<open.index).at(-1)!;need(before?.data.succeeded===true&&before.data.snapshotHash===r.canonicalSnapshotHash&&before.data.phase?.kind==='extraction'&&before.data.phase.wave===2&&before.data.phase.nextBatch===2&&before.data.phase.totalBatches===6,'normal_review_not_next_batch');need(events.filter(e=>e.kind==='executor-freeze').at(-1)?.data.manifestHash===r.previousManifest.sha256,'normal_review_previous_executor_changed');return {normal:p,open,closure,generation:stageAd[0],failedReview:stageAd[1]};
}
export function readNormalReviewPlan(ref:RecoveryRef):NormalReviewPlan{
 const p=refJson(ref) as NormalReviewPlan;const extra='askPerOuterMs,backgroundPerOuterMs,bindingsHash,canonicalSnapshotPath,completeRunPlanningCeiling,contextTime,cumulativeCap,draftPayloadHash,failedSnapshotPath,generationInput,generationResult,inheritedAdmissions,inheritedCompleted,inheritedFailed,inheritedUnknownUsage,limits,newWavePlan,oldSupervisor,oldWavePlan,policy,preparationCommitment,preparationExecutorHash,preparedPath,preparedSnapshotHash,productionHash,recoveryCumulativeCap,recoveryId,request,rootManifest,runtimeHash,settingsHash,stopHashes,supervisor,targetRetryCap,targetStage,validation'.split(',');exactKeys(p,[...reviewRequestKeys.split(','),...extra].sort().join(','),'normal_review_plan_fields_changed');need(p.schema==='mote-heldout-normal-review-recovery-plan@1'&&p.policy==='normal-exact-review-once@1'&&/^[0-9a-f-]{36}$/.test(p.recoveryId),'normal_review_plan_invalid');const r=readNormalReviewRequest(p.request);for(const key of Object.keys(r).filter(k=>k!=='schema') as Array<keyof Omit<NormalReviewRequest,'schema'>>)same(p[key],r[key],'normal_review_request_binding_changed');same(p.limits,normalReviewLimits,'normal_review_limits_changed');need(p.inheritedAdmissions===20&&p.inheritedCompleted===17&&p.inheritedFailed===3&&p.inheritedUnknownUsage===3&&p.targetRetryCap===1&&p.recoveryCumulativeCap===21&&p.cumulativeCap===124&&p.completeRunPlanningCeiling===123&&p.backgroundPerOuterMs===600000&&p.askPerOuterMs===300000,'normal_review_budget_changed');need(p.targetStage===`wave2-normal-review-${p.recoveryId}-batch-2`&&[p.preparedSnapshotHash,p.preparationExecutorHash,p.productionHash,p.runtimeHash,p.settingsHash,p.bindingsHash,p.draftPayloadHash].every(isHash),'normal_review_plan_binding_invalid');return p;
}
export function validateNormalReviewPrefix(events:LedgerEvent[],ref:RecoveryRef){const p=readNormalReviewPlan(ref),prior=stoppedNormalReview(events,readNormalReviewRequest(p.request));same(p.stopHashes,events.filter(e=>e.kind==='stop').map(e=>e.sha256),'normal_review_stops_changed');same(p.rootManifest,prior.normal.rootManifest,'normal_review_root_changed');same(p.oldSupervisor,prior.normal.supervisor,'normal_review_old_supervisor_changed');need(p.runtimeHash===prior.normal.runtimeHash&&p.productionHash===prior.normal.productionHash&&p.settingsHash===prior.normal.effectiveSettingsHash&&p.bindingsHash===prior.normal.bindingsHash&&p.contextTime===prior.normal.contextTime,'normal_review_inherited_pins_changed');const previous=refJson(p.previousManifest);same(previous.normalContinuation,p.normalContinuation,'normal_review_previous_normal_changed');same(previous.task,{kind:'extraction',wave:2,contextTime:p.contextTime,index:2,wavePlan:p.oldWavePlan},'normal_review_previous_task_changed');need(!previous.normalReviewRecovery&&!previous.recoveryLineage&&!previous.recoveryE,'normal_review_previous_scope_changed');const commitment=refJson(p.preparationCommitment);same(commitment,{schema:'mote-heldout-normal-review-preparation@1',experimentHash:p.experimentHash,stoppedHeadHash:p.stoppedHeadHash,recoveryId:p.recoveryId,request:p.request,output:commitment.output},'normal_review_commitment_changed');need(join(commitment.output,'DO_NOT_OPEN','prepared-checkpoint')===p.preparedPath,'normal_review_prepared_path_changed');return p;}
export function normalReviewAuthorization(events:LedgerEvent[],normal:NormalContinuation,proof:NormalReviewRecovery,ask?:AskRecovery):NormalReviewPlan{
 if(ask){const recovery=askRecoveryAuthorization(events,ask,normal,proof),origin=events.find(e=>e.sha256===recovery.failedStopHash)!;const p=normalReviewAuthorization(events.slice(0,origin.index),normal,proof);return {...p,stopHashes:recovery.stopHashes};}
 exactKeys(proof,'eventHash,plan','normal_review_proof_invalid');need(isHash(proof.eventHash),'normal_review_proof_invalid');const es=events.filter(e=>e.kind==='normal-review-recovery-authorized');need(es.length===1&&es[0].sha256===proof.eventHash,'normal_review_event_changed');const event=es[0];same(event.data.plan,proof.plan,'normal_review_event_plan_changed');const p=validateNormalReviewPrefix(events.slice(0,event.index),proof.plan);same(p.normalContinuation,normal,'normal_review_normal_changed');need(event.previous===p.stoppedHeadHash&&event.data.preparedSnapshotHash===p.preparedSnapshotHash,'normal_review_event_parent_changed');normalReviewCorrection(events,proof);const after=events.slice(event.index+1);need(!after.some(e=>['stop','recovery-authorized','recovery-e-authorized','normal-continuation-authorized','normal-review-recovery-authorized','host-rejection-receipt'].includes(e.kind)),'normal_review_new_stop_forbidden');
 const opens=after.filter(e=>e.kind==='stage-open'),closed=after.filter(e=>e.kind==='stage-close'&&e.data.stage===p.targetStage),ad=after.filter(e=>e.kind==='admit'&&e.data.stage===p.targetStage);need(closed.length<=1&&ad.length<=1,'normal_review_consumed_twice');if(opens.length)need(opens[0].data.stage===p.targetStage&&opens[0].data.parentHash===p.preparedSnapshotHash&&opens[0].data.maxCalls===1,'normal_review_first_stage_changed');for(const a of ad)need(a.data.logicalKey===hash([p.target.jobId,p.target.batchId,'review',proof.plan.sha256,2]),'normal_review_admission_changed');
 if(closed.length){const c=closed[0];need(c.data.succeeded===true&&ad.length===1&&ad[0].index<c.index,'normal_review_success_invalid');const t=after.filter(e=>e.kind==='terminal'&&e.data.callId===ad[0].data.callId),u=after.filter(e=>e.kind==='receipt'&&e.data.id===ad[0].data.receiptId);need(t.length===1&&u.length===1&&t[0].index<c.index&&u[0].index<c.index&&t[0].data.status==='completed'&&u[0].data.status==='completed','normal_review_success_receipt_unknown');same(c.data.phase,{kind:'extraction',wave:2,contextTime:p.contextTime,archiveHeadHash:c.data.snapshotHash,totalBatches:6,nextBatch:3,evaluatedPairs:0,wavePlan:p.newWavePlan},'normal_review_success_cursor_changed');need(opens.slice(1).every(o=>o.index>c.index),'normal_review_next_stage_before_success');}
 else need(opens.length<=1&&after.filter(e=>e.kind==='admit').every(e=>e.data.stage===p.targetStage),'normal_review_success_required');return p;
}
export function reserveNormalReviewPreparation(directory:string,request:RecoveryRef,recoveryId:string,output:string):RecoveryRef{let lock:number;try{lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}let fd:number|undefined,writing=false;try{const r=readNormalReviewRequest(request);stoppedNormalReview(readAdmissionChain(directory),r);const path=join(directory,'normal-review-preparation.json');need(!existsSync(path),'normal_review_preparation_already_reserved');const bytes=JSON.stringify({schema:'mote-heldout-normal-review-preparation@1',experimentHash:r.experimentHash,stoppedHeadHash:r.stoppedHeadHash,recoveryId,request,output})+'\n';fd=openSync(path,'wx',0o600);writing=true;writeSync(fd,bytes);fsyncSync(fd);writing=false;return {path,sha256:createHash('sha256').update(bytes).digest('hex')};}finally{if(fd!==undefined)closeSync(fd);closeSync(lock);if(!writing)unlinkSync(join(directory,'writer.lock'));}}
export function authorizeNormalReview(directory:string,plan:RecoveryRef):NormalReviewRecovery{let lock:number;try{lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}let fd:number|undefined,writing=false;try{const events=readAdmissionChain(directory),p=validateNormalReviewPrefix(events,plan),body={index:events.length,at:new Date().toISOString(),previous:p.stoppedHeadHash,kind:'normal-review-recovery-authorized',data:{plan,preparedSnapshotHash:p.preparedSnapshotHash}},event={...body,sha256:hash(body)};fd=openSync(join(directory,'admissions.ndjson'),'a',0o600);writing=true;writeSync(fd,JSON.stringify(event)+'\n');fsyncSync(fd);writing=false;return {plan,eventHash:event.sha256};}finally{if(fd!==undefined)closeSync(fd);closeSync(lock);if(!writing)unlinkSync(join(directory,'writer.lock'));}}

/** A correction never changes the original authorization or paid logical keys. */
export type NormalReviewCorrection={authorization:NormalReviewRecovery;oldExecutors:Record<string,string>;newExecutors:Record<string,string>;validation:RecoveryRef};
export function validateNormalReviewCorrection(data:NormalReviewCorrection,proof:NormalReviewRecovery){
 exactKeys(data,'authorization,newExecutors,oldExecutors,validation','normal_review_correction_shape');same(data.authorization,proof,'normal_review_correction_parent');
 const p=readNormalReviewPlan(proof.plan),old=refJson(p.validation),next=refJson(data.validation);
 same(data.oldExecutors,old.executorCodeHashes,'normal_review_correction_old_executor');need(hash(data.oldExecutors)===p.preparationExecutorHash,'normal_review_correction_old_executor');
 same(Object.keys(data.newExecutors).sort(),Object.keys(data.oldExecutors).sort(),'normal_review_correction_executor_scope');
 const allowed=['scripts/test-heldout-memory-replay-ledger.ts','scripts/test-heldout-memory-replay-recovery.ts','scripts/test-heldout-memory-replay-sequence.ts'];
 const changed=Object.keys(data.oldExecutors).filter(k=>data.oldExecutors[k]!==data.newExecutors[k]);need(changed.length>0&&changed.every(k=>allowed.includes(k))&&Object.values(data.newExecutors).every(isHash),'normal_review_correction_executor_scope');
 need(next.schema==='mote-heldout-sequence-validation@1'&&next.status==='passed'&&next.realModelCalls===0&&next.heldoutSemanticInputsRead===false&&next.validatedPhases?.includes('normal-review-recovery'),'normal_review_correction_validation');same(next.executorCodeHashes,data.newExecutors,'normal_review_correction_validation_executor');return p;
}
export function normalReviewCorrection(events:LedgerEvent[],proof:NormalReviewRecovery){
 const matches=events.filter(e=>e.kind==='normal-review-preparation-corrected');need(matches.length<=1,'normal_review_correction_duplicate');if(!matches.length)return undefined;
 const e=matches[0],parent=events.find(p=>p.sha256===proof.eventHash);need(parent&&e.index===parent.index+1&&e.previous===proof.eventHash,'normal_review_correction_not_preparation');validateNormalReviewCorrection(e.data as NormalReviewCorrection,proof);return e.data as NormalReviewCorrection;
}

/** A quota-rejected first Ask arm is the only additional recovery boundary. */
export type AskRecovery={plan:RecoveryRef;eventHash:string};
export const askRecoveryLimits={stageOuter:2,perOuterMs:300000,stageProcessMs:720000,cumulativePlanningCap:124,automaticOuterRetries:0,concurrency:1} as const;
export type AskRecoveryRequest={schema:'mote-heldout-ask-recovery-request@1';experimentHash:string;previousManifest:RecoveryRef;stoppedHeadHash:string;failedOpenHash:string;failedAdmissionHash:string;failedStopHash:string;failedTerminalHash:string;failedReceiptHash:string;canonicalSnapshotHash:string;failureReport:RecoveryRef;supervision:RecoveryRef;diagnostic:RecoveryRef};
export type AskRecoveryPlan=Omit<AskRecoveryRequest,'schema'>&{schema:'mote-heldout-ask-recovery-plan@1';policy:'quota-first-arm-pair-once@1';request:RecoveryRef;recoveryId:string;targetStage:string;rootManifest:RecoveryRef;validation:RecoveryRef;supervisor:RecoveryRef;preparationCommitment:RecoveryRef;productionHash:string;runtimeHash:string;oldExecutors:Record<string,string>;newExecutors:Record<string,string>;canonicalPath:string;failedOutputPath:string;failedTreeHash:string;failedCloseAt:string;normalContinuation?:NormalContinuation;normalReviewRecovery?:NormalReviewRecovery;stopHashes:string[];inheritedAdmissions:number;inheritedCompleted:number;inheritedFailed:number;inheritedUnknownUsage:number;recoveryCumulativeCap:number;limits:typeof askRecoveryLimits;successPhase:PhaseClosure};
const askRequestKeys='canonicalSnapshotHash,diagnostic,experimentHash,failedAdmissionHash,failedOpenHash,failedReceiptHash,failedStopHash,failedTerminalHash,failureReport,previousManifest,schema,stoppedHeadHash,supervision';
export function readAskRecoveryRequest(ref:RecoveryRef):AskRecoveryRequest{
 const r=refJson(ref) as AskRecoveryRequest;exactKeys(r,askRequestKeys,'ask_recovery_request_invalid');need(r.schema==='mote-heldout-ask-recovery-request@1'&&[r.experimentHash,r.stoppedHeadHash,r.failedOpenHash,r.failedAdmissionHash,r.failedStopHash,r.failedTerminalHash,r.failedReceiptHash,r.canonicalSnapshotHash].every(isHash),'ask_recovery_request_invalid');for(const v of [r.previousManifest,r.failureReport,r.supervision,r.diagnostic])refJson(v);return r;
}
export function stoppedAsk(events:LedgerEvent[],r:AskRecoveryRequest){
 need(!events.some(e=>e.kind==='ask-recovery-authorized')&&events.at(-1)?.sha256===r.stoppedHeadHash&&events[0]?.data.manifestHash===r.experimentHash,'ask_recovery_not_original_stop');
 const m=refJson(r.previousManifest),stage=`wave2-pair-0-${m.task?.plan?.sha256}`,tail=events.slice(-6);same(tail.map(e=>e.kind),['executor-freeze','stage-open','admit','stop','terminal','receipt'],'ask_recovery_failed_sequence_changed');const [freeze,open,admit,stop,terminal,receipt]=tail;
 same([open.sha256,admit.sha256,stop.sha256,terminal.sha256,receipt.sha256],[r.failedOpenHash,r.failedAdmissionHash,r.failedStopHash,r.failedTerminalHash,r.failedReceiptHash],'ask_recovery_failed_binding_changed');need(freeze.data.manifestHash===r.previousManifest.sha256&&open.data.stage===stage&&open.data.parentHash===r.canonicalSnapshotHash&&open.data.maxCalls===2&&admit.data.stage===stage&&terminal.data.callId===admit.data.callId&&receipt.data.id===admit.data.receiptId&&terminal.data.status==='failed'&&receipt.data.status==='failed'&&stop.data.code==='internal_error_details_sealed'&&terminal.data.safeCode==='internal_error_details_sealed'&&terminal.data.modelRunStarts===1&&terminal.data.repairs===0&&receipt.data.tokens?.complete!==true,'ask_recovery_failure_changed');
 need(m.schema==='mote-heldout-phase-manifest@1'&&['heldout','mechanical'].includes(m.kind)&&m.experimentHash===r.experimentHash&&m.task?.kind==='evaluation'&&m.task.wave===2&&m.task.index===0&&!m.askRecovery&&!m.recoveryLineage,'ask_recovery_original_scope_changed');same(m.limits,askRecoveryLimits,'ask_recovery_original_limits_changed');need(m.parent.treeHash===r.canonicalSnapshotHash&&m.parent.ledgerHeadHash===freeze.previous,'ask_recovery_original_parent_changed');
 const commitment=refJson(m.task.commitment);same(commitment.plan,m.task.plan,'ask_recovery_commitment_changed');need(commitment.schema==='mote-heldout-ask-plan-commitment@1'&&commitment.experimentHash===r.experimentHash,'ask_recovery_commitment_changed');const plan=refJson(m.task.plan),pairs=plan.pairs?.filter((p:any)=>p.checkpointWave===2);need(plan.schema==='mote-heldout-ask-plan@1'&&plan.experimentHash===r.experimentHash&&plan.pairs?.length===8&&pairs.length===1&&pairs[0].slots.length===2&&admit.data.logicalKey===pairs[0].slots[0].id,'ask_recovery_first_slot_changed');
 const prior=events.slice(0,freeze.index),closes=prior.filter(e=>e.kind==='stage-close'),last=closes.at(-1);need(last?.data.succeeded===true&&last.data.phase?.kind==='integration'&&last.data.phase.wave===2&&last.data.phase.evaluatedPairs===0&&last.data.phase.archiveHeadHash===r.canonicalSnapshotHash&&last.data.snapshotHash===r.canonicalSnapshotHash,'ask_recovery_integration_parent_changed');need(prior.filter(e=>e.kind==='stage-open').every(o=>closes.filter(c=>c.data.stage===o.data.stage).length===1),'ask_recovery_prior_unclosed');
 const covered=m.normalContinuation?normalAuthorization(prior,m.normalContinuation,m.normalReviewRecovery).stopHashes:[];need(prior.filter(e=>e.kind==='stop').every(e=>covered.includes(e.sha256))&&!events.some(e=>e.kind==='host-rejection-receipt'),'ask_recovery_prior_stop_changed');
 const ads=events.filter(e=>e.kind==='admit'),ts=events.filter(e=>e.kind==='terminal'),rs=events.filter(e=>e.kind==='receipt');need(ads.length===ts.length&&ads.length===rs.length,'ask_recovery_accounting_unknown');for(const a of ads){const t=ts.filter(t=>t.data.callId===a.data.callId),u=rs.filter(u=>u.data.id===a.data.receiptId);need(t.length===1&&u.length===1&&t[0].data.status===u[0].data.status&&['completed','failed'].includes(u[0].data.status),'ask_recovery_receipt_conflict');}
 if(m.kind==='heldout')need(ads.length===28&&ts.filter(e=>e.data.status==='completed').length===24&&ts.filter(e=>e.data.status==='failed').length===4&&rs.filter(e=>e.data.tokens?.complete!==true).length===4&&m.normalContinuation&&m.normalReviewRecovery,'ask_recovery_actual_history_changed');
 const report=refJson(r.failureReport),supervision=refJson(r.supervision),diagnostic=refJson(r.diagnostic);need(report.schema==='mote-heldout-ask-stage@1'&&report.status==='stopped'&&report.phase==='evaluation'&&report.wave===2&&report.pairOrdinal===0&&report.completedCalls===0&&report.manifestHash===r.previousManifest.sha256&&report.experimentHash===r.experimentHash&&report.planHash===m.task.plan.sha256&&report.failure?.code==='stage_api_status_502'&&report.cumulative?.headHash===r.stoppedHeadHash,'ask_recovery_report_changed');need(supervision.status==='process-closed'&&supervision.phase==='evaluation'&&supervision.mode==='stage-ask-live'&&supervision.exitCode===1&&supervision.processGroupClosed===true&&supervision.terminationRequested===false&&supervision.interrupted===false&&supervision.remainingProcessGroupAfterParentExit===false&&supervision.ledgerPrefixUnchangedAfterClose===true&&supervision.frozenControlsUnchangedAfterClose===true&&supervision.manifestSha256===r.previousManifest.sha256,'ask_recovery_process_not_closed');
 need(diagnostic.schema==='mote-goal-continuation-safe-quota-diagnosis@1'&&diagnostic.state==='read-only-diagnosis-complete'&&diagnostic.semanticContentExposed===false&&diagnostic.diagnosis?.terminalCodexDiscriminant==='usageLimitExceeded'&&diagnostic.diagnosis.fixedCode==='provider_quota'&&diagnostic.diagnosis.upstreamHttpStatus===null&&diagnostic.diagnosis.localTimeoutProven===false&&diagnostic.diagnosis.productMappingRepairRequired===false&&diagnostic.events?.some((e:any)=>e.type==='codex.error'&&e.codexErrorInfo==='usageLimitExceeded'&&e.willRetry===false)&&[r.previousManifest,r.failureReport,r.supervision].every(ref=>diagnostic.sourceMetadata?.some((s:any)=>s.path===ref.path&&s.sha256===ref.sha256)),'ask_recovery_quota_diagnostic_required');return {manifest:m,open,admit,stop,terminal,receipt,last,admissions:ads.length,completed:ts.filter(e=>e.data.status==='completed').length,failed:ts.filter(e=>e.data.status==='failed').length,unknownUsage:rs.filter(e=>e.data.tokens?.complete!==true).length};
}
export function readAskRecoveryPlan(ref:RecoveryRef):AskRecoveryPlan{
 const p=refJson(ref) as AskRecoveryPlan,extra='canonicalPath,failedCloseAt,failedOutputPath,failedTreeHash,inheritedAdmissions,inheritedCompleted,inheritedFailed,inheritedUnknownUsage,limits,newExecutors,oldExecutors,policy,preparationCommitment,productionHash,recoveryCumulativeCap,recoveryId,request,rootManifest,runtimeHash,stopHashes,successPhase,supervisor,targetStage,validation'.split(',');exactKeys(p,[...askRequestKeys.split(','),...extra,...(Object.hasOwn(p,'normalContinuation')?['normalContinuation']:[]),...(Object.hasOwn(p,'normalReviewRecovery')?['normalReviewRecovery']:[])].sort().join(','),'ask_recovery_plan_fields_changed');need(p.schema==='mote-heldout-ask-recovery-plan@1'&&p.policy==='quota-first-arm-pair-once@1'&&/^[0-9a-f-]{36}$/.test(p.recoveryId),'ask_recovery_plan_invalid');const r=readAskRecoveryRequest(p.request);for(const k of Object.keys(r).filter(k=>k!=='schema'))same((p as any)[k],(r as any)[k],'ask_recovery_request_binding_changed');same(p.limits,askRecoveryLimits,'ask_recovery_limits_changed');need(p.recoveryCumulativeCap===p.inheritedAdmissions+2&&p.recoveryCumulativeCap<=124&&[p.productionHash,p.runtimeHash,p.failedTreeHash].every(isHash)&&Number.isFinite(Date.parse(p.failedCloseAt)),'ask_recovery_budget_changed');return p;
}
export function askRecoveryLogicalKeys(p:AskRecoveryPlan){const m=refJson(p.previousManifest),plan=refJson(m.task.plan),pair=plan.pairs.filter((q:any)=>q.checkpointWave===2)[0];return pair.slots.map((s:any,i:number)=>hash(['ask-recovery@1',p.recoveryId,s.id,i,i===0?2:1]));}
export function validateAskRecoveryPrefix(events:LedgerEvent[],ref:RecoveryRef){
 const p=readAskRecoveryPlan(ref),prior=stoppedAsk(events,readAskRecoveryRequest(p.request)),m=prior.manifest,root=refJson(p.rootManifest),v=refJson(p.validation);same(p.rootManifest,m.rootManifest,'ask_recovery_root_changed');same(p.normalContinuation,m.normalContinuation,'ask_recovery_normal_changed');same(p.normalReviewRecovery,m.normalReviewRecovery,'ask_recovery_review_changed');same([p.inheritedAdmissions,p.inheritedCompleted,p.inheritedFailed,p.inheritedUnknownUsage],[prior.admissions,prior.completed,prior.failed,prior.unknownUsage],'ask_recovery_history_changed');same(p.stopHashes,events.filter(e=>e.kind==='stop').map(e=>e.sha256),'ask_recovery_stops_changed');need(p.canonicalPath===m.parent.path&&p.targetStage===`wave2-pair-0-recovery-${p.recoveryId}-${m.task.plan.sha256}`,'ask_recovery_target_changed');same(p.successPhase,{...prior.last!.data.phase,kind:'evaluation',evaluatedPairs:1},'ask_recovery_success_scope_changed');
 same(p.oldExecutors,Object.fromEntries(Object.entries(m.codeHashes).filter(([file])=>file.startsWith('scripts/'))),'ask_recovery_old_executor_changed');same(Object.keys(p.oldExecutors).sort(),Object.keys(p.newExecutors).sort(),'ask_recovery_executor_scope_changed');const allowed=['scripts/test-heldout-memory-replay.ts','scripts/test-heldout-memory-replay-ledger.ts','scripts/test-heldout-memory-replay-ask.ts','scripts/test-heldout-memory-replay-recovery.ts','scripts/test-heldout-memory-replay-stage.ts','scripts/test-heldout-memory-replay-sequence.ts','scripts/test-heldout-memory-replay-integration.ts'];need(Object.keys(p.newExecutors).every(k=>isHash(p.newExecutors[k])&&(p.oldExecutors[k]===p.newExecutors[k]||allowed.includes(k))),'ask_recovery_executor_scope_changed');need(v.schema==='mote-heldout-sequence-validation@1'&&v.status==='passed'&&v.realModelCalls===0&&v.heldoutSemanticInputsRead===false&&v.validatedPhases?.includes('ask-recovery'),'ask_recovery_validation_required');same(v.executorCodeHashes,p.newExecutors,'ask_recovery_validation_executor_changed');need(p.productionHash===hash(Object.fromEntries(Object.entries(root.codeHashes).filter(([file])=>!file.startsWith('scripts/'))))&&p.runtimeHash===hash(root.runtime),'ask_recovery_production_runtime_changed');const c=refJson(p.preparationCommitment);same(c,{schema:'mote-heldout-ask-recovery-preparation@1',experimentHash:p.experimentHash,stoppedHeadHash:p.stoppedHeadHash,recoveryId:p.recoveryId,request:p.request,output:c.output},'ask_recovery_preparation_changed');need(p.failedOutputPath===refJson(p.supervision).stageOutput,'ask_recovery_failed_output_changed');return p;
}
function askFailedClose(events:LedgerEvent[],p:AskRecoveryPlan){const body={index:events.length,at:p.failedCloseAt,previous:p.stoppedHeadHash,kind:'stage-close',data:{stage:refJson(p.failureReport).wave===2?`wave2-pair-0-${refJson(p.previousManifest).task.plan.sha256}`:'',snapshotHash:p.failedTreeHash,succeeded:false,recoveryRequest:p.request.sha256}};return {...body,sha256:hash(body)};}
export function askRecoveryAuthorization(events:LedgerEvent[],proof:AskRecovery,normal?:NormalContinuation,review?:NormalReviewRecovery){
 exactKeys(proof,'eventHash,plan','ask_recovery_proof_invalid');const es=events.filter(e=>e.kind==='ask-recovery-authorized');need(es.length===1&&es[0].sha256===proof.eventHash,'ask_recovery_event_changed');const event=es[0],prefix=events.slice(0,event.index-1),p=validateAskRecoveryPrefix(prefix,proof.plan),close=events[event.index-1];same(close,askFailedClose(prefix,p),'ask_recovery_failed_close_changed');same(event.data,{plan:proof.plan,failedCloseHash:close.sha256},'ask_recovery_event_plan_changed');need(event.previous===close.sha256,'ask_recovery_event_parent_changed');same(normal,p.normalContinuation,'ask_recovery_normal_changed');same(review,p.normalReviewRecovery,'ask_recovery_review_changed');
 const after=events.slice(event.index+1);need(!after.some(e=>['stop','ask-recovery-authorized','normal-continuation-authorized','normal-review-recovery-authorized','recovery-authorized','recovery-e-authorized','host-rejection-receipt'].includes(e.kind)),'ask_recovery_new_stop_forbidden');const opens=after.filter(e=>e.kind==='stage-open'),closes=after.filter(e=>e.kind==='stage-close'&&e.data.stage===p.targetStage),ad=after.filter(e=>e.kind==='admit'&&e.data.stage===p.targetStage);need(closes.length<=1&&ad.length<=2,'ask_recovery_consumed_twice');if(opens.length)need(opens[0].data.stage===p.targetStage&&opens[0].data.parentHash===p.canonicalSnapshotHash&&opens[0].data.maxCalls===2,'ask_recovery_first_stage_changed');const keys=askRecoveryLogicalKeys(p);for(const [i,a] of ad.entries())need(a.data.logicalKey===keys[i],'ask_recovery_slot_changed');
 if(closes.length){const c=closes[0];need(c.data.succeeded===true&&ad.length===2&&ad.every(a=>a.index<c.index),'ask_recovery_success_invalid');same(c.data.phase,p.successPhase,'ask_recovery_success_cursor_changed');for(const a of ad){const t=after.filter(e=>e.kind==='terminal'&&e.data.callId===a.data.callId),u=after.filter(e=>e.kind==='receipt'&&e.data.id===a.data.receiptId);need(t.length===1&&u.length===1&&t[0].index<c.index&&u[0].index<c.index&&t[0].data.status==='completed'&&u[0].data.status==='completed','ask_recovery_success_receipt_unknown');}need(opens.slice(1).every(o=>o.index>c.index),'ask_recovery_next_before_success');}else need(opens.length<=1&&after.filter(e=>e.kind==='admit').every(e=>e.data.stage===p.targetStage),'ask_recovery_success_required');return p;
}
export function reserveAskRecoveryPreparation(directory:string,request:RecoveryRef,recoveryId:string,output:string):RecoveryRef{let lock:number;try{lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}let fd:number|undefined,writing=false;try{const r=readAskRecoveryRequest(request);stoppedAsk(readAdmissionChain(directory),r);const path=join(directory,'ask-recovery-preparation.json');need(!existsSync(path),'ask_recovery_preparation_already_reserved');fd=openSync(path,'wx',0o600);const bytes=JSON.stringify({schema:'mote-heldout-ask-recovery-preparation@1',experimentHash:r.experimentHash,stoppedHeadHash:r.stoppedHeadHash,recoveryId,request,output})+'\n';writing=true;writeSync(fd,bytes);fsyncSync(fd);writing=false;return {path,sha256:createHash('sha256').update(bytes).digest('hex')};}finally{if(fd!==undefined)closeSync(fd);closeSync(lock);if(!writing)unlinkSync(join(directory,'writer.lock'));}}
export function authorizeAskRecovery(directory:string,plan:RecoveryRef):AskRecovery{let lock:number;try{lock=openSync(join(directory,'writer.lock'),'wx',0o600);}catch{throw new StageSafetyError('ledger_locked_unknown_interruption');}let fd:number|undefined,writing=false;try{const events=readAdmissionChain(directory),p=validateAskRecoveryPrefix(events,plan),closure=askFailedClose(events,p),body={index:events.length+1,at:new Date().toISOString(),previous:closure.sha256,kind:'ask-recovery-authorized',data:{plan,failedCloseHash:closure.sha256}},event={...body,sha256:hash(body)};fd=openSync(join(directory,'admissions.ndjson'),'a',0o600);writing=true;writeSync(fd,JSON.stringify(closure)+'\n'+JSON.stringify(event)+'\n');fsyncSync(fd);writing=false;return {plan,eventHash:event.sha256};}finally{if(fd!==undefined)closeSync(fd);closeSync(lock);if(!writing)unlinkSync(join(directory,'writer.lock'));}}
