/** Generated SourceItem/Material fixture only; never opens the heldout dataset or ledger. */
import {test as nodeTest,after,mock,type TestContext} from 'node:test';
let testCount=0,passedTests=0;const test=(name:string,fn:(t:TestContext)=>unknown)=>{testCount++;return nodeTest(name,async t=>{await fn(t);passedTests++;});};
import {mkdir,writeFile,readFile,cp,unlink} from 'node:fs/promises';
import {join} from 'node:path';
import {existsSync} from 'node:fs';
import childProcess,{spawnSync} from 'node:child_process';
import {syncBuiltinESMExports} from 'node:module';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {type ContextReader,type QueryInput} from '@mote/agent';
import type {QueryResult} from '@mote/shared';
import {UsageLedger} from '../apps/server/src/usage.js';
import {sha256} from '../apps/server/src/store.js';
import {ProviderFailure} from '@mote/shared';
import {base,recipes,check,equal,json,cloneClosed,closed,hashObject,SafeFailure} from './test-heldout-memory-replay.js';
import {openNode,drain,treeHash,type Manifest,runBatch,freezeStage,newOutput,batchPin,settings,bindings,protectedTables,codeHashes,executorPins,experimentHash} from './test-heldout-memory-replay-stage.js';
import {AdmissionLedger,inspectAdmissionLedger,StageSafetyError,readAdmissionChain,authorizeRecovery,readRecoveryPlan,validateRecoveryPrefix,type RecoveryLineage,type RecoveryEPlan,readRecoveryEPlan,readRecoveryERequest,recoveryEAuthorization,authorizeRecoveryE,recoveryELimits} from './test-heldout-memory-replay-ledger.js';
import {ref,freezePhase,runPhase,phaseCursor,type WavePlan,type EPhaseManifest,eBatchAuthority} from './test-heldout-memory-replay-sequence.js';
import {freezeIntegration,runIntegration} from './test-heldout-memory-replay-integration.js';
import {freezeAsk,runAsk} from './test-heldout-memory-replay-ask.js';
import {prepareNativeRetry,freezeRecovery,freezeRecoveryE,assertRecoveryESettings} from './test-heldout-memory-replay-recovery.js';
const output=process.env.MOTE_HELDOUT_RECOVERY_E_TEST_OUTPUT??join(base,'heldout-recovery-E-offline-'+Date.now());await mkdir(output,{mode:0o700});const checks:unknown[]=[];let calls=0,bootstrapCalls=0;
const recoverySupervisor=join(base,'run-heldout-phase-v2-supervised.py');
const model:Manifest['model']={provider:'codex',protocol:'codex-app-server',model:'gpt-6-sol',reasoningEffort:'max',codexBin:'/nonexistent-recovery-stub',codexBinHash:'stub',codexHome:'/nonexistent-recovery-home'},time='2025-12-31T23:59:59+08:00';
let failedSnapshot='',canonicalSnapshot='',jobId='',failing=false;let originalRows:any[]=[],frozenSettings='',frozenBindings='',frozenProtected='';let inheritedReceipts:any[]=[],failedReceipt:any;
// Historical 27dafcd runner deadline, deliberately isolated from the corrected
// future runBatch timer. Keep its persisted model_failed state; never substitute AgentTimeoutError.
const fixtureOuterDeadline=():Promise<never>=>new Promise((_,reject)=>setTimeout(()=>reject(new StageSafetyError('outer_deadline_exceeded')),10));
test('normal generated inputs form six batches; first generation timeout leaves five pending',async()=>{
 const vault=join(output,'generated-seed');let node:Awaited<ReturnType<typeof openNode>>['node'];const stub=async(reader:ContextReader,input:QueryInput):Promise<QueryResult>=>{if(!failing){bootstrapCalls++;input.onUsage?.({measurement:'thread_cumulative',complete:true,requests:0,reportedRequests:0,inputTokens:5,outputTokens:3,totalTokens:8});const source=(await reader.evidence({ids:input.evidenceIds!}))[0];const domain=input.traceContext?.batchIndex===1?'coding':'personal';return {answer:JSON.stringify({memories:[{domain,...(domain==='coding'?{coding:{kind:'decision',scope:'session',applicability:'Generated fixture',validation:'observed'}}:{}),title:'Prior generated fixture',statement:'Prior literal ['+source.id+']',uncertainty:'Generated fixture',admission:{layer:'memory',reason:'Generated fixture',scope:'Fixture',attribution:'observed'},evidenceIds:[source.id],evidence:[{id:source.id,quote:source.ocrText}]}]}),citations:[{id:source.id,capturedAt:source.capturedAt,appName:source.appName,excerpt:source.ocrText}],trace:[],runId:randomUUID()};}calls++;node.memoryPipeline.pause(jobId);input.onUsage?.({measurement:'thread_cumulative',complete:false,requests:0,reportedRequests:0,inputTokens:11,outputTokens:0,totalTokens:11});return fixtureOuterDeadline();};const opened=await openNode(vault,model,time,stub);node=opened.node;
 try{await opened.request('POST','/api/sources',{id:'recovery-fixture',name:'Generated recovery fixture',kind:'custom',deviceId:'generated-recovery',platform:'import',retention:'archive'});
 await opened.request('PUT','/api/sources/recovery-fixture/items',{externalId:'prior-wave',revision:'1',kind:'message',layer:'original',observedAt:'2025-11-01T09:00:00+08:00',text:'Prior generated history literal.',document:{contentRole:'authored',recordedAt:'2025-11-01T09:00:00+08:00',timeBasis:'recorded'}});await drain(node);const priorIds=node.store.db.prepare('SELECT id FROM material_heads WHERE retired=0 ORDER BY id').all().flatMap(row=>node.materials.evidenceIds(node.materials.get(String(row.id))!.ref));const priorJob=node.memoryPipeline.create({evidenceIds:priorIds,recipes,contextTime:'2025-11-30T23:59:59+08:00',timeZone:'Asia/Shanghai',batchCharacters:12000});check((await node.memoryPipeline.run(priorJob.id)).status==='completed','fixture_prior_wave_failed');check(Number(node.store.db.prepare('SELECT count(*) n FROM memories').get()!.n)>0&&Number(node.store.db.prepare('SELECT count(*) n FROM memory_extraction_drafts WHERE shared=1').get()!.n)>0&&Number(node.store.db.prepare('SELECT count(*) n FROM memory_checkpoints').get()!.n)>0,'fixture_nonempty_history_missing');const meters=new UsageLedger(node.store);for(let i=0;i<9;i++){const meter=meters.start('codex','gpt-6-sol','generated-accounting-only');meter.update({complete:true,inputTokens:5,outputTokens:3,totalTokens:8,requests:0,reportedRequests:0});meter.finish('completed');}inheritedReceipts=node.store.db.prepare('SELECT json FROM model_usage ORDER BY created_at,id').all().map(r=>JSON.parse(String(r.json)));equal(inheritedReceipts.length,12,'fixture_inherited_count');failing=true;
 for(let i=0;i<24;i++)await opened.request('PUT','/api/sources/recovery-fixture/items',{externalId:'generated-'+String(i).padStart(2,'0'),revision:'1',kind:'message',layer:'original',observedAt:'2025-12-01T09:00:00+08:00',text:'Generated literal mechanical marker. '.repeat(30),document:{contentRole:'authored',recordedAt:'2025-12-01T09:00:00+08:00',timeBasis:'recorded'}});
 await drain(node);const ids=node.store.db.prepare('SELECT id FROM material_heads WHERE retired=0 ORDER BY id').all().flatMap(row=>node.materials.evidenceIds(node.materials.get(String(row.id))!.ref));const job=node.memoryPipeline.create({evidenceIds:ids.filter(id=>!priorIds.includes(id)),recipes,contextTime:time,timeZone:'Asia/Shanghai',batchCharacters:12000});jobId=job.id;
 const planned=node.store.db.prepare('SELECT json FROM memory_batches WHERE job_id=? ORDER BY idx').all(jobId).map(row=>JSON.parse(String(row.json)));await writeFile(join(output,'ROOT_SAFE_plan-shape.json'),json({batches:planned.length,chunks:planned.map(b=>b.chunks.length),chars:planned.map(b=>b.chunks.map((c:any)=>c.length))}));
 equal(planned.length,6,'fixture_six_batch_plan');equal(planned[0].chunks.length,8,'fixture_first_eight_chunks');
 originalRows=planned;frozenSettings=hashObject(settings(node));frozenBindings=hashObject(bindings(node));frozenProtected=hashObject(protectedTables(node.store.db));node.memoryPipeline.pause(jobId);await node.app.close();await closed(vault);canonicalSnapshot=join(output,'canonical-before-timeout');await cloneClosed(vault,canonicalSnapshot);node=(await openNode(vault,model,time,stub)).node;node.memoryPipeline.resume(jobId);const result=await node.memoryPipeline.run(jobId);check(result.status==='paused'&&result.failedBatches===1&&result.completedBatches===0,'fixture_failure_boundary');equal(calls,1,'fixture_later_provider_called');await new Promise(resolve=>setTimeout(resolve,Math.max(0,(result.availableAt??0)-Date.now())+10));failedReceipt=JSON.parse(String(node.store.db.prepare("SELECT json FROM model_usage WHERE json_extract(json,'$.status')='failed'").get()!.json));
 }finally{await node.app.close();}
 await closed(vault);failedSnapshot=join(output,'failed-closed');await cloneClosed(vault,failedSnapshot);const proof=new DatabaseSync(join(failedSnapshot,'mote.sqlite'),{readOnly:true});try{const batch=JSON.parse(String(proof.prepare('SELECT json FROM memory_batches WHERE job_id=? ORDER BY idx LIMIT 1').get(jobId)!.json));equal([batch.status,batch.phase,batch.errorCode,batch.attempts,batch.chunks.length],['failed','extract','model_failed',1,8],'fixture_outer_deadline_mapping');}finally{proof.close();}checks.push({name:'six-batch-native-timeout',passed:true,stubCalls:1});
});
test('same-stack native retry pause closes and reopens with zero new calls',async()=>{
 check(failedSnapshot,'fixture_seed_required');const parentHash=await treeHash(failedSnapshot),destination=join(output,'prepared');const result=await prepareNativeRetry({parent:failedSnapshot,destination,model,contextTime:time,jobId});equal(result.providerAttempts,0,'fixture_prepare_admitted');
 let reopenedCalls=0;const {node}=await openNode(destination,model,time,async()=>{reopenedCalls++;throw new Error('fixture_reopen_forbidden');});try{await node.executor.tick();equal(node.memoryPipeline.get(jobId).status,'paused','fixture_restart_not_paused');equal(reopenedCalls,0,'fixture_restart_admitted');}finally{await node.app.close();}
 equal(await treeHash(failedSnapshot),parentHash,'fixture_failed_snapshot_mutated');checks.push({name:'retry-pause-closed-reopen',passed:true,...result,reopenedCalls});
});
let fixtureRoot:Manifest,rootPath='',previousPath='',ledgerDirectory='',validationPath='',lineage:RecoveryLineage,recoveryManifestPath='',recoveryParent='',lastSuccessParent='',lastSuccessManifest='';let syntheticHistoricalAdmissions=0,executionCalls=0;
const usageProjection=(r:any)=>({id:r.id,status:r.status,tokens:r.tokens,estimatedCost:r.estimatedCost,currency:r.currency,durationMs:r.durationMs});
const rejection=async(name:string,fn:()=>unknown|Promise<unknown>,expected:string)=>{let code='';try{await fn();}catch(error){code=error instanceof SafeFailure||error instanceof StageSafetyError?error.code:'unexpected_error';}equal(code,expected,'recovery_negative_code');checks.push({name,passed:true,code});};
test('explicit preparation authorizes only the closed timeout and preserves all 13 prior ledger admissions',async()=>{
 const seedOutput=await newOutput(join(output,'root-fixture'));const template=await freezeStage(seedOutput,true);fixtureRoot={...template,seed:canonicalSnapshot,seedTreeHash:await treeHash(canonicalSnapshot),jobId,contextTime:time,batchPlan:originalRows.map(b=>({id:b.id,index:b.index,sha256:batchPin(b),recipe:b.strategy?.recipe})),settingsHash:frozenSettings,bindingsHash:frozenBindings,protectedHash:frozenProtected};fixtureRoot.experimentHash=experimentHash(fixtureRoot);rootPath=join(output,'ROOT_SAFE_root-fixture.json');await writeFile(rootPath,json(fixtureRoot));
 const oldPlan:WavePlan={schema:'mote-heldout-wave-plan@1',experimentHash:fixtureRoot.experimentHash,wave:2,contextTime:time,jobId,batchPlan:fixtureRoot.batchPlan,settingsHash:frozenSettings,bindingsHash:frozenBindings,protectedHash:frozenProtected,deliveries:24,materials:25,sourceInputHash:'a'.repeat(64),ingressSnapshot:{path:canonicalSnapshot,treeHash:fixtureRoot.seedTreeHash}};const oldPlanPath=join(output,'ROOT_SAFE_old-wave-plan.json');await writeFile(oldPlanPath,json(oldPlan));const oldPlanRef=await ref(oldPlanPath);
 ledgerDirectory=join(output,'recovery-ledger');const ledger=new AdmissionLedger(ledgerDirectory,fixtureRoot.experimentHash);ledger.bindExecutor('fixture-history');
 // Twelve synthetic accounting records exercise historic budget retention. They are not model calls.
 for(let batch=0;batch<6;batch++){ledger.begin('wave1-batch-'+batch,fixtureRoot.seedTreeHash,2);for(let n=0;n<2;n++){const receipt=inheritedReceipts[batch*2+n],id=ledger.reserve('history-'+batch+'-'+n,'literal-input-hash',receipt.id);ledger.terminal(id,'completed','ok',{modelRunStarts:1,repairs:0});ledger.receipts([usageProjection(receipt)]);syntheticHistoricalAdmissions++;}ledger.finish(fixtureRoot.seedTreeHash,true);}
 ledger.begin('wave1-integration',fixtureRoot.seedTreeHash,0);ledger.finish(fixtureRoot.seedTreeHash,true,{kind:'integration',wave:1,contextTime:time,archiveHeadHash:fixtureRoot.seedTreeHash,totalBatches:6,nextBatch:6,evaluatedPairs:0});ledger.begin('wave2-ingress',fixtureRoot.seedTreeHash,0);ledger.finish(fixtureRoot.seedTreeHash,true,{kind:'ingress',wave:2,contextTime:time,archiveHeadHash:fixtureRoot.seedTreeHash,totalBatches:6,nextBatch:0,evaluatedPairs:0,wavePlan:oldPlanRef});
 const previous={schema:'mote-heldout-phase-manifest@1',kind:'mechanical',experimentHash:fixtureRoot.experimentHash,rootManifest:await ref(rootPath),previousManifest:{path:rootPath,sha256:'a'.repeat(64)},validation:{path:rootPath,sha256:'a'.repeat(64)},runtime:fixtureRoot.runtime,executor:fixtureRoot.executor,codeHashes:await codeHashes(),limits:fixtureRoot.limits,parent:{path:canonicalSnapshot,treeHash:fixtureRoot.seedTreeHash,ledgerHeadHash:ledger.summary().headHash},task:{kind:'extraction',wave:2,contextTime:time,index:0,wavePlan:oldPlanRef}};previousPath=join(output,'ROOT_SAFE_failed-manifest-fixture.json');await writeFile(previousPath,json(previous));ledger.bindExecutor(sha256(await readFile(previousPath)),'fixture-history','a'.repeat(64));ledger.begin('wave2-batch-0',fixtureRoot.seedTreeHash,2);const failedId=ledger.reserve(hashObject([jobId,originalRows[0].id,'extract']),'fixture-failed-input',failedReceipt.id);ledger.terminal(failedId,'failed','outer_deadline_exceeded',{modelRunStarts:1,repairs:0});ledger.receipts([usageProjection(failedReceipt)]);ledger.finish(await treeHash(failedSnapshot),false);ledger.close();
 const prefix=await readFile(join(ledgerDirectory,'admissions.ndjson'));validationPath=join(output,'ROOT_SAFE_validation-fixture.json');await writeFile(validationPath,json({schema:'mote-heldout-sequence-validation@1',validatedPhases:['recovery-E','recovery-D','extraction','ingress','integration','evaluation'],status:'passed',realModelCalls:0,heldoutSemanticInputsRead:false,executorCodeHashes:executorPins(await codeHashes()),note:'Validator-shape fixture; final verdict is the separate test report.'}));
 const freezeOutput=await newOutput(join(output,'recovery-freeze'));const frozen=await freezeRecovery({rootManifest:rootPath,previousManifest:previousPath,failedSnapshot,ledgerDirectory,validation:validationPath,supervisorPath:recoverySupervisor,output:freezeOutput});lineage=frozen.lineage;recoveryManifestPath=join(freezeOutput,'ROOT_SAFE_manifest.json');recoveryParent=frozen.plan.preparedPath;
 check((await readFile(join(ledgerDirectory,'admissions.ndjson'))).subarray(0,prefix.length).equals(prefix),'recovery_historical_prefix_mutated');const events=inspectAdmissionLedger(ledgerDirectory,fixtureRoot.experimentHash,lineage),cursor=phaseCursor(events,fixtureRoot,lineage);equal([cursor.nextBatch,cursor.totalBatches,cursor.archiveHeadHash,cursor.recoveryInputHash],[0,6,fixtureRoot.seedTreeHash,frozen.plan.preparedSnapshotHash],'recovery_cursor_wrong');await cp(ledgerDirectory,join(output,'authorized-ledger-baseline'),{recursive:true});checks.push({name:'explicit-single-lineage',passed:true,historicalAdmissions:13,newProviderCalls:0,immutablePrefix:true});
});
let eSource='',eLedger='',eManifest:EPhaseManifest,ePlan:RecoveryEPlan,eManifestPath='',eRequestPath='',eBaseline='',dSecondCalls=0,eCalls=0;
const eSupervisor=join(base,'run-heldout-phase-e-supervised.py');
test('generated historical D failure preserves old model_failed and closes 14 receipts',async()=>{
 const dPlan=readRecoveryPlan(lineage.plan),vault=join(output,'d-second-working');await cloneClosed(recoveryParent,vault);eLedger=join(output,'e-ledger');await cp(join(output,'authorized-ledger-baseline'),eLedger,{recursive:true});const ledger=new AdmissionLedger(eLedger,fixtureRoot.experimentHash,124,lineage);ledger.bindExecutor(sha256(await readFile(recoveryManifestPath)),sha256(await readFile(previousPath)),sha256(await readFile(validationPath)));ledger.begin(dPlan.targetStage,dPlan.preparedSnapshotHash,2);let node:Awaited<ReturnType<typeof openNode>>['node'];
 ({node}=await openNode(vault,model,time,async(_reader,input)=>{dSecondCalls++;node.memoryPipeline.pause(jobId);const running=node.store.db.prepare("SELECT id FROM model_usage WHERE json_extract(json,'$.status')='running'").all();equal(running.length,1,'fixture_d_receipt_ambiguous');const id=ledger.reserve(hashObject([jobId,originalRows[0].id,'extract',lineage.plan.sha256,2]),'generated-d-failure',String(running[0].id));try{return await fixtureOuterDeadline();}catch(error){ledger.terminal(id,'failed','outer_deadline_exceeded',{modelRunStarts:1,repairs:0});throw error;}}));
 try{node.memoryPipeline.resume(jobId);const result=await node.memoryPipeline.run(jobId);check(result.status==='paused'&&result.batches[0].attempts===2&&result.batches[0].errorCode==='model_failed','fixture_d_second_failure');await new Promise(resolve=>setTimeout(resolve,Math.max(0,(result.availableAt??0)-Date.now())+10));}finally{await node.app.close();}
 const db=new DatabaseSync(join(vault,'mote.sqlite'),{readOnly:true});try{const usage=db.prepare('SELECT json FROM model_usage').all().map(r=>JSON.parse(String(r.json))),prior=new Set(ledger.events.filter(e=>e.kind==='receipt').map(e=>e.data.id));ledger.receipts(usage.filter(r=>!prior.has(r.id)).map(usageProjection));}finally{db.close();}eSource=join(output,'d-second-closed');await cloneClosed(vault,eSource);ledger.finish(await treeHash(eSource),false);equal([ledger.summary().admitted,ledger.summary().completed,ledger.summary().failed,ledger.summary().incompleteReceipts],[14,12,2,2],'fixture_d_history_shape');ledger.close();
 await cp(eLedger,join(output,'e-stopped-baseline'),{recursive:true});eRequestPath=join(output,'ROOT_SAFE_e-request.json');await writeFile(eRequestPath,json({schema:'mote-heldout-recovery-e-request@1',experimentHash:fixtureRoot.experimentHash,parentD:lineage,stoppedHeadHash:readAdmissionChain(eLedger).at(-1)!.sha256,failedSnapshotHash:await treeHash(eSource)}));checks.push({name:'historical-d-second-failure',passed:true,stubCalls:1,oldErrorPreserved:true});
});
test('E prepares one attempt with zero admissions and only the effective deadline changes',async()=>{
 const prefix=await readFile(join(eLedger,'admissions.ndjson')),source=await treeHash(eSource),out=await newOutput(join(output,'e-freeze'));const frozen=await freezeRecoveryE({request:await ref(eRequestPath),rootManifest:rootPath,previousManifest:recoveryManifestPath,failedSnapshot:eSource,ledgerDirectory:eLedger,validation:validationPath,supervisorPath:eSupervisor,output:out});eManifest=frozen.manifest;ePlan=frozen.plan;eManifestPath=join(out,'ROOT_SAFE_manifest.json');equal(await treeHash(eSource),source,'fixture_e_source_mutated');check((await readFile(join(eLedger,'admissions.ndjson'))).subarray(0,prefix.length).equals(prefix),'fixture_e_old_bytes_changed');equal(readAdmissionChain(eLedger).filter(e=>e.kind==='admit').length,14,'fixture_e_prepare_admitted');equal(eManifest.limits,recoveryELimits,'fixture_e_limits');check(ePlan.oldSettingsHash!==ePlan.effectiveSettingsHash,'fixture_e_settings_not_updated');eBaseline=join(output,'e-authorized-baseline');await cp(eLedger,eBaseline,{recursive:true});checks.push({name:'e-zero-call-preparation',passed:true,inheritedAdmissions:14,newProviderCalls:0,oldBytesPreserved:true});
});
async function freshE(name:string){const ledgerDirectory=join(output,'e-'+name+'-ledger');await cp(eBaseline,ledgerDirectory,{recursive:true});return {manifest:fixtureRoot,manifestHash:sha256(await readFile(eManifestPath)),sequence:eManifest,ledgerDirectory,output:await newOutput(join(output,'e-'+name+'-run'))};}
const memoryAnswer=async(reader:ContextReader,input:QueryInput):Promise<QueryResult>=>{const source=(await reader.evidence({ids:input.evidenceIds!}))[0];input.onUsage?.({measurement:'thread_cumulative',complete:true,requests:0,reportedRequests:0,inputTokens:5,outputTokens:3,totalTokens:8});return {answer:JSON.stringify({memories:[{domain:'personal',title:'E generated fixture',statement:'Generated literal ['+source.id+']',uncertainty:'Mechanical only',admission:{layer:'memory',reason:'Generated fixture',scope:'Fixture',attribution:'observed'},evidenceIds:[source.id],evidence:[{id:source.id,quote:source.ocrText.slice(0,60)}]}]}),citations:[{id:source.id,capturedAt:source.capturedAt,appName:source.appName,excerpt:source.ocrText}],trace:[],runId:randomUUID()};};
test('E generation and review commit once then stop before every subsequent phase',async()=>{
 const outerTimers:number[]=[];const originalSetTimeout=globalThis.setTimeout;const timerMock=mock.method(globalThis,'setTimeout',((fn:any,ms:number,...args:any[])=>{if(ms===600000)outerTimers.push(ms);return originalSetTimeout(fn,ms,...args);}) as typeof setTimeout);const opts=await freshE('success'),prefix=await readFile(join(opts.ledgerDirectory,'admissions.ndjson')),seen:string[]=[];const result=await runBatch({...opts,stub:async(reader,input)=>{eCalls++;seen.push(String(input.traceContext?.phase));equal(input.traceContext?.attempt,3,'fixture_e_attempt_changed');return memoryAnswer(reader,input);}});timerMock.mock.restore();equal(outerTimers,[600000,600000],'fixture_e_outer_deadlines_changed');check(result.succeeded,'fixture_e_not_successful');equal(seen,['extract','review'],'fixture_e_expected_two_phases');equal([result.report.cumulative.admitted,result.report.cumulative.completed,result.report.cumulative.failed,result.report.cumulative.incompleteReceipts],[16,14,2,2],'fixture_e_history_lost');equal([result.report.status,result.report.effectiveAgentTimeoutMs,result.report.cumulative.stopped],['completed-stopped',600000,true],'fixture_e_not_closed');const events=readAdmissionChain(opts.ledgerDirectory);equal(events.slice(-2).map(e=>[e.kind,e.data.succeeded??e.data.code]),[['stage-close',true],['stop','recovery_e_complete']],'fixture_e_success_close_order');check((await readFile(join(opts.ledgerDirectory,'admissions.ndjson'))).subarray(0,prefix.length).equals(prefix),'fixture_e_prefix_mutated');await rejection('e-reopen',()=>new AdmissionLedger(opts.ledgerDirectory,fixtureRoot.experimentHash,124,undefined,eManifest.recoveryE),'recovery_e_already_consumed');await rejection('e-next-phase',()=>eBatchAuthority({...eManifest,task:{...eManifest.task,index:1 as 0}},opts.ledgerDirectory),'recovery_e_phase_scope_invalid');checks.push({name:'e-complete-and-stop',passed:true,stubCalls:2,admitted:16});
});
for(const failure of ['extract','review','abort'] as const)test('E '+failure+' stops new admission and retains historical failures',async()=>{
 const opts=await freshE(failure);let calls=0;const result=await runBatch({...opts,stub:async(reader,input)=>{calls++;eCalls++;if(failure==='abort')return new Promise<never>((_,reject)=>{input.signal!.addEventListener('abort',()=>reject(input.signal!.reason),{once:true});setImmediate(()=>process.emit('SIGINT'));});if(input.traceContext?.phase===failure)throw new Error('Generated model failure');return memoryAnswer(reader,input);}});check(!result.succeeded,'fixture_e_failure_not_stopped');equal(calls,failure==='review'?2:1,'fixture_e_failure_more_calls');equal(result.report.cumulative.failed,3,'fixture_e_prior_failure_lost');const events=readAdmissionChain(opts.ledgerDirectory);check(events.at(-1)?.kind==='stage-close'&&events.at(-1)?.data.succeeded===false,'fixture_e_failed_close_missing');if(failure==='abort')equal(events.filter(e=>e.kind==='stop').at(-1)?.data.code,'stage_interrupted','fixture_e_abort_changed');await rejection('e-failure-reopen-'+failure,()=>new AdmissionLedger(opts.ledgerDirectory,fixtureRoot.experimentHash,124,undefined,eManifest.recoveryE),'recovery_e_already_consumed');checks.push({name:'e-stop-'+failure,passed:true,stubCalls:calls});
});
test('E parent mutation cannot be recorded as a successful closed batch',async()=>{
 const opts=await freshE('parent-mutation'),marker=join(ePlan.preparedPath,'generated-parent-mutation');try{const result=await runBatch({...opts,stub:async(reader,input)=>{eCalls++;if(input.traceContext?.phase==='review')await writeFile(marker,'generated fixture');return memoryAnswer(reader,input);}});check(!result.succeeded,'fixture_e_mutated_parent_succeeded');const tail=readAdmissionChain(opts.ledgerDirectory).filter(e=>e.index>readAdmissionChain(eBaseline).at(-1)!.index);check(!tail.some(e=>e.kind==='stage-close'&&e.data.succeeded===true)&&!tail.some(e=>e.kind==='stop'&&e.data.code==='recovery_e_complete'),'fixture_e_success_recorded_before_final_guard');checks.push({name:'e-parent-guard-before-success',passed:true,stubCalls:2});}finally{await unlink(marker).catch(()=>{});}
});
test('E strict scope, hash, limits and single permission reject before admission',async()=>{
 const before=await readFile(join(eBaseline,'admissions.ndjson'));
 await rejection('e-old-d-reuse',()=>authorizeRecovery(eBaseline,lineage.plan),'recovery_not_original_stopped_head');
 await rejection('e-second-permission',()=>authorizeRecoveryE(eBaseline,eManifest.recoveryE.plan),'recovery_e_already_authorized');
 for(const [name,mutate,code] of [['old-schema',(m:any)=>m.schema='mote-heldout-phase-manifest@1','recovery_e_phase_scope_invalid'],['old-lineage',(m:any)=>m.recoveryLineage=lineage,'recovery_e_phase_scope_invalid'],['wave',(m:any)=>m.task.wave=3,'recovery_e_phase_scope_invalid'],['timeout',(m:any)=>m.limits.perOuterMs=300000,'recovery_e_limits_changed'],['bool',(m:any)=>m.limits.stageOuter=true,'recovery_e_limits_changed'],['hash',(m:any)=>m.recoveryE.plan.sha256='0'.repeat(64),'recovery_e_event_plan_changed']] as const){const m=structuredClone(eManifest);mutate(m);await rejection('e-'+name,()=>eBatchAuthority(m,eBaseline),code);}
 equal(await readFile(join(eBaseline,'admissions.ndjson'),'utf8'),before.toString(),'fixture_e_negative_ledger_changed');
 const directory=join(output,'e-budget-ledger');await cp(eBaseline,directory,{recursive:true});const ledger=new AdmissionLedger(directory,fixtureRoot.experimentHash,124,undefined,eManifest.recoveryE);try{await rejection('e-other-stage',()=>ledger.begin('other',ePlan.preparedSnapshotHash,2),'recovery_e_stage_scope_changed');ledger.begin(ePlan.targetStage,ePlan.preparedSnapshotHash,2);for(let i=0;i<2;i++){const receipt='generated-e-cap-'+i,id=ledger.reserve(receipt,'generated',receipt);ledger.terminal(id,'completed','ok',{modelRunStarts:0,repairs:0});ledger.receipts([{id:receipt,status:'completed',tokens:{complete:true,totalTokens:0}}]);}await rejection('e-seventeenth',()=>ledger.reserve('generated-third','generated','generated-third'),'admission_budget_exceeded');equal(ledger.admitted.length,16,'fixture_e_cap_not16');}finally{ledger.close();}checks.push({name:'e-guarded-permission',passed:true,newProviderCalls:0});
});
test('actual E freeze CLI is explicit and missing or mixed E arguments reject before reservation',async()=>{
 const clean=Object.fromEntries(Object.entries(process.env).filter(([key])=>!key.startsWith('MOTE_')&&!key.startsWith('NODE_')));const directory=join(output,'e-cli-ledger');await cp(join(output,'e-stopped-baseline'),directory,{recursive:true});const before=await readFile(join(directory,'admissions.ndjson'));const common={...clean,MOTE_HELDOUT_MODE:'stage-recovery-freeze',MOTE_HELDOUT_ROOT_MANIFEST:rootPath,MOTE_HELDOUT_MANIFEST:recoveryManifestPath,MOTE_HELDOUT_LEDGER:directory,MOTE_HELDOUT_PARENT:eSource,MOTE_HELDOUT_VALIDATION:validationPath,MOTE_HELDOUT_SUPERVISOR:eSupervisor,MOTE_HELDOUT_RECOVERY_E_REQUEST:eRequestPath};
 for(const [name,extra,code] of [['missing-hash',{},'recovery_e_request_pair_required'],['mixed-lineage',{MOTE_HELDOUT_RECOVERY_E_REQUEST_SHA256:(await ref(eRequestPath)).sha256,MOTE_HELDOUT_RECOVERY_LINEAGE:'generated-unused'},'recovery_e_cli_scope_invalid']] as const){const destination=join(output,'e-cli-'+name),result=spawnSync(process.execPath,['--import','tsx','scripts/test-heldout-memory-replay.ts'],{cwd:process.cwd(),env:{...common,...extra,MOTE_HELDOUT_OUTPUT:destination},encoding:'utf8',timeout:30000});equal(result.status,1,'fixture_e_cli_negative_exit');const status=JSON.parse(await readFile(join(destination,'ROOT_SAFE_status.json'),'utf8'));equal(status.code,code,'fixture_e_cli_negative_code');check(!existsSync(join(directory,'recovery-e-preparation.json')),'fixture_e_cli_invalid_reserved');equal(await readFile(join(directory,'admissions.ndjson'),'utf8'),before.toString(),'fixture_e_cli_negative_ledger_changed');}
 const destination=join(output,'e-cli-frozen'),result=spawnSync(process.execPath,['--import','tsx','scripts/test-heldout-memory-replay.ts'],{cwd:process.cwd(),env:{...common,MOTE_HELDOUT_RECOVERY_E_REQUEST_SHA256:(await ref(eRequestPath)).sha256,MOTE_HELDOUT_OUTPUT:destination},encoding:'utf8',timeout:30000});equal(result.status,0,'fixture_e_cli_freeze_failed');const manifest=JSON.parse(await readFile(join(destination,'ROOT_SAFE_manifest.json'),'utf8'));equal(manifest.schema,'mote-heldout-e-phase-manifest@1','fixture_e_cli_wrong_schema');check((await readFile(join(directory,'admissions.ndjson'))).subarray(0,before.length).equals(before),'fixture_e_cli_prefix_changed');equal(readAdmissionChain(directory).filter(e=>e.kind==='admit').length,14,'fixture_e_cli_called_provider');checks.push({name:'actual-e-freeze-cli',passed:true,newProviderCalls:0,negativeCases:2});
});
test('generated Codex transport receives actual 600000 timers beyond the old scaled deadline',async()=>{
 const transportRoot=join(output,'generated-codex-transport');let transportSpawns=0;const originalSpawn=childProcess.spawn;const spawnMock=mock.method(childProcess,'spawn',((command:string,...args:any[])=>{check(command.startsWith(transportRoot+'/fake-codex-'),'fixture_transport_spawn_outside_generated');transportSpawns++;return (originalSpawn as any)(command,...args);}) as typeof childProcess.spawn);syncBuiltinESMExports();await mkdir(transportRoot);await writeFile(join(transportRoot,'auth.json'),JSON.stringify({OPENAI_API_KEY:'generated-unused-key'}));const timers:number[]=[],signals:number[]=[];const originalSetTimeout=globalThis.setTimeout,originalSignalTimeout=AbortSignal.timeout.bind(AbortSignal);
 const timerMock=mock.method(globalThis,'setTimeout',((fn:any,ms:number,...args:any[])=>{if(ms===600000||ms===300000)timers.push(ms);return originalSetTimeout(fn,ms===600000?6000:ms===300000?3000:ms,...args);}) as typeof setTimeout);const signalMock=mock.method(AbortSignal,'timeout',(ms:number)=>{if(ms===600000||ms===300000)signals.push(ms);return originalSignalTimeout(ms===600000?6000:ms===300000?3000:ms);});
 try{for(const mode of ['completed','deadline'] as const){const bin=join(transportRoot,'fake-codex-'+mode+'.mjs');await writeFile(bin,`#!${process.execPath}
import readline from 'node:readline';
import {appendFileSync} from 'node:fs';
const send=v=>process.stdout.write(JSON.stringify(v)+'\\n');
readline.createInterface({input:process.stdin}).on('line',line=>{const m=JSON.parse(line);appendFileSync(${JSON.stringify(join(transportRoot,'ROOT_SAFE_rpc-'+mode+'.ndjson'))},JSON.stringify({method:m.method??null})+'\\n');if(m.method==='initialize')send({id:m.id,result:{}});else if(m.method==='account/read')send({id:m.id,result:{account:{type:'apiKey'}}});else if(m.method==='thread/start')send({id:m.id,result:{thread:{id:'generated'},approvalPolicy:'never',sandbox:{type:'readOnly'}}});else if(m.method==='turn/start'){send({id:m.id,result:{turn:{id:'generated-turn'}}});${mode==='completed'?`setTimeout(()=>{send({method:'item/completed',params:{threadId:'generated',item:{id:'generated-answer',type:'agentMessage',text:JSON.stringify({answer:'{"memories":[]}',citationIds:[]})}}});send({method:'turn/completed',params:{threadId:'generated',turn:{status:'completed'}}});},3500);`:''}}});
`,{mode:0o700});const liveStubModel={...model,codexBin:bin,codexBinHash:sha256(await readFile(bin)),codexHome:transportRoot};const {node}=await openNode(join(transportRoot,'vault-'+mode),liveStubModel,time,undefined,600000);try{equal(node.modelSettings.select('memory').settings.agentTimeoutMs,600000,'fixture_codex_profile_deadline');let failure:unknown;const types:string[]=[];try{await node.featureServices.queryAgent({question:'Generated timer fixture',skill:'memory-extraction',responseMode:'memory-extraction',onTrace:event=>types.push(event.type)},'query','memories');}catch(error){failure=error;}await writeFile(join(transportRoot,'ROOT_SAFE_'+mode+'.json'),json({error:failure instanceof Error?failure.name:null,reason:(failure as any)?.reason??null,types,timers,signals}));if(mode==='completed')check(!failure,'fixture_codex_old_deadline_still_active');else check(failure instanceof Error&&failure.name==='AgentTimeoutError','fixture_codex_deadline_not_enforced');}finally{await node.app.close();}}
 equal(transportSpawns,2,'fixture_codex_child_count');equal(timers,[600000,600000],'fixture_codex_session_timer_not600');equal(signals,[600000,600000],'fixture_server_signal_not600');checks.push({name:'effective-server-agent-codex-deadline',passed:true,generatedCodexProcesses:2,realProviderCalls:0,configuredMs:600000,scaledMs:6000,completedAfterMs:3500,oldScaledMs:3000,serverSignals:signals,sessionTimers:timers});
 }finally{timerMock.mock.restore();signalMock.mock.restore();spawnMock.mock.restore();syncBuiltinESMExports();}
});
after(async()=>{await writeFile(join(output,'ROOT_SAFE_recovery-E.json'),json({schema:'mote-heldout-sequence-validation@1',status:passedTests===testCount?'passed':'incomplete',tests:{passed:passedTests,total:testCount},validatedPhases:['recovery-E'],realModelCalls:0,heldoutSemanticInputsRead:false,stubModelCalls:calls+bootstrapCalls+dSecondCalls+eCalls,syntheticHistoricalAdmissions,executorCodeHashes:executorPins(await codeHashes()),checks}));});
