/** One planned wave-1 batch per invocation. All model/source payloads stay in DO_NOT_OPEN. */
import {execFileSync} from 'node:child_process';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdir,readFile,readdir,realpath,writeFile} from 'node:fs/promises';
import {join,resolve,relative} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import type {AgentAnswer,ContextReader,QueryInput} from '@mote/agent';
import {sourceItemSchema,type QueryResult,type UsageReceipt} from '@mote/shared';
import {buildApp} from '../apps/server/src/app.js';
import {repositoryRoot,type Config} from '../apps/server/src/config.js';
import {sha256} from '../apps/server/src/store.js';
import {usageTotals} from '../apps/server/src/usage.js';
import {defaultMemoryIntegrationRecipe} from '../apps/server/src/memory-integration-policy.js';
import {corpus,evaluation,freezes,recipes,SafeFailure,check,equal,json,hashObject,externalNew,parse,verifyFreeze,lines,config,tables,closed,cloneClosed,ablateClone,sqliteCheck} from './test-heldout-memory-replay.js';
import {AdmissionLedger,StageSafetyError,inspectAdmissionLedger,type LedgerEvent} from './test-heldout-memory-replay-ledger.js';
type Node=Awaited<ReturnType<typeof buildApp>>;
type Stub=(reader:ContextReader,input:QueryInput)=>Promise<QueryResult>;
export type RuntimePin={nodeVersion:string;nodeExecutable:string;nodeExecutableSha256:string};
export async function runtimePin():Promise<RuntimePin>{const nodeExecutable=await realpath(process.execPath);return {nodeVersion:process.version,nodeExecutable,nodeExecutableSha256:sha256(await readFile(nodeExecutable))};}
export async function assertRuntimePin(expected:RuntimePin){const actual=await runtimePin();check(expected.nodeVersion===actual.nodeVersion,'runtime_node_changed');check(expected.nodeExecutable===actual.nodeExecutable,'runtime_node_path_changed');check(expected.nodeExecutableSha256===actual.nodeExecutableSha256,'runtime_node_binary_changed');}
export type Manifest={continuation?:{parent:string;parentTreeHash:string;index:number;previousManifestPath:string;previousManifestHash:string;offlineValidationPath:string;offlineValidationHash:string};schema:string;executor:{supervisorPath:string;supervisorHash:string};runtime:RuntimePin;experimentHash:string;experimentPlan:unknown;kind:'heldout'|'mechanical';revision:string;corpusFreeze:string;evaluationFreeze:string;codeHashes:Record<string,string>;model:{provider:'codex';protocol:'codex-app-server';model:'gpt-6-sol';reasoningEffort:'max';codexBin:string;codexBinHash:string;codexHome:string};contextTime:string;limits:{stageOuter:2;perOuterMs:300000;stageProcessMs:720000;cumulativePlanningCap:124;automaticOuterRetries:0;concurrency:1};seed:string;seedTreeHash:string;jobId:string;batchPlan:Array<{id:string;index:number;sha256:string;recipe:unknown}>;settingsHash:string;bindingsHash:string;protectedHash:string;scope:{wave:1;deliveries:number;materials:number;selectedBatchIndex:0;futureWavesImported:false};remainingRunner:'Integration, later-wave ingestion, multi-question A/B and failure retry are not implemented or validated by this runner.'};
const fixedLimits={stageOuter:2,perOuterMs:300000,stageProcessMs:720000,cumulativePlanningCap:124,automaticOuterRetries:0,concurrency:1} as const;
const experimentPlan={version:'heldout-v2.1-six-wave@1',batchesByWave:[6,6,10,6,8,6],stageOuterCaps:[2,14,18,26,18,22,16,2,2,2,2],totalOuterPlanningCap:124,extractionRecipes:recipes,integrationRecipe:defaultMemoryIntegrationRecipe,batchCharacters:12000,clock:'checkpoint-availability.json contextTime frozen per host task',outerAutomaticRetries:0};
export function experimentHash(m:Manifest){return hashObject({corpus:m.corpusFreeze,evaluation:m.evaluationFreeze,production:Object.fromEntries(Object.entries(m.codeHashes).filter(([file])=>!file.startsWith('scripts/'))),model:m.model,runtime:m.runtime,bindings:m.bindingsHash,initialSeed:m.seedTreeHash,initialBatchPlan:m.batchPlan,plan:m.experimentPlan});}
const supervisor=join('/Users/utopiafar/Documents/Codex/mote-goal-2026-09-27','run-heldout-stage-supervised.py');
const semantics='2025-11-30T23:59:59+08:00';
const safeCode=(e:unknown)=>e instanceof SafeFailure||e instanceof StageSafetyError?e.code:'internal_error_details_sealed';
async function privateWrite(path:string,value:unknown){await writeFile(path,json(value),{mode:0o600});}
async function sealedError(directory:string,error:unknown){await privateWrite(join(directory,'error-'+randomUUID()+'.json'),{name:error instanceof Error?error.name:typeof error,message:error instanceof Error?error.message:String(error),stack:error instanceof Error?error.stack:undefined});}
async function newOutput(path:string){const output=await externalNew(path);await mkdir(output,{mode:0o700});await mkdir(join(output,'DO_NOT_OPEN'),{mode:0o700});await writeFile(join(output,'DO_NOT_OPEN','README.txt'),'SEALED heldout source, identities, model output, traces and exception details. Root and implementation agents must not inspect.\n',{mode:0o600});return output;}
async function treeFiles(directory:string,prefix=''):Promise<string[]>{const out:string[]=[];for(const entry of await readdir(join(directory,prefix),{withFileTypes:true})){const name=join(prefix,entry.name);if(entry.isDirectory())out.push(...await treeFiles(directory,name));else if(entry.isFile())out.push(name);else throw new SafeFailure('snapshot_contains_link');}return out.sort();}
async function treeHash(directory:string){const names=(await treeFiles(directory)).filter(name=>!name.startsWith('logs/')&&name!=='token'&&!name.endsWith('-shm')&&!name.endsWith('-wal'));return hashObject(Object.fromEntries(await Promise.all(names.map(async name=>[name,sha256(await readFile(join(directory,name)))]))));}
export async function codeHashes(){const tracked=execFileSync('git',['ls-files','apps/server/src','packages/agent/src','packages/agent/skills','packages/shared/src','packages/local-inference/src','packages/diagnostics/src','package-lock.json','package.json','tsconfig.base.json','apps/server/package.json','apps/server/tsconfig.json','packages/agent/package.json','packages/shared/package.json','packages/local-inference/package.json','packages/diagnostics/package.json'],{cwd:repositoryRoot,encoding:'utf8'}).trim().split('\n').filter(Boolean);const paths=[...tracked,'scripts/test-heldout-memory-replay.ts','scripts/test-heldout-memory-replay-stage.ts','scripts/test-heldout-memory-replay-ledger.ts','scripts/test-heldout-memory-replay-sequence.ts','scripts/test-heldout-memory-replay-integration.ts','scripts/test-heldout-memory-replay-ask.ts','scripts/test-heldout-memory-replay-ask-schema.json'];for(const name of ['agent','shared','local-inference','diagnostics'])for(const file of await treeFiles(join(repositoryRoot,'packages',name,'dist')))paths.push(join('packages',name,'dist',file));return Object.fromEntries(await Promise.all([...new Set(paths)].sort().map(async file=>[file,sha256(await readFile(join(repositoryRoot,file)))])));}
const mutable=new Set(['memories','memory_catalog','memory_scopes','memory_dependencies','memory_artifact_dependencies','memory_jobs','memory_batches','memory_batch_dependencies','memory_job_counts','memory_checkpoints','memory_extraction_drafts','memory_extraction_draft_dependencies','memory_lifecycle_state','memory_events','memory_input_plans','memory_input_authorizations','memories_fts','memories_fts_data','memories_fts_idx','memories_fts_content','memories_fts_docsize','memories_fts_config','storage_ledger','model_usage','execution_operations','execution_steps','execution_jobs','execution_fairness','execution_operation_steps','execution_sequence','execution_resources','operation_changes','operation_progress','run_execution_owners']);
function protectedTables(db:DatabaseSync){return Object.fromEntries(Object.entries(tables(db)).filter(([name])=>!mutable.has(name)));}
function batchPin(value:any){const copy=structuredClone(value);if(copy.status==='pending'&&copy.attempts===0&&copy.errorCode==='paused')delete copy.errorCode;return hashObject(copy);}
function bindings(node:Node){return {extraction:recipes.map(recipe=>node.memoryStrategies.resolve(recipe).binding),integration:node.memoryStrategies.resolveIntegration(defaultMemoryIntegrationRecipe).binding};}
function settings(node:Node){return {models:node.modelSettings.view(),execution:JSON.parse(String(node.store.db.prepare("SELECT value FROM settings WHERE key='execution-settings'").get()!.value)),lifecycle:node.lifecycle.settings(),bindings:bindings(node)};}
function stageConfig(vault:string,model:Manifest['model'],stub:boolean):Config{return {...config(vault),token:randomBytes(32).toString('hex'),model:'gpt-6-sol',modelProvider:'codex',modelProtocol:'codex-app-server',modelBaseUrl:'',allowUnauthenticatedLocal:false,modelReasoningEffort:'max',agentConcurrency:1,llmConcurrency:1,memoryConcurrency:1,agentTimeoutMs:300000,codexBin:stub?'/nonexistent-stage-stub':model.codexBin,codexHome:stub?join(vault,'unused-codex-home'):model.codexHome};}
async function openNode(vault:string,model:Manifest['model'],time:string,stub?:Stub){const cfg=stageConfig(vault,model,Boolean(stub)),node=await buildApp(cfg,{backgroundWorker:false,semanticContextTime:()=>time,...(stub?{createModelAgent:async(_settings:any,reader:ContextReader)=>({configured:true,close:async()=>{},query:(input:QueryInput)=>stub(reader,input)})}:{})});
  const lifecycle=node.lifecycle.settings();for(const key of ['extraction','consolidation','insights','working'] as const)lifecycle[key].enabled=false;node.lifecycle.configure(lifecycle);node.memoryRecipeSettings.configure({recipes});await node.app.ready();
  const request=async(method:'POST'|'PUT',url:string,payload:unknown)=>{const response=await node.app.inject({method,url,payload:payload as object,headers:{authorization:'Bearer '+cfg.token,'x-mote-ingress-version':'2'}});check(response.statusCode>=200&&response.statusCode<300,'stage_api_status_'+response.statusCode);return response.json();};await request('PUT','/api/execution-settings',{interactiveConcurrency:1,agentConcurrency:1,llmConcurrency:1,memoryConcurrency:1});return {node,request};}
async function drain(node:Node){for(const operation of [()=>node.sourcePipelines.tick(100),()=>node.materialOrganizer.tick(100)]){let done=false;for(let i=0;i<30;i++)if(await operation()===0){done=true;break;}check(done,'stage_source_not_drained');}for(let i=0;i<30;i++)if(node.store.archive.aggregate(100)===0)break;check(Number(node.store.db.prepare('SELECT count(*) n FROM context_dirty').get()!.n)===0,'stage_index_not_drained');}
async function modelPin(mechanical:boolean):Promise<Manifest['model']>{if(mechanical)return {provider:'codex',protocol:'codex-app-server',model:'gpt-6-sol',reasoningEffort:'max',codexBin:'/nonexistent-stage-stub',codexBinHash:'stub',codexHome:'/nonexistent-stage-stub-home'};
  check(process.env.MOTE_CODEX_BIN&&process.env.MOTE_CODEX_HOME,'explicit_codex_paths_required');const codexBin=await realpath(process.env.MOTE_CODEX_BIN),codexHome=await realpath(process.env.MOTE_CODEX_HOME);return {provider:'codex',protocol:'codex-app-server',model:'gpt-6-sol',reasoningEffort:'max',codexBin,codexBinHash:sha256(await readFile(codexBin)),codexHome};}
const noProvider:Stub=async()=>{throw new SafeFailure('freeze_provider_forbidden');};
/** Freeze only wave 1 from ordinary ingress. No query or model result is loaded. */
export async function freezeStage(output:string,mechanical=false,mechanicalRecords:1|2=1,mechanicalExtraSources:unknown[]=[]){
  check(mechanical||mechanicalExtraSources.length===0,'mechanical_sources_forbidden');
  const model=await modelPin(mechanical);if(!mechanical){await verifyFreeze(corpus,freezes.corpus);await verifyFreeze(evaluation,freezes.evaluation);}
  const vault=join(output,'DO_NOT_OPEN','fresh-import'),{node,request}=await openNode(vault,model,semantics,noProvider);let manifest:Manifest;
  try{
    let deliveries=0;
    if(mechanical){for(const source of mechanicalExtraSources)await request('POST','/api/sources',source);await request('POST','/api/sources',{id:'stage-fixture',name:'Mechanical stage fixture',kind:'custom',deviceId:'stage-fixture',platform:'import',retention:'archive'});for(let record=0;record<mechanicalRecords;record++)await request('PUT','/api/sources/stage-fixture/items',{externalId:'mechanical-'+record,revision:'1',kind:'message',layer:'original',observedAt:'2025-11-01T10:00:00+08:00',text:'Independent mechanical stage fixture. The marker is a literal, generated sentence used to exercise durable batch boundaries.'.repeat(mechanicalRecords===2?4:1),document:{contentRole:'authored',recordedAt:'2025-11-01T10:00:00+08:00',timeBasis:'recorded'}});deliveries=mechanicalRecords;await drain(node);}
    else{
      const transport=await parse(join(corpus,'transport-manifest.json')),items=await lines(join(corpus,'source-items.ndjson')),availability=await parse(join(evaluation,'checkpoint-availability.json'));const checkpoint=availability.checkpoints.find((row:any)=>row.checkpointWave===1);check(checkpoint?.contextTime===semantics,'wave1_clock_changed');const wave=transport.deliveries.filter((row:any)=>row.wave===1);check(wave.length===17,'wave1_delivery_count_changed');
      for(const source of transport.sources)await request('POST','/api/sources',source);
      for(const delivery of wave){const line=items[delivery.sourceItemLine-1];check(line&&sha256(line.bytes)===delivery.sourceItemSha256,'wave1_item_hash_mismatch');const item=sourceItemSchema.parse(line.value);for(const field of ['wave','availableAfter','eventGroups','receivedAt'])check(!Object.hasOwn(item,field),'wave1_orchestration_leak');const before=Date.now();const ack=await request('PUT','/api/sources/'+encodeURIComponent(delivery.sourceId)+'/items',item);check(!ack.duplicate,'wave1_unexpected_duplicate');const capture=node.store.evidence([ack.id])[0];if(capture)check(Date.parse(capture.receivedAt)>=before&&Date.parse(capture.receivedAt)<=Date.now(),'wave1_received_at_not_real');if(item.document?.coding)await drain(node);deliveries++;}
      await drain(node);
    }
    const heads=node.store.db.prepare('SELECT id FROM material_heads WHERE retired=0 ORDER BY id').all();const ids=[...new Set(heads.flatMap(row=>node.materials.evidenceIds(node.materials.get(String(row.id))!.ref)))];check(ids.length>0,'stage_no_inputs');const job=node.memoryPipeline.create({evidenceIds:ids,recipes,contextTime:semantics,timeZone:'Asia/Shanghai',batchCharacters:mechanical&&mechanicalRecords===2?1024:12000});check(job.totalBatches===(mechanical?2*mechanicalRecords:6),'stage_batch_plan_changed');node.memoryPipeline.pause(job.id);check(node.memoryPipeline.get(job.id).status==='paused','freeze_pause_failed');
    const batchRows=node.store.db.prepare('SELECT json FROM memory_batches WHERE job_id=? ORDER BY idx').all(job.id).map(row=>JSON.parse(String(row.json)));check(batchRows.every(row=>row.status==='pending'&&row.attempts===0),'freeze_started_model_work');
    manifest={schema:'mote-heldout-first-batch-manifest@1',executor:{supervisorPath:supervisor,supervisorHash:sha256(await readFile(supervisor))},runtime:await runtimePin(),experimentHash:'pending',experimentPlan,kind:mechanical?'mechanical':'heldout',revision:execFileSync('git',['rev-parse','HEAD'],{cwd:repositoryRoot,encoding:'utf8'}).trim(),corpusFreeze:freezes.corpus,evaluationFreeze:freezes.evaluation,codeHashes:await codeHashes(),model,contextTime:semantics,limits:fixedLimits,seed:join(output,'DO_NOT_OPEN','frozen-seed'),seedTreeHash:'pending',jobId:job.id,batchPlan:batchRows.map(row=>({id:row.id,index:row.index,sha256:batchPin(row),recipe:row.strategy?.recipe})),settingsHash:hashObject(settings(node)),bindingsHash:hashObject(bindings(node)),protectedHash:hashObject(protectedTables(node.store.db)),scope:{wave:1,deliveries,materials:heads.length,selectedBatchIndex:0,futureWavesImported:false},remainingRunner:'Integration, later-wave ingestion, multi-question A/B and failure retry are not implemented or validated by this runner.'};
    await privateWrite(join(output,'DO_NOT_OPEN','batch-plan.json'),batchRows);
  }finally{await node.app.close();}
  await closed(vault);await cloneClosed(vault,manifest!.seed);manifest!.seedTreeHash=await treeHash(manifest!.seed);const db=new DatabaseSync(join(manifest!.seed,'mote.sqlite'),{readOnly:true});try{check(Number(db.prepare('SELECT count(*) n FROM model_usage').get()!.n)===0,'freeze_usage_not_empty');sqliteCheck(db);}finally{db.close();}
  manifest!.experimentHash=experimentHash(manifest!);await privateWrite(join(output,'ROOT_SAFE_manifest.json'),manifest!);return manifest!;
}
const productionPins=(hashes:Record<string,string>)=>Object.fromEntries(Object.entries(hashes).filter(([file])=>!file.startsWith('scripts/')));
export const executorPins=(hashes:Record<string,string>)=>Object.fromEntries(Object.entries(hashes).filter(([file])=>file.startsWith('scripts/')));
function assertNextStage(events:LedgerEvent[],m:Manifest,parentHash:string,index:number,previousManifestHash:string){
  const stages=events.filter(row=>row.kind==='stage-close');check(stages.length===index&&stages.every((row,i)=>row.data.succeeded&&row.data.stage==='wave1-batch-'+i),'resume_index_not_next');
  const last=stages.at(-1);check(last&&last.data.snapshotHash===parentHash,'resume_parent_not_latest_checkpoint');
  check(events.filter(row=>row.kind==='executor-freeze').at(-1)?.data.manifestHash===previousManifestHash,'resume_executor_not_latest');
  check(index>=1&&index<m.batchPlan.length&&index<=5,'resume_index_out_of_scope');
}
async function assertPendingBoundary(parent:string,m:Manifest,index:number){
  await closed(parent);const db=new DatabaseSync(join(parent,'mote.sqlite'),{readOnly:true});try{sqliteCheck(db);
    equal(hashObject(protectedTables(db)),m.protectedHash,'source_snapshot_changed');const row=db.prepare('SELECT json FROM memory_jobs WHERE id=?').get(m.jobId);check(row,'resume_job_missing');const job=JSON.parse(String(row.json));check(job.status==='paused'&&job.contextTime===m.contextTime&&job.failedBatches===0,'resume_job_not_clean');
    const batches=db.prepare('SELECT json FROM memory_batches WHERE job_id=? ORDER BY idx').all(m.jobId).map(row=>JSON.parse(String(row.json)));check(batches.length===m.batchPlan.length&&batches.every((batch,i)=>batch.id===m.batchPlan[i].id&&(i<index?batch.status==='completed':batch.status==='pending'&&batch.attempts===0&&batchPin(batch)===m.batchPlan[i].sha256)),'resume_batch_boundary_invalid');
    check(batches.findIndex(batch=>batch.status!=='completed')===index,'resume_index_not_next');check(batches.slice(0,index).every(batch=>batch.chunks.every((chunk:any)=>db.prepare('SELECT key FROM memory_checkpoints WHERE key=?').get(chunk.key))),'resume_completed_checkpoint_missing');
  }finally{db.close();}
}
async function validateContinuation(m:Manifest,parent:string,index:number,ledgerDirectory:string){
  const continuation=m.continuation;check(continuation&&continuation.index===index&&await realpath(parent)===continuation.parent,'continuation_parameters_changed');
  const previousBytes=await readFile(continuation.previousManifestPath);check(sha256(previousBytes)===continuation.previousManifestHash,'previous_executor_manifest_changed');const previous=JSON.parse(previousBytes.toString()) as Manifest;
  check(previous.experimentHash===m.experimentHash&&experimentHash(previous)===m.experimentHash,'continuation_experiment_changed');
  const previousStable={...previous,codeHashes:productionPins(previous.codeHashes)},currentStable={...m,codeHashes:productionPins(m.codeHashes)};
  for(const value of [previousStable,currentStable]){delete value.continuation;delete (value as any).executor;delete (value as any).revision;}
  equal(previousStable,currentStable,'continuation_frozen_pins_changed');const validationBytes=await readFile(continuation.offlineValidationPath);check(sha256(validationBytes)===continuation.offlineValidationHash,'continuation_validation_changed');
  const validation=JSON.parse(validationBytes.toString());check(validation.schema==='mote-heldout-continuation-validation@1'&&validation.status==='passed'&&validation.realModelCalls===0&&validation.heldoutSemanticInputsRead===false,'continuation_validation_not_passed');equal(validation.executorCodeHashes,executorPins(m.codeHashes),'continuation_validation_wrong_executor');
  const parentHash=await treeHash(parent);check(parentHash===continuation.parentTreeHash,'continuation_parent_changed');const events=inspectAdmissionLedger(ledgerDirectory,m.experimentHash);assertNextStage(events,m,parentHash,index,continuation.previousManifestHash);await assertPendingBoundary(parent,m,index);return events.at(-1)!.sha256;
}
/** Makes only a new executor manifest. Previous manifests, ledger and closed vault stay read-only. */
export async function freezeContinuation(options:{previousManifest:string;parent:string;index:number;ledgerDirectory:string;validation:string;output:string}){
  const previousManifestPath=await realpath(options.previousManifest),previousBytes=await readFile(previousManifestPath),m=JSON.parse(previousBytes.toString()) as Manifest;check(experimentHash(m)===m.experimentHash,'experiment_identity_changed');await assertRuntimePin(m.runtime);
  const currentHashes=await codeHashes();equal(productionPins(currentHashes),productionPins(m.codeHashes),'continuation_production_pins_changed');const parent=await realpath(options.parent),beforeLedger=inspectAdmissionLedger(options.ledgerDirectory,m.experimentHash).at(-1)!.sha256;
  const next:Manifest={...m,revision:execFileSync('git',['rev-parse','HEAD'],{cwd:repositoryRoot,encoding:'utf8'}).trim(),codeHashes:currentHashes,executor:{supervisorPath:supervisor,supervisorHash:sha256(await readFile(supervisor))},continuation:{parent,parentTreeHash:await treeHash(parent),index:options.index,previousManifestPath,previousManifestHash:sha256(previousBytes),offlineValidationPath:await realpath(options.validation),offlineValidationHash:sha256(await readFile(options.validation))}};
  await validateContinuation(next,parent,options.index,options.ledgerDirectory);check(experimentHash(next)===m.experimentHash,'continuation_experiment_changed');await privateWrite(join(options.output,'ROOT_SAFE_manifest.json'),next);check(inspectAdmissionLedger(options.ledgerDirectory,m.experimentHash).at(-1)!.sha256===beforeLedger,'resume_freeze_mutated_ledger');return next;
}
/** Guards the real factory boundary; no semantic outputs are returned to public metadata. */
export async function runBatch(options:{manifest:Manifest;manifestHash:string;output:string;ledgerDirectory:string;parent?:string;index?:number;stub?:Stub;perOuterMs?:number;sequence?:import('./test-heldout-memory-replay-sequence.js').PhaseManifest}){
  const authority=options.sequence?await (await import('./test-heldout-memory-replay-sequence.js')).phaseBatchAuthority(options.sequence,options.ledgerDirectory):undefined;
  if(authority)equal(options.manifest,authority.root,'phase_execution_root_changed');
  const m:Manifest=authority?{...options.manifest,executor:authority.manifest.executor,codeHashes:authority.manifest.codeHashes,jobId:authority.plan.jobId,batchPlan:authority.plan.batchPlan,contextTime:authority.plan.contextTime,settingsHash:authority.plan.settingsHash,bindingsHash:authority.plan.bindingsHash,protectedHash:authority.plan.protectedHash,scope:{wave:authority.plan.wave as 1,deliveries:authority.plan.deliveries,materials:authority.plan.materials,selectedBatchIndex:0,futureWavesImported:false}}:options.manifest;
  const {output,stub}=options,index=authority?.index??options.index??m.continuation?.index??0;check(Number.isInteger(index)&&index>=0&&index<m.batchPlan.length&&(Boolean(authority)||index<=5),'resume_index_out_of_scope');check(stub||authority||index===0||Boolean(m.continuation),'continuation_manifest_required');check(Boolean(stub)===(m.kind==='mechanical'),'stub_live_manifest_mismatch');
  await assertRuntimePin(m.runtime);
  if(!stub){check(sha256(await readFile(m.executor.supervisorPath))===m.executor.supervisorHash,'supervisor_changed');equal(await codeHashes(),m.codeHashes,'runtime_code_changed');await verifyFreeze(corpus,m.corpusFreeze);await verifyFreeze(evaluation,m.evaluationFreeze);check(sha256(await readFile(m.model.codexBin))===m.model.codexBinHash,'codex_binary_changed');}
  if(!authority)check(m.schema==='mote-heldout-first-batch-manifest@1'&&m.scope.wave===1&&m.scope.selectedBatchIndex===0&&m.scope.futureWavesImported===false,'stage_scope_changed');equal(m.limits,fixedLimits,'stage_limits_changed');equal(m.experimentPlan,experimentPlan,'experiment_plan_changed');check(experimentHash(options.manifest)===m.experimentHash,'experiment_identity_changed');const parent=authority?.manifest.parent.path??options.parent??m.continuation?.parent??m.seed;await closed(parent);if(index===0&&!authority)check(await treeHash(parent)===m.seedTreeHash,'frozen_seed_changed');
  const checkedLedgerHead=authority?.ledgerHead??(m.continuation?await validateContinuation(m,parent,index,options.ledgerDirectory):undefined);if(index>0&&!m.continuation&&!authority){const events=inspectAdmissionLedger(options.ledgerDirectory,m.experimentHash);assertNextStage(events,m,await treeHash(parent),index,options.manifestHash);await assertPendingBoundary(parent,m,index);}
  await externalNew(options.ledgerDirectory);for(const other of [output,parent])for(const [a,b] of [[other,options.ledgerDirectory],[options.ledgerDirectory,other]]){const part=relative(a,b);check(part==='..'||part.startsWith('../'),'ledger_must_be_outside_snapshots');}const ledger=new AdmissionLedger(options.ledgerDirectory,m.experimentHash,124);const stage=authority?.stage??'wave1-batch-'+index;const parentHash=await treeHash(parent);const vault=join(output,'DO_NOT_OPEN','working');let node:Node|undefined;let failure:unknown;let succeeded=false;let inherited=new Set<string>();let newReceipts:UsageReceipt[]=[];let finalJob:any;let snapshot='';let ledgerStarted=false;let activeControl:AbortController|undefined;const interrupted=()=>{ledger.stop('stage_interrupted');activeControl?.abort();node?.memoryPipeline.pause(m.jobId);};process.on('SIGTERM',interrupted);process.on('SIGINT',interrupted);
  const report:Record<string,any>={schema:authority?'mote-heldout-extraction-stage@1':'mote-heldout-first-batch-stage@1',stage,status:'running',manifestHash:options.manifestHash,realModelCalls:0,stubModelCalls:0,outerCountMeaning:'Conservative durable outer admissions; reservation may precede provider start, and unknown reservations are never refunded.',internalCountMeaning:'modelRunStarts counts observed Codex turns, not underlying provider HTTP requests. Thread-cumulative usage may leave request counts unknown.',semanticContentExposed:false,scope:{...m.scope,selectedBatchIndex:index},continuation:m.continuation?{parentTreeHash:m.continuation.parentTreeHash,previousManifestHash:m.continuation.previousManifestHash,offlineValidationHash:m.continuation.offlineValidationHash}:null,startedAt:new Date().toISOString(),limits:m.limits};
  try{
    // Continuation accepts only the preceding completed closed snapshot from this append ledger.
    const prior=ledger.events.filter(row=>row.kind==='stage-close').at(-1);if(!authority&&index>0)check(prior?.data.succeeded&&prior.data.snapshotHash===parentHash,'resume_parent_not_latest_checkpoint');else if(!authority)check(!ledger.admitted.length,'fresh_seed_cannot_rollback_ledger');
    if(checkedLedgerHead)check(ledger.events.at(-1)?.sha256===checkedLedgerHead,'resume_ledger_changed');ledger.bindExecutor(options.manifestHash,authority?.manifest.previousManifest.sha256??m.continuation?.previousManifestHash,authority?.manifest.validation.sha256??m.continuation?.offlineValidationHash);ledger.begin(stage,parentHash,2);ledgerStarted=true;await cloneClosed(parent,vault);
    const initial=new DatabaseSync(join(vault,'mote.sqlite'),{readOnly:true});try{inherited=new Set(initial.prepare('SELECT id FROM model_usage').all().map(row=>String(row.id)));equal(hashObject(protectedTables(initial)),m.protectedHash,'source_snapshot_changed');}finally{initial.close();}
    ({node}=await openNode(vault,m.model,m.contextTime,stub));equal(hashObject(bindings(node)),m.bindingsHash,'recipe_bindings_changed');equal(hashObject(settings(node)),m.settingsHash,'runtime_settings_changed');const job=node.memoryPipeline.get(m.jobId),target=m.batchPlan[index];check(target&&job.status==='paused','stage_job_not_paused');check(batchPin(JSON.parse(String(node.store.db.prepare('SELECT json FROM memory_batches WHERE id=?').get(target.id)!.json)))===target.sha256,'selected_batch_pin_changed');check(job.batches[index].id===target.id&&job.batches[index].status==='pending'&&job.batches[index].attempts===0,'target_batch_not_fresh');check(job.batches.every((batch,i)=>i<index?batch.status==='completed':batch.status==='pending'),'stage_batch_boundary_invalid');
    // This synchronous public projection also runs for a cached empty batch with no query.
    // Pause after the ordinary running projection so the selected grant can finish and commit.
    const originalProject=node.memoryPipeline.engine.project.bind(node.memoryPipeline.engine);node.memoryPipeline.engine.project=(id:string)=>{originalProject(id);if(id===target.id&&node!.memoryPipeline.engine.get(id)?.state==='running')node!.memoryPipeline.pause(m.jobId);};
    const originalQuery=node.agent.query.bind(node.agent);let inFlight=false;const usedReceipts=new Set<string>();
    node.agent.query=async(input:QueryInput)=>{
      const trace=input.traceContext,phase=trace?.phase;
      try{check(!inFlight,'concurrent_outer_forbidden');check(trace?.jobId===m.jobId&&trace?.batchId===target.id&&(phase==='extract'||phase==='review')&&trace.attempt===1,'unexpected_outer_scope');check(input.contextTime===m.contextTime,'outer_semantic_clock_mismatch');
        // Pausing once the selected batch runs preserves its review/commit and bars every next batch.
        node!.memoryPipeline.pause(m.jobId);const receipts=node!.store.db.prepare("SELECT id FROM model_usage WHERE json_extract(json,'$.status')='running'").all().map(row=>String(row.id)).filter(id=>!inherited.has(id)&&!usedReceipts.has(id));check(receipts.length===1,'running_receipt_ambiguous');const receiptId=receipts[0];usedReceipts.add(receiptId);
        const serial=JSON.parse(JSON.stringify(input,(_key,value)=>typeof value==='function'?undefined:value));const inputHash=hashObject(serial);const callId=ledger.reserve(hashObject([m.jobId,target.id,phase]),inputHash,receiptId);inFlight=true;
        await privateWrite(join(output,'DO_NOT_OPEN',callId+'-input.json'),serial);const control=new AbortController();activeControl=control;let timer:ReturnType<typeof setTimeout>|undefined;let requests=0,repairs=0;const traces:unknown[]=[];const abort=()=>control.abort(input.signal?.reason);input.signal?.addEventListener('abort',abort,{once:true});
        try{input.signal?.throwIfAborted();const answer=await Promise.race([originalQuery({...input,signal:control.signal,onTrace:event=>{traces.push(event);if(event.type==='model.started'){requests++;if((event.payload as {repair?:boolean}|undefined)?.repair===true)repairs++;}input.onTrace?.(event);}}),new Promise<never>((_ok,reject)=>{timer=setTimeout(()=>{control.abort();reject(new StageSafetyError('outer_deadline_exceeded'));},options.perOuterMs??m.limits.perOuterMs);})]);
          // The ordinary agent already performs output validation. Verify host mechanics before a success terminal.
          const issue=await input.validateOutput?.(answer as AgentAnswer);check(!issue,'outer_host_validation_failed');await privateWrite(join(output,'DO_NOT_OPEN',callId+'-result.json'),answer);ledger.terminal(callId,'completed','ok',{modelRunStarts:requests||null,repairs:requests?repairs:null});return answer;
        }catch(error){control.abort();await sealedError(join(output,'DO_NOT_OPEN'),error);ledger.terminal(callId,'failed',error instanceof StageSafetyError?error.code:'outer_failed',{modelRunStarts:requests||null,repairs:requests?repairs:null});throw error;}
        finally{if(timer)clearTimeout(timer);input.signal?.removeEventListener('abort',abort);await privateWrite(join(output,'DO_NOT_OPEN',callId+'-trace.json'),traces);inFlight=false;activeControl=undefined;}
      }catch(error){ledger.stop(safeCode(error)==='internal_error_details_sealed'?'outer_failed':safeCode(error));node!.memoryPipeline.pause(m.jobId);throw error;}
    };
    node.memoryPipeline.resume(m.jobId);finalJob=await node.memoryPipeline.run(m.jobId);check(!ledger.stopped,'stage_circuit_stopped');check(finalJob.batches[index].status==='completed'&&finalJob.failedBatches===0&&!finalJob.runningBatches,'selected_batch_not_completed');const storedBatch=JSON.parse(String(node.store.db.prepare('SELECT json FROM memory_batches WHERE id=?').get(target.id)!.json));check(storedBatch.chunks.every((chunk:any)=>node!.store.db.prepare('SELECT key FROM memory_checkpoints WHERE key=?').get(chunk.key)),'committed_checkpoint_missing');check(finalJob.batches.every((batch:any,i:number)=>i<=index?batch.status==='completed':batch.status==='pending'&&batch.attempts===0),'later_batch_started');check(index===m.batchPlan.length-1?['completed','paused'].includes(finalJob.status):finalJob.status==='paused','stage_not_cleanly_paused');
    equal(hashObject(protectedTables(node.store.db)),m.protectedHash,'protected_source_mutated');succeeded=true;
  }catch(error){failure=error;if(ledgerStarted)ledger.stop(safeCode(error));await sealedError(join(output,'DO_NOT_OPEN'),error);}
  finally{
    if(node){node.memoryPipeline.pause(m.jobId);try{await node.app.close();}catch(error){failure??=error;succeeded=false;ledger.stop('close_failed');await sealedError(join(output,'DO_NOT_OPEN'),error);}}
    try{
      await closed(vault);const db=new DatabaseSync(join(vault,'mote.sqlite'),{readOnly:true});try{sqliteCheck(db);newReceipts=db.prepare('SELECT json FROM model_usage').all().map(row=>JSON.parse(String(row.json)) as UsageReceipt).filter(row=>!inherited.has(row.id));report.terminalUsage={readAfterClose:true,inherited:inherited.size,new:newReceipts.length,totals:usageTotals(newReceipts)};report.closedProtectedHash=hashObject(protectedTables(db));}finally{db.close();}
      const admittedIds=new Set(ledger.admitted.map(row=>row.data.receiptId));report.hostRejectedReceipts=newReceipts.filter(row=>!admittedIds.has(row.id)).length;if(report.hostRejectedReceipts)succeeded=false;ledger.rejectedReceipts(newReceipts.filter(row=>!admittedIds.has(row.id)).map(row=>({id:row.id,status:row.status,tokens:row.tokens,estimatedCost:row.estimatedCost,currency:row.currency,durationMs:row.durationMs})));ledger.receipts(newReceipts.filter(row=>admittedIds.has(row.id)).map(row=>({id:row.id,status:row.status,tokens:row.tokens,estimatedCost:row.estimatedCost,currency:row.currency,durationMs:row.durationMs})));equal(report.closedProtectedHash,m.protectedHash,'closed_protected_source_mutated');snapshot=join(output,'DO_NOT_OPEN','closed-checkpoint');await cloneClosed(vault,snapshot);const snapshotHash=await treeHash(snapshot);report.checkpoint={path:snapshot,treeHash:snapshotHash,parentTreeHash:parentHash};if(ledgerStarted)ledger.finish(snapshotHash,succeeded,authority?{kind:'extraction',wave:authority.plan.wave,contextTime:m.contextTime,archiveHeadHash:snapshotHash,totalBatches:m.batchPlan.length,nextBatch:index+1,evaluatedPairs:0,wavePlan:authority.cursor.wavePlan}:undefined);
      check(await treeHash(parent)===parentHash,'parent_snapshot_mutated');
    }catch(error){failure??=error;succeeded=false;ledger.stop(safeCode(error));await sealedError(join(output,'DO_NOT_OPEN'),error);}
    const cumulative=ledger.summary();report.cumulative={...cumulative,usage:usageTotals(ledger.events.filter(row=>row.kind==='receipt').map(row=>row.data as UsageReceipt))};const stageAdmissions=ledger.admitted.filter(row=>row.data.stage===stage).length;report.realModelCalls=stub?0:stageAdmissions;report.stubModelCalls=stub?stageAdmissions:0;report.status=succeeded?'paused-success':'stopped';report.failure=failure?{code:safeCode(failure)}:undefined;report.finishedAt=new Date().toISOString();report.terminalBatchCounts=finalJob?{completed:finalJob.completedBatches,total:finalJob.totalBatches}:undefined;process.off('SIGTERM',interrupted);process.off('SIGINT',interrupted);ledger.close();await privateWrite(join(output,'ROOT_SAFE_stage.json'),report);
  }
  return {report,snapshot,succeeded};
}
export async function stageMain(){const path=process.env.MOTE_HELDOUT_OUTPUT;check(path,'stage_output_required');const output=await newOutput(path);const mode=process.env.MOTE_HELDOUT_MODE;
  try{
    if(mode==='stage-freeze'){const manifest=await freezeStage(output);await privateWrite(join(output,'ROOT_SAFE_status.json'),{status:'frozen',manifestHash:sha256(await readFile(join(output,'ROOT_SAFE_manifest.json'))),realModelCalls:0,deliveries:manifest.scope.deliveries,batches:manifest.batchPlan.length});}
    else if(mode==='stage-resume-freeze'){check(process.env.MOTE_HELDOUT_MANIFEST&&process.env.MOTE_HELDOUT_LEDGER&&process.env.MOTE_HELDOUT_PARENT&&process.env.MOTE_HELDOUT_BATCH_INDEX&&process.env.MOTE_HELDOUT_VALIDATION,'resume_freeze_arguments_required');const manifest=await freezeContinuation({previousManifest:process.env.MOTE_HELDOUT_MANIFEST,parent:process.env.MOTE_HELDOUT_PARENT,index:Number(process.env.MOTE_HELDOUT_BATCH_INDEX),ledgerDirectory:process.env.MOTE_HELDOUT_LEDGER,validation:process.env.MOTE_HELDOUT_VALIDATION,output});await privateWrite(join(output,'ROOT_SAFE_status.json'),{status:'continuation-frozen',manifestHash:sha256(await readFile(join(output,'ROOT_SAFE_manifest.json'))),experimentHash:manifest.experimentHash,index:manifest.continuation!.index,realModelCalls:0});}
    else if(mode==='stage-ingress-freeze'||mode==='stage-extract-freeze'){check(process.env.MOTE_HELDOUT_ROOT_MANIFEST&&process.env.MOTE_HELDOUT_MANIFEST&&process.env.MOTE_HELDOUT_LEDGER&&process.env.MOTE_HELDOUT_PARENT&&process.env.MOTE_HELDOUT_VALIDATION,'phase_freeze_arguments_required');const {freezePhase}=await import('./test-heldout-memory-replay-sequence.js');const manifest=await freezePhase({rootManifest:process.env.MOTE_HELDOUT_ROOT_MANIFEST,previousManifest:process.env.MOTE_HELDOUT_MANIFEST,parent:process.env.MOTE_HELDOUT_PARENT,ledgerDirectory:process.env.MOTE_HELDOUT_LEDGER,validation:process.env.MOTE_HELDOUT_VALIDATION,output,kind:mode==='stage-ingress-freeze'?'ingress':'extraction',wave:Number(process.env.MOTE_HELDOUT_WAVE),index:Number(process.env.MOTE_HELDOUT_BATCH_INDEX)});await privateWrite(join(output,'ROOT_SAFE_status.json'),{status:'phase-frozen',kind:manifest.task.kind,wave:manifest.task.wave,manifestHash:sha256(await readFile(join(output,'ROOT_SAFE_manifest.json'))),experimentHash:manifest.experimentHash,realModelCalls:0});}
    else if(mode==='stage-integration-freeze'){check(process.env.MOTE_HELDOUT_ROOT_MANIFEST&&process.env.MOTE_HELDOUT_MANIFEST&&process.env.MOTE_HELDOUT_LEDGER&&process.env.MOTE_HELDOUT_PARENT&&process.env.MOTE_HELDOUT_VALIDATION&&process.env.MOTE_HELDOUT_SUPERVISOR,'integration_freeze_arguments_required');const {freezeIntegration}=await import('./test-heldout-memory-replay-integration.js');const manifest=await freezeIntegration({rootManifest:process.env.MOTE_HELDOUT_ROOT_MANIFEST,previousManifest:process.env.MOTE_HELDOUT_MANIFEST,parent:process.env.MOTE_HELDOUT_PARENT,ledgerDirectory:process.env.MOTE_HELDOUT_LEDGER,validation:process.env.MOTE_HELDOUT_VALIDATION,supervisorPath:process.env.MOTE_HELDOUT_SUPERVISOR,output});await privateWrite(join(output,'ROOT_SAFE_status.json'),{status:'integration-frozen',kind:manifest.task.kind,wave:manifest.task.wave,manifestHash:sha256(await readFile(join(output,'ROOT_SAFE_manifest.json'))),experimentHash:manifest.experimentHash,realModelCalls:0});}
    else if(mode==='stage-integration-live'){check(process.env.MOTE_HELDOUT_MANIFEST&&process.env.MOTE_HELDOUT_LEDGER,'stage_manifest_and_ledger_required');const bytes=await readFile(process.env.MOTE_HELDOUT_MANIFEST),manifest=JSON.parse(bytes.toString()) as import('./test-heldout-memory-replay-integration.js').IntegrationManifest;check(manifest.kind==='heldout','integration_cli_requires_heldout');check(manifest.schema==='mote-heldout-phase-manifest@1'&&manifest.task?.kind==='integration','integration_cli_scope_invalid');const {runIntegration}=await import('./test-heldout-memory-replay-integration.js');const result=await runIntegration({manifest,manifestHash:sha256(bytes),output,ledgerDirectory:resolve(process.env.MOTE_HELDOUT_LEDGER),live:true});if(!result.succeeded)process.exitCode=1;}
    else if(mode==='stage-ask-freeze'){check(process.env.MOTE_HELDOUT_ROOT_MANIFEST&&process.env.MOTE_HELDOUT_MANIFEST&&process.env.MOTE_HELDOUT_LEDGER&&process.env.MOTE_HELDOUT_PARENT&&process.env.MOTE_HELDOUT_VALIDATION&&process.env.MOTE_HELDOUT_SUPERVISOR,'ask_freeze_arguments_required');const {freezeAsk}=await import('./test-heldout-memory-replay-ask.js');const manifest=await freezeAsk({rootManifest:process.env.MOTE_HELDOUT_ROOT_MANIFEST,previousManifest:process.env.MOTE_HELDOUT_MANIFEST,parent:process.env.MOTE_HELDOUT_PARENT,ledgerDirectory:process.env.MOTE_HELDOUT_LEDGER,validation:process.env.MOTE_HELDOUT_VALIDATION,supervisorPath:process.env.MOTE_HELDOUT_SUPERVISOR,output,planPath:process.env.MOTE_HELDOUT_ASK_PLAN});await privateWrite(join(output,'ROOT_SAFE_status.json'),{status:'ask-frozen',kind:manifest.task.kind,wave:manifest.task.wave,pairOrdinal:manifest.task.index,planHash:manifest.task.plan.sha256,manifestHash:sha256(await readFile(join(output,'ROOT_SAFE_manifest.json'))),experimentHash:manifest.experimentHash,realModelCalls:0});}
    else if(mode==='stage-ask-live'){check(process.env.MOTE_HELDOUT_MANIFEST&&process.env.MOTE_HELDOUT_LEDGER,'stage_manifest_and_ledger_required');const bytes=await readFile(process.env.MOTE_HELDOUT_MANIFEST),manifest=JSON.parse(bytes.toString()) as import('./test-heldout-memory-replay-ask.js').AskManifest;check(manifest.kind==='heldout','ask_cli_requires_heldout');check(manifest.schema==='mote-heldout-phase-manifest@1'&&manifest.task?.kind==='evaluation','ask_cli_scope_invalid');const {runAsk}=await import('./test-heldout-memory-replay-ask.js');const result=await runAsk({manifest,manifestHash:sha256(bytes),output,ledgerDirectory:resolve(process.env.MOTE_HELDOUT_LEDGER),live:true});if(!result.succeeded)process.exitCode=1;}
    else if(mode==='stage-live'){check(process.env.MOTE_HELDOUT_MANIFEST&&process.env.MOTE_HELDOUT_LEDGER,'stage_manifest_and_ledger_required');const bytes=await readFile(process.env.MOTE_HELDOUT_MANIFEST),manifest=JSON.parse(bytes.toString()) as Manifest;check(manifest.kind==='heldout','stage_manifest_invalid');const result=manifest.schema==='mote-heldout-phase-manifest@1'?await (await import('./test-heldout-memory-replay-sequence.js')).runPhase({manifestPath:process.env.MOTE_HELDOUT_MANIFEST,output,ledgerDirectory:resolve(process.env.MOTE_HELDOUT_LEDGER)}):await runBatch({manifest,manifestHash:sha256(bytes),output,ledgerDirectory:resolve(process.env.MOTE_HELDOUT_LEDGER)});if(!result.succeeded)process.exitCode=1;}
    else throw new SafeFailure('stage_mode_unsupported');
    console.log(JSON.stringify({status:process.exitCode?'stopped':'completed',mode,output,semanticContentExposed:false}));
  }catch(error){await sealedError(join(output,'DO_NOT_OPEN'),error);await privateWrite(join(output,'ROOT_SAFE_status.json'),{status:'stopped',code:safeCode(error),realModelCalls:['stage-live','stage-integration-live','stage-ask-live'].includes(mode??'')?'unknown':0,ledger:process.env.MOTE_HELDOUT_LEDGER??null,semanticContentExposed:false});console.error(JSON.stringify({status:'stopped',code:safeCode(error),output,semanticContentExposed:false}));process.exitCode=1;}
}
export {newOutput,treeHash,protectedTables,privateWrite,sealedError,safeCode,batchPin,bindings,settings,openNode,drain,noProvider,supervisor,fixedLimits};
