/** Generated fixtures only. No heldout data, live provider, or production mutation. */
import {after,test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import type {ContextReader,QueryInput} from '@mote/agent';
import type {QueryResult} from '@mote/shared';
import type {Memory} from '../apps/server/src/memory-schema.js';
import {base,check,equal,json,hashObject,cloneClosed,SafeFailure} from './test-heldout-memory-replay.js';
import {sha256} from '../apps/server/src/store.js';
import {inspectAdmissionLedger,AdmissionLedger} from './test-heldout-memory-replay-ledger.js';
import {freezeStage,newOutput,runBatch,freezeContinuation,codeHashes,executorPins,treeHash,type Manifest} from './test-heldout-memory-replay-stage.js';
import {freezeIntegration,runIntegration,IntegrationCallOrder,integrationSelection} from './test-heldout-memory-replay-integration.js';

const root=process.env.MOTE_HELDOUT_INTEGRATION_TEST_OUTPUT??join(base,'heldout-integration-offline-'+Date.now());await mkdir(root,{mode:0o700});
const checks:unknown[]=[];let stubCalls=0;const originalFetch=globalThis.fetch;globalThis.fetch=async()=>{throw Error('Generated integration test forbids network');};
const log=async(name:string,value:Record<string,unknown>)=>{checks.push({name,passed:true,...value});await writeFile(join(root,'ROOT_SAFE_progress.json'),json({realModelCalls:0,heldoutSemanticInputsRead:false,checks}));};
const usage=(input:QueryInput,complete=true)=>{input.onTrace?.({type:'model.started',payload:{}});input.onUsage?.({measurement:'thread_cumulative',complete,requests:0,reportedRequests:0,inputTokens:13,outputTokens:5,totalTokens:18});};
async function setup(name:string,mode:'normal'|'empty'|'large'='normal'){
  const output=await newOutput(join(root,name+'-seed')),m=await freezeStage(output,true,mode==='large'?2:1),ledgerDirectory=join(root,name+'-ledger'),validation=join(root,name+'-validation.json'),supervisorPath=join(root,name+'-supervisor-fixture.txt');
  await writeFile(validation,json({schema:'mote-heldout-sequence-validation@1',status:'passed',realModelCalls:0,heldoutSemanticInputsRead:false,validatedPhases:['integration'],executorCodeHashes:executorPins(await codeHashes()),note:'Mechanical validation-shape fixture, not a fabricated acceptance report. Final result is ROOT_SAFE_integration.json.'}));await writeFile(supervisorPath,'Generated supervisor fingerprint fixture; not executable and not a live timeout validation.\n');
  const extraction=async(reader:ContextReader,input:QueryInput):Promise<QueryResult>=>{stubCalls++;usage(input);if(mode==='empty')return {answer:'{"memories":[]}',citations:[],trace:[],runId:randomUUID()};const records=await reader.evidence({ids:input.evidenceIds!}),record=records[0];check(record,'integration_fixture_evidence');const index=input.traceContext!.batchIndex!,domain=(m.batchPlan[index].recipe as {id:string}).id==='mote.coding-memory'?'coding':'personal';return {answer:JSON.stringify({memories:Array.from({length:mode==='large'?8:1},(_v,i)=>({domain,title:'Generated seed',statement:`Generated seed ${index}/${i} [${record.id}]`,uncertainty:'Mechanical fixture only',admission:{layer:'memory',reason:'Generated fixture',scope:'Generated session',attribution:'observed'},evidenceIds:[record.id],evidence:[{id:record.id,quote:record.ocrText}],...(domain==='coding'?{coding:{kind:'decision',scope:'session',applicability:'Generated fixture',validation:'observed'}}:{})}))}),citations:records.map(r=>({id:r.id,capturedAt:r.capturedAt,appName:r.appName,excerpt:r.ocrText})),trace:[],runId:randomUUID()};};
  const rootManifest=join(output,'ROOT_SAFE_manifest.json');let previousManifest=rootManifest,manifest=m,parent=m.seed;
  for(let index=0;index<m.batchPlan.length;index++){
    if(index>1){const continuationValidation=join(root,name+'-continuation-validation.json');await writeFile(continuationValidation,json({schema:'mote-heldout-continuation-validation@1',status:'passed',realModelCalls:0,heldoutSemanticInputsRead:false,executorCodeHashes:executorPins(await codeHashes()),note:'Mechanical shape fixture.'}));const next=await newOutput(join(root,name+'-continuation-'+index));manifest=await freezeContinuation({previousManifest,parent,index,ledgerDirectory,validation:continuationValidation,output:next});previousManifest=join(next,'ROOT_SAFE_manifest.json');}
    const result=await runBatch({manifest,manifestHash:sha256(await readFile(previousManifest)),output:await newOutput(join(root,name+'-extraction-'+index)),ledgerDirectory,parent,index,stub:extraction});check(result.succeeded,'integration_fixture_extraction_failed');parent=result.snapshot;
  }
  return {rootManifest,previousManifest,parent,ledgerDirectory,validation,supervisorPath,m};
}
async function frozen(name:string,mode:'normal'|'empty'='normal'){
  const seed=await setup(name,mode),output=await newOutput(join(root,name+'-freeze')),manifest=await freezeIntegration({...seed,output});return {...seed,manifest,manifestHash:sha256(await readFile(join(output,'ROOT_SAFE_manifest.json')))};
}
function answer(options:{empty?:boolean;failure?:'extract'|'review';timeout?:boolean;counter:{value:number}}){return async(reader:ContextReader,input:QueryInput):Promise<QueryResult>=>{
  stubCalls++;options.counter.value++;usage(input,!(options.failure||options.timeout));if(options.timeout)return new Promise((_resolve,reject)=>input.signal!.addEventListener('abort',()=>reject(Error('Generated abort')),{once:true}));if(options.failure===input.traceContext?.phase)throw Error('Generated failure');if(options.empty)return {answer:'{"memories":[]}',citations:[],trace:[],runId:randomUUID()};
  // The fixture model reads the literal host card-ID array; the executor does not infer a domain from text.
  const ids=JSON.parse(input.question.slice(input.question.lastIndexOf('\n')+1)) as string[];check(reader.memories,'integration_fixture_memory_tool');const cards=await Promise.all(ids.map(async id=>(await reader.memories!({id})).items[0] as Memory));check(cards.every(Boolean),'integration_fixture_cards');const domain=cards[0].domain??'personal',evidenceIds=[...new Set(cards.flatMap(card=>card.evidenceIds))],evidence=await reader.evidence({ids:evidenceIds});
  return {answer:JSON.stringify({memories:[{domain,title:'Generated integration',statement:`Mechanical synthesis ${domain} ${evidenceIds.map(id=>'['+id+']').join(' ')}`,uncertainty:'No semantic quality assertion',admission:{layer:'memory',reason:'Mechanical integration',scope:'Generated session',attribution:'observed'},relatedMemoryIds:ids,evidenceIds,evidence:evidence.map(r=>({id:r.id,quote:r.ocrText})),...(domain==='coding'?{coding:{kind:'decision',scope:'session',applicability:'Generated fixture',validation:'observed'}}:{})}]}),citations:evidence.map(r=>({id:r.id,capturedAt:r.capturedAt,appName:r.appName,excerpt:r.ocrText})),trace:[],runId:randomUUID()};
};}
const code=(error:unknown)=>error instanceof SafeFailure?error.code:error instanceof Error?error.message:'unknown';
test('complete two-domain window commits, closes receipts, preserves originals and refuses replay',async()=>{
  const data=await frozen('normal'),counter={value:0},before=await treeHash(data.parent),result=await runIntegration({...data,output:await newOutput(join(root,'normal-run')),stub:answer({counter})});assert.ok(result.succeeded,JSON.stringify(result.report.failure));assert.equal(counter.value,4);assert.equal(result.report.completedDomainCount,2);assert.equal(result.report.terminalUsage.readAfterClose,true);assert.equal(result.report.hostRejectedReceipts,0);assert.equal(await treeHash(data.parent),before);assert.equal(result.report.sourceProtectedHash,data.m.protectedHash);
  for(const event of inspectAdmissionLedger(data.ledgerDirectory,data.m.experimentHash).filter(row=>row.kind==='receipt'))assert.ok(Object.keys(event.data).every(key=>['id','status','tokens','estimatedCost','currency','durationMs'].includes(key)));
  const replay=await newOutput(join(root,'normal-replay'));await assert.rejects(()=>runIntegration({...data,output:replay,stub:answer({counter})}),e=>code(e)==='integration_ledger_advanced');assert.equal(counter.value,4);await log('completed-window',{outer:4,receiptReadAfterClose:true,receiptFieldsAllowlisted:true,originalsUnchanged:true,replayRejected:true});
});
test('both domains returning empty consume two generations and no review',async()=>{const data=await frozen('empty-output'),counter={value:0},result=await runIntegration({...data,output:await newOutput(join(root,'empty-output-run')),stub:answer({empty:true,counter})});assert.ok(result.succeeded);assert.equal(counter.value,2);assert.equal(result.report.stubModelCalls,2);await log('empty-output',{outer:2});});
test('zero eligible cards creates no window and no model usage',async()=>{const data=await frozen('zero','empty'),counter={value:0},result=await runIntegration({...data,output:await newOutput(join(root,'zero-run')),stub:answer({counter})});assert.ok(result.succeeded);assert.equal(counter.value,0);assert.equal(result.report.status,'completed-no-input');assert.equal(result.report.terminalUsage.new,0);const db=new DatabaseSync(join(result.snapshot,'mote.sqlite'),{readOnly:true});try{assert.equal(JSON.parse(String(db.prepare("SELECT json FROM memory_lifecycle_state WHERE id='consolidation'").get()!.json)).active,undefined);}finally{db.close();}await log('zero-input',{outer:0,newUsage:0,windowCreated:false});});
for(const failure of ['extract','review'] as const)test(failure+' failure closes admissions before the next domain',async()=>{const data=await frozen('failure-'+failure),counter={value:0},result=await runIntegration({...data,output:await newOutput(join(root,'failure-'+failure+'-run')),stub:answer({failure,counter})});assert.ok(!result.succeeded);assert.equal(counter.value,failure==='extract'?1:2);assert.equal(result.report.hostRejectedReceipts,1);assert.equal(result.report.cumulative.failed,1);assert.equal(result.report.cumulative.unknown,0);assert.ok(result.report.cumulative.stopped);assert.throws(()=>inspectAdmissionLedger(data.ledgerDirectory,data.m.experimentHash));await log('failure-'+failure,{outer:counter.value,postFailureAdmissions:0,hostRejectedReceipts:1,incompleteUsagePreserved:result.report.cumulative.incompleteReceipts>0});});
test('deadline preserves failed usage and does not admit another domain',async()=>{const data=await frozen('deadline'),counter={value:0},result=await runIntegration({...data,output:await newOutput(join(root,'deadline-run')),stub:answer({timeout:true,counter}),perOuterMs:10});assert.ok(!result.succeeded);assert.equal(counter.value,1);assert.equal(result.report.cumulative.failed,1);assert.equal(result.report.hostRejectedReceipts,1);await log('deadline',{outer:1,postFailureAdmissions:0});});
test('successful paid review followed by commit rollback blocks next generation',async()=>{const data=await frozen('commit'),counter={value:0},result=await runIntegration({...data,output:await newOutput(join(root,'commit-run')),stub:answer({counter}),mechanicalHook:node=>{const original=node.memories.extract.bind(node.memories);let once=true;node.memories.extract=(answer,model,options={})=>{if(once&&options.tier==='consolidated'&&!options.validateOnly){once=false;return original(answer,model,{...options,onSaved:items=>{options.onSaved?.(items);throw Error('Generated post-save rollback');}});}return original(answer,model,options);};}});assert.ok(!result.succeeded);assert.equal(counter.value,2);assert.equal(result.report.terminalUsage.totals.completed,2);assert.equal(result.report.terminalUsage.totals.failed,1);assert.equal(result.report.cumulative.failed,0);assert.equal(result.report.hostRejectedReceipts,1);assert.equal(result.report.completedDomainCount,0);const db=new DatabaseSync(join(result.snapshot,'mote.sqlite'),{readOnly:true});try{assert.equal(Number(db.prepare("SELECT count(*) n FROM memories WHERE json_extract(json,'$.tier')='consolidated'").get()!.n),0);}finally{db.close();}await log('post-review-commit-failure',{paidSuccessfulOuter:2,products:0,postFailureAdmissions:0,hostRejectedReceipts:1});});
test('uncertain admission is never resumed or refunded',async()=>{const directory=join(root,'unknown-ledger'),ledger=new AdmissionLedger(directory,'generated-unknown');ledger.begin('integration','parent',4);ledger.reserve('window-personal-extract','input','receipt');ledger.close();assert.throws(()=>inspectAdmissionLedger(directory,'generated-unknown'));assert.throws(()=>new AdmissionLedger(directory,'generated-unknown'));await log('unknown',{postUnknownAdmissions:0,unknownAdmissionPreserved:true});});
test('the complete set above frozen capacity stops before a new window',async()=>{const data=await setup('capacity','large'),before=await treeHash(data.parent),ledgerBefore=sha256(await readFile(join(data.ledgerDirectory,'admissions.ndjson'))),output=await newOutput(join(root,'capacity-freeze'));await assert.rejects(()=>freezeIntegration({...data,output}),e=>code(e)==='integration_complete_set_over_capacity');assert.equal(await treeHash(data.parent),before);assert.equal(sha256(await readFile(join(data.ledgerDirectory,'admissions.ndjson'))),ledgerBefore);await log('capacity',{completeSet:32,effectiveCapacity:30,admissions:0,windowCreated:false,parentAndLedgerUnchanged:true});});
test('call order cannot choose a domain from question text or skip an uncommitted result',async()=>{const a=randomUUID(),b=randomUUID(),order=new IntegrationCallOrder([{id:a,hash:'a'.repeat(64),domain:'personal'},{id:b,hash:'b'.repeat(64),domain:'coding'}]);assert.equal(order.next([],'extract','coding misleading prose\n'+JSON.stringify([a])),'personal');order.complete('personal','extract','{"memories":[]}');assert.throws(()=>order.next([],'extract','anything\n'+JSON.stringify([b])));assert.equal(order.next(['personal'],'extract','personal misleading prose\n'+JSON.stringify([b])),'coding');assert.throws(()=>order.next(['coding'],'extract','anything'));await log('structural-order',{questionSemanticsIgnored:true,uncommittedPriorDomainRejected:true});});
test('complete structural scan includes old consolidation and rejects proposed or unknown states',async()=>{const data=await setup('selection'),path=join(root,'selection-clone');await cloneClosed(data.parent,path);const db=new DatabaseSync(join(path,'mote.sqlite'));try{const row=db.prepare('SELECT id,json FROM memories ORDER BY id LIMIT 1').get()!,original=JSON.parse(String(row.json));const change=(patch:object)=>db.prepare('UPDATE memories SET json=? WHERE id=?').run(JSON.stringify({...original,...patch}),String(row.id));change({tier:'consolidated',createdAt:'2020-01-01T00:00:00Z'});assert.ok(integrationSelection(db,data.m.contextTime).inputs.some(input=>input.id===row.id));change({validUntil:data.m.contextTime});assert.equal(integrationSelection(db,data.m.contextTime).excluded.inactive,1);change({status:'stale',staleReason:'evidence_changed'});assert.equal(integrationSelection(db,data.m.contextTime).excluded.stale,1);change({status:'proposed'});assert.throws(()=>integrationSelection(db,data.m.contextTime),e=>code(e)==='integration_proposed_requires_review');change({status:'unrecognized'});assert.throws(()=>integrationSelection(db,data.m.contextTime),e=>code(e)==='integration_memory_shape_unknown');}finally{db.close();}await log('complete-selection',{oldConsolidatedIncluded:true,timeValidityApplied:true,proposedAndUnknownFailClosed:true});});
test('a changed protected table fails before any model admission',async()=>{const data=await frozen('protection'),counter={value:0},result=await runIntegration({...data,output:await newOutput(join(root,'protection-run')),stub:answer({counter}),mechanicalHook:node=>{node.store.db.prepare("INSERT INTO settings VALUES('generated-protected-change','1')").run();}});assert.ok(!result.succeeded);assert.equal(counter.value,0);assert.equal(result.report.stubModelCalls,0);assert.ok(result.report.cumulative.stopped);assert.ok(!result.report.checkpoint?.canonical);await log('protected-mutation',{admissions:0,canonicalCheckpoint:false});});
test('closed admitted and host-rejected receipts expose only the accounting allowlist',async()=>{const data=await frozen('receipt-fields'),counter={value:0},output=await newOutput(join(root,'receipt-fields-run')),result=await runIntegration({...data,output,stub:answer({failure:'review',counter}),mechanicalHook:node=>{const close=node.app.close.bind(node.app);node.app.close=(async()=>{for(const row of node.store.db.prepare('SELECT id,json FROM model_usage').all()){const receipt=JSON.parse(String(row.json));node.store.db.prepare('UPDATE model_usage SET json=? WHERE id=?').run(JSON.stringify({...receipt,extraProbe:{generatedOnly:'PRIVATE_FIXTURE_FIELD'},operation:'GENERATED_PRIVATE_OPERATION'}),String(row.id));}await close();}) as typeof node.app.close;}});assert.ok(!result.succeeded);assert.equal(counter.value,2);assert.equal(result.report.hostRejectedReceipts,1);const db=new DatabaseSync(join(result.snapshot,'mote.sqlite'),{readOnly:true});try{const events=(await readFile(join(data.ledgerDirectory,'admissions.ndjson'),'utf8')).trim().split('\n').map(line=>JSON.parse(line)),safeKeys=['id','status','tokens','estimatedCost','currency','durationMs'];for(const kind of ['receipt','host-rejection-receipt']){const rows=events.filter(row=>row.kind===kind);assert.ok(rows.length>0);for(const event of rows){assert.ok(Object.keys(event.data).every(key=>safeKeys.includes(key)));const raw=JSON.parse(String(db.prepare('SELECT json FROM model_usage WHERE id=?').get(event.data.id)!.json));assert.ok(raw.extraProbe);assert.equal(raw.operation,'GENERATED_PRIVATE_OPERATION');equal(event.data,JSON.parse(JSON.stringify(Object.fromEntries(safeKeys.map(key=>[key,raw[key]])))),'integration_receipt_projection_changed');}}}finally{db.close();}await log('receipt-allowlist',{admittedAndHostRejectedChecked:true,extraFieldsSealed:true,originalAccountingPreserved:true});});

after(async()=>{globalThis.fetch=originalFetch;await writeFile(join(root,'ROOT_SAFE_integration.json'),json({schema:'mote-heldout-sequence-validation@1',validatedPhases:['integration'],status:checks.length===13?'passed':'incomplete',realModelCalls:0,heldoutSemanticInputsRead:false,stubModelCalls:stubCalls,checks,executorCodeHashes:executorPins(await codeHashes())}),{mode:0o600});});
