package dev.mote.collector

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Test
import java.io.File
import java.nio.file.Files
import java.util.UUID
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.spec.GCMParameterSpec

/** Generated bytes only. Also runs on Android to exercise the same JSON/storage contracts. */
class CentralNativeContractTest {
    private fun encrypted() = object : ByteCipher {
        private val key = KeyGenerator.getInstance("AES").apply { init(128) }.generateKey()
        override fun seal(bytes: ByteArray): ByteArray = Cipher.getInstance("AES/GCM/NoPadding").run {
            init(Cipher.ENCRYPT_MODE, key); iv + doFinal(bytes)
        }
        override fun open(bytes: ByteArray): ByteArray = Cipher.getInstance("AES/GCM/NoPadding").run {
            init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(128, bytes.copyOfRange(0, 12))); doFinal(bytes.copyOfRange(12, bytes.size))
        }
    }
    private fun temporary(test: (File) -> Unit) {
        val root = Files.createTempDirectory("central-native-fixture").toFile()
        try { test(root) } finally { root.deleteRecursively() }
    }
    private val origin = "https://central.fixture.invalid"
    private val token = "generated-native-owner-fixture-token-123456"

    @Test fun ownerSessionIsSharedButNeverSentToAnotherOrigin() = temporary { root ->
        val store = CentralSessionStore(File(root, "session"), encrypted())
        store.select(origin); assertNull(store.client(origin)); store.signIn(origin, token)
        val old = store.client(origin)!!; assertNotNull(store.client(origin + "/"))
        assertNull(store.client("https://other.fixture.invalid"))
        store.select("https://other.fixture.invalid"); assertNull(store.client(origin))
        assertThrows(IllegalStateException::class.java) { old.get("/api/configuration") }
        store.signIn("https://other.fixture.invalid", token)
        assertThrows(IllegalStateException::class.java) { old.get("/api/configuration") }
    }
    @Test fun durationIsEncryptedAndExpiresAcrossRecreation() = temporary { root ->
        var now = 1000L; val cipher = encrypted(); val file = File(root, "session")
        val store = CentralSessionStore(file, cipher, { now })
        store.select(origin); store.signIn(origin, token, 86400000L)
        assertFalse(String(file.readBytes()).contains(token))
        val restored = CentralSessionStore(file, cipher, { now }); restored.select(origin)
        assertNotNull(restored.client(origin)); val old = restored.client(origin)!!
        now += 86400001L
        assertThrows(IllegalStateException::class.java) { old.get("/api/status") }
        assertNull(restored.client(origin)); assertFalse(restored.mayReuse(token))
    }
    @Test fun appSessionDoesNotPersistOwnerToken() = temporary { root ->
        val cipher = encrypted(); val file = File(root, "session")
        val store = CentralSessionStore(file, cipher); store.select(origin); store.signIn(origin, token)
        assertFalse(file.exists())
        val restarted = CentralSessionStore(file, cipher); restarted.select(origin); assertNull(restarted.client(origin))
    }
    @Test fun logoutSurvivesRestartAndDoesNotAutomaticallyReuseConfiguredToken() = temporary { root ->
        val cipher = encrypted(); val file = File(root, "session")
        val store = CentralSessionStore(file, cipher); store.select(origin)
        assertTrue(store.mayReuse(token)); assertFalse(store.mayReuse(token))
        store.signIn(origin, token); val old = store.client(origin)!!; store.signOut()
        assertThrows(IllegalStateException::class.java) { old.get("/api/status") }
        val restarted = CentralSessionStore(file, cipher); restarted.select(origin)
        assertNull(restarted.client(origin)); assertFalse(restarted.mayReuse(token))
    }
    @Test fun inFlightVerificationCannotRestoreALoggedOutSession() = temporary { root ->
        val store = CentralSessionStore(File(root, "session"), encrypted()); store.select(origin)
        val generation = store.generation; store.signOut()
        assertThrows(IllegalStateException::class.java) { store.signIn(origin, token, expectedGeneration = generation) }
        assertNull(store.client(origin))
    }
    @Test fun changingConfiguredNodeInvalidatesAnAlreadyIssuedClient() = temporary { root ->
        var selected = origin
        val store = CentralSessionStore(File(root, "session"), encrypted(), originActive = { it == selected })
        store.select(origin); store.signIn(origin, token); val old = store.client(origin)!!
        selected = "https://other.fixture.invalid"
        assertThrows(IllegalStateException::class.java) { old.get("/api/status") }
    }
    @Test fun staleUnauthorizedResponseCannotLogOutANewerSession() = temporary { root ->
        val store = CentralSessionStore(File(root, "session"), encrypted()); store.select(origin); store.signIn(origin, token)
        val old = store.generation; store.signIn(origin, token + "new"); store.signOut(old)
        assertNotNull(store.client(origin))
    }
    @Test fun transientBootstrapFailureCanRetryButLogoutCannotBeUndone() = temporary { root ->
        val store = CentralSessionStore(File(root, "session"), encrypted()); store.select(origin)
        assertTrue(store.mayReuse(token)); assertFalse(store.mayReuse(token))
        val generation = store.generation; store.retryReuse(token, generation); assertTrue(store.mayReuse(token))
        store.signOut(); store.retryReuse(token, generation); assertFalse(store.mayReuse(token))
    }
    @Test fun transportOnlyUsesFixedApiOriginAndRedactsCredential() {
        val calls = mutableListOf<String>()
        val client = CentralClient(origin, token, { _, url, _, auth, _ ->
            assertEquals(token, auth); calls.add(url); 200 to JSONObject().put("ok", true)
        })
        client.get("/api/status"); assertEquals(listOf("$origin/api/status"), calls)
        for (path in listOf("https://other.invalid/api/status", "//other.invalid/api/status", "/oauth/callback", "/api/../status", "/api/%2e%2e/status", "/api/status#token"))
            assertThrows(IllegalArgumentException::class.java) { client.get(path) }
        assertEquals(1, calls.size); assertFalse(client.toString().contains(token))
    }
    @Test fun unauthorizedIsDifferentFromAConnectorNeedingAuthorization() {
        var invalidations = 0
        val unauthorized = CentralClient(origin, token, { _, _, _, _, _ -> 401 to JSONObject().put("error", "unauthorized") }, unauthorized = { invalidations++ })
        val failure = assertThrows(CentralFailure::class.java) { unauthorized.get("/api/status") }; assertEquals("unauthorized", failure.code)
        assertEquals(1, invalidations)
        val connector = CentralClient(origin, token, { _, _, _, _, _ -> 401 to JSONObject().put("error", "google_not_connected").put("message", "Generated connector status") }, unauthorized = { invalidations++ })
        val separate = assertThrows(CentralFailure::class.java) { connector.get("/api/connectors/google/calendars") }
        assertEquals("google_not_connected", separate.code); assertEquals("Generated connector status", separate.message)
        assertEquals(1, invalidations)
    }
    @Test fun noteOutboxSurvivesAmbiguousAckAndOnlyRemovesTheExactReceipt() = temporary { root ->
        val cipher = encrypted(); val store = CentralNoteStore(root, cipher)
        val text = "Generated 中文 🐾 <script>untrusted evidence</script>"
        store.edit(text, "fixture", JSONArray()); val note = store.enqueue("fixture-phone", "Generated phone")
        assertEquals("", store.read().getJSONObject("draft").getString("text"))
        assertThrows(IllegalArgumentException::class.java) { store.enqueue("fixture-phone", "Generated phone") }
        val restored = CentralNoteStore(root, cipher)
        assertEquals(note.toString(), restored.read().getJSONArray("pending").getJSONObject(0).toString())
        assertFalse(String(File(root, "notes.enc").readBytes()).contains("untrusted evidence"))
        assertThrows(IllegalArgumentException::class.java) { restored.acknowledge(note.getString("id"), JSONObject().put("id", UUID.randomUUID().toString())) }
        assertEquals(1, restored.read().getJSONArray("pending").length())
        restored.acknowledge(note.getString("id"), JSONObject().put("id", note.getString("id")))
        assertEquals(0, restored.read().getJSONArray("pending").length())
    }
    @Test fun attachmentRetryPreservesManifestAndSkipsDurableParts() = temporary { root ->
        val file = File(root, "generated-image").apply { writeBytes(ByteArray(4 * 1024 * 1024 + 3) { (it % 251).toByte() }) }
        val uploadId = UUID.randomUUID().toString(); val captureId = UUID.randomUUID().toString()
        val manifests = mutableListOf<String>(); val parts = mutableListOf<String>(); var attempt = 0
        val client = CentralClient(origin, token, { _, url, bytes, _, _ ->
            when {
                url.endsWith("/api/sources") -> 200 to JSONObject()
                url.endsWith("/uploads") -> {
                    manifests.add(String(bytes!!)); attempt++
                    200 to JSONObject().put("uploadId", uploadId).put("parts", if (attempt == 1) JSONArray() else JSONArray().put(JSONObject().put("part", 0)))
                }
                url.contains("/parts/") -> { parts.add(url); 200 to JSONObject() }
                else -> if (attempt == 1) throw java.io.IOException("Generated lost response") else 200 to JSONObject().put("captureId", captureId)
            }
        })
        assertThrows(java.io.IOException::class.java) { CentralAttachments.upload(client, file, "fixture.png", "image/png", "fixture-phone", { 1000L }) }
        assertEquals(captureId, CentralAttachments.upload(client, file, "fixture.png", "image/png", "fixture-phone", { 1000L }))
        assertEquals(manifests[0], manifests[1]); assertEquals(3, parts.size); assertTrue(parts.last().endsWith("/parts/1"))
    }
    @Test fun importRetryAfterLostAdmissionResponseUsesSameArchivedFileAndRequestId() = temporary { root ->
        val cipher = encrypted(); val uploadId = UUID.randomUUID().toString(); val requestId = UUID.randomUUID().toString()
        val fileId = UUID.randomUUID().toString(); val jobId = UUID.randomUUID().toString()
        CentralStateFile(root, "import", cipher).write(JSONObject().put("manifest", JSONObject().put("id", uploadId).put("name", "generated.txt").put("sizeBytes", 3))
            .put("requestId", requestId).put("instruction", "Generated instruction"))
        File(root, "part-0.enc").writeBytes(cipher.seal(byteArrayOf(1, 2, 3)))
        var committed = false; var attempts = 0; var partCalls = 0; val requests = mutableListOf<String>()
        val client = CentralClient(origin, token, { _, url, bytes, _, _ -> when {
            url.endsWith("/api/import-uploads") -> 200 to JSONObject().put("id", uploadId).put("partBytes", CentralImports.PART).put("parts", JSONArray()).apply { if (committed) put("fileId", fileId) }
            url.contains("/parts/") -> { partCalls++; 200 to JSONObject() }
            url.endsWith("/commit") -> { committed = true; 200 to JSONObject().put("id", fileId) }
            else -> { requests.add(String(bytes!!)); attempts++
                if (attempts == 1) throw java.io.IOException("Generated lost admission response") else 202 to JSONObject().put("id", jobId)
            }
        } })
        val store = CentralImports(root, cipher)
        assertThrows(java.io.IOException::class.java) { store.send(client) { _, _ -> } }
        assertTrue(store.pending().has("manifest"))
        assertEquals(jobId, CentralImports(root, cipher).send(client) { _, _ -> }.getString("id"))
        assertEquals(requests[0], requests[1]); assertEquals(1, partCalls); assertFalse(store.pending().has("manifest"))
        assertEquals(requestId, JSONObject(requests[0]).getString("requestId"))
        assertEquals(fileId, JSONObject(requests[0]).getJSONArray("archivedFileIds").getString(0))
    }
}
