package dev.mote.collector

import android.database.Cursor
import android.database.MatrixCursor
import android.os.ParcelFileDescriptor
import android.provider.DocumentsContract
import android.provider.DocumentsProvider
import java.io.File

/** Debug-only provider of files generated by instrumentation, never personal storage. */
class FileFixtureProvider : DocumentsProvider() {
    private val root get() = File(context!!.filesDir, "generated-file-sync").canonicalFile.apply { mkdirs() }
    private fun file(id: String): File = if (id == "root") root else File(root, id).canonicalFile.also { require(it.path.startsWith(root.canonicalPath + "/")) }
    private fun mime(f: File) = if (f.isDirectory) DocumentsContract.Document.MIME_TYPE_DIR else when (f.extension) { "wav" -> "audio/wav"; "txt" -> "text/plain"; else -> "application/octet-stream" }
    private val columns = arrayOf("document_id", "_display_name", "mime_type", "_size", "last_modified", "flags")
    private fun add(cursor: MatrixCursor, f: File) {
        val values: Map<String, Any?> = mapOf("document_id" to if (f == root) "root" else f.relativeTo(root).invariantSeparatorsPath, "_display_name" to f.name, "mime_type" to mime(f), "_size" to f.length(), "last_modified" to f.lastModified(), "flags" to 0)
        cursor.addRow(cursor.columnNames.map { values[it] }.toTypedArray())
    }
    override fun isChildDocument(parentDocumentId: String, documentId: String) = file(documentId).path.startsWith(file(parentDocumentId).path + "/")
    override fun onCreate() = true
    override fun queryRoots(projection: Array<out String>?): Cursor = MatrixCursor(projection ?: arrayOf("root_id", "document_id", "title")).also { c -> c.addRow(c.columnNames.map { when (it) { "root_id", "document_id" -> "root"; "title" -> "Generated file fixtures"; else -> null } }.toTypedArray()) }
    override fun queryDocument(documentId: String, projection: Array<out String>?): Cursor = MatrixCursor(projection ?: columns).also { c -> file(documentId).takeIf { it.exists() }?.let { add(c, it) } }
    override fun queryChildDocuments(parentDocumentId: String, projection: Array<out String>?, sortOrder: String?): Cursor {
        check(!context!!.getSharedPreferences("file-fixture", 0).getBoolean("failure", false))
        return MatrixCursor(projection ?: columns).also { c -> file(parentDocumentId).listFiles()?.sortedBy { it.name }?.forEach { add(c, it) } ?: error("Missing fixture directory") }
    }
    override fun openDocument(documentId: String, mode: String, signal: android.os.CancellationSignal?): ParcelFileDescriptor {
        require(mode == "r")
        val prefs = context!!.getSharedPreferences("file-fixture", 0); prefs.edit().putInt("reads", prefs.getInt("reads", 0) + 1).commit()
        return ParcelFileDescriptor.open(file(documentId), ParcelFileDescriptor.MODE_READ_ONLY)
    }
}
