import {describe,it,expect} from 'vitest';
import {CalendarActions,type CalendarActionIO} from '../src/calendar-actions';
const id='11111111-1111-4111-8111-111111111111',operationId='22222222-2222-4222-8222-222222222222';
const action={id,operationId,kind:'calendar.create',status:'executing',target:{deviceId:'mac',calendarId:'existing'},event:{title:'合成评审',start:'2099-09-18T15:00:00+08:00',end:'2099-09-18T16:00:00+08:00',timeZone:'Asia/Shanghai',allDay:false,location:'',description:''}};
describe('calendar execution fixtures (no real calendar access)',()=>{
 it('lost HTTP receipt retries the ledger without another native insertion',async()=>{const ledger=new Map<string,string>();let inserts=0,receipts=0;const io:CalendarActionIO={request:async path=>{if(path.endsWith('claim'))return action;if(++receipts===1)throw Error('offline');return {};},native:async(_c,input:any)=>{expect(input.description).toContain(`[Mote:${id}]`);inserts++;return {externalId:'fixture-event'};},read:async k=>ledger.get(k),write:async(k,v)=>{ledger.set(k,v);}};const client=new CalendarActions({deviceId:'mac',deviceName:'合成 Mac'},io);await expect(client.execute(id)).rejects.toThrow();await client.execute(id);expect(inserts).toBe(1);expect(ledger.get(operationId)).toBe('fixture-event');});
 it('crash after starting native write may only reconcile, including across process restart',async()=>{const ledger=new Map<string,string>();const allowed:boolean[]=[];const io:CalendarActionIO={request:async path=>path.endsWith('claim')?action:{},native:async(_c,input:any)=>{allowed.push(input.createAllowed);throw Error('process stopped');},read:async k=>ledger.get(k),write:async(k,v)=>{ledger.set(k,v);}};await expect(new CalendarActions({deviceId:'mac',deviceName:'fixture'},io).execute(id)).rejects.toThrow();await expect(new CalendarActions({deviceId:'mac',deviceName:'fixture'},io).execute(id)).rejects.toThrow();expect(allowed).toEqual([true,false]);});
 it('refuses a foreign device and serializes double clicks',async()=>{const ledger=new Map<string,string>();let count=0;const io:CalendarActionIO={request:async()=>action,native:async()=>{count++;return {externalId:'fixture'};},read:async k=>ledger.get(k),write:async(k,v)=>{ledger.set(k,v);}};const client=new CalendarActions({deviceId:'mac',deviceName:'fixture'},io);const secondWindow=new CalendarActions({deviceId:'mac',deviceName:'fixture'},io);await Promise.all([client.execute(id),secondWindow.execute(id)]);expect(count).toBe(1);await expect(new CalendarActions({deviceId:'other',deviceName:'fixture'},io).execute(id)).rejects.toThrow();});
});
