import {sourceAck} from './fixtures';
import {sourceHash} from '../src/source-sync';
/** Generated bytes and mocked durable central ACKs only; no decoding or live model. */
export function fileTransport(sourceId:()=>string,onCommit?:(item:any)=>Promise<void>|void){
 const sessions=new Map<string,any>();
 return async(url:string,init?:RequestInit):Promise<Response|undefined>=>{
  const path=new URL(url).pathname;
  if(!path.startsWith('/api/file-sync/'))return undefined;
  if(path.endsWith('/head'))return new Response(JSON.stringify({revision:null}));
  if(path.includes('/parts/')){const bytes=Buffer.from(await new Response(init!.body).arrayBuffer()),part=Number(path.split('/').at(-1));return new Response(JSON.stringify({part,hash:sourceHash(bytes),bytes:bytes.length}));}
  if(path.endsWith('/uploads')){const manifest=JSON.parse(await new Response(init!.body).text()),uploadId=manifest.item.revision;sessions.set(uploadId,manifest);return new Response(JSON.stringify({uploadId,partBytes:4194304,parts:[]}));}
  if(path.endsWith('/commit')){const manifest=sessions.get(path.split('/').at(-2)!);await onCommit?.(manifest.item);return new Response(JSON.stringify({...sourceAck(sourceId(),manifest.item,'file-revision'),sha256:manifest.sha256,sizeBytes:manifest.sizeBytes}));}
  throw Error('Unexpected generated file transport route '+path);
 };
}
