import {afterEach,expect,it} from 'vitest';
import {mkdtemp,mkdir,readFile,readdir,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {LocalSourceManager} from '../src/source-manager';
import {defaultConfig} from '../src/config';

const directories:string[]=[];
afterEach(async()=>{for(const directory of directories.splice(0))await rm(directory,{recursive:true,force:true});});

it('removes legacy source original spools once and keeps v2-created spools on restart',async()=>{
  const directory=await mkdtemp(join(tmpdir(),'mote-ingress-migration-'));directories.push(directory);
  const access=join(directory,'access-markers');await mkdir(access);
  const oldSpool=join(access,'local-f50650f0-fb31-4215-90cd-c96dc62d5e92.json.originals');
  await mkdir(join(oldSpool,'synthetic-original'),{recursive:true});
  await writeFile(join(oldSpool,'synthetic-original','0'),'generated bytes');
  await writeFile(join(access,'unrelated.txt'),'keep');
  const connection={serverUrl:'',token:undefined,deviceId:defaultConfig().deviceId};
  const first=new LocalSourceManager(directory,connection,'/synthetic/helper');
  try{await first.initialize();}finally{await first.close();}
  expect(await readdir(access)).toEqual(['unrelated.txt']);
  expect(JSON.parse(await readFile(join(directory,'ingress-v2.json'),'utf8'))).toEqual({version:2});
  await mkdir(join(oldSpool,'new-v2-original'),{recursive:true});
  const restarted=new LocalSourceManager(directory,connection,'/synthetic/helper');
  try{await restarted.initialize();}finally{await restarted.close();}
  expect(await readdir(oldSpool)).toEqual(['new-v2-original']);
});
