import {afterEach,expect,it} from 'vitest';
import {mkdtemp,mkdir,readFile,readdir,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {LocalSourceManager} from '../src/source-manager';
import {defaultConfig} from '../src/config';

const directories:string[]=[];
afterEach(async()=>{for(const directory of directories.splice(0))await rm(directory,{recursive:true,force:true});});

it('rejects an old source directory and leaves its original spools and metadata untouched',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'mote-ingress-format-'));directories.push(directory);const access=join(directory,'access-markers');await mkdir(access);
 const oldSpool=join(access,'local-f50650f0-fb31-4215-90cd-c96dc62d5e92.json.originals');await mkdir(join(oldSpool,'generated-original'),{recursive:true});const part=join(oldSpool,'generated-original','0');await writeFile(part,'generated bytes');
 const connection={serverUrl:'',token:undefined,deviceId:defaultConfig().deviceId},manager=new LocalSourceManager(directory,connection,'/synthetic/helper');
 try{await expect(manager.initialize()).rejects.toThrow('Unsupported desktop storage format');}finally{await manager.close();}
 expect(await readFile(part,'utf8')).toBe('generated bytes');expect(await readdir(access)).toEqual(['local-f50650f0-fb31-4215-90cd-c96dc62d5e92.json.originals']);
});
