import type { ReactNode } from 'react';
import type { Activity,Answer,Api,Capture,Device,Range,Status } from '../api';
import type { ArchiveTab } from '../Archive';
import type { Page } from '../navigation';
import type { SessionLifetime } from '../session';
export type PageProps={api:Api;status:Status|null;devices:Device[];activity:Activity;recent:Capture[];insights:Answer[];onPage:(page:Page)=>void;onOpen:(ref:string)=>void;range:Range;archiveTab:ArchiveTab;setArchiveTab:(tab:ArchiveTab)=>void;timelineRevision:number;refresh:()=>void;disconnect:()=>void;sessionLifetime:SessionLifetime;changeSessionLifetime:(value:SessionLifetime)=>void};
export type PageEntry={id:string;route?:string;label?:string;section?:'library'|'connections'|'system';order?:number;featureId:string;requires?:string[];render:(props:PageProps)=>ReactNode};
export type ViewValue={kind:string;schemaVersion:number;representation:string;ref:string;revision:string;title:string;text:string};
export type ViewProps={value:ViewValue;api:Api;onOpen:(ref:string)=>void};
export type ViewEntry={id:string;kind:string;schemaVersion:number;representation:string;render:(props:ViewProps)=>ReactNode};
export type CollectionProps={api:Api;devices:Device[];range:Range;activity:Activity;revision:number;onOpen:(ref:string)=>void;onChanged?:()=>void};
export type CollectionEntry={id:string;featureId:string;label:string;order:number;render:(props:CollectionProps)=>ReactNode};
